### ISSUE TITLE
Dark mode does not work properly in Windows 11

### ISSUE THREAD

**Issue by sumeshir26** [TomSchimansky/CustomTkinter#10]
When running the complex example and OS mode set to dark:
![image](https://user-images.githubusercontent.com/68823982/136735399-9fd3496c-8a9d-4d49-a742-9e0bacb22eee.png)
Only the CtkFrames become dark, not the background.
(I removed the macos darkmode lines and removed the checkbox due to a error.)

**Comment by TomSchimansky** [comment]
Did the window background and/or the window header was dark in Windows 10 or 8?
I couldn't find any information if Tkinter supports dark window style in Windows 11, seems like it does not.
I will try to color the background manually on Windows, but I don't think I can do anything with the window header.

**Comment by TomSchimansky** [comment]
The dark background should now work with version 2.0 right out of the box.

**Comment by sumeshir26** [comment]
Thank you!
