### ISSUE TITLE
Mistake in Documentation for CTkOptionMenu

### ISSUE THREAD

**Issue by S3idOtaku** [TomSchimansky/CustomTkinter#1007]
**There is a mistake in the Documentation for CTkOptionMenu**

`dropdown_color` is not a valid argument
it should be changed to `dropdown_fg_color`

EDIT: I Found out more about it!
if you use `.configure` the command `dropdown_color` is the right one and `dropdown_fg_color` will give error

**Comment by TomSchimansky** [comment]
Fixed now with version 5.0.4.
