### ISSUE TITLE
textbox auto scroll while inserting

### ISSUE THREAD

**Issue by GermanYoshi** [TomSchimansky/CustomTkinter#1022]
So basically i insert insert a bunch of lines in a textbox.
At some point the Windows is full and the scrollbar activates. 
Fine so far, but as i continue to insert the "user" does not see the text. (cause it gets inserted in the end, out of view)

is there a way to enable auto scrolling, so it gets scrolled to the end? I am pretty sure that normal tkinter does that out of the box!?

**Comment by Akascape** [comment]
@GermanYoshi
Use this to get to the end.
```python
Textbox.see(tkinter.END)
```

**Comment by GermanYoshi** [comment]
thanks :)
