### ISSUE TITLE
get state of progressbar

### ISSUE THREAD

**Issue by GermanYoshi** [TomSchimansky/CustomTkinter#1026]
is there a way to check if the progress bar is already running?

i am using mode='indeterminate' so i cant get the current value to check if it is > 0
how do i check it then? can we get a function for this?

**Comment by Akascape** [comment]
@GermanYoshi Use `progressbar.cget("mode")` to get the current mode.

**Comment by GermanYoshi** [comment]
sorry my question was a bit inaccurate.
how do i see if the progressbar is in state progressbar.start() or .stop()

**Comment by M4hbod** [comment]
You can go to "widgets -> ctk_progressbar.py" and jump to cget method then add this
```
elif attribute_name == "loop_running":
    return self._loop_running
```
then use ```progressbar.cget("loop_running")```

**Comment by Akascape** [comment]
@GermanYoshi 
Or you can directly use `progressbar._loop_running` instead of doing changes in the module.

**Comment by GermanYoshi** [comment]
thanks
