### ISSUE TITLE
CTk window appears on the taskbar when overredirected is True

### ISSUE THREAD

**Issue by Zingzy** [TomSchimansky/CustomTkinter#1030]
The CTk window appears on the taskbar even overredirect is True
![image](https://user-images.githubusercontent.com/90309290/211562479-8863d763-a3c9-4e7a-a798-d8047338895b.png)

**Comment by Akascape** [comment]
@Zingzy Use this method to remove the window from taskbar:
```python
root = customtkinter.CTk()
x = root.winfo_x()
y = root.winfo_y()
root.wm_state("zoomed")
root.overrideredirect(True) 
root.state("normal")
root.geometry(f'+{x}+{y}')
```
