### ISSUE TITLE
Bug with init() in version 5.0.3

### ISSUE THREAD

**Issue by lachesis17** [TomSchimansky/CustomTkinter#1032]
I've been running version 4.6.3 for a long time without issues.

Today I installed the latest version (5.0.3) for a virtual environment and can't seem to get around this TypeError no matter what positional arguments I use.

TypeError: __init__() missing 1 required positional argument: 'master'

Looks like there's a similar issue here: https://github.com/TomSchimansky/CustomTkinter/issues/1021

I've tried with several scripts running customtkinter GUIs and can't get window to create on the latest version.

**Comment by lachesis17** [comment]
Have used this package for a while and love it, which is why I'd like to get past this TypeError to compile via pyinstaller using latest version 5.0.3.

Example code:


      import customtkinter as ct
      
      class Application(ct.CTkFrame):
      
          ct.set_appearance_mode("system")
          ct.set_default_color_theme("dark-blue")
      
          def __init__(self):
              super(Application, self).__init__()
              
              #functions and buttons here
      
      window = ct.CTk()
      app = Application()
      window.mainloop()

**Comment by Akascape** [comment]
@lachesis17 You have to specify the master:
```python
```

**Comment by lachesis17** [comment]
> @lachesis17 You have to specify the master window:
> 
> ```python
> super(Application, self).__init__(window)
> ```
> 
> Also, don't forget to replace some parameters like `text_font` with `font`. Here is the [full changelog](https://github.com/TomSchimansky/CustomTkinter/blob/master/CHANGELOG.md) for the new version.

Ah I did try passing the master window but for some reason got the "init has 4 arguments instead of 3" error but actually this suggestion fixed it - I totally missed the text_font change which might have been throwing me, thanks!
