### ISSUE TITLE
state=disabled/enabled never becomes enabled again

### ISSUE THREAD

**Issue by cfivek** [TomSchimansky/CustomTkinter#1049]
I have not tested this on all widgets but those I have tested on are being affected by this.

widget.configure(state="disabled") Once this is triggered on a CTkCheckBox it becomes unclickable despite further toggles

If used for CTkButton the button is still clickable following re-enable, but it no longer becomes highlighed on a mouseover

**Comment by Akascape** [comment]
@cfivek when you want to enable a button, use `state='normal'` instead of `state='enabled'`

```python
btn.configure(state = 'normal')
```

**Comment by cfivek** [comment]
Thx.
