### ISSUE TITLE
Can you add line-height on CTkLabel ?

### ISSUE THREAD

**Issue by felle9900** [TomSchimansky/CustomTkinter#105]
Hello and thanks for the great work!
Could you add the possibility to change the line-height (in px) on CTkLabel ?

**Comment by TomSchimansky** [comment]
Hi, what do you mean by changing the line height, do you mean the height attribute of the label? Or the number of lines in the label? The number of lines only depends on the given text.

**Comment by felle9900** [comment]
Im building a pdf step and repeat (nup) program, and when I select a pdf-file, I currently now have a CTkLabel showing some multi-line information about the selected pdf like, mediaBox size, trimBox size, build program, build date etc...

but I don't want the lines underneath each other so close, because that's to narrow for my design taste. So currently I use 2 line breaks as my only alternative "\n\n" but I would love to be able to set the line-height of a 12 px font to maybe 20 px instead of instead of some standard 15 px

**Comment by felle9900** [comment]
Thank you for your time. John's trick is nice, but I'll wait a little, its only a cosmetic upgrade for me.
Probably a Treeview would be better for me, with a alternate line bg_color - is that in the pipeline ?

**Comment by TomSchimansky** [comment]
I want to create a table at some point in the future, but before this, there are a lot of other things that need to be done.
