### ISSUE TITLE
[Question] Is there a way to add CustomTkinter without having to use pip?

### ISSUE THREAD

**Issue by Ahmed-E-86** [TomSchimansky/CustomTkinter#1050]
I just have a question about CustomTkinter if you do not mind.
Is there a way to add CustomTkinter to my project without having to use `pip3 install customtkinter`?

I have used a theme before, and all I had to do is copying some files to my project folder, then using import theme_name, and that is it. Is that even possible with CustomTkinter?

**Comment by Akascape** [comment]
@Ahmed-E-86 Yes, you just need the folder `customtkinter` in the same directory where your program is present. It will then import it as a local module.
You can download a copy of that folder.

**Comment by cmdeejay** [comment]
In your project folder, run: 

Git clone https://github.com/TomSchimansky/CustomTkinter.git 

and then just import it in your project.

**Comment by Ahmed-E-86** [comment]
> @Ahmed-E-86 Yes, you just need the folder [`customtkinter`](https://github.com/TomSchimansky/CustomTkinter/tree/master/customtkinter) in the same directory where your program is present. It will then import it as a local module. You can download a copy of that folder.

I tried that with the example in the repo, and it fired a lot of errors, and I tried a lot of different themes that did not look better, so I gave up, and used 'clam' as the default Tkinter theme. Thanks anyway for your suggestion.
