### ISSUE TITLE
CTkTextbox .get method returning error

### ISSUE THREAD

**Issue by BenjaminTGa** [TomSchimansky/CustomTkinter#1057]
Hi,
I'm using the CTkTextbox in my program and it's returning an error when I try to use the `get` method to retrieve the text from it.
My code looks like this:
```python
global mainText
mainText = customtkinter.CTkTextbox(master=self, width=500, height=500, font=("arial", 14))
#lots of code later...
textToCopy = mainText.get(index1=1, index2=10)
pyperclip.copy(textToCopy)
print(textToCopy)
```
I had a peek at #602 and at #378 but they suggest that the CTkTexbox is still under development, but these questions were a while age and I'm not sure if I can use these methods yet, or if I'm making a mistake with the syntax.
Thanks!

**Comment by M4hbod** [comment]
use
index1=1.0, index2=10.0

**Comment by BenjaminTGa** [comment]
Ok, thanks!
