### ISSUE TITLE
Disabled Widgets are not immediately identifiable from Enabled widgets...

### ISSUE THREAD

**Issue by TheWicklowWolf** [TomSchimansky/CustomTkinter#1063]
Here is an example with CustomTkinter:

![ct1](https://user-images.githubusercontent.com/111055425/212883332-969cc7ac-02d4-4f4e-afcc-717fa4be3fa1.PNG)

![ct2](https://user-images.githubusercontent.com/111055425/212883334-e227c1b5-065e-477c-8b03-9f8e2409b85f.PNG)

---
Here is an example with ttk:

![UbuntuTk](https://user-images.githubusercontent.com/111055425/212883664-fcabb8ee-9a03-4ad9-a8a7-f3f31224f29a.PNG)

Fantastic library by the way!

**Comment by Wolf-SO** [comment]
@TheWicklowWolf there is obviously an issue with `CTkEntry`: it doesn't support a `text_color_disabled` whereas `CTkButton` does. So I'd suggest you to change the issue's summary to something less abstract as to rise the chance to get this fixed.

**Comment by TheWicklowWolf** [comment]
@Wolf-SO Fair point on the `CTkEntry`, I was also referring to background colour as-well.
But this is probably more of a feature request rather than an issue, and I'd imagine there are higher priority issues.

**Comment by cristian64** [comment]
I came here looking for this issue.

Graying out the label does not seem sufficient to tell the widget states apart. They are still too similar. It's almost as if `fg_color_disabled` needs to be introduced in the themes.

**Comment by TheWicklowWolf** [comment]
Any joy with this?

**Comment by randose** [comment]
@TomSchimansky great library, major improvement over basic tk. I agree with this issue - adding fg_color_disabled for buttons would be great and make for cleaner code.
