### ISSUE TITLE
Update label text

### ISSUE THREAD

**Issue by dwburger** [TomSchimansky/CustomTkinter#1065]
I'm updating text of a label with the following code:

```
    update_label = ctk.CTkLabel(valve_info_frame, text= "                       ")
    update_label = ctk.CTkLabel(valve_info_frame, text= "Running valves...")
    update_label.grid(row=10, column=0, padx=20)
    valve_info_frame.update()
```
The updated text overwrites previous text and if the new text is shorter than existing text, the previous text remains.  I tried to write over the text with blanks, but it doesn't work.  What am I doing wrong???  Thanks for any help!

**Comment by Akascape** [comment]
@dwburger You don't need to define the update label again and again. 
There is a method called `configure` that you can use to update the text and other parameters.

```python
update_label.configure(text='New_Text')
```

**Comment by dwburger** [comment]
Thanks!

**Comment by TranHuuHieu15** [comment]
> @dwburger You don't have to define the update label again and again. There is a method called `configure` that you can use to update the text and other parameters.
> 
> ```python
> update_label.configure(text='New_Text')
> ```

i try it but it not work
