### ISSUE TITLE
Any suggestions on how I can track down a customtkinter graphics issue? 

### ISSUE THREAD

**Issue by diarmaidocualain** [TomSchimansky/CustomTkinter#1073]
I have two Ubuntu installations. On one, apps made with customtkinter (for example, the simple_example.py) look great. 
However, on my second installation, the same app looks like this: 

![image](https://user-images.githubusercontent.com/5493218/213423896-bea95f62-1662-485a-bdbc-6a41dc126d3e.png)

Would anyone know of what might be causing the issue? 
For reference, I am using a conda virtual environment on both Ubuntu environments. I installed customtkinter using pip. This is the versions of the packages that are installed: 

customtkinter==5.0.3
darkdetect==0.8.0
Ubuntu 22.04.1 LTS
python3-tk_3.10.6-1~22.04_amd64.deb

Thanks!

**Comment by TomSchimansky** [comment]
The problem is that the font needed for rendering could not be loaded. I think there was a problem with conda, but I don't know why this is not working.

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/300
