### ISSUE TITLE
The geometry method behaves incorrectly on 4K monitor

### ISSUE THREAD

**Issue by Leonwenbin** [TomSchimansky/CustomTkinter#1075]
My code here
```python
from customtkinter import CTk

window = CTk()
window_width = 500
window_height = 300
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
window_pos_x = int((screen_width - window_width) / 2)
window_pos_y = int((screen_height - window_height) / 2)

window.geometry(f'{window_width}x{window_height}+{window_pos_x}+{window_pos_y}')
window.mainloop()
```
As you can see, I want to center my window in the screen. When i run the code, the position of the window is in the upper left corner, but it works fine on other low resolution screens, for example 2K, 1080p.

Just like in the picture
![example](https://user-images.githubusercontent.com/56778345/213491915-cf987d9e-4a43-4c74-8998-ff82f3f0e3f8.png)

Could you reply me? thank you very much!

**Comment by TomSchimansky** [comment]
.geometry() should work correctly. But the winfo_screenwidth() method is not implemented for CustomTkinter, so it returns wrong values, it will probably return the true size of the monitor which is 3840x2160 for a 4K monitor. But it has probably 2x scaling, and the values for CTk are independent of scaling so with a window size of 1920x1080 your method of entering the window should work.

I will implement the winfo methods to be indpenedent of scaling soon.

**Comment by Leonwenbin** [comment]
> .geometry() should work correctly. But the winfo_screenwidth() method is not implemented for CustomTkinter, so it returns wrong values, it will probably return the true size of the monitor which is 3840x2160 for a 4K monitor. But it has probably 2x scaling, and the values for CTk are independent of scaling so with a window size of 1920x1080 your method of entering the window should work.
> 
> I will implement the winfo methods to be indpenedent of scaling soon.

I see. I'm looking forward to your update.

**Comment by robochopbg** [comment]
Good day. 
I also have this issue with a HD screen 1920x1080.
CustomTkinter does not position the window in the center.
So when will custometkinter support winfo_screenwidth() and winfo_screenheight() ??
Does it even support - winfo_width / winfo_height / winfo_rooty / winfo_y etc ??
