### ISSUE TITLE
filedialog.askdirectory() CustomTkinter

### ISSUE THREAD

**Issue by c0d3r911** [TomSchimansky/CustomTkinter#1079]
How i can use choose folder option, like filedialog.askdirectory() in tk?

**Comment by supercam19** [comment]
Importing from regular tkinter should be fine
```python
from tkinter import filedialog
filedialog.askdirectory()
```

**Comment by c0d3r911** [comment]
> Importing from regular tkinter should be fine
> 
> ```python
> from tkinter import filedialog
> filedialog.askdirectory()
> ```

GUI looks very old

**Comment by TomSchimansky** [comment]
You can do:
```python
from customtkinter import filedialog
filedialog.askdirectory()
```
I can't do anything about the appearance of the filedilaog. If you want an other file dialog you have to use a library that's not based on Tk, for example Qt.
