### ISSUE TITLE
"invalid command name" error while pressing a button

### ISSUE THREAD

**Issue by BatelG** [TomSchimansky/CustomTkinter#109]
Hi,
I keep receiving the following error while I pressing the Button widget:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/72447351/170122967-e903287f-b15c-4200-b00c-3129c18c76ef.png">
The GUI is working fine and the command methods are executing with no problems, but the error keep showing in the console log.
Thank you.

**Comment by TomSchimansky** [comment]
Hi, I will try to fix this.

**Comment by TomSchimansky** [comment]
Can you post an example code where this appears for you?

**Comment by BatelG** [comment]
*This happens for each button I press, with no connection to the action of
the command method, for example:*

self.folder_btn = customtkinter.CTkButton(master=self.frame_left,
image=folder_image,

text="", width=30, height=30,
                                          compound="left", command=self
.__show_in_explorer_btn_handler)
self.folder_btn.grid(row=6, column=0, pady=0, padx=0, sticky="n")

def __show_in_explorer_btn_handler(self):
self.destroy()

*No exception is thrown, only printed to the console, but all is working
fine.*

**Comment by Think-IT-think-gui** [comment]
Did you places the button in a function managed by a separate thread?

**Comment by BatelG** [comment]
No, I didn't.

**Comment by Think-IT-think-gui** [comment]
Because that was what I did in mine that gave me similar prompt

**Comment by TomSchimansky** [comment]
This shouldn't happen in the current version, at least for m it is not reproducible.

**Comment by BatelG** [comment]
Ok, I will look into it. Thank you!
