### ISSUE TITLE
 hover color, tuple: (light_color, dark_color)

### ISSUE THREAD

**Issue by c0d3r911** [TomSchimansky/CustomTkinter#1115]
CTkButton hover_color | hover color, tuple: (light_color, dark_color) or single color

any examples? How to use?
I have need to change colors in white and dark theme

**Comment by ElectricCandlelight** [comment]
From the wiki under Themes and colours
`button = customtkinter.CTkButton(root_tk, fg_color=("#DB3E39", "#821D1A"))  # tuple color`

**Comment by c0d3r911** [comment]
Thanks!
