### ISSUE TITLE
set application icon not working in 5.0.5

### ISSUE THREAD

**Issue by emcek** [TomSchimansky/CustomTkinter#1125]
With `5.0.3` both are working, I can see app icon in upper left corner:
```python
import customtkinter
from PIL import ImageTk

def one():
    root = customtkinter.CTk()
    root.iconbitmap('d.ico')
    root.mainloop()

def two():
    root = customtkinter.CTk()
    root.iconphoto(False, ImageTk.PhotoImage('d.png'))
    root.mainloop()
```
But in `5.0.4` and `5.0.5` none!

Releated to: #839 and #837

Python 3.10
Windows 10 (22H2)

**Comment by emcek** [comment]
Looks like commit 8a537076cebc4adeb7003e8287f2fa8698392413 is related to this issue.

**Comment by emcek** [comment]
Fixed with [5.1.0](https://github.com/TomSchimansky/CustomTkinter/releases/tag/v5.1.0)

**Comment by Martin-Ferrand** [comment]
Hello, with ```5.1.2``` the following code is not working. There is an icon on top left but not the one expected.

```python
from PIL import ImageTk
import customtkinter

root = customtkinter.CTk()
root.iconphoto(False, ImageTk.PhotoImage(file='settings.png'))
root.mainloop()
```

I have tried to use version ```5.1.0``` as mentioned above to no avail.

Python 3.11
Windows 10

**Comment by emcek** [comment]
> I have tried to use version `5.1.0` as mentioned above to no avail.
> 
> Python 3.11 Windows 10
It was working with version `5.0.3`. With newest you need `ico` type and first method. Or open new issue.

**Comment by dishb** [comment]
Hi, I'm using using the
```python
.iconbitmap("...")
```
method to set an icon for my `customtkinter` window. When I try to set the icon (which is a `.png` file), I don't see the appear. I instead see a "document"-looking icon next to the title of the window.

The code for my project can be found [here](https://github.com/dishb/hive/blob/9185f9661dbf6458fbac8aea45332bfb40ae011d/hive.py).
The image I'm using can be found [here](https://github.com/dishb/hive/blob/9185f9661dbf6458fbac8aea45332bfb40ae011d/src/icon.png).

Machine: Macbook Air running `macOS 12.6.5`.
Python: `python 3.11.2`.
Customtkinter: Unsure - will add once I get home and check.

**Note:** I don't get any exceptions/errors raised by my code.

**Comment by Ricc4rdo0107** [comment]
Same to me
