### ISSUE TITLE
I get an error image "pyimage8" doesn't exist

### ISSUE THREAD

**Issue by wordofday** [TomSchimansky/CustomTkinter#1126]
If I change the code up and make some error once and then fix the error, I get the above error unless I restart the kernel. Anyone come across that?

The full error looks like the following:

in __init__
    self.navigation_frame_label = customtkinter.CTkLabel(self.navigation_frame, text="  Custom Tkinter", image=self.logo_image,

  File ~\anaconda3\Lib\site-packages\customtkinter\windows\widgets\ctk_label.py:93 in __init__
    self._update_image()

  File ~\anaconda3\Lib\site-packages\customtkinter\windows\widgets\ctk_label.py:130 in _update_image
    self._label.configure(image=self._image.create_scaled_photo_image(self._get_widget_scaling(),

  File ~\AppData\Local\Programs\Spyder\pkgs\tkinter\__init__.py:1646 in configure
    return self._configure('configure', cnf, kw)

  File ~\AppData\Local\Programs\Spyder\pkgs\tkinter\__init__.py:1636 in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))

TclError: image "pyimage8" doesn't exist

**Comment by TomSchimansky** [comment]
How was the image created?

**Comment by mvolar** [comment]
I always get the error when launching from Anaconda Spyder IDE if the application ended with an interruption/error. It is a known error of [tkinter/spyder interaction](https://stackoverflow.com/questions/24274072/tkinter-pyimage-doesnt-exist) and not an error of this project per se. Either switch your IDE, or have a seperate powershell/anaconda/terminal session open from which you run your script if you are used to the look and feel of Spyder.

**Comment by wordofday** [comment]
Thank you! That makes a lot of sense. I am using Spyder, but I guess I can try and run it through a separate terminal as you mentioned. I appreciate the quick response!
