### ISSUE TITLE
_tkinter.TclError: named font "font2" doesn't exist

### ISSUE THREAD

**Issue by LeonPupier** [TomSchimansky/CustomTkinter#114]
```python
customtkinter.CTkLabel( self.scrollable_frame_discution, text="Hello", text_font=self.font_message, wraplength=190, fg_color=("gray70", color_focus), width=20).grid(row=0, column=0, sticky=tkinter.E)
```
I get this error after executing the instruction above:
> **Traceback (most recent call last):**
>   **File "C:\Users\badwi\Desktop\Exchange Network\app.pyw", line 321, in <module>**
>     app = App()
>   **File "C:\Users\badwi\Desktop\Exchange Network\app.pyw", line 166, in __init__**
>     customtkinter.CTkLabel( self.scrollable_frame_discution, text="Hello", text_font=self.font_message, wraplength=190, fg_color=("gray70", color_focus), width=20).grid(row=0, column=0, sticky=tkinter.E)
>   **File "C:\Program Files\Python310\lib\site-packages\customtkinter\widgets\ctk_label.py", line 56, in __init__**
>     font=self.apply_font_scaling(self.text_font),
>   **File "C:\Program Files\Python310\lib\site-packages\customtkinter\widgets\widget_base_class.py", line 224, in apply_font_scaling**
>     if font.cget("size") < 0:
>   **File "C:\Program Files\Python310\lib\tkinter\font.py", line 143, in cget**
>     return self._call("font", "config", self.name, "-"+option)
> **_tkinter.TclError: named font "font2" doesn't exist**
> 
> _Process finished with exit code 1_

I use version 1.4.0 of customtkinter, since I updated the package I get this problem...

**Comment by TomSchimansky** [comment]
How is `self.font_message` defined?

**Comment by LeonPupier** [comment]
Like this:
`self.font_message = tkFont.Font(family="Segoe UI", size=9)`

**Comment by LeonPupier** [comment]
I import it like this:
`import tkinter.font as tkFont`

**Comment by TomSchimansky** [comment]
Ok, I don't get this error, maybe it will help if you store the label in a variable, because otherwise it will get garbage collected at some point:
```python
self.label = customtkinter.CTkLabel( self.scrollable_frame_discution, text="Hello", text_font=self.font_message, wraplength=190, fg_color=("gray70", color_focus), width=20)
self.label.grid(row=0, column=0, sticky=tkinter.E)
```

A quick fix would be to define the font as a tuple: `self.font_message = ("Segoe UI", 9)`

**Comment by LeonPupier** [comment]
Indeed by defining the fonts with tuples the program works, thanks a lot!

**Comment by LeonPupier** [comment]
I also wanted to know if the HightDPI support can be disabled?

**Comment by TomSchimansky** [comment]
But then the app will be blurry on 4K displays or with higher scaling than 100% on Windows.

**Comment by LeonPupier** [comment]
A yes I understand, thank you very much for your help, your work and your responsiveness.
I have no more requests :)
