### ISSUE TITLE
CTkProgressbar indeterminate mode

### ISSUE THREAD

**Issue by brandon-yilmaz** [TomSchimansky/CustomTkinter#115]
Hi,

Is it possible to establish an 'indeterminate' mode in the CtkProgressbar?

thanks

**Comment by TomSchimansky** [comment]
No, currently not. But maybe I will add this at some point.

**Comment by brandon-yilmaz** [comment]
Is there any example about how to use the CTkProgressbar ? Doesn't seem quite obvious to me!
thanks in advance

**Comment by TomSchimansky** [comment]
Did you look at the wiki: https://github.com/TomSchimansky/CustomTkinter/wiki/CTkProgressBar
You can also set the value with a tkinter variable (IntVar), which is not mentioned in the wiki (pass the variable with the `variable` attribute).

**Comment by TomSchimansky** [comment]
I added indeterminate mode with version 4.6.0. Check out the wiki for more information.
