### ISSUE TITLE
The CTkImage class does not exist?

### ISSUE THREAD

**Issue by eporto2021** [TomSchimansky/CustomTkinter#1183]
Hey Tom,

I can't find the CtkImage class

I'm encountering the following error 

 AttributeError: module 'customtkinter' has no attribute 'CTkImage'

**Comment by eporto2021** [comment]
I've figured out a work around.

If anyone else has the same issue, then, using the "ImageTk" class from Pillow instead of the "CtkImage" class from customtkinter (my best guess is that "CtkImage" was removed from customertkinter in a recent update - not sure though) as below might help:

from PIL import ImageTk
image_3_path = str(os.path.join(image_path, "124010.png"))
img3=ImageTk.PhotoImage(Image.open(image_3_path).resize((20,20), Image.ANTIALIAS))

**Comment by TomSchimansky** [comment]
I don't know what's the problem but maybe you have another folder or file named customtkinter in your directory? The CTkImage class should work fine.
