### ISSUE TITLE
Click Text to select radiobuttons and checkboxes?

### ISSUE THREAD

**Issue by DomGravante** [TomSchimansky/CustomTkinter#119]
In Tk, selecting the text next to a radiobutton/checkbox will toggle that box and run the command, whereas in CTk it does not. The only way to toggle it in CTk is to actually click the square/circle button. Is this a limitation in the way the program draws to the canvas?

Also doesn't run on the complex example given, so I'm pretty sure it's not my code but it might be.

Thanks! Couldn't find if this was asked before.

**Comment by TomSchimansky** [comment]
I can implement this, in the next release it should work...

**Comment by TomSchimansky** [comment]
It's now possible with version 4.2.0.
