### ISSUE TITLE
Label background

### ISSUE THREAD

**Issue by 2Beelzebub2** [TomSchimansky/CustomTkinter#120]
I am making a school project, and right now I'm having a problem with the label's backgrounds.
![image](https://user-images.githubusercontent.com/105885878/170829847-7dffbc57-6651-4509-8cc4-be0d44ac2b5f.png)
![image](https://user-images.githubusercontent.com/105885878/170829919-79620de3-15b3-46fb-a428-2eb3aae61fe0.png)

the objective is to make the label's background the same as the frame in both dark and light themes, and if possible remove the little different color on the edges of the buttons.
![image](https://user-images.githubusercontent.com/105885878/170829883-74a87b90-9c47-47d7-a39d-f1b4b2f1a9c6.png)
![image](https://user-images.githubusercontent.com/105885878/170829922-d3f5c3fe-5ac9-4a6f-b162-bcb27b771dba.png)

**Comment by TomSchimansky** [comment]
Can you post your code? How do you create the frame where the buttons are placed on?

**Comment by Think-IT-think-gui** [comment]
Try creating another frame on that frame

or

check the hex color value of the frame in light and dark mode I thing it 333333 and dedede and 
move to the  change_mode function and try configuring your buttons and labels under each condition 
as shown below 


def change_mode():
        if switch_2.get() == 1:
          set_appearance_mode("dark")
          Your_button.config(bg="#333333",activebackground="#333333")
          Your_Label.config(bg="#333333")
        else:
          set_appearance_mode("light")
          Your_button.config(bg="#dedede",activebackground="#dedede")
          Your_Label.config(bg="#dedede")

**Comment by 2Beelzebub2** [comment]
I forgot to say but I got it, I was putting the labels on the wrong frame i had label(root_tk,...) and i needed label(Frame2,....)
