### ISSUE TITLE
Error when using pyinstaller

### ISSUE THREAD

**Issue by iaZe** [TomSchimansky/CustomTkinter#1202]
As you can see in the example below, I have this error when using pyinstaller on a file that contains import from customtkinter

![image](https://user-images.githubusercontent.com/62972715/217344319-bccc79e1-418f-438e-9a1c-4d40347593aa.png)

**Comment by UserJoo9** [comment]
@iaZe try to use method in Wiki page, 
otherwise try to downgrade the pip to 22.2.2

**Comment by Nomeon** [comment]
@iaZe Please check [this discussion](https://github.com/TomSchimansky/CustomTkinter/discussions/423#discussioncomment-3549223) for some more information/guidance.

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

**Comment by kennarttech** [comment]
Sir please Error when using cx_Freeeze
![Screenshot (19)](https://user-images.githubusercontent.com/122741553/218773209-5f7fa371-6889-4753-a6db-9722792cd102.png)
![Screenshot (20)](https://user-images.githubusercontent.com/122741553/218773227-33cbee5c-7182-4484-9559-7160d576118c.png)

**Comment by kennarttech** [comment]
Sir please i'm using cx_freeze to freeeze the script but this is the error i'm getting (raise ConfigError(f"cannot find file/directory named {source!s}")
cx_Freeze.exception.ConfigError: cannot find file/directory named icons.

and i want to ask how do i include the path of the icon into my cx_freeze script
