### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by MLietzow** [TomSchimansky/CustomTkinter#122]
Hey,
sometimes I am getting an error `ValueError: invalid literal for int() with base 10: ''` at customtkinter/windows/ctk_toplevel.py, line 87, in apply_geometry_scaling, and line 110, in geometry:
`numbers = list(map(int, re.split(r"[x+]", geometry_string)))  # split geometry string into list of numbers`.
The reason is an empty string in the resulting list if `geometry_string` is, e.g., '+50+95'.
`numbers = [int(num) for num in re.split(r"[x+]", geometry_string) if num != '']` solved my problem.
Thank you!

(MacOS 10.14.6, python 3.9.12)

**Comment by ciobania** [comment]
Can bypass that by changing the regex: 
`numbers = list(map(int, re.findall(r"\d+", geometry_string)))`

no need to check for empty strings, since you only want to get the geometry numbers.
Tested it with all possible values. ;)

**Comment by TomSchimansky** [comment]
This should be fixed now with version 4.2.0.
