### ISSUE TITLE
app.state("zoomed") does not work after v5.1.2 update

### ISSUE THREAD

**Issue by ASH1998** [TomSchimansky/CustomTkinter#1223]
After updating to version : v5.1.2
"Zoomed State" does not work anymore, it zooms and reverts back to "normal" state.
I have tried this with older version, and they work correctly. 

OS : Windows 11
Python : 3.10

### Sample : 
```python
from customtkinter import CTk

root = CTk()
root.state('zoomed')
root.mainloop()
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23384411/218378537-8986a09e-1acf-4ea3-aea0-5f1b27adc82a.gif)

Tried this with all other options like `root.wm_state`, `attributes` etc, none of these work.

**Comment by kennarttech** [comment]
please i think there is a problem with your import of customtkinter, so what you have to do is.


""" from customtkinter import CTk
root = CTk()
root.state('zoomed')
root.mainloop()"""


[instead of doing it like that just look at my own]

import customtkinter

root = customtkinter.CTk()
root.title('my new window')
root.geometry('500x500')
root.state('zoomed)      <====[this zoomed worked perfectly on windows]

root.attributes('-zoomed, True)   <====[this works fine on kali linux because that is the os i'm using]






root.mainloop()

**Comment by ElectricCandlelight** [comment]
Try this work around.

```
from customtkinter import CTk

def maximize():
    root.state('zoomed')

root = CTk()
root.after(0, maximize)
root.mainloop()
```

**Comment by Wolf-SO** [comment]
Try setting your code in triple backticks:

   ```python

   from customtkinter import CTk
   # etc.
   ```
see *[Creating and highlighting code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks "Creating and highlighting code blocks - GitHub Docs")* for details

**Comment by ASH1998** [comment]
> please i think there is a problem with your import of customtkinter, so what you have to do is.
> 
> """ from customtkinter import CTk root = CTk() root.state('zoomed') root.mainloop()"""
> 
> [instead of doing it like that just look at my own]
> 
> import customtkinter
> 
> root = customtkinter.CTk() root.title('my new window') root.geometry('500x500') root.state('zoomed) <====[this zoomed worked perfectly on windows]
> 
> root.attributes('-zoomed, True) <====[this works fine on kali linux because that is the os i'm using]
> 
> root.mainloop()

This does not work. 
The way you initialized is just different, this does not do anything different from what I shared. I am assuming you are new, so thanks for the help nonetheless.
Also there is a syntax error my man. Please run the code before posting. Thanks and keep it up!

**Comment by ASH1998** [comment]
> Try this work around.
> 
> ```python
> from customtkinter import CTk
> 
> root = CTk()
> root.after(0, lambda:root.state('zoomed'))
> root.mainloop()
> ```

Thanks @ElectricCandlelight 
This works. 

But am curious what changes were made post v5.0.5 that regular stuff does not work. @TomSchimansky @Wolf-SO 
I am thinking this [particular code](https://github.com/TomSchimansky/CustomTkinter/compare/v5.0.5...v5.1.0#diff-e89ade0594cc8e7c9e21a75c268853bbeb416d6176f4c2cf6ccdf18a7f3f4fe0R321:~:text=to%20be%20called-,if%20self.focused_widget_before_widthdraw%20is%20not%20None%3A,self.focused_widget_before_widthdraw%20%3D%20None,-def%20_set_appearance_mode( ) might be what is affecting this.
