### ISSUE TITLE
AttributeError: module 'customtkinter' has no attribute 'CTkScrollableFrame'

### ISSUE THREAD

**Issue by Vaman19** [TomSchimansky/CustomTkinter#1232]

**Comment by Wolf-SO** [comment]
I cannot reproduce this. What version of `customtkinter` are you using?

You can get it in IDLE:

```python
>>> import customtkinter
>>> customtkinter.__version__
```
... or in the console:

```con
pip show customtkinter
```

**Comment by Vaman19** [comment]
5.0.5 and using vs code

**Comment by ElectricCandlelight** [comment]
Update to the newest version. 

`pip3 install customtkinter --upgrade`

Pretty sure CTkScrollableFrame wasn't added till version 5.1.0

**Comment by Wolf-SO** [comment]
[Implementation started on Feb, 4. 2023](https://github.com/TomSchimansky/CustomTkinter/commit/a478334fb706edbe764c95f14e9df2efe28cf4bc), 5.0.5 was released on Jan, 22. 2022

**Comment by Vaman19** [comment]
thankyou for help the widget is now working when I updated the package.
