### ISSUE TITLE
Try to build app with MacOS

### ISSUE THREAD

**Issue by simon88** [TomSchimansky/CustomTkinter#1238]
Hi,

I'm trying to packaging like it's describre [https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging](url) with my Mac but it's doesn't work.

`pip show customtkinter`rturns to me `/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/` my full command is `pyinstaller --noconfirm --onedir --windowed --add-data /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/customtkinter;customtkinter/ test.py` 

but I always got this error : `pyinstaller: error: argument --add-data: invalid add_data_or_binary value: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/customtkinter'` what should I do ?

**Comment by xwydq** [comment]
same ！！+1

**Comment by simon88** [comment]
Find the solution change `customtkinter;customtkinter`to `customtkinter:customtkinter`for Mac
