### ISSUE TITLE
Facing problems using bind

### ISSUE THREAD

**Issue by iaZe** [TomSchimansky/CustomTkinter#1240]
I've tried to use bind in several ways but it never works.... I've always used it the following way
``` 
self.bind("<Return>", self.master.order_registration)
```
But it does not work

**Comment by Wolf-SO** [comment]
Please provide a minimal example (script in text from) that reproduces the issue! Thanks.

The following script, for example, **doesn't reproduce** the issue:

```python
import customtkinter

def on_return(event):
    print("Return", event)

root = customtkinter.CTk()
root.bind("<Return>", on_return)
root.mainloop()
```

**Comment by Wolf-SO** [comment]
BTW, as already indicated by the title *“How to use bind?”* of this entry, it would have been better to post it in [Discussions (Q&A)](https://github.com/TomSchimansky/CustomTkinter/discussions/806#discussion-4639794).

(I know that @TomSchimansky can easily move it there.)

**Comment by iaZe** [comment]
> Binding it to the wrong thing. If it's for a log on forum bind the return key to the text entry box instead.

It even works, but only when I have the box active. Which sounds like a go horse since it should work just being on the screen like with tkinter. However, I'll leave the idea for a next ft

**Comment by ElectricCandlelight** [comment]
That's how bind for key works even in tkinter. It uses what ever widget is currently in focus. Hence why it's working when you have the frame active. 

Hence why I suggested having it on the entry widget user types in password and presses return which will trigger it
