### ISSUE TITLE
Scrollable Frame issue (AttributeError)

### ISSUE THREAD

**Issue by nikita276956** [TomSchimansky/CustomTkinter#1253]
when I try to use CTkScrollableFrame
it types: AttributeError: module 'customtkinter' has no attribute 'CTkScrollableFrame'

**Comment by ElectricCandlelight** [comment]
Possible duplicate of #1232 

Please try upgrading to the latest version

```pip3 install customtkinter --upgrade```

**Comment by nikita276956** [comment]
Thanks it worked!

בתאריך יום ב׳, 20 בפבר׳ 2023, 16:31, מאת ElectricCandlelight ‏<
***@***.***>:
