### ISSUE TITLE
CTkOptionMenu "command" parameter not working

### ISSUE THREAD

**Issue by louislautz** [TomSchimansky/CustomTkinter#129]
I tried to use the CTkOptionMenu Widget and want to execute a function when the value changes. I checked out the widgets code and saw that it has a "command" parameter, just like a button or checkbox. However, when I run the simple_example.py with the CTkOptionMenu widget and add a function to it like so: 
`optionmenu_1 = customtkinter.CTkOptionMenu(master=frame_1, values=["Option 1", "Option 2", "Option 3"], command=test_function)`, the test_function is not getting executed.

Other than that I really loves this project though ;P

**Comment by TomSchimansky** [comment]
It is working, but the selected string gets passed to the function as a parameter, so the callback function needs to have one attribute. I catch this error in the current version but that's a fail, I will change this.
