### ISSUE TITLE
The background color does not change

### ISSUE THREAD

**Issue by dmitroard** [TomSchimansky/CustomTkinter#1290]
![image](https://user-images.githubusercontent.com/124613856/221911978-465a0956-60e6-4ad0-a728-f1c3f083c700.png)

I tried different ways, but the white color does not change. Here is a piece of code

![image](https://user-images.githubusercontent.com/124613856/221912135-2b598b30-4e4a-4736-9236-71610153d889.png)

![image](https://user-images.githubusercontent.com/124613856/221912199-09c4dccf-4eea-4656-b520-a18ad18d25a5.png)

**Comment by Akascape** [comment]
@dmitroard Try adding `bg_color="#242424"` parameter to the ctk switch. (Also change the text_color or else the text will not be visible)

**Comment by TomSchimansky** [comment]
Maybe it's because of your self-made scrollable frame? There is a CTkScrollableFrame class with which everything should work fine.
