### ISSUE TITLE
Scroll frame with horizontal and vertical scrollbar

### ISSUE THREAD

**Issue by liturriago** [TomSchimansky/CustomTkinter#1294]
Is there a way to create a Scroll Frame that integrates a horizontal Scrollbar and a vertical Scrollbar at the same time?, that they can be both at the same time

**Comment by TomSchimansky** [comment]
No that's not possible at the moment, I don't remember why, but there were some problems and therefore I decided not to implement this.

**Comment by AnonymousVibrate** [comment]
Therefore there is no hope for this to enable BOTH orientation ?
