### ISSUE TITLE
Attr.Error for CTkFrame

### ISSUE THREAD

**Issue by pourhakimi** [TomSchimansky/CustomTkinter#130]
Hi, 

I was using the CTk module for a project, mainly on customtkinter==3.7.0, however, when I upgraded to the latest version (4.3.0 I think), I could not run my code because I kept getting the error: 

**[AttributeError, CTkFrame does not have the width option]**

So I uninstalled and reinstalled customtkinter back to version 3.7.0 and it worked fine. I tried version 4.0.0, but I got the same error. 

Is this an issue with the module, or perhaps with my coding? 

Thanks in advance.

**Comment by TomSchimansky** [comment]
Can you show an example of your code?

**Comment by pourhakimi** [comment]
Sounds good - I will need to figure out a way to get a specific width because the standard CTkEntry has a fixed width and this may be too short or too long. But I will try playing around with the code and see what happens. Thanks again!
