### ISSUE TITLE
Scrolable frame, "Dragging", Chocking, canvas size limit?

### ISSUE THREAD

**Issue by ZerducK** [TomSchimansky/CustomTkinter#1306]
I'm getting info from google sheets using sheet api and to display it i create scrollable frame.
And for each  list in list of lists that i get from DB, i create a scrollable frame(so that if there not much screen real-estate u still could see the info by scroll, fixed height because amount of labels is static and i can predict how much px i need.), amount of lists was like 10, so i thought i would test it on scale before sticking to it, i created ~100 entries in DB and then this happened.

As u can see on the video there is weird tracing of previous frames, i compiled and tested same, tested on different machine fine, i assume it's some weird driver or system interactions, but if this was the only problem.

Basically when there 2-3 filtered values it's ok, but when i disable filter and all values displayed its starts to behave very weird, moving or resizing window is basically Win XP style without tracers and ~30% of generated frames is gone, not displayed or kinda weirdly stuffed.
I assume it's canvas size limit, of some sort? 
Any recommendations how to get around that?

Here is the video:
[https://www.youtube.com/watch?v=3yuqvOnjXxk](url)

Here is the code that i use to display items:

`mainframe2 = tk.Frame(master=app)
mainframe2.pack(padx=5, pady=5, fill=tk.BOTH, expand=tk.TRUE)

info_frame = customtkinter.CTkScrollableFrame(mainframe2)
info_frame.place(relwidth=0.5, relheight=1)

cart_frame = customtkinter.CTkScrollableFrame(mainframe2)
cart_frame.place(relwidth=0.5, relheight=1, relx=0.5)

def createitem():
    
    for frame in info_frame.winfo_children():
        frame.destroy()
        
    values_to_delete = []    
    rowid = 0
    columnid = 0
    deckrowid = 0
    deckcolumnid = 0
    
    
    for item in values:
        for x in item:
            if combobox0.get() != "Не выбрано" and combobox0.get() not in str(item[1]):
                values_to_delete.append(item)
            elif combobox1.get() != "Не выбрано" and combobox1.get() not in str(item[3]):
                values_to_delete.append(item)
            elif combobox2.get() != "Не выбрано" and combobox2.get() not in str(item[4]):
                values_to_delete.append(item)
            elif combobox3.get() != "Не выбрано" and combobox3.get() not in str(item[5]):
                values_to_delete.append(item)
            elif combobox4.get() != "Не выбрано" and combobox4.get() not in str(item[6]):
                values_to_delete.append(item)    
            elif combobox5.get() != "Не выбрано" and combobox5.get() not in str(item[7]):
                values_to_delete.append(item)
            elif combobox6.get() != "Не выбрано" and combobox6.get() not in str(item[8]):
                values_to_delete.append(item)
            elif combobox7.get() != "Не выбрано" and combobox7.get() not in str(item[9]):
                values_to_delete.append(item)
            elif combobox8.get() != "Не выбрано" and combobox8.get() not in str(item[10]):
                values_to_delete.append(item)
            elif combobox9.get() != "Не выбрано" and combobox9.get() not in str(item[11]):
                values_to_delete.append(item)    
            elif combobox10.get() != "Не выбрано" and combobox10.get() not in str(item[12]):
                values_to_delete.append(item)
            elif combobox11.get() != "Не выбрано" and combobox11.get() not in str(item[13]):
                values_to_delete.append(item)
            elif combobox12.get() != "Не выбрано" and combobox12.get() not in str(item[14]):
                values_to_delete.append(item)
            elif combobox13.get() != "Не выбрано" and combobox13.get() not in str(item[15]):
                values_to_delete.append(item)
            elif combobox14.get() != "Не выбрано" and combobox13.get() not in str(item[16]):
                values_to_delete.append(item)
    
    for item in values:
        if item not in values_to_delete:
            imgid = int(item[0])
            name = f"{item[2]}\n"
            type = f"Вид: {item[1]}\n"
            lighttype = f"Подсветка: {item[4]}\n"
            volume = f"Тип: {item[3]}\n"
            face = f"Лицо: {item[5]}\n"
            side = f"Торец: {item[6]}\n"
            back = f"Задник: {item[7]}\n"
            manufacturer = f"Производство: {item[9]}\n"
            minmaxsize = f"Размер: {item[19]}-{item[20]} см\n"
            depth = f"Глубина: {item[17]}-{item[18]} мм\n"
            light = f"Подсветка: {item[8]}\n"
            avgtime= f"Срок изготовления: {item[30]} раб. дней\n"
            
            frame = customtkinter.CTkScrollableFrame(master=info_frame, fg_color="green", height=430, orientation="horizontal")
            frame.pack(expand=True, fill=tk.BOTH, anchor=tk.NW)
        
            label = tk.Label(frame, image = imglist[imgid])
            label.grid(row=deckrowid, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=type)
            label.grid(row=deckrowid+1, column=deckcolumnid, sticky=tk.W) 
            
            label = customtkinter.CTkLabel(master=frame, text=lighttype)
            label.grid(row=deckrowid+2, column=deckcolumnid, sticky=tk.W) 
            
            label = customtkinter.CTkLabel(master=frame, text=volume)
            label.grid(row=deckrowid+3, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=face)
            label.grid(row=deckrowid+4, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=side)
            label.grid(row=deckrowid+5, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=back)
            label.grid(row=deckrowid+6, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=manufacturer)
            label.grid(row=deckrowid+7, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=minmaxsize)
            label.grid(row=deckrowid+8, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=depth)
            label.grid(row=deckrowid+9, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=light)
            label.grid(row=deckrowid+10, column=deckcolumnid, sticky=tk.W)
            
            label = customtkinter.CTkLabel(master=frame, text=avgtime)
            label.grid(row=deckrowid+11, column=deckcolumnid, sticky=tk.W)

            rowid += 1
            deckrowid += 1
            info_frame._parent_canvas.yview("moveto", 0.0)` # for getting around the bug, when amount of frames changes to lesser amount that previously was, scroll is not updating by itself and when u touch scrollbar it can get stuck in weird position, so i just move to start of the canvas, which automatically updates it.

**Comment by ElectricCandlelight** [comment]
Could be too many widgets getting drawn at one time. Can you not display the results in one CTkTextbox? Or use something like Tkinter treeview widget?

If you want to keep using the CTkScrollableFrame maybe limit it to display 10 results then a button for the next 10 and repeat.

**Comment by ZerducK** [comment]
> Could be too many widgets getting drawn at one time. Can you not display the results in one CTkTextbox? Or use something like Tkinter treeview widget?
> 

I'm displaying it using labels, because I was gonna stack them in couple of rows using grid system, and formatting the text with different fonts, weight and size is basically impossible in textbox.

Tried commenting out, all the labels beside one that holds a picture, ye performance is a bit better, but amount of displayed frames is the same, still chokes 70% of the way.

> If you want to keep using the CTkScrollableFrame maybe limit it to display 10 results then a button for the next 10 and repeat.
>

Yes, limiting amount of displayed results is one way to do it, but it's gonna be quite annoying to use when u have like 50 entry's and on 1080 display fits like 3, 5 at best, boys with 1366x768(Most popular res), gonna cry any other suggestions?

**Comment by ZerducK** [comment]
Will try tomorrow, to limit amount of displayed results, and try to make them automatically change when u scroll or something, gonna post results asap.

**Comment by ZerducK** [comment]
Yeah, tinkering with it, i found out that it is possible to limit and automate it, by checking frames coordinates on mouse-scroll, it's kinda junky and i couldn't make it to work when moving scroll with mouse,don't have enough brain power and will to fix it.
So i think i just remake it with different GUI.
