### ISSUE TITLE
Request: Add function tag_config to CTkTextbox

### ISSUE THREAD

**Issue by elixirbeats** [TomSchimansky/CustomTkinter#1314]
Hello, 

Maybe I am doing something wrong.. but it seems CTkTextbox doesn't have the method `tag_config` from the regular tk.Text class ( https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/text-methods.html ). Using tags allows you to make different colored text lines in the same box in original tk so for instance you could make error lines red, success green etc instead of changing all the text to the same color.. I am not able to get it working in customtkinter.. can you please add this feature? Or if im looking in the wrong spot appreciate any guidance.. 

thanks!

**Comment by brandon10135** [comment]
I'm not sure if this answers your question but I was honestly just looking for a similar answer as I want to change the text font inside one of my textboxes. It seems to work on an initial look at least for color in the textbox I have. 

https://github.com/TomSchimansky/CustomTkinter/discussions/1288

**Comment by DanoCH-boop** [comment]
Hello, you muse be doing something wrong, because i have this method available on CTkTextbox, maybe just upgrade your customtkitner package?

**Comment by elixirbeats** [comment]
Hm, yep that was it. Upgrading customtkinter fixed it. Thanks for your help!
