### ISSUE TITLE
I can't use different language?

### ISSUE THREAD

**Issue by vitaluska123** [TomSchimansky/CustomTkinter#1317]
how can I set coding: utf-8?
`# -*- coding: cp1251 -*- `      doesn't help!!

I wood to do multi language support to the app!

**Comment by Akascape** [comment]
@vitaluska123 You can add different language fonts with this method:
```python
customtkinter.FontManager.load_font("language_1.ttf")
```
Then use them easily like `font=('language_1', 18)`.
