### ISSUE TITLE
CTkImage not displaying properly

### ISSUE THREAD

**Issue by DominicCulyer** [TomSchimansky/CustomTkinter#1319]
I recently updated to customtkinter 5.1, and I noticed I was receiving warning messages when using normal tkinter images. So I tried to convert to a CTkImage, but it displays strangely.

Here is a screenshot of what the image looks like using CTkImage:
![image](https://user-images.githubusercontent.com/79280228/224054272-d16e7de0-1ea3-4eba-b1ef-83e8be6be218.png)

Here is a screenshot of what the image looks like using Tkinter PhotoImage (and what is should look like when using CTkImage):
![image](https://user-images.githubusercontent.com/79280228/224054616-69c80e3a-775e-41ed-8881-7afa91152741.png)

Here is my code:
![image](https://user-images.githubusercontent.com/79280228/224055002-5a2843f8-d34e-42c8-b558-1588a19fb868.png)

Obviously when generating the above screenshots only one of the techniques were used (other one was commented out)

Any ideas why this us?

**Comment by ElectricCandlelight** [comment]
Have you tried switching light_image and dark_image?

**Comment by DominicCulyer** [comment]
Swapping light_image and dark_image gives this output (which is still incorrect)

![image](https://user-images.githubusercontent.com/79280228/224300999-b5d44771-e59c-4a34-961c-5ae865e44ba4.png)

The images I am using have no backgrounds, so I am not sure as to why it does when used with a CTkImage object.

**Comment by TomSchimansky** [comment]
Here are multiple examples of using the CTkImage on labels, I have no idea what's causing your white background:
https://github.com/TomSchimansky/CustomTkinter/blob/master/examples/image_example.py
