### ISSUE TITLE
Button images cause lag when opening toplevel windows or moving root window

### ISSUE THREAD

**Issue by zebhall** [TomSchimansky/CustomTkinter#1323]
I am creating a program that is made up of one root window and a toplevel window. I have some background processes being handled with multithreading. It is stable and has been running smoothly for some time. I added some icons to my buttons in the root window and toplevel window using the following code e.g.

    icon_systemtime = ctk.CTkImage(light_image=Image.open(resource_path("icons/time-fill.png")), size=(18, 18))
    icon_apply = ctk.CTkImage(light_image=Image.open(resource_path("icons/check-line.png")), size=(18, 18))

    button_setsystemtime = ctk.CTkButton(master=root, width = 13, image=icon_systemtime, text = "Sync", command = syncTime)
    button_setsystemtime.grid(row=3, column=0, padx=4, pady=4, sticky=tk.NSEW)

    button_apply = ctk.CTkButton(master=toplevelwin, width = 13, image=icon_apply, text = "Apply", command = applySettings)
    button_apply.grid(row=1, column=1, padx=4, pady=4, sticky=tk.NSEW)

The source images are PNGs at a res of 64x64px from https://remixicon.com/, and I have also tried using 18x18px versions as well.

The root window performs normally until it is resized or moved, at which point all actions inside the interface become very delayed, and the window usually becomes unresponsive. The same problem occurs when the toplevel window is moved or resized at all , whether or not the toplevel has image buttons.

This is potentially an issue with Pillow or Tk in general - here are some issue threads I have found that sound similar.
https://core.tcl-lang.org/tk/tktview/b9827ece14da1cd186c5816dc45abc29cf9b8a9c
https://stackoverflow.com/questions/67644302/tkinter-performance-degrades-when-i-change-png-files-but-i-cant-figure-out-why
https://stackoverflow.com/questions/69164390/tkinter-image-rendering-is-slow-how-should-i-improve-it

Has anyone else experienced this? Is there any workaround, or should I just give up on the image buttons for now?

**Comment by ElectricCandlelight** [comment]
Can you provide an a minimal code example reproducing the error? 

There could be a lot of reasons for this behaviour but hard to say without an example.

**Comment by zebhall** [comment]
Oh wow. I'm sorry, this isn't a CTk issue at all! For some reason it was only happening to me after I added image to the buttons, but apparently it's to do with the polling rate of the mouse I am using:

https://stackoverflow.com/questions/71884285/tkinter-root-window-mouse-drag-motion-becomes-slower

What a bizarre issue.
Thanks anyway ElectricCandlelight :)

**Comment by ElectricCandlelight** [comment]
Not a problem. If you still want to have your mouse set at a hill poling rate this should help with the issue

```Python 

import customtkinter
from time import sleep


def on_configure(event):
    if event.widget == app:
        sleep(0.005)

app = customtkinter.CTk()
app.bind("<Configure>", on_configure)
app.mainloop()

```

**Comment by zebhall** [comment]
Thank you very much!
