### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by KayaliYousef** [TomSchimansky/CustomTkinter#133]
Hello I am working on a project where I use multiple tabs and I am using two monitors, the problem is that when I move the GUI window from one monitor to the other, the tabs disappear and get mixed into on window, this also happens when I minimize the GUI window.
this is my tabs definition code and I will attach two screen shots (before and after)

```python
root = customtkinter.CTk()
root.geometry("700x600")
root.title("GUI/EXCEL_AUTOMATION")
root.iconbitmap("Logo.ico")

my_notebook = ttk.Notebook(root)
my_notebook.pack()

my_frame1 = customtkinter.CTkFrame(my_notebook, width=700, height=600)
my_frame2 = customtkinter.CTkFrame(my_notebook, width=700, height=600)
my_frame3 = customtkinter.CTkFrame(my_notebook, width=700, height=600)

my_frame1.pack(fill="both", expand=1)
my_frame2.pack(fill="both", expand=1)
my_frame3.pack(fill="both", expand=1)

my_notebook.add(my_frame1, text="excel")
my_notebook.add(my_frame2, text="GUI")
my_notebook.add(my_frame3, text="AHT")
```

![before](https://user-images.githubusercontent.com/106653731/171351952-8e7a9121-d951-472f-8507-90b30c4df9c1.PNG)
![after](https://user-images.githubusercontent.com/106653731/171351957-b98b3bd9-4519-4539-b501-c7546b400c49.PNG)

**Comment by TomSchimansky** [comment]
Does this not happen when you use normal tkinter windows and elements?

**Comment by KayaliYousef** [comment]
Nope, it's happening only with CustomTkinter

**Comment by Think-IT-think-gui** [comment]
It's a problem that affects tkinter too. I think when the widgets are many, it takes more time to render them but since customtkinter by default has embedded widget inside tkinter's  normal widget to produce it down widget's, the  it will probably take longer or sometimes skip the rendering process unless you click around the widgets in the window or you drag the window around simultaneously.. My advice group your buttons, labels and entry boxes into frames or reduce them...

**Comment by KayaliYousef** [comment]
So I created three empty tabs with customtkinter frames, then dragged the window from one screen to the other and the tabs disappered. I had zero entries, buttons or labels in the tabs so it doesn't seem to be a rendering issue.

**Comment by Think-IT-think-gui** [comment]
then try creating a normal  tkinter frame and created the CTkinter frame on top and see if it fixe's the problem

**Comment by KayaliYousef** [comment]
I don't really get what you mean by "Create the CTkinter frame on top", however I tried using the normal tkinter frame as you suggested and it worked. Thanks a lot for the help.

my_frame1 = Frame(my_notebook, width=700, height=600)
my_frame2 = Frame(my_notebook, width=700, height=600)
my_frame3 = Frame(my_notebook, width=700, height=600)

**Comment by Think-IT-think-gui** [comment]
You are welcome

**Comment by felipetesc** [comment]
> I don't really get what you mean by "Create the CTkinter frame on top", however I tried using the normal tkinter frame as you suggested and it worked. Thanks a lot for the help.
> 
> my_frame1 = Frame(my_notebook, width=700, height=600) my_frame2 = Frame(my_notebook, width=700, height=600) my_frame3 = Frame(my_notebook, width=700, height=600)

When you add a new frame at same location of another, and you don't remove the first frame, tkinter puts the second on the  top of the first. So, it seems the first one is gone, but it is there behind the first.

**Comment by felipetesc** [comment]
After your customizations, you can use this sample: https://github.com/TomSchimansky/CustomTkinter/issues/90#issuecomment-1150193296
