### ISSUE TITLE
"Flush" existing elements

### ISSUE THREAD

**Issue by khlmood** [TomSchimansky/CustomTkinter#1332]
I am working on finishing my small project (https://github.com/khlmood/musicD), after clicking the search for the second time nothing happens because there is already a bunch of CTkCheckBox elements. So my question is how to "flush" the old CTkCheckBox and their CTkLabel so i can create new ones.

**Comment by ElectricCandlelight** [comment]
If your widgets are inside a frame you can use 

```Python

for widget in frane_obj.winfo_children()
    widget.destroy()
```

If they aren't in a frame store your widgets in a list when creating them and use 

```Python
for widget in widget_list
    widget.destroy()
```

**Comment by khlmood** [comment]
The right way would be to create a frame and drop them inside + add scrollbar + store the bool values in a list? Also, how can I know when a checkbox value is changed so I can update the list values? thank you in advance

**Comment by TomSchimansky** [comment]
You can do something like this: https://customtkinter.tomschimansky.com/tutorial/frames#dynamic-frame-class
