### ISSUE TITLE
TABLE

### ISSUE THREAD

**Issue by tiagolofi** [TomSchimansky/CustomTkinter#1340]
could you please implement CTkTable?

**Comment by Akascape** [comment]
@NotchApple1703 Here is a table widget for customtkinter: https://github.com/Akascape/CTkTable
![Screenshot](https://user-images.githubusercontent.com/89206401/233420929-bf210cb3-5b5f-49b2-ba7a-f01d187e72cf.jpg)

**Comment by tiagolofi** [comment]
thanks, beautiful implementation!
