### ISSUE TITLE
Corner radius not working

### ISSUE THREAD

**Issue by biscuitrescue** [TomSchimansky/CustomTkinter#1348]
i was made a CTkButton, like so, 
![image](https://user-images.githubusercontent.com/67876678/225029818-c7c7c337-1dc2-4f1d-9fec-690f2751908d.png)
but the corners were not rounded still. 

![image](https://user-images.githubusercontent.com/67876678/225030530-b960a2fa-b5f2-4255-90f1-0b929f9cfd1b.png)

**Comment by Akascape** [comment]
@biscuitrescue It is happening because you have set the fg_color to transparent. Set it to a different color.

![Example](https://user-images.githubusercontent.com/89206401/189685084-f3bacda3-88c7-415c-93e5-916c61c2c1c0.png)

**Note that bg_color cannot be set as transparent.**

**Comment by Akascape** [comment]
@pwall2222 All customtkinter widgets are created in tkinter canvas which are square in shape. Both the ctkframe and ctkbutton are different canvas widget, bg_color of button is made to camouflage with fg_color of frame.

But this will not work if you use the button in root (main CTk() window).

**Comment by pwall2222** [comment]
@Akascape So you can't make it transparent, because of tkinker limitations?

**Comment by Akascape** [comment]
> So you can't make it transparent, because of tkinker limitations?

@pwall2222 Indirectly yes, root window is basically the same tkinter window with a little modifications. 
But you can use a ctkframe to cover the whole root window and then place all widgets in it. The bg_color of all widgets will camouflage with the frame.

**Comment by pwall2222** [comment]
> But again, overlapping widgets will also not work.

Thats what I was trying to see bcs im doing a background image and the borders just overlap the image.

**Comment by Akascape** [comment]
@pwall2222 You can just change each background corner color to match with the bg image.

It will do the work if your window is not resizable.

**Comment by pwall2222** [comment]
@Akascape how can i make the window not resizable, and how can i make it so it grabs the image colors?

**Comment by Akascape** [comment]
@pwall2222 change each corner color by adding this parameter in the widget: `background_corner_colors=(color1, color2, color3, color4)`

You can make the root window non resizable by adding `root.resizable(width=False, height=False)`.

**Comment by MaxNiark** [comment]
some exemple about bg/fb color for corner 

![image](https://user-images.githubusercontent.com/126392328/226094779-fb3f0a4f-74b8-4b69-8e95-98092d81ef37.png)

**Comment by biscuitrescue** [comment]
a friend used the same config for CTButton as i did: 
![image](https://user-images.githubusercontent.com/67876678/226741052-f9ab4ecd-1fc8-4108-b3b6-948867dc5a66.png)
and it was working for him:
![image](https://user-images.githubusercontent.com/67876678/226741159-b3f2cea6-ae89-4f9f-8de5-75ba4d36811d.png)
the code is identical.

**Comment by Akascape** [comment]
@pwall2222 @biscuitrescue @MaxNiark @felipetesc Check this: https://github.com/TomSchimansky/CustomTkinter/discussions/2214

**Comment by felipetesc** [comment]
Parent background color ?

**Comment by Akascape** [comment]
> Parent background color ?

@felipetesc the parent background color is not affected. In tkinter, the alpha and transparency was only working with root window, but with pywinstyles we can work on all of the widgets separately.
