### ISSUE TITLE
Threding in Button Commands not working

### ISSUE THREAD

**Issue by IGoshenI** [TomSchimansky/CustomTkinter#1351]
It seems that there is no Threading in the CTkButton command parameter, so when functions in  `command` are being called the GUI window freezes while the called function runs properly.

https://github.com/TomSchimansky/CustomTkinter/discussions/611
https://github.com/TomSchimansky/CustomTkinter/discussions/611#discussioncomment-4555705

this discussion addresses the same problem and gives this as a fix:

`command=lambda: threading.Thread(target=self.button_callback, args=["test2"]).start()`

a fix which should be the default behavior to enable parallelity and responsive GUI

**Comment by ElectricCandlelight** [comment]
This probably won't be addressed as it's how original TKinter works.  

You should avoid using long / blocking functions.

If you need to have a function running in the background it's easy enough to set that up yourself just need to remember TKinter doesn't play well with threads so any UI operations should be done on the main thread.

**Comment by NebularNerd** [comment]
@IGoshenI 
I had a similar issue and used the thread below  as a basis on getting it working, I have several elements in a project that needed to update at various steps and this works a treat once you get the hang of it.  The main issue is making sure that any variables passed make it in and out the defs when multi-threading. My solution was to use a pre-defined dictionary to pass values around, I'm sure there are better ways of getting it done but that worked for me.

[How to get the result of a ping to show in tkinter?](https://python-forum.io/thread-18983-post-83001.html#pid83001)

**Comment by IGoshenI** [comment]
> This probably won't be addressed as it's how original TKinter works.
> 
> You should avoid using long / blocking functions.
> 
> If you need to have a function running in the background it's easy enough to set that up yourself just need to remember TKinter doesn't play well with threads so any UI operations should be done on the main thread.

oh wow sorry didn't knew that...
it's still absurd that the most popular python GUI doesn't have this functionality as default but ok.
