### ISSUE TITLE
Changing button states with command causes deformation of their shapes and eventually throws Exception: "faster drawing without color changes"

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#1353]
I noticed when you use `threading.Thread()` in a button command and change their states then comes back to normal, their shapes get distorted, it happens not only after the process it also happens during the process.

My observations about this situations:
- Changing button's states is probably responsible for this.
- It happens to those who have assigned commands, even if the command does nothing (e.g. `func3()`). Their shapes don't get distorted if they have no assigned commands.
- `threading.Thread()` needs to be involved.
- Whether having an image doesn't matter, when it does have an image it just distorts more obviously.

```python
import threading
import time
import customtkinter
from PIL import Image

customtkinter.set_appearance_mode("dark")
customtkinter.set_default_color_theme("green")

def func():
    threading.Thread(target=func2).start()

def func2():
    button2.configure(state="disabled")
    button1.configure(state="disabled")
    time.sleep(5)
    button2.configure(state="normal")
    button1.configure(state="normal")

def func3():
    pass

root = customtkinter.CTk()

icon = customtkinter.CTkImage(dark_image=Image.open("download.png"), size=(15, 14))
button1 = customtkinter.CTkButton(master=root, text="Button 1", text_color="white", fg_color="purple", height=25, width=0, corner_radius=15, border_width=0, hover_color="#EA047E", font=customtkinter.CTkFont(size=14), command=func3)
button1.pack(pady=20)
button2 = customtkinter.CTkButton(root, text="Button 2", width=10, height=30, text_color="white", fg_color="#4C0027", bg_color="gray17", corner_radius=20, border_color="#FF008E", border_width=1, hover_color="#FF008E", font=customtkinter.CTkFont(family="Century Gothic", size=15, weight="normal"), image=icon, command=func)
button2.pack(pady=30)

root.mainloop()
```
Here are some of the examples of the deformations:
![1](https://user-images.githubusercontent.com/100048974/225688201-a5486922-3d09-4d5a-a596-7435f68a5a3d.png) ![2](https://user-images.githubusercontent.com/100048974/225688229-7feaa02c-d25d-4f53-98ab-94d6db57a284.png) ![3](https://user-images.githubusercontent.com/100048974/225688254-64bb2f86-3554-455a-b16e-e278d99064cb.png)

And if you click couple of times in a row, you get this traceback:
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 196, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_rect_with_border(self._apply_widget_scaling(self._current_width),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 128, in draw_rounded_rect_with_border
    return self.__draw_rounded_rect_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius, ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 227, in __draw_rounded_rect_with_border_font_shapes
    self._canvas.coords("border_oval_2_a", width - corner_radius, corner_radius, corner_radius)
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\ctk_canvas.py", line 99, in coords
    super().coords(tag_or_id, *args)
  File "D:\Python311\Lib\tkinter\__init__.py", line 2822, in coords
    self.tk.call((self._w, 'coords') + args))]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: wrong # coordinates: expected 0 or 2, got 3
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 188, in _update_dimensions_event
    self._draw(no_color_updates=True)  # faster drawing without color changes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 196, in _draw
    requires_recoloring = self._draw_engine.draw_rounded_rect_with_border(self._apply_widget_scaling(self._current_width),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 128, in draw_rounded_rect_with_border
    return self.__draw_rounded_rect_with_border_font_shapes(width, height, corner_radius, border_width, inner_corner_radius, ())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\draw_engine.py", line 286, in __draw_rounded_rect_with_border_font_shapes
    self._canvas.coords("inner_oval_1_b", border_width + inner_corner_radius, border_width + inner_corner_radius, inner_corner_radius)
  File "D:\Python311\Lib\site-packages\customtkinter\windows\widgets\core_rendering\ctk_canvas.py", line 99, in coords
    super().coords(tag_or_id, *args)
  File "D:\Python311\Lib\tkinter\__init__.py", line 2822, in coords
    self.tk.call((self._w, 'coords') + args))]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: wrong # coordinates: expected 0 or 2, got 3
```
I'm pretty sure it's a bug but it might have something to do with tkinter's non-threadfriendly attitude.
![download](https://user-images.githubusercontent.com/100048974/225689149-fb529add-af7e-4023-981c-68659a738a0a.png)

**Comment by ElectricCandlelight** [comment]
There is no need to use threading in the example you posted if you need to change a UI element after a period of time use .after()

**Comment by duruburak** [comment]
`event_generate()` might be a good solution, I'll give it a try. And yeah in this example there is no need for `threading.Thread()`, this example is oversimplified version of my situation and in my situation I have to use `threading.Thread()`.

**Comment by duruburak** [comment]
I'm trying to avoid buttons freezing during their states' changing, that's why I'm using `threading.Thread()`, and I guess `event_generate()` is not useful for my situation...

> There is no need to use threading in the example you posted if you need to change a UI element after a period of time use .after()

**Comment by ElectricCandlelight** [comment]
What do you mean by button freezing? Can you provide a minimal example of the issue?

**Comment by duruburak** [comment]
> What do you mean by button freezing? Can you provide a minimal example of the issue?
If you remove `threading.Thread()` and put `func2()` into `func()` then when you press the button, the GUI freezes during the process. That's the situation I'm intending to avoid.

```python
def func():
    button2.configure(state="disabled")
    time.sleep(5)
    button2.configure(state="normal")

root = customtkinter.CTk()
icon = customtkinter.CTkImage(dark_image=Image.open("./icons/download.png"), size=(15, 14))
button2 = customtkinter.CTkButton(root, text="Button 2", width=10, height=30, text_color="white", fg_color="#4C0027", bg_color="gray17", corner_radius=20, border_color="#FF008E", border_width=1, hover_color="#FF008E", font=customtkinter.CTkFont(family="Century Gothic", size=15, weight="normal"), image=icon, command=func)
button2.pack(pady=30)

root.mainloop()
```

**Comment by ElectricCandlelight** [comment]
Because you're using sleep. Just use .after() instead

**Comment by duruburak** [comment]
> Because you're using sleep. Just use .after() instead

No, not really. I used `sleep()` to demonstrate there will be some process going on during the `Thread()` and it will take some time. You can replace `sleep()` with anything, the result will be the same. The purpose of `sleep()` was basically `# Do something`.

**Comment by ElectricCandlelight** [comment]
```Python 
import customtkinter
import threading
from time import sleep


def blocking_func():
    while True:
        root.event_generate("<<ButtonDisable>>")
        sleep(5)
        root.event_generate("<<ButtonEnable>>")
        sleep(5)


def button_disable(event):
    button.configure(state="disabled")


def button_normal(event):
    button.configure(state="normal")


def button_command():
    thread = threading.Thread(target=blocking_func, args=(), daemon=True)
    thread.start()


root = customtkinter.CTk()

root.bind("<<ButtonDisable>>", button_disable)
root.bind("<<ButtonEnable>>", button_normal)

button = customtkinter.CTkButton(
    master=root,
    text="Button 1",
    text_color="white",
    fg_color="purple",
    height=25,
    width=0,
    corner_radius=15,
    border_width=0,
    hover_color="#EA047E",
    font=customtkinter.CTkFont(size=14),
    command=button_command,
)
button.pack(pady=50, padx=50)

root.mainloop()

```

Small example on how to use threading while keeping the UI functions on the main thread.

**Comment by duruburak** [comment]
> ```python
> import customtkinter
> import threading
> from time import sleep
> 
> 
> def blocking_func():
>     while True:
>         root.event_generate("<<ButtonDisable>>")
>         sleep(5)
>         root.event_generate("<<ButtonEnable>>")
>         sleep(5)
> 
> 
> def button_disable(event):
>     button.configure(state="disabled")
> 
> 
> def button_normal(event):
>     button.configure(state="normal")
> 
> 
> def button_command():
>     thread = threading.Thread(target=blocking_func, args=(), daemon=True)
>     thread.start()
> 
> 
> root = customtkinter.CTk()
> 
> root.bind("<<ButtonDisable>>", button_disable)
> root.bind("<<ButtonEnable>>", button_normal)
> 
> button = customtkinter.CTkButton(
>     master=root,
>     text="Button 1",
>     text_color="white",
>     fg_color="purple",
>     height=25,
>     width=0,
>     corner_radius=15,
>     border_width=0,
>     hover_color="#EA047E",
>     font=customtkinter.CTkFont(size=14),
>     command=button_command,
> )
> button.pack(pady=50, padx=50)
> 
> root.mainloop()
> ```
> 
> Small example on how to use threading while keeping the UI functions on the main thread.

This worked, thank you! 🙏🙌
