### ISSUE TITLE
CTkOptionMenu and CTkComboBox are not scrollable

### ISSUE THREAD

**Issue by ViktorKeray** [TomSchimansky/CustomTkinter#137]
With long lists of options the CTkOptionMenu and CTkComboBox do not automatically add a scroll bar to the drop-down menu that appears when clicked and therefor are unusable in this situation. 

Is there a way to force these widgets to become scrollable?

**Comment by TomSchimansky** [comment]
No, currently there is no way to make them scrollable, I would have to implement it... Maybe I will try to do this in the next time. Thanks for mentioning this.

**Comment by shubham-pawar** [comment]
Did you add a option to make CTkOptionMenu or CTkComboBox scrollable? If yes, could you please provide demo code?

**Comment by ViktorKeray** [comment]
With the current version (5.1.2) the CTkOptionMenu becomes automatically scrollable when the list of items becomes too long. So you don't have to add anything to your code, just initialize the component as normal. 

FYI there is no scroll bar on the right side of the menu, but rather two buttons on the top and the bottom that allow you to scroll through the list!

**Comment by shubham-pawar** [comment]
Thank you for your reply. Yes, I have those two buttons to move the bottom and top of the options menu. But, I wanted the more smooth mouse-enabled scrollable option. I hope that we will get it in later versions. Happy coding :-)
