### ISSUE TITLE
Adding a Font in Tag_config , seem to be incomatible with scaling , how can i fix this i want a specifc tag to have diffrent font

### ISSUE THREAD

**Issue by OSTEsayed** [TomSchimansky/CustomTkinter#1370]
tag_config
    raise AttributeError("'font' option forbidden, because would be incompatible with scaling")
AttributeError: 'font' option forbidden, because would be incompatible with scaling

**Comment by surajnandu18** [comment]
Try this:

Comment out 
```
# if "font" in kwargs: 
#     raise AttributeError("'font' option forbidden, because would be incompatible with scaling")
```
and use tkinter tupple font like         
```
textbox = CTkTextBox(frame,300,300)
textbox.tag_config("custom_tag", font=("Helvetica",16,"bold"))
```

It works!!!

**Comment by TomSchimansky** [comment]
Remember that if you do this and run this on Windows with a scaling other than 100% in the Windows settings, this will result in undefined behaviour.

**Comment by Wyko** [comment]
@TomSchimansky What would be a better alternative to patching out your warning then? I don't know the background as to why this wouldn't work, but I have to imagine that most font changes aside from font size wouldn't break scaling (although feel free to correct that assumption). Is there a way to configure things like tag bolding without breaking the textbox?

**Comment by Wyko** [comment]
As a side note to anyone: Instead of commenting out source code, which isn't reproducible next time you build your application, just do this:
`your_text_box.tag_config = lambda tagName, **kwargs: txt_box._textbox.tag_config(tagName, **kwargs)`

**Comment by AjnoEO** [comment]
This problem is quite frustrating, is there any chance it will get patched?
