### ISSUE TITLE
I think that something buggy is going on with validations.

### ISSUE THREAD

**Issue by biobrad** [TomSchimansky/CustomTkinter#1378]
I think that something buggy is going on with validations.

I have been wrestling with getting validation to work for the last 2 days.
Last night, i copied and pasted the code from @ElectricCandlelight into a fresh python file, ran it, and it worked.
An entry box popped up and behaved as it should.

So today, I tried to make a few small amendments to it - i started getting this error:
```
Traceback (most recent call last):
  File "C:\D_Drive\programming files\tkinter\plop.py", line 10, in <module>
    input=customtkinter.CTkEntry(root,validate="key", validatecommand=(validation, '%S'))
  File "C:\Users\bradh\miniconda3\envs\tkinter\lib\site-packages\customtkinter\windows\widgets\ctk_entry.py", line 95, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Users\bradh\miniconda3\envs\tkinter\lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['validatecommand'] are not supported arguments. Look at the documentation for supported arguments.
```
So I started rolling back the the small changes to see where I went wrong.
I kept getting the error message.

So I rolled it all the way back so the file is just the original script from @ElectricCandlelight and i am still getting the value error command.

![image](https://user-images.githubusercontent.com/55652506/227646963-5199c22c-06bc-4afb-86d7-e9429a76d5ab.png)

Any help would be awesome. Tearing my hair out a bit. 😓

_Originally posted by @biobrad in https://github.com/TomSchimansky/CustomTkinter/discussions/1243#discussioncomment-5423138_

**Comment by biobrad** [comment]
Aha!! fixed it! 
I edited the 0.0 out of the "0.0validatecommand" so it was just 'validatecommand' and now it is working. 
wooooooooooo

**Comment by Akascape** [comment]
@biobrad So close this issue plz if you have fixed it.

**Comment by biobrad** [comment]
Yeah sure, no problem.
Sorry, i sorted it out just before i had to work for the day, i was going to check if it was in the code in the repo.
Will close the issue.
