### ISSUE TITLE
tk.messagebox puts CTkToplevel window to the back...

### ISSUE THREAD

**Issue by TheWicklowWolf** [TomSchimansky/CustomTkinter#1379]
When a CTkTopLevel window is open and a tk.message is displayed,  the CTkTopLevel window is put behind the main window.
Any workarounds to prevent the  CTkTopLevel window from going to back?

**Comment by Akascape** [comment]
@TheWicklowWolf 
Try to add `.transient()` to the toplevel.
Eg: `toplevel.transient(root)`.

You can also try this modern CtkMessagebox: https://github.com/Akascape/CTkMessagebox

**Comment by TheWicklowWolf** [comment]
@Akascape 
That works, thank you.
Also I will check out that add-on, it looks good!
