### ISSUE TITLE
CTkFrame not being drawn if height is set to 1 px

### ISSUE THREAD

**Issue by LucianoSaldivia** [TomSchimansky/CustomTkinter#1386]
Minimal examples are simple to create and check

It doesn't draw anything when you try:
```python
separator1 = ctk.CTkFrame(self, height=1, fg_color="red", border_width=0)
separator1.pack()
```

Yet works ok when you try the following:
```python
separator2 = ctk.CTkFrame(self, height=2, fg_color="red", border_width=0)
separator2.pack()
```

**Comment by Sahil481** [comment]
I will try to look into this matter

**Comment by TomSchimansky** [comment]
CTk widget will be rendered to even dimension numbers in most cases. I don't remember exactly why I did that but I think with uneven dimensions there rendering looked weird sometimes.
