### ISSUE TITLE
CTkButton anchor attribute not working

### ISSUE THREAD

**Issue by LucianoSaldivia** [TomSchimansky/CustomTkinter#1393]
In the [documentation ](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkButton)it's metioned that "alignment of text an image in button ("n", "ne", "e", "se", "s", "sw", "w", "nw", "center")", yet when i configure `anchor="w"` the text keeps being centered.
Here's an example
```python
import customtkinter as ctk

def main():
    root = ctk.CTk()
    root.geometry("400x400")

    boton = ctk.CTkButton(root)
    boton.configure(
        text="Archivo",
        corner_radius=7,
        fg_color="transparent",
        hover_color="darkblue",
        width=200,
        anchor="w",
    )
    boton.pack()

    root.mainloop()

if __name__ == "__main__":
    main()
```

Am i doing something wrong or is this a bug?

**Comment by Akascape** [comment]
@LucianoSaldivia anchor doesn't work if you configure it.
Use it like this: `boton = ctk.CTkButton(root, anchor='w')`

Maybe it is a bug in the configure options.

**Comment by LucianoSaldivia** [comment]
Great, thanks a lot.
I'll report this as a bug and close this post.

**Comment by Sahil481** [comment]
I have raised a pr which solves this issue
