### ISSUE TITLE
[Bug] CTkButton anchor only working at __init__() and not in configure()

### ISSUE THREAD

**Issue by LucianoSaldivia** [TomSchimansky/CustomTkinter#1394]
If you want to configure a CTkButton's anchor, you can only do it when you create it, passing the anchor to configure() afterwards doesn't work.

This works as expected:
```python
import customtkinter as ctk

root = ctk.CTk()
root.geometry("300x300+100+100")

button = ctk.CTkButton(master=root, text="Hi.", anchor="w")
button.pack()

root.mainloop()
```

This doesn't work as expected:
```python
import customtkinter as ctk

root = ctk.CTk()
root.geometry("300x300+100+100")

button = ctk.CTkButton(master=root, text="Hi.")
button.configure(anchor="w")
button.pack()

root.mainloop()
```

**Comment by Sahil481** [comment]
Could you provide some more information on the issue? like the error message?

**Comment by Sahil481** [comment]
I have ran your code and when I ran it, it didn't matter what I wrote in anchor="" it was always centered. is this your issue? is this what you mean by not working as expected?

**Comment by Sahil481** [comment]
I seem to have solved the issue, will raise a pr soon enough...

**Comment by LucianoSaldivia** [comment]
@Sahil481 Yes that is exactly what i meant, i just know realise i haven't explicitly wrote that, sorry.
Thanks for solving the issue and raising the pr.
