### ISSUE TITLE
Linux Option Menu Error

### ISSUE THREAD

**Issue by petersonBrandon** [TomSchimansky/CustomTkinter#140]
The option menu displays a black box instead of the options when using the option menu widget on a Linux machine.

Error seems to stem from the dropdown_menu.py file where it calls `self.wm_attributes("-transparentcolor", "#010302")`

Error message:
`File "/usr/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-transparentcolor": must be -alpha, -topmost, -zoomed, -fullscreen, or -type`

**Comment by eliasywoo** [comment]
I had the same error, apparently wm attributes in linux does not have the "transparentcolor" option.
https://wiki.tcl-lang.org/page/wm+attributes
What I did to make it work was just comment the line
81 #self.wm_attributes("-transparentcolor", "#010302")
Although I'm not sure if this can be a solution.
![imagen](https://user-images.githubusercontent.com/78565113/171905796-d73a2cfb-b547-4f63-8266-d6d89d81a9c9.png)

**Comment by petersonBrandon** [comment]
While that does get the dropdown to display, the dropdown is then stuck after that and won't retract. 

Apart from commenting out the `self.wm_attributes("-transparentcolor", "#010302")` I also tried changing `-transparentcolor` to `-alpha` with a range of arguments from 0.0 - 1.0. However, this did not work either.

I am still looking into it to see if I can find the cause of the issue, but I haven't found anything as of yet.

**Comment by TomSchimansky** [comment]
It should work now on Linux too, since I use a normal tkinter menu for the dropdown now with version 4.4.0.
