### ISSUE TITLE
cannot get the "master" atribute value from a CTkFrame

### ISSUE THREAD

**Issue by cfvilela** [TomSchimansky/CustomTkinter#1409]
I am fairly new to python and to tkinter. I have set a frame, as follows:
`label = CTkLabel(
			master=frame,
			width=lw,
			fg_color="red",
			corner_radius=10,
			anchor="w",
			text=label
			)`
when I try to retrieve the master attribute value:
`x = frame.cget("master")
		return x`
I get the following error:
`ValueError: 'master' is not a supported argument. Look at the documentation for supported arguments.`

Is there another way to get this value? Thank you

**Comment by TrintinAffleck** [comment]
Try
`master = frame.winfo_toplevel()`
to get the top level window. The cget method doesn't have an arg for the master attribute you are trying to access. Above code will give you the top level window though.

**Comment by TomSchimansky** [comment]
You can also use the public `.master` attribute of every tkinter and CustomTkinter widget.
