### ISSUE TITLE
will it support ttk.treeview ?

### ISSUE THREAD

**Issue by tadegenban** [TomSchimansky/CustomTkinter#141]
This looks really great project.
I have a glance on the code, looks using Canvas to render each customize widgets. 
i'm wondering can this approach also support ttk.treeview ?
https://tcl.tk/man/tcl8.6/TkCmd/ttk_treeview.htm

Thanks.

**Comment by TomSchimansky** [comment]
It would be possible when I implement the drawing of a treeview on a tkinter.Canvas. But currently that's not done, and it would require an extensive amount of work. I will possibly do a Table at some point, but at the moment I'm focusing on scrolling and menus.
