### ISSUE TITLE
Start a windows in maximized state

### ISSUE THREAD

**Issue by IshanJ25** [TomSchimansky/CustomTkinter#142]
How can I initiate a windows in maximized state and disable resizing?

This is not for full-screen, but maximized mode.

``` python
root.state('zoomed')
```

this only resizes the main body of windows but it is not maximized

**Comment by TomSchimansky** [comment]
I have no idea, this is should not be CustomTkinter specific. It should work like in normal tkinter.

**Comment by felipetesc** [comment]
```python
import tkinter
import customtkinter


class App(customtkinter.CTk):

    def try_alter_the_size(self):
        self.geometry("800x600")
            
    def __init__(self):
        super().__init__()
        self.title("No resizable Window ")
        self.maxsize(self.winfo_screenwidth(), self.winfo_screenheight())
        self.minsize(self.winfo_screenwidth(), self.winfo_screenheight())
        self.resizable(height = None, width = None)
        # bt to test if we can resize it
        bt = customtkinter.CTkButton(self, width=100, height=50, text="Click", command=self.try_alter_the_size)
        bt.place(anchor="center", relx="0.5", rely="0.5")

a = App()
a.mainloop()

```

**Comment by evgenidzze** [comment]
> I have no idea, this is should not be CustomTkinter specific. It should work like in normal tkinter.

`root.state("zoomed")` isn't working like in normal tkinter

**Comment by Wolf-SO** [comment]
> `root.state("zoomed")` isn't working like in normal tkinter

@evgenidzze This absolutely works for me (Windows 10, Python 3.11), it may depend on the function call order.


@IshanJ25 If your actual goal was to switch to full-screen mode, I read that from

> this only resizes the main body of windows but it is not maximized

… then you should use the `attributes` method:

```python
root.attributes("-fullscreen", True)
```
