### ISSUE TITLE
Please help an noob

### ISSUE THREAD

**Issue by Yoko11111111** [TomSchimansky/CustomTkinter#1424]
Hi, i am using CustomTkinter to design a UI, I wanted to have an checkbox which disables another Checkbox when the first checkbox is ticked. example: Checkbox 1 is enabled = Checkbox 2 gets disabled, Checkbox 1 is disabled = Checkbox 2 can be enabled. How can i do this? Im an beginer with ui in general etc. Thx for help guys. Here are some snippets of my code:
(ofc it doesnt work but how can i do smth like that i think you know what i mean now.)

class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.info_frame1 = customtkinter.CTkCheckBox(self.info_frame, text="SafeMode", command=self.update_button_states)
        self.info_frame1.grid(row=1, column=0, padx=20, pady=10)
        
        self.disable_button_1 = customtkinter.CTkCheckBox(self.home_frame, text="Enable Options? (?)")
        self.disable_button_1.grid(row=1, column=0, padx=20, pady=10)
        
     def update_button_state(self):
        if self.info_frame1.is_checked():
            self.disable_button_1.config(state="disabled")
        else:
            self.disable_button_1.config(state="normal")

if __name__ == "__main__":
    app = App()
    app.mainloop()

**Comment by VasigaranAndAngel** [comment]
```

class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.info_frame1 = customtkinter.CTkCheckBox(self.info_frame, text="SafeMode", command=self.update_button_state)
        self.info_frame1.grid(row=1, column=0, padx=20, pady=10)

        self.disable_button_1 = customtkinter.CTkCheckBox(self.home_frame, text="Enable Options? (?)")
        self.disable_button_1.grid(row=1, column=0, padx=20, pady=10)

    def update_button_state(self):
        if self.info_frame1.get():
            self.disable_button_1.configure(state="disabled")
        else:
            self.disable_button_1.configure(state="normal")

if __name__ == "__main__":
    app = App()
    app.mainloop()
```

- `self.info_frame1 = customtkinter.CTkCheckBox(self.info_frame, text="SafeMode", command=self.update_button_states)`
The spelling is wrong here - `self.update_button_state`
- there is no `is_checked()` attribute in `CTkCheckBox`. use `get()` instead. it will return 1 if checked and 0 if unchecked.
- `config` is not implemented for CTk widgets. use `configure` instead.

🙂

**Comment by Yoko11111111** [comment]
Thank you very much my friend I really appreciate it :)
