### ISSUE TITLE
Transparent Text Box 

### ISSUE THREAD

**Issue by mahashiah** [TomSchimansky/CustomTkinter#1427]
hello, i have a defaut text box created with CTK

import tkinter as tk
import customtkinter

joi = customtkinter.CTk()
joi.geometry('777x444')
joi.background_img = tk.PhotoImage(file=r'C:\xampp\htdocs\automator\jupyter\jupyter33\JOI\uI\joi_UI.png')
joi.background_label = tk.Label(image=joi.background_img, borderwidth=0)
joi.background_label.place(x=0, y=0)
input_box = customtkinter.CTkTextbox(joi,  font=("Arial", 10), width=30)
input_box.place(relx=0.27, rely=0.33, relwidth=0.48, relheight=0.15)
joi.mainloop()

the code creates a background image on window.. how can i turn the text box transparent? its possible?  text colors of letters stills white but fg_color of textbox = transparent 

something like that?

many thanks! CustomTkinter is amazing!

**Comment by mahashiah** [comment]
![image](https://user-images.githubusercontent.com/124979318/230224152-bc9b3fbd-e139-4648-baf1-ca3c951a2e99.png)

**Comment by TomSchimansky** [comment]
There is no transparency in tkinter or customtkinter, so it's not possible. fg_color="transparent" would only use the color behind the widget o make it look transparent, but this obviously won't work for images.
