### ISSUE TITLE
How to change the font of CTkOptionMenu dropdown text?

### ISSUE THREAD

**Issue by beeee506** [TomSchimansky/CustomTkinter#143]
Hello,

I try to replace my old Tkinter Optionmenu widget with CTkOptionMenu. 
When I try to use the `nametowidget()` method to get the widget object and then set the font of dropdown text, it shows an **AttributeError** like below. 
Is there any way can change the font of CTkOptionMenu dropdown text? 

Thanks.
```
optionmenu = customtkinter.CTkOptionMenu(master=app, ...)

ns14 = tkFont.Font(family='Noto Sans TC Medium', size=14)
menu = app.nametowidget(optionmenu.menuname)
menu.config(font=ns14)
```
**AttributeError: 'CTkOptionMenu' object has no attribute 'menuname'**

**Comment by TomSchimansky** [comment]
Currently there is no option to change the font of the dropdown menu. But I think I will change them anyway very soon to normal tkinter menus, and I could also add an attribute to change the font.
