### ISSUE TITLE
How to bind textvariable to entry? 

### ISSUE THREAD

**Issue by John-coder777** [TomSchimansky/CustomTkinter#1432]
I did customtkinter.CTkEntry(root, width=140,self._textvariable_callback_name == self._textvariable_trace_add(value)) I received error, position argument follows keyword argument

**Comment by duruburak** [comment]
It's impossible to understand anything from the code you posted, you should be more clear and give us some minimal reproducible example.

```python
entry_var = customtkinter.StringVar(value="")
entry = customtkinter.CTkEntry(master=root, textvariable=entry_var)
```

**Comment by John-coder777** [comment]
> It's impossible to understand anything from the code you posted, you should be more clear and give us some minimal reproducible example.
> 
> ```python
> entry_var = customtkinter.StringVar(value="")
> entry = customtkinter.CTkEntry(master=root, textvariable=entry_var)
> ```
Thank you!
