### ISSUE TITLE
MacOS black app

### ISSUE THREAD

**Issue by H31md411** [TomSchimansky/CustomTkinter#144]
When running the simple exampleon MacOS, the app has a black screen.
Button is clickable.
![Bildschirmfoto 2022-06-03 um 15 49 38](https://user-images.githubusercontent.com/52346542/171870985-28c9ea41-46ab-41b8-805b-fa803b9f9f10.png)

**Comment by TomSchimansky** [comment]
You can do this in the Terminal: `defaults delete -g NSRequiresAquaSystemAppearance`
And then at the beginning of your program you can add this:
```python
customtkinter.Settings.deactivate_macos_window_header_manipulation = True
```
But then you don't get the dark window titlebar in macOS dark mode. Which python version are you using? To get the dark window titlebar to work properly you have to install python >= 3.10 or use an anaconda python version. So my suggestion would be to install the newest python version.

**Comment by H31md411** [comment]
Thank you, that worked :)
