### ISSUE TITLE
CTkEntry spellcheck (red squiggly line)

### ISSUE THREAD

**Issue by Red-exe-Engineer** [TomSchimansky/CustomTkinter#1440]
I looked into it but I don't know how to add it myself.
Would also make a good option/addition.

**Comment by TomSchimansky** [comment]
I don't think tkinter can do this, you can only underline text by changing the font:
```
entry.cget("font").configure(underline=True)
```

**Comment by Red-exe-Engineer** [comment]
> I don't think tkinter can do this, you can only underline text by changing the font:

Yes you can, tag_config.

![Screenshot_2023-04-13_22-13-01](https://user-images.githubusercontent.com/90420989/231894793-85e292de-9040-499a-9872-36127a0d4a77.png)

```py3
import tkinter as tk

root = tk.Tk()

textbox = tk.Text(root, width=30, height=10, font=("Courier New", 12))
textbox.pack()

textbox.tag_config("squiggly", bgstipple="@squiggly.xbm", background='red')
textbox.insert("end", "Hello world!\n")
textbox.insert("end", "Here's a sqiggly line, ")
textbox.insert("end", "abcdef", "squiggly")

root.mainloop()
```
You'll need to make a squiggly.xbm file.

Reference: https://stackoverflow.com/a/61604625/19348326

**Comment by Red-exe-Engineer** [comment]
@TomSchimansky? Hi I looked into it a bit and it looks like CTkTextbox might be able to implement this, I'll see about adding it myself and making a PR.
