### ISSUE TITLE
Lag and Slow runtime on pretty old hardwear and softwear

### ISSUE THREAD

**Issue by H1Mohamed** [TomSchimansky/CustomTkinter#1445]
I have installed the library and ran some examples, as in the `complex_exsample.py` I encountered some lag and slowness in the app, and malfunctions while resizing the window, I ran an i5 2450M 2.50GHz 32bit CPU and 4G of ram, if there is a fix I would be happy to see it as I'm thinking of using it in my project

**Comment by TomSchimansky** [comment]
Tkinter itself is a slow UI library and drawing everything on a canvas for CustomTkinter makes performance even worse. You have to use an other library if its not working fine for you.
