### ISSUE TITLE
dropdown Bug (Important)

### ISSUE THREAD

**Issue by attiqRahman** [TomSchimansky/CustomTkinter#1452]
Dropdown was working Fine but all of sudden it is not working. gives the following error below after clicking on dropdown:

ERROR: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by ElectricCandlelight** [comment]
Can you provide a minimal code example that reproduces the error?

**Comment by attiqRahman** [comment]
switch_window_button_post = ctk.CTkOptionMenu(
            leftSubFrame,
            height=40,
            width=100,
            corner_radius=8,
            dropdown_fg_color="white",
            dropdown_hover_color="red",
            values=["Hot", "New", "Top"],  
        )

This is working in Windows but not in Mac M1 Pro. I think just creating an OptionMenu and click the option menu on M1 should reproduce this error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by TomSchimansky** [comment]
I can not test this, because I have no M1 mac, but this would be a tkinter related issue, since I use a tkinter menu for the dropdown.
