### ISSUE TITLE
CTkToplevel instantiation (master= causes exception)

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1468]
Hi. 
I am migrating an app from CustomTkinter v4 to v5 and I am hitting an issue when creating a top level widget:

My method looks like this:
```
import customtkinter as ctk
...
    def _launch_preferences(self):
        _self._top_prefs = ctk.CTkToplevel(master=self.ctk_control_panel)
        self._top_prefs.title('CTk Theme Builder Preferences')
        self._top_prefs.geometry('500x500') 
...
```
The error stack is:
```
/home/clive/PycharmProjects/ctk5_theme_builder/venv/bin/python /home/clive/PycharmProjects/ctk5_theme_builder/ctk_theme_builder.py 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/ctk_theme_builder.py", line 632, in _launch_preferences
    self._top_prefs = ctk.CTkToplevel(master=self.ctk_control_panel)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/ctk_toplevel.py", line 39, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['master'] are not supported arguments. Look at the documentation for supported arguments.
```
Line 632, maps to the first line in the method (_self._top_prefs = ctk.CTkToplevel(master=self.ctk_control_panel_).
Here is infor from the debug panel in PyCharm:

![exception](https://user-images.githubusercontent.com/89534395/232332554-ba9455c5-0c5d-4283-8797-dafe881eef75.png)

Not sure how I'm supposed to set a parent, when it doesn't recognise "master"?

Thanks.

**Comment by bfedie518** [comment]
Looks like `master` is not in the list of [valid kwargs](https://github.com/TomSchimansky/CustomTkinter/blob/09e584634c867f2b6074fcbfe41cba80d2b78c66/customtkinter/windows/ctk_toplevel.py#L22-L24)

Does it work if you pass it without the `master` keyword?  Like `ctk.CTkToplevel(self.ctk_control_panel)`?

**Comment by avalon60** [comment]
Hi Brandon.

Yes it does work, but there should surely be a way of referencing this by keyword. Neither "root" or "master" are accepted as keywords. The impact here is that I would have to crawl through all previous programs and library functions and change them to work differently. This looks like a regression to me.

**Comment by bfedie518** [comment]
> Hi Brandon.
> 
> Yes it does work, but there should surely be a way of referencing this by keyword. Neither "root" or "master" are accepted as keywords. The impact here is that I would have to crawl through all previous programs and library functions and change them to work differently. This looks like a regression to me.

I fully agree. I've never used CTkTopLevel and wanted to make sure the bug was what I suspected and not something deeper.  I should have a PR later today.

**Comment by avalon60** [comment]
> > Hi Brandon.
> > Yes it does work, but there should surely be a way of referencing this by keyword. Neither "root" or "master" are accepted as keywords. The impact here is that I would have to crawl through all previous programs and library functions and change them to work differently. This looks like a regression to me.
> 
> I fully agree. I've never used CTkTopLevel and wanted to make sure the bug was what I suspected and not something deeper. I should have a PR later today.

Yes, I notice that the CTkToplevel entry in the wiki, shows an example, but it doesn't reference a CTk parent.  Something which is handy if you wish to do something like, instruct the parent window, to do a _wait_window_ on a pop-up dialog, but making the "wait" call from within the pop-up dialog.

**Comment by bfedie518** [comment]
Ended up being too busy yesterday, but I got to it today.  #1478

**Comment by TomSchimansky** [comment]
fixed now
