### ISSUE TITLE
Putting an entry in a grid (can't use pack)

### ISSUE THREAD

**Issue by Willmizzle** [TomSchimansky/CustomTkinter#1472]
The documentation for "CTKEntry" uses 'pack', which only works when you are not inside a grid. 

So if I am in a grid, and I have the code:

self.entry = customtkinter.CTkEntry(master=self, placeholder_text="CTkEntry")

How am I supposed to place this? I had a bunch of guesses and none of them worked.

**Comment by bfedie518** [comment]
[This part of a tutorial](https://realpython.com/python-gui-tkinter/#the-grid-geometry-manager) shows how to use the grid manager with Tkinter.  It's exactly the same in CustomTkinter.

I suggest going through the entire tutorial on that page, not just the grid section. It does a good job showing the basics of Tkinter--all of which transfers over to CTk.

**Comment by Pgsaisuhas** [comment]
CTkEntry can use grid, i have used it and it works, but i have placed it in a frame, maybe that is what is helping CTkEntry to use grid, try out once placing you CTkEntry in a frame

**Comment by TomSchimansky** [comment]
The grid is explained one the new website too: https://customtkinter.tomschimansky.com/tutorial/
