### ISSUE TITLE
command parameter for CTkEntry

### ISSUE THREAD

**Issue by emcek** [TomSchimansky/CustomTkinter#1477]
I would like trigger action when content of `CTkEntry` was change.

Just add `command` parameter, like for example `CTkSwitch`

**Comment by bfedie518** [comment]
You have two options at the moment:
1. You can piggyback on the 'validate' method and run what you want in there.
2. You can attach a StringVar to the Entry and trace the variable so a method runs when it changes.

**Comment by emcek** [comment]
> 
1. you mean `validate` or `validatecommand` [validate](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkEntry), how to us it?
2. I got attached StringVar, but how you can trigger function on value change of variable?

**Comment by emcek** [comment]
Got it:
```python
import customtkinter
import tkinter as tk

def is_okay(self, what):
    print(what)
    return True

customtkinter.CTkEntry(master=tabview.tab('Advanced'), state=tk.NORMAL, placeholder_text='git reference', width=390, validate='key', validatecommand=(self.master.register(self.is_okay), '%P'))
```

**Comment by TomSchimansky** [comment]
I think you can simply use the `bind` method like `entry.bind("<Key>", callback)`.
