### ISSUE TITLE
ModuleNotFoundError: No module named 'customtkinter' on macOS Big Sur

### ISSUE THREAD

**Issue by RepubblicaTech** [TomSchimansky/CustomTkinter#1484]
OS: macOS Big Sur 11.7.6
Build: 20G1231
Python version: Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10)

Just installed `customtkinter` with `pip3 install customtkinter`, but if i try to import either in any IDE (VSCod/IDLE) or the `python3` shell, it just says:
`ModuleNotFoundError: No module named 'customtkinter'`
Also reinstalled the module, but nothing.
Should i reboot the computer?

Thanks.

**Comment by TomSchimansky** [comment]
Try to install it with `python3 -m pip install customtkinter`. This way you make sure you install it for the python version you are using with the `python3` command.
