### ISSUE TITLE
MacOS OptionMenu and ComboBox

### ISSUE THREAD

**Issue by PeymanSeirafi** [TomSchimansky/CustomTkinter#149]
Today I was trying to create a simple app in my mac with python and customtkinter but I had a simple problem. When I use OptionMenu or ComboBox there is a frame like an app window and makes OptionMenu not like the thing that it should be. you can see what i mean:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/91782017/172013132-cd8548b9-9374-414b-abac-4ff07f12b159.png">

**please** solve this problem as fast as possible because I need OptionMenu for my code ...

**Comment by felipetesc** [comment]
Hello PeymanSeirafi. Can you post the code please ? Thank you.

**Comment by TomSchimansky** [comment]
I know of this problem, this occurs only on macOS with python >= 3.10.0. I think I will convert the dropdown menu to a standard tkinter.Menu, very soon, because there occur so much platform specific bugs. It's just not possible to create a custom dropdown menu with tkinter.Toplevel, which works reliable on every platform.

**Comment by PeymanSeirafi** [comment]
> Hello PeymanSeirafi. Can you post the code please ? Thank you.

import tkinter
import customtkinter

customtkinter.set_appearance_mode("dark")  # Modes: "System" (standard), "Dark", "Light"
customtkinter.set_default_color_theme("blue")  # Themes: "blue" (standard), "green", "dark-blue"

app = customtkinter.CTk()
app.geometry("400x580")
app.title("CustomTkinter simple_example.py")


def button_callback():
    print("Button click", combobox_1.get())


def slider_callback(value):
    progressbar_1.set(value)


frame_1 = customtkinter.CTkFrame(master=app)
frame_1.pack(pady=20, padx=60, fill="both", expand=True)

label_1 = customtkinter.CTkLabel(master=frame_1, justify=tkinter.LEFT)
label_1.pack(pady=12, padx=10)

progressbar_1 = customtkinter.CTkProgressBar(master=frame_1)
progressbar_1.pack(pady=12, padx=10)

button_1 = customtkinter.CTkButton(master=frame_1, command=button_callback)
button_1.pack(pady=12, padx=10)

slider_1 = customtkinter.CTkSlider(master=frame_1, command=slider_callback, from_=0, to=1)
slider_1.pack(pady=12, padx=10)
slider_1.set(0.5)

entry_1 = customtkinter.CTkEntry(master=frame_1, placeholder_text="CTkEntry")
entry_1.pack(pady=12, padx=10)

optionmenu_1 = customtkinter.CTkOptionMenu(frame_1, values=["Option 1", "Option 2", "Option 42"])
optionmenu_1.pack(pady=12, padx=10)
optionmenu_1.set("CTkOptionMenu")

combobox_1 = customtkinter.CTkComboBox(frame_1, values=["Option 1", "Option 2", "Option 42"])
combobox_1.pack(pady=12, padx=10)
optionmenu_1.set("CTkComboBox")

checkbox_1 = customtkinter.CTkCheckBox(master=frame_1)
checkbox_1.pack(pady=12, padx=10)

radiobutton_var = tkinter.IntVar(value=1)

radiobutton_1 = customtkinter.CTkRadioButton(master=frame_1, variable=radiobutton_var, value=1)
radiobutton_1.pack(pady=12, padx=10)

radiobutton_2 = customtkinter.CTkRadioButton(master=frame_1, variable=radiobutton_var, value=2)
radiobutton_2.pack(pady=12, padx=10)

switch_1 = customtkinter.CTkSwitch(master=frame_1)
switch_1.pack(pady=12, padx=10)

app.mainloop()

**Comment by TomSchimansky** [comment]
This is fixed now with version 4.4.0.
