### ISSUE TITLE
Exception raised when trying to configure text_color for CTkSwitch 

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1497]
Hi: customtkinter v5.1.2

When trying to configure the colour for a CTkSwitch widget the exception is encountered:

```
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['text_color'] are not supported arguments. Look at the documentation for supported arguments.
```
This can be reproduced with the complex_example.py, by adding the line at the end here: 

```
        for i in range(100):
            switch = customtkinter.CTkSwitch(master=self.scrollable_frame, text=f"CTkSwitch {i}")
            switch.grid(row=i, column=0, padx=10, pady=(0, 20))
            self.scrollable_frame_switches.append(switch)
            switch.configure(text_color='red') 
```

**Comment by MaxNiark** [comment]
Hello, Yeah you cant configure the text_color like this because .py function doens't allow. 

please the CTKswitch.py in widget folder CTKinter to know how set this :) 

there are many way !! :) 


```
    def configure(self, require_redraw=False, **kwargs):
        if "corner_radius" in kwargs:
            self._corner_radius = kwargs.pop("corner_radius")
            require_redraw = True

        if "border_width" in kwargs:
            self._border_width = kwargs.pop("border_width")
            require_redraw = True

        if "button_length" in kwargs:
            self._button_length = kwargs.pop("button_length")
            require_redraw = True

        if "switch_width" in kwargs:
            self._switch_width = kwargs.pop("switch_width")
            self._canvas.configure(width=self._apply_widget_scaling(self._switch_width))
            require_redraw = True

        if "switch_height" in kwargs:
            self._switch_height = kwargs.pop("switch_height")
            self._canvas.configure(height=self._apply_widget_scaling(self._switch_height))
            require_redraw = True

        if "text" in kwargs:
            self._text = kwargs.pop("text")
            self._text_label.configure(text=self._text)

        if "font" in kwargs:
            if isinstance(self._font, CTkFont):
                self._font.remove_size_configure_callback(self._update_font)
            self._font = self._check_font_type(kwargs.pop("font"))
            if isinstance(self._font, CTkFont):
                self._font.add_size_configure_callback(self._update_font)

            self._update_font()

        if "state" in kwargs:
            self._state = kwargs.pop("state")
            self._set_cursor()
            require_redraw = True

        if "fg_color" in kwargs:
            self._fg_color = self._check_color_type(kwargs.pop("fg_color"))
            require_redraw = True

        if "progress_color" in kwargs:
            self._progress_color = self._check_color_type(kwargs.pop("progress_color"), transparency=True)
            require_redraw = True

        if "button_color" in kwargs:
            self._button_color = self._check_color_type(kwargs.pop("button_color"))
            require_redraw = True

        if "button_hover_color" in kwargs:
            self._button_hover_color = self._check_color_type(kwargs.pop("button_hover_color"))
            require_redraw = True

        if "border_color" in kwargs:
            self._border_color = self._check_color_type(kwargs.pop("border_color"), transparency=True)
            require_redraw = True

        if "hover" in kwargs:
            self._hover = kwargs.pop("hover")

        if "command" in kwargs:
            self._command = kwargs.pop("command")

        if "textvariable" in kwargs:
            self._textvariable = kwargs.pop("textvariable")
            self._text_label.configure(textvariable=self._textvariable)

        if "variable" in kwargs:
            if self._variable is not None and self._variable != "":
                self._variable.trace_remove("write", self._variable_callback_name)

            self._variable = kwargs.pop("variable")

            if self._variable is not None and self._variable != "":
                self._variable_callback_name = self._variable.trace_add("write", self._variable_callback)
                self._check_state = True if self._variable.get() == self._onvalue else False
                require_redraw = True

        super().configure(require_redraw=require_redraw, **kwargs)
```

**Comment by MaxNiark** [comment]
in this call : 

switch = customtkinter.CTkSwitch(master=self.scrollable_frame, text=f"CTkSwitch {i}, text_color "GREEN")
Json file, or theme configure change is a way  i guess 

![image](https://user-images.githubusercontent.com/126392328/233840381-bb9362dc-4453-4494-a2ef-2e24a3a3d3dd.png)

**Comment by avalon60** [comment]
I'm building a WYSIWYG CustomTkinter theme builder. When the user changes a colour for a widget property, a preview widget is meant to change colour in response (right hand panel in image), I require the ability to configure property colours for all widgets.
![image](https://user-images.githubusercontent.com/89534395/233851444-5a5289ef-a338-45cb-82e0-0157fc36d5dc.png)

**Comment by avalon60** [comment]
> Hello, Yeah you cant configure the text_color like this because .py function doens't allow.
> 
> please the CTKswitch.py in widget folder CTKinter to know how set this :)
> 
> there are many way !! :)
> 
> ```
>     def configure(self, require_redraw=False, **kwargs):
>         if "corner_radius" in kwargs:
>             self._corner_radius = kwargs.pop("corner_radius")
>             require_redraw = True
> 
>         if "border_width" in kwargs:
>             self._border_width = kwargs.pop("border_width")
>             require_redraw = True
> 
>         if "button_length" in kwargs:
>             self._button_length = kwargs.pop("button_length")
>             require_redraw = True
> 
>         if "switch_width" in kwargs:
>             self._switch_width = kwargs.pop("switch_width")
>             self._canvas.configure(width=self._apply_widget_scaling(self._switch_width))
>             require_redraw = True
> 
>         if "switch_height" in kwargs:
>             self._switch_height = kwargs.pop("switch_height")
>             self._canvas.configure(height=self._apply_widget_scaling(self._switch_height))
>             require_redraw = True
> 
>         if "text" in kwargs:
>             self._text = kwargs.pop("text")
>             self._text_label.configure(text=self._text)
> 
>         if "font" in kwargs:
>             if isinstance(self._font, CTkFont):
>                 self._font.remove_size_configure_callback(self._update_font)
>             self._font = self._check_font_type(kwargs.pop("font"))
>             if isinstance(self._font, CTkFont):
>                 self._font.add_size_configure_callback(self._update_font)
> 
>             self._update_font()
> 
>         if "state" in kwargs:
>             self._state = kwargs.pop("state")
>             self._set_cursor()
>             require_redraw = True
> 
>         if "fg_color" in kwargs:
>             self._fg_color = self._check_color_type(kwargs.pop("fg_color"))
>             require_redraw = True
> 
>         if "progress_color" in kwargs:
>             self._progress_color = self._check_color_type(kwargs.pop("progress_color"), transparency=True)
>             require_redraw = True
> 
>         if "button_color" in kwargs:
>             self._button_color = self._check_color_type(kwargs.pop("button_color"))
>             require_redraw = True
> 
>         if "button_hover_color" in kwargs:
>             self._button_hover_color = self._check_color_type(kwargs.pop("button_hover_color"))
>             require_redraw = True
> 
>         if "border_color" in kwargs:
>             self._border_color = self._check_color_type(kwargs.pop("border_color"), transparency=True)
>             require_redraw = True
> 
>         if "hover" in kwargs:
>             self._hover = kwargs.pop("hover")
> 
>         if "command" in kwargs:
>             self._command = kwargs.pop("command")
> 
>         if "textvariable" in kwargs:
>             self._textvariable = kwargs.pop("textvariable")
>             self._text_label.configure(textvariable=self._textvariable)
> 
>         if "variable" in kwargs:
>             if self._variable is not None and self._variable != "":
>                 self._variable.trace_remove("write", self._variable_callback_name)
> 
>             self._variable = kwargs.pop("variable")
> 
>             if self._variable is not None and self._variable != "":
>                 self._variable_callback_name = self._variable.trace_add("write", self._variable_callback)
>                 self._check_state = True if self._variable.get() == self._onvalue else False
>                 require_redraw = True
> 
>         super().configure(require_redraw=require_redraw, **kwargs)
> ```

Yes, but the docs say that you can configure it, and so this is a bug. Please see my earlier response.

**Comment by Adrian8115** [comment]
It's nothing more than adding:
```
if "text_color" in kwargs:
     self._text_color = self._check_color_type(kwargs.pop("text_color"))
     require_redraw = True
```
to line 284

in customtkinter\windows\widgets\ctk_switch.py

**Comment by TomSchimansky** [comment]
fixed, the theme builder looks promising by the way.
