### ISSUE TITLE
CTkTabview blinking

### ISSUE THREAD

**Issue by vitalibr** [TomSchimansky/CustomTkinter#1508]
I'm using the CTkTabview but when I click on the tab the content flashes (blank), I've tried changing the theme and the behavior keeps happening.

the same behavior happens using the example code from the documentation:
https://customtkinter.tomschimansky.com/documentation/widgets/tabview 
```from tkinter import *
import customtkinter

class MyTabView(customtkinter.CTkTabview):
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)

        # create tabs
        self.add("tab 1")
        self.add("tab 2")

        # add widgets on tabs
        self.label = customtkinter.CTkLabel(master=self.tab("tab 1"))
        self.label.grid(row=0, column=0, padx=20, pady=10)


class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.tab_view = MyTabView(master=self)
        self.tab_view.grid(row=0, column=0, padx=20, pady=20)


app = App()
app.mainloop()
```

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExODk2ODA2YzRjMGU2NGQ4NzQ2YjM5MmVkMmYwYzU5OWM1NGQ5OGMyZiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/PjCZpestIwfuICzzde/giphy.gif)

Macbook M1 with macOS Ventura 13.1
customtkinter==5.1.2
python-tk@3.11.3

i was analyzing the CustomTkinter code to find the root cause, but no success

**Comment by TomSchimansky** [comment]
For me this is not happening on macOS Ventura with python3.11.0 on Intel mac, so I can not test other options here. But maybe you can test these two replacements for the the method `_segmented_button_callback` in `CTkTabview` for me.

Option 1:
```python
    def _segmented_button_callback(self, selected_name):
        self._set_grid_tab_by_name(selected_name)
        self._tab_dict[self._current_name].grid_forget()
        self._current_name = selected_name

        if self._command is not None:
            self._command()
```

Option 2:
```python
    def _segmented_button_callback(self, selected_name):
        self._set_grid_tab_by_name(selected_name)
        old_name = self._current_name
        self.after(5, lambda: self._tab_dict[old_name].grid_forget())
        self._current_name = selected_name

        if self._command is not None:
            self._command()
```

Maybe these will fix this issue.

**Comment by eirnym** [comment]
Hi @TomSchimansky 

I have the same issue on macOS Monterey on arm64 (M2). I've tried both versions of proposed solution and the second one flickers less, than the first one. The solution, which not flickers is below. See #2002 for a PR

I use Python 3.11 and customtkinter-5.2.0


```python
    def _segmented_button_callback(self, selected_name):
        self._set_grid_tab_by_name(selected_name)
        old_name = self._current_name
        # on fast switching delaying `grid_forget` causing flickering
        self._tab_dict[old_name].grid_forget()
        # following line also causing flickering
        # self._current_name = selected_name 

        if self._command is not None:
            self._command()
```

**Comment by dweebio** [comment]
Hi @eirnym Did you ever find a fix?

**Comment by eirnym** [comment]
I've mentioned the fix. Later I've chosen other UI framework as author wasn't interested to fix it

**Comment by eirnym** [comment]
`PySide6` is for bigger projects, `fltk`/`imgui` (with emphasis on imgui) for smaller projects, native API is also used from time to time.
