### ISSUE TITLE
Why is the top level window not focused when it's opened?

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#1517]
Here's the basic example for `CTkTopLevel` from the documentation. The top level window stays behind the root when it's called, it is not focused. When I try to focus it after calling it, it doesn't work. How can I make it automatically focused when it's called?

```python
import customtkinter

class ToplevelWindow(customtkinter.CTkToplevel):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.focus() # not working
        self.geometry("400x300")

        self.label = customtkinter.CTkLabel(self, text="ToplevelWindow")
        self.label.pack(padx=20, pady=20)


class App(customtkinter.CTk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.geometry("500x400")

        self.button_1 = customtkinter.CTkButton(self, text="open toplevel", command=self.open_toplevel)
        self.button_1.pack(side="top", padx=20, pady=20)

        self.toplevel_window = None

    def open_toplevel(self):
        if self.toplevel_window is None or not self.toplevel_window.winfo_exists():
            self.toplevel_window = ToplevelWindow(self)
        else:
            self.toplevel_window.focus()


app = App()
app.mainloop()
```

**Comment by Shahzaib1432** [comment]
i have a similar issue, i needed a way to make the window ALWAYS focused for a prank.

**Comment by OSTEsayed** [comment]
in my case it work fine it focused normally , even without the self.focus() 
but you can use " self.lift() " instead and it will work like charm

**Comment by duruburak** [comment]
> in my case it work fine it focused normally , even without the self.focus() but you can use " self.lift() " instead and it will work like charm

It doesn't work.

**Comment by Slawik88** [comment]
Same problem, it doesn't work for me either

**Comment by avalon60** [comment]
Have you tried self.toplevel_window.grab_set()?

Not at my computer just now, so I haven't tried it myself.

**Comment by duruburak** [comment]
> Have you tried self.toplevel_window.grab_set()?
> 
> Not at my computer just now, so I haven't tried it myself.

Yes, I tried that as well.

**Comment by ElectricCandlelight** [comment]
```Python
self.toplevel_window = ToplevelWindow(self)
self.toplevel_window.after(0, self.toplevel_window.lift)
``` 
Or in your ToplevelWindow class 

```Python
self.after(0, self.lift)
```

**Comment by duruburak** [comment]
> ```python
> self.toplevel_window.after(0, self.toplevel_window.lift)
> ```

This didn't work either. It must be something to do with the source code of customtkinter.

**Comment by mdlattimore** [comment]
I'm having the same issue. Toplevel window opens and immediately moves to back (.lift() and .focus() have no effect). It is worth noting that I have run this on both Mac and Windows platforms and this seems only to be a problem in Windows (haven't tested on Linux). On Mac, the Toplevel window opens in front and stays there out of the box (no need to .lift() or .focus()).

**Comment by mdlattimore** [comment]
> in my case it work fine it focused normally , even without the self.focus() but you can use " self.lift() " instead and it will work like charm

Any chance you're getting this result on MacOS?

**Comment by yizhouzhao** [comment]
self.toplevel_window = ToplevelWindow(self)
self.toplevel_window.after(10, self.toplevel_window.lift)

**Comment by duruburak** [comment]
> self.toplevel_window = ToplevelWindow(self) self.toplevel_window.after(10, self.toplevel_window.lift)

This one works, thanks. 👌

**Comment by addaguob** [comment]
```
class ToplevelWindow(customtkinter.CTkToplevel):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.focus()  # not working
        self.after(100, self.focus) # 200ms if your CPU is too fast
        self.geometry("400x300")

        self.label = customtkinter.CTkLabel(self, text="ToplevelWindow")
        self.label.pack(padx=20, pady=20)
```

> Here's the basic example for `CTkTopLevel` from the documentation. The top level window stays behind the root when it's called, it is not focused. When I try to focus it after calling it, it doesn't work. How can I make it automatically focused when it's called?
> 
> ```python
> import customtkinter
> 
> class ToplevelWindow(customtkinter.CTkToplevel):
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.focus() # not working
>         self.geometry("400x300")
> 
>         self.label = customtkinter.CTkLabel(self, text="ToplevelWindow")
>         self.label.pack(padx=20, pady=20)
> 
> 
> class App(customtkinter.CTk):
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.geometry("500x400")
> 
>         self.button_1 = customtkinter.CTkButton(self, text="open toplevel", command=self.open_toplevel)
>         self.button_1.pack(side="top", padx=20, pady=20)
> 
>         self.toplevel_window = None
> 
>     def open_toplevel(self):
>         if self.toplevel_window is None or not self.toplevel_window.winfo_exists():
>             self.toplevel_window = ToplevelWindow(self)
>         else:
>             self.toplevel_window.focus()
> 
> 
> app = App()
> app.mainloop()
> ```

**Comment by kurawlefaraaz** [comment]
I noticed that Toplevel appears first before Tk(technically Tk is created first but the Toplevel appears on screen first). So if we use `self.update()` then we get the desired output.

So the final code must be:

```python
import customtkinter

class ToplevelWindow(customtkinter.CTkToplevel):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.focus() # not working
        self.geometry("400x300")

        self.label = customtkinter.CTkLabel(self, text="ToplevelWindow")
        self.label.pack(padx=20, pady=20)


class App(customtkinter.CTk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.geometry("500x400")
        self.update() ##### Notice Here ##########
        self.button_1 = customtkinter.CTkButton(self, text="open toplevel", command=self.open_toplevel)
        self.button_1.pack(side="top", padx=20, pady=20)

        self.toplevel_window = None

    def open_toplevel(self):
        if self.toplevel_window is None or not self.toplevel_window.winfo_exists():
            self.toplevel_window = ToplevelWindow(self)
        else:
            self.toplevel_window.focus()


app = App()
app.mainloop()
```
