### ISSUE TITLE
An error occurrence when changing fonts using tags 

### ISSUE THREAD

**Issue by Kurzuxus** [TomSchimansky/CustomTkinter#1527]
I have a code that changes the font style of a highlighted text segment inside a text_box widget according the style chosen by the user from a combo_box. The problem is that tkinter seems to refuse changing a segment of text and raises this error: 

#raise AttributeError("'font' option forbidden, because would be incompatible with scaling") 
#AttributeError: 'font' option forbidden, because would be incompatible with scaling

I have been wondering how can I work around this. This is how my function is currently looking:
```
def change_style(style):
    current_style = style_menu.get()
    selected_text = text.tag_ranges('sel')
    tag_name = 'style_' + current_style
    text.tag_config(tag_name, font=('','30', current_style))
    text.tag_add(tag_name, selected_text[0], selected_text[1])
```

**Comment by TomSchimansky** [comment]
I disabled this on purpose because its not possible to keep track of the scaling and this would lead to undefined behaviour across multiple devices with different scaling settings.
