### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by synapticvoid** [TomSchimansky/CustomTkinter#1536]
Hi,

The [documentation site](https://customtkinter.tomschimansky.com/) seems to be broken. Here's what I see:
![Screenshot_20230430_091503](https://user-images.githubusercontent.com/3283773/235340796-6fb09390-57a1-4a29-b022-55a1413ed9d3.png)

I was just about to learn CustomTkinter :sob: !

**Comment by priyamsaha** [comment]
Disabling any ad blocker should work

**Comment by synapticvoid** [comment]
Much better, thanks!
