### ISSUE TITLE
parent scaling with children scaling -width only- baseclass 

### ISSUE THREAD

**Issue by MaxNiark** [TomSchimansky/CustomTkinter#1574]
Hello, 

i create personnal baseclasswidget( based on exists). import widget class type variable, and use .gridmethod() for popup the frame. 
i'm working withtabview and scrollableframe. tabview baseclass to create and use cavnas/segmentedbutton, the scrollable is the import in class type var from another file .py

![image](https://user-images.githubusercontent.com/126392328/236648647-99bc6735-6ba3-41b3-8c02-ad83802024de.png)
![image](https://user-images.githubusercontent.com/126392328/236648654-c5ed125a-dffd-42f8-9a48-f30f3346dcc4.png)
![image](https://user-images.githubusercontent.com/126392328/236648678-e189495b-19d5-4375-bbe3-4017e0e2a714.png)

![image](https://user-images.githubusercontent.com/126392328/236649332-3c2962cc-f039-47b2-a283-ccdf6934cb51.png)

**Comment by MaxNiark** [comment]
Huuum lot of part of grid scaling needed to be re-set x)

![image](https://user-images.githubusercontent.com/126392328/236636357-a189e07e-93e2-4194-be00-2e752191cca7.png)

**Comment by MaxNiark** [comment]
![image](https://user-images.githubusercontent.com/126392328/236648092-807825d9-969e-45a3-b035-bac45de8f943.png)
![image](https://user-images.githubusercontent.com/126392328/236648109-a98b31f7-1176-45eb-b9ea-11f873e5ea5d.png)

**Comment by TomSchimansky** [comment]
What's the value of this post, is this an issue with the library? If you found a big please specify the problem, if you want to showcase something please refer to discussions. But please stop posting random screenshots without context.
