### ISSUE TITLE
Documentation on new website not accessible or working

### ISSUE THREAD

**Issue by Archern4r** [TomSchimansky/CustomTkinter#1590]
Hi there, 

upon trying to visit the new website for the documentation on custom tkinter I first get a warning from Firefox (and Safari, for that matter) that the website is either faultily coded or has wrong certificates and should not be trusted; if I choose to trust the website anyway, it is blocked by my employers firewall. If I try to access the website on my phone, the same warnings show but if I decide to trust it there anyway, it never loads. 

Am I the only one having that issue? Right now, the documentation for this library is inaccessible except for the old wiki entrys that say "Outdated" and refer to the official documentation. 

In case I did something wrong or this is a known issue, please let me know.

**Comment by TomSchimansky** [comment]
ssllabs.com now gives A+ rating instead of A, I don't think there's more I can do.
https://www.ssllabs.com/ssltest/analyze.html?d=customtkinter.tomschimansky.com
