### ISSUE TITLE
BUG: Restoring window from minimization

### ISSUE THREAD

**Issue by sukhov-andrii** [TomSchimansky/CustomTkinter#1597]
I mentioned weird graphics bug during restoring windows from minimization.
When I click to minimized app in taskbar its windows will appear on the screen. However, for part of second I can see black rectangles instead of widgets. They disappear as soon as widgets are loaded completely.

I captured it in video. [Google Drive](https://drive.google.com/file/d/1o9EHGhYsaEqkWa3QLyhyC6aAikfcoq5x/view?usp=sharing)

Anyone else have this bug?  

Minimal example:
This example is not about where I met this bug in my application, I am just trying to populate window with many widgets to reproduce the bug and make it more noticeable.
```
import customtkinter as ctk

root = ctk.CTk()
root.geometry('800x800')

for i in range(10):
    ctk.CTkButton(root, text="Click me...").grid()
    ctk.CTkLabel(root, text="Text").grid()


root.mainloop()
```

**Comment by TomSchimansky** [comment]
Tkinter rendering is not the fastest, there's nothing I can do about it. If you want a more performant interface you have to try maybe PyQt or a website rendering with electron.
