### ISSUE TITLE
Ability to display color of progressed scale widget?

### ISSUE THREAD

**Issue by IshanJ25** [TomSchimansky/CustomTkinter#16]
Is it possible to achieve this setting? (refer to the image)
I want to use the scale widget to make a color picker like this here. See the color filled in upto value?
![image](https://user-images.githubusercontent.com/86649457/145866706-d8cbb168-6d10-431d-b269-e30951369d71.png)

**Comment by TomSchimansky** [comment]
Currently that's not possible because the slider only has one line, and you cannot make the color transparent and put a progress bar underneath it, but I will see if I can change it so that its possible.

**Comment by IshanJ25** [comment]
okay
thanks for quick reply

**Comment by TomSchimansky** [comment]
I added the option `progress_color`, which is by default the same as `fg_color`, and which colors the line before the round button as shown in the image above.

When you add the argument to the slider in simple_example.py, then it looks like this:
<img width="512" alt="Bildschirmfoto 2021-12-13 um 21 54 03" src="https://user-images.githubusercontent.com/66446067/145887836-49fb8edc-7f0d-4e6a-82f6-b6ee1634f9b1.png">

```python
slider_1 = customtkinter.CTkSlider(master=frame_1, command=slider_function, from_=0, to=2, progress_color="gray40")
slider_1.place(relx=0.5, rely=0.55, anchor=tkinter.CENTER)
slider_1.set(1.5)
```

I didnt upload the new version on pip yet, but you can just download the repository and place the custom tkinter folder next to your file and use it like this if you want.
