### ISSUE TITLE
Option Menu don't open if the master is grab

### ISSUE THREAD

**Issue by Lucas-BRT** [TomSchimansky/CustomTkinter#160]
Hello, i trying to do a simple project, but in one step the user's don't 
can click back to the main screem until complete the data inform,
i tryed use the the grab_set function, but now the option menu don't open anymore

example of code:
in this first the option menu works, but the users can back to the main screen in a simply click

`import tkinter
from customtkinter import *

values = ["monkey","dog","cat"]
WIDTH = HEIGTH = 300
app = CTk()
def floating_window():
    flo_win = CTkToplevel(app)
    flo_win.geometry(f"{WIDTH}x{HEIGTH}")
    def test():
        print("ok")
    CTkOptionMenu(flo_win,values=values).pack()
    CTkButton(flo_win,text="test",command=test).pack()
CTkButton(app,command=floating_window).pack()
app.mainloop()`

in this second the users can't back to the main screen until close direct the window, but the option menu doesn't open

`import tkinter
from customtkinter import *

values = ["monkey","dog","cat"]
WIDTH = HEIGTH = 300
app = CTk()
def floating_window():
    flo_win = CTkToplevel(app)
    flo_win.geometry(f"{WIDTH}x{HEIGTH}")
    flo_win.grab_set()
    def test():
        print("ok")
    CTkOptionMenu(flo_win,values=values).pack()
    CTkButton(flo_win,text="test",command=test).pack()
CTkButton(app,command=floating_window).pack()
app.mainloop()`

as I've been studying programming for a short time, I'm not sure if this 
is really a bug or if I'm using the wrong function for this purpose.

**Comment by TomSchimansky** [comment]
I don't now if this was a bug, but there should be no problems with the dropdown menu as of version 4.4.0, because I use tkinter.Menu for the dropdown now, instead of a tkinter.Toplevel window.
