### ISSUE TITLE
Cannot Access Items In CTkComboBox and CTkOptionMenu With Many Values

### ISSUE THREAD

**Issue by PercentBoat4164** [TomSchimansky/CustomTkinter#1610]
###  The Problem
Whenever a CTkComboBox or CTkOptionMenu is given a large number of items, they begin too misbehave. I have noticed a few things.
 - On click the menu opens and on release the menu closes selecting whichever element the mouse was over at the time. Typical behaviour demonstrated by these widgets when there are few items involves clicking once to open the menu, then clicking again on the desired element.
 - Upon opening the menu, the element that is first in the list of values is at the top of the screen, and (on Ubuntu) is unclickable.
 - Upon opening the menu, elements cascade down the screen and beyond. There is no way to access elements beyond the bounds of the screen because, upon scrolling withing this menu, the menu closes and selects whichever element the mouse was over at the time.

### How to Solve it
The first problem is an implementation detail, but the second and third can be solved the same way. Limit the maximum size of the CTkComboBox or CTkOptionMenu sub windows. Any excess elements should still be accessible by scrolling down using the mouse wheel or a scroll bar.

**Comment by Akascape** [comment]
Try this: https://github.com/Akascape/CTkScrollableDropdown

**Comment by TomSchimansky** [comment]
The menu is just a tkinter menu, I did not create this myself. And tkinter does not support scrolling on a menu on Linux so there's nothing I can do. I would say if you have more than 20 elements to choose from you should create a scrollable list like described here: https://customtkinter.tomschimansky.com/tutorial/scrollable-frames
