### ISSUE TITLE
Missing Widget Class Example

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1616]
Tom, you used to have an example of how to create a new class of widget. Is this still around?
It would be good to reinstate this at the new docs location.

I can't remember the details, but it would be good to  outline any requisite base class inheritance requirements as well as any method overloading required for redrawing, for instance, when appearance mode is changed. That is, if this is permissable, since the CTkBaseClass._draw() method is private. If I understand the way CustomTkinter works, then overriding CTkBaseClass._draw() might be a necessary requirement in the case of some classes based on Tkinter widgets?

**Comment by TomSchimansky** [comment]
Do you mean this: https://customtkinter.tomschimansky.com/tutorial/spinbox
Something else might be somewhere in the issues or discussions but I can't remember. But why do you want to call _draw()? If you want to create a new widget based on CTkBaseCLass you can just take any CTk widget as a template.

**Comment by avalon60** [comment]
> Do you mean this: https://customtkinter.tomschimansky.com/tutorial/spinbox Something else might be somewhere in the issues or discussions but I can't remember. But why do you want to call _draw()? If you want to create a new widget based on CTkBaseCLass you can just take any CTk widget as a template.

I wanted to create a tkinter.Menu based widget, presumably _draw() would be needed to change the Dark / Light mode changes for the Tkinter component?

**Comment by TomSchimansky** [comment]
`CTkAppearanceModeBaseClass` is responsible for the appearance mode and automatic appearance mode changes. You cannot directly import it, you have to import it like this:
```python
from customtkinter.windows.widgets.appearance_mode.appearance_mode_base_class import CTkAppearanceModeBaseClass
```
Then you inherit from this class:
```python
class CBtkMenu(tk.Menu, CTkAppearanceModeBaseClass):
```

And you can override the `_set_appearance_mode` method, which gets called on appearance mode changes, like this:
```python
    def _set_appearance_mode(self, mode_string):
        super()._set_appearance_mode(mode_string)
        self._draw()
```
And in the `_draw` method, that you have to implement yourself, you can update the colors with the help of the `_apply_appearance_mode `:
```python
    def _draw(self):
        single_color = self._apply_appearance_mode(color)
        ...
```
`_apply_appearance_mode ` selects the correct color for tuple colors but can also handle single colors.

That's how its done for CTk widgets.

**Comment by avalon60** [comment]
Thanks Tom.
