### ISSUE TITLE
Minor bug (and a suggestion)

### ISSUE THREAD

**Issue by DamirTomic** [TomSchimansky/CustomTkinter#1631]
https://github.com/TomSchimansky/CustomTkinter/blob/1960c0b1e055539f2856256d5deac472f019fe13/customtkinter/windows/ctk_input_dialog.py#L89 - shouldn't this call _cancel_event method instead of _ok_event?

Also, 
https://github.com/TomSchimansky/CustomTkinter/blob/1960c0b1e055539f2856256d5deac472f019fe13/customtkinter/windows/ctk_input_dialog.py#L62 - It might be better to use the title for the label or add a new param: description. I'm passing a variable input and it's a bit strange that the label changes with the input text.

**Comment by dishb** [comment]
I'll open a PR for the issue (using `._cancel_event()`)

**Comment by dishb** [comment]
Maybe make a new issue for the enhancement/feature req or add it to the Discussions tab (it has an Ideas section).

**Comment by TomSchimansky** [comment]
could be a good idea
