### ISSUE TITLE
CTkScrollableFrame: how to use CTkScrollableFrame both horizontal and vertical

### ISSUE THREAD

**Issue by Chang-LeHung** [TomSchimansky/CustomTkinter#1637]
I need to use a scrollbar for both horizontal and vertical orientation but only can choose one orientation

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/1294
Maybe will try to do it in the future.

**Comment by Chang-LeHung** [comment]
ok, thanks

**Comment by Sahar-Saif** [comment]
hello [TomSchimansky]
i want your help with GUI code, if you have free time
