### ISSUE TITLE
Align content in CTKButtons

### ISSUE THREAD

**Issue by DomGravante** [TomSchimansky/CustomTkinter#164]
Please consider adding another flag in the creation of CTKButtons to allow for the text and image to be aligned. I've attached an image below of the benefits to adding this optional flag.  I personally think this looks a lot more clean and more professional, and could be a great option for users looking keep text looking clean and oriented.
![CTKButton_Align](https://user-images.githubusercontent.com/24944743/172425415-a94537f2-8b89-4115-b3af-fa2564eddeb4.png)

It could just be an optional flag, like:
`button1 = ctk.CTkButton(self.frame, text ="Start Program", image=self.listIcon), compound="left", align_content="w")`
`button2 = ctk.CTkButton(self.frame, text ="Save", image=self.saveIcon), compound="right", align_content="e")`

I went to manually add it and submit a pull request, since it seems like a pretty easy replacement of some of the `sticky` arguments in the button's `draw` method, but I found myself having some issues with the alignment. I think the best and simplest way is to have the `image_label` and `text_label` masters be a separate frame, which can be oriented as needed. I almost have it working and will submit it in a pull request when done. 

Any thoughts?

**Comment by TomSchimansky** [comment]
I will have a look at this!

**Comment by austrianadrian** [comment]
Good Morning...
is this problem now solved ? 
If yes.. 
what ist the special word ? align_content ?? at the moment not integrated in the current version..

**Comment by TomSchimansky** [comment]
It's not solved yet, but I will do it in the next days. The pull request provided by @DomGravante was not sufficient, because it destroyed other functionality, but I will try to do it...

**Comment by TomSchimansky** [comment]
With version 5.0.0 I added the `anchor`and `border_spaing` option, the text and image can now be aligned in the button.
