### ISSUE TITLE
Double window

### ISSUE THREAD

**Issue by Alefrasca90** [TomSchimansky/CustomTkinter#1658]
Why every window I create with customtkinter does spawn on top of an old tkinter window? This also happens with top-level windows and dialogs

**Comment by TomSchimansky** [comment]
You have to provide a code example, otherwise nobody help you and please refer to the Discussions tab.

**Comment by Akascape** [comment]
@Alefrasca90 so where do you want to spawn it. You can use the geometry method i.e:  `{'width'x'height'+'x'+'y'}`.
Tip: 
Use `(root.winfo_screenwidth()-width)/2` as x and `(root.winfo_screenheight()-height)/2` as y to spawn it in the middle of the screen.
(Here width and height are of the toplevel window)

**Comment by Alefrasca90** [comment]
I'm running the example from the repository to pop up a top-level from the app window by clicking the button, I copy-pasted the code but I get this error 

AttributeError: 'Toplevel' object has no attribute '_CTkScalingBaseClass__scaling_type'

**Comment by Akascape** [comment]
@Alefrasca90 update customtkinter properly. Check the versions.

**Comment by Alefrasca90** [comment]
I'm sorry to bother but it says requirement already satisfied for the version 5.1.3 and 0.8.0 (from customtkinter)

**Comment by Akascape** [comment]
@Alefrasca90 Paste the new customtkinter folder in the same directory where your program is present

**Comment by Alefrasca90** [comment]
Thanks! Looks working now

**Comment by Akascape** [comment]
@Alefrasca90 I guess, you are using the python version which has an older version of customtkinter installed. But you have updated the ctk installed different python version. So try to switch the python version in environment settings.
