### ISSUE TITLE
Visual Bug Frame

### ISSUE THREAD

**Issue by DaniEnsi** [TomSchimansky/CustomTkinter#166]
Hi, I have a problem, that the frame in your example in issue#90 always looks like this... Any idea how to fix it?
![Bildschirmfoto 2022-06-07 um 21 48 32](https://user-images.githubusercontent.com/74594229/172479687-ceabf38c-f5d1-4939-8fd0-d0e88e08ae42.png)

**Comment by Think-IT-think-gui** [comment]
check if that frame is inside another frame or widget, if so increase the size of that widget or remove the text from the frame and see if it will affect anything.

**Comment by TomSchimansky** [comment]
Pleas post the code of a minimal example of the problem. Otherwise it will be hard to reproduce this...

**Comment by DaniEnsi** [comment]
I fixed It, sorry... :)
