### ISSUE TITLE
CTk 5.1.3: CTkSwitch: cannot apply custom theme

### ISSUE THREAD

**Issue by dishb** [TomSchimansky/CustomTkinter#1666]
### Traceback:
```
Traceback (most recent call last):
  File "/Users/dishb/Documents/hive/hive.py", line 206, in <module>
    hive_app = HiveApp()
               ^^^^^^^^^
  File "/Users/dishb/Documents/hive/hive.py", line 94, in __init__
    self.sys_files_switch = SysFilesSwitch(self, self.sys_files_var)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dishb/Documents/hive/core/sys_files.py", line 40, in __init__
    super().__init__(master = master,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_switch.py", line 57, in __init__
    self._fg_color = ThemeManager.theme["CTkSwitch"]["fg_color"] if fg_color is None else self._check_color_type(fg_color)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'fg_color'
```
### Related:
- #1665

### Code:
Here's the code I'm using: [dishb/hive](https://github.com/dishb/hive)

### Notes:
Unlike in #1665, this issue does not appear to be fixed in the current development version.

**Comment by avalon60** [comment]
There was an issue in 5.1.2, whereby the CTkSwitch had fg_Color instead of fg_color. This was fixed with 5.1.3. You'll need to ensure that any custom themes are updated, to replace the uppercase C of Color with lowercase c - color. If you have fg_Color in your theme file,  that would explain the key error.

**Comment by dishb** [comment]
@avalon60 - Hmmm, I’ll try that, thank you.

**Comment by dishb** [comment]
None of my JSON custom theme files had a uppercase "C", but now it works. This stuff is magikal...
