### ISSUE TITLE
change the icon off the app

### ISSUE THREAD

**Issue by GermanYoshi** [TomSchimansky/CustomTkinter#1674]
hello, is there a way to change the icon of the app?
![image](https://github.com/TomSchimansky/CustomTkinter/assets/39739909/cf18546e-6702-439a-8dd4-5802abde7e01)

**Comment by dishb** [comment]
I would suggest posting this in the Q & A section of the Discussions tab.

One way you can do this is with the following code:
```python
import customtkinter
your_app = customtkinter.CTk()
your_app.iconbitmap("path to a .ico file")
```
