### ISSUE TITLE
Missing comma in wiki documentation

### ISSUE THREAD

**Issue by tjsanzen** [TomSchimansky/CustomTkinter#168]
In the following code from the wiki on the entry form, in the customized example code: https://github.com/TomSchimansky/CustomTkinter/wiki/CTkEntry

`entry = customtkinter.CTkEntry(master=root_tk,
                               placeholder_text="CTkEntry",
                               width=120,
                               height=25,
                               border_width=2
                               corner_radius=10)
entry.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)`

There is a comma missing after border_width=2

Cheers,

**Comment by TomSchimansky** [comment]
Thanks for mentioning this!
