### ISSUE TITLE
Rendering issue on Windows 11

### ISSUE THREAD

**Issue by cheddarking** [TomSchimansky/CustomTkinter#1682]
I have written a program for my windows users and it works fine on Windows 10, however on some (not all) Windows 11 users' machines some rendering issues occur. Please see below

**Working on Windows 11**

![image](https://github.com/TomSchimansky/CustomTkinter/assets/31318846/406e2ec9-a7b7-40ea-bb52-7c6133eff1e7)

**Not working on Windows 11**

![image](https://github.com/TomSchimansky/CustomTkinter/assets/31318846/40787370-fd3b-44b7-937f-60b253170072)

As you can see some of the text and hyperlinks get garbled. What could be causing this?

**Comment by octimot** [comment]
What fonts are you using in your theme?

**Comment by cheddarking** [comment]
> What fonts are you using in your theme?

The copyright label uses ctk.CTkFont(family="Inter", weight="normal" )

The User Manual and csv template links both use ctk.CTkFont(family="Inter", size=12, weight="normal" )

**Comment by dishb** [comment]
It looks like the fonts are the problem. I think we can rule out OS or OS version as you mentioned that some Windows 11 users _are_ able to run the program properly.

Maybe the users (those facing issues) don't have the font installed. How are you providing the font? Is it being loaded or are you assuming the font is installed?

I also don't think this is a CustomTkinter issue. A better place for this would've been in the Discussions tab of this repository. Perhaps the Q&A section.

**Comment by dishb** [comment]
@cheddarking - Just checked [this page](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list), the font Inter is _not_ installed on Windows 11 by default. The problem may be that you are assuming the font to be installed rather than providing it with the app.

**Comment by TomSchimansky** [comment]
@cheddarking there is just a different font used than you intended, either you have to install it properly or the name is not specific enough.
