### ISSUE TITLE
Feature Request: Simplify widget configuration

### ISSUE THREAD

**Issue by Wyko** [TomSchimansky/CustomTkinter#1683]
It would be really nice if there was a consistent way to get and set the current state of all widgets. For example, if every widget implemented an identical `get_value` and `set_value` method, so that the output of the `get` could be fed into `set` and have the value be the same. This would allow things like this:

```python
for widget in [
  my_entry,
  my_switch,
  my_textbox,
  # ...etc
]:
  saved_val = widget.get_value()
  # ... later, with a new widget of the same type:
  my_new_widget.set_value(saved_val)
```

This would save people from needing to know the specific implementation of how to get and set the different widgets, and simplify bulk loading and saving of fields. Now I need to do something like this:

```python
if isinstance(widget, UsableTextbox):
    widget.clear()
    widget.write(result) #Cutom method, that makes writing easier
elif isinstance(widget, ctk.CTkEntry):
    widget.delete(0, "end")
    widget.insert(0, result)
elif isinstance(widget, ctk.CTkComboBox):
    widget.set(result)
elif isinstance(widget, ctk.CTkTabview):
    widget.set(result)
elif isinstance(widget, ctk.CTkSwitch):
    widget.configure(variable=result) # I'm currently trying to figure this one out, which prompted this issue
else:
    raise ValueError(
        "Found unknown widget type when attempting to restore previous value: "
        + str(type(widget))
    )
```

**Comment by avalon60** [comment]
It's not that straight forward. For example, you need to use a customtkinter  variable with groups of radio buttons. Also with textbox widgets, the methods cater for inserting text into the middle of existing text.

In the majority of cases you can do a get() or a set().

**Comment by Wyko** [comment]
Of course, different widgets can have different configuration options. The point is not to remove the ability to turn the specific buttons each one needs, but two additionally offer a single method that can install the previous settings.

This means that the `get` method might return a different object for each widget, or maybe a dictionary results or something. But whatever it returns could be given to the `set` method without needing to know the specific implementation of the widget, and the widget would be set to that value.

If you needed to do specific things like insert the results into the middle of the text or something, then you turn the specific knobs needed. But that would be beyond the scope of that method anyway.

**Comment by dishb** [comment]
This would be a leap further,but maybe something like` kv-lang` for `kivy`?

**Comment by TomSchimansky** [comment]
I don't think this could be done easily with the current state of CustomTkinter and how it uses the methods of tkinter. If you would write a UI library from scratch maybe you could try this approach but for CustomTkinter there are currently more urgent problems and my time is limited...
