### ISSUE TITLE
ComboBox Border Color Dropdown

### ISSUE THREAD

**Issue by WaltherSR** [TomSchimansky/CustomTkinter#1696]
Hi,
is it possible to set the border color of dropdown of a combo box?
In image you can see it is white, but I want to have it in a different color. I couldn't find anything in the documentation.
Thank you for your help in advance!

<img width="115" alt="Screenshot 2023-06-07 155620" src="https://github.com/TomSchimansky/CustomTkinter/assets/61822774/ff2cb7eb-0f7a-4cfe-b837-e3febb999895">

**Comment by Akascape** [comment]
@WaltherSR That dropdown is actually a simple tkmenu widget without having much customisability.

Here is a new dropdown menu you can implement easily:
https://github.com/Akascape/CTkScrollableDropdown

![screenshots](https://user-images.githubusercontent.com/89206401/236677843-8d8b76fd-6145-47b1-8f4d-b6a64b08e1ea.png)

**Comment by avalon60** [comment]
> Hi, is it possible to set the border color of dropdown of a combo box? In image you can see it is white, but I want to have it in a different color. I couldn't find anything in the documentation. Thank you for your help in advance!
> 
> <img alt="Screenshot 2023-06-07 155620" width="115" src="https://user-images.githubusercontent.com/61822774/244109842-ff2cb7eb-0f7a-4cfe-b837-e3febb999895.png">

How did you get the border on there in the first place?

**Comment by Akascape** [comment]
> How did you get the border on there in the first place?

Hi @avalon60 , this border is there by default in the tkmenu of windows. MacOS and linux tkmenu doesn't have that border.

**Comment by avalon60** [comment]
> > How did you get the border on there in the first place?
> 
> Hi @avalon60 , this border is there by default in the tkmenu of windows. MacOS and linux tkmenu doesn't have that border.

Thanks @Akascape. It's been a while since I tinkered (pardon the pun - almost) with CustomTkinter on Windows, I must have forgotten. 

Anyway @WaltherSR, there isn't a CustomTkinter theme property, which maps to that border, neither is there a configure option.  The only thing  you could do, is go with @Akascape's solution.

**Comment by WaltherSR** [comment]
@Akascape @avalon60 thank you for your answers!
I assumed that already, but wanted to be sure. I will try @Akascape solution, otherwise I have to live with it. Just change colors overall so it fit better :D
