### ISSUE TITLE
CTkLabel's image to not to be removed (pyimage doesn't exist)

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#1697]
I'm trying to do a very simple thing: Removing the image of a label. But it really doesn't go as planned. I tried but really couldn't debug it. What do you think causes this, any ideas?

![pyimage2 doesn't exist](https://github.com/TomSchimansky/CustomTkinter/assets/100048974/4334bf5a-9116-4225-b8a1-27aabd8acf40)

Here's another Traceback I've encountered also:

```python
-> self.update()
(Pdb) Readline internal error
Traceback (most recent call last):
  File "D:\Python311\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
    res = ensure_str(readline_hook(prompt))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pyreadline3\rlmain.py", line 589, in readline
    self._readline_from_keyboard()
  File "D:\Python311\Lib\site-packages\pyreadline3\rlmain.py", line 553, in _readline_from_keyboard
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pyreadline3\rlmain.py", line 570, in _readline_from_keyboard_poll
    event = c.getkeypress()
            ^^^^^^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pyreadline3\console\console.py", line 534, in getkeypress
    e = self.get()
        ^^^^^^^^^^
  File "D:\Python311\Lib\site-packages\pyreadline3\console\console.py", line 524, in get
    call_function(inputHookFunc, ())
OSError: exception: access violation writing 0x0000000000000158
```

**Comment by dishb** [comment]
Based on the traceback this looks like an issue with `pyreadline3`...? Unless this is your code/project.

The traceback also shows an `OSError` rather than a `TclError` in the screenshot you provided.

Could you give a portion of the code, or a minimal, reproducible example?

**Comment by duruburak** [comment]
> Based on the traceback this looks like an issue with `pyreadline3`...? Unless this is your code/project.
> 
> The traceback also shows an `OSError` rather than a `TclError` in the screenshot you provided.
> 
> Could you give a portion of the code, or a minimal, reproducible example?

I'm trying to understand why would it throw an "image pyimage2 doesn't exist" error when i'm trying to update it to None? I'll try to make a minimal reproducible example out of it also.

**Comment by duruburak** [comment]
I solved it... I forgot to update a global variable.

**Comment by dishb** [comment]
> I solved it... I forgot to update a global variable.

Oh okay, great! 👍
