### ISSUE TITLE
Mistake in Documentation of CTkToplevel

### ISSUE THREAD

**Issue by abdullahibnamin** [TomSchimansky/CustomTkinter#1709]
https://customtkinter.tomschimansky.com/documentation/windows/toplevel/#geomtrygeometry_string

Probably would be ".geometry()"

**Comment by dishb** [comment]
Probably just make a quick PR for this. Not a big issue that requires any code review or discussion.

**Comment by Awle** [comment]
@dishb could do it but I would need permission.

**Comment by dishb** [comment]
> @dishb could do it but I would need permission.

Yeah... unfortunately few people are able to merge PRs, make changes, and close issues.

**Comment by TomSchimansky** [comment]
The website is a separate repository but currently not public on Github, maybe at some point, but I fixed the issues.
