### ISSUE TITLE
Error to convert a .py file to .exe

### ISSUE THREAD

**Issue by nickriz77** [TomSchimansky/CustomTkinter#171]
Good evening,

I try to convert a .py file to .exe with pyinstaller. The file includes customtkinter,  but at the end of the process  the following error is occured: 

Error: import customtkinter

I tried to convert it without customtkiner and it worked. 
 
 Thanks!

**Comment by DomGravante** [comment]
Have you tried following the steps in this wiki article? Might help troubleshooting.
[https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging](https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging)

**Comment by nickriz77** [comment]
> Have you tried following the steps in this wiki article? Might help troubleshooting.
> https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

Thank you so much my friend 😀😀
Have a nice day!
