### ISSUE TITLE
Color substrings of a `CTkLabel`

### ISSUE THREAD

**Issue by MoritzNekolla** [TomSchimansky/CustomTkinter#1710]
@TomSchimansky 

You answered my question [here](https://github.com/TomSchimansky/CustomTkinter/discussions/1603#discussion-5186665) about coloring substrings in a `CTkTextbox`.

Could you explain how I color substrings of a `CTkLabel` as well? `tag_add()` does not work here neither does Latex Strings.

Thanks in advance

**Comment by Akascape** [comment]
@MoritzNekolla use the same textbox with readonly state an with transparent fg color.
