### ISSUE TITLE
Title widget progressbar not work

### ISSUE THREAD

**Issue by JM-command** [TomSchimansky/CustomTkinter#1713]
how to put the title higher without being cut?

`class CircularProgressBarClients(tk.Canvas):
    def __init__(self, parent, size, bg_color='#2b2b2b', fill_color='#00aaff'):
        super().__init__(parent, width=size, height=size, bg=bg_color, highlightthickness=0)
        self.size = size
        self.bg_color = bg_color
        self.fill_color = fill_color

    def update_progress(self, current, total):
        angle = 360 * current / total
        self.delete("progress")
        self.create_arc((5, 5, self.size-5, self.size-5), start=90, extent=-angle, outline='', fill=self.fill_color, tags="progress")
        self.create_oval((40, 40, self.size-40, self.size-40), fill=self.bg_color, outline='')
        self.create_text((self.size//2, 10), text="My Small text of widget", fill=self.fill_color, font=customtkinter.CTkFont(size=16, weight="bold"))
        self.create_text((self.size//2, self.size//2), text=f"{current}/{total}", fill=self.fill_color, font=customtkinter.CTkFont(size=24, weight="bold"))
`

<img width="316" alt="Capture d’écran 2023-06-13 à 13 00 55" src="https://github.com/TomSchimansky/CustomTkinter/assets/45996599/cc565c70-fee7-4a7f-9dd6-2e0c6d7c633c">

:up: frist screen

with self.create_text((self.size//2, -5), text=".............
second screen 
<img width="263" alt="Capture d’écran 2023-06-13 à 13 03 43" src="https://github.com/TomSchimansky/CustomTkinter/assets/45996599/d42f8839-b6dc-4807-a27b-58e16dd1a528">

my repo : https://github.com/JM-command/BanqueDubois-Tkinter-Python

**Comment by dishb** [comment]
Looking through `main.py` in your repository, it looks like you're drawing this arc/progress bar/circle with `tkinter.Canvas`. I'm assuming that your screenshots show the full size of the window. If you don't want the text to be cut off, simply place the text (with `.grid()`, `.place()` or other methods CustomTkinter provides) higher. 

If the text is being cut off at the top, make your window bigger. The window also appears to be a `tkinter.Tk()` instance. Correct me if I am wrong.

I would suggest closing this as "not planned" (the gray circle) as it doesn't appear to be an issue with CustomTkinter.

**Comment by Akascape** [comment]
@JM-command Adjust the canvas height properly.
You can also use this ready made circular progress bar:
https://github.com/Akascape/TkDial

**Comment by dishb** [comment]
@JM-command - I'd recommend using @Akascape solution (in the comment above) as it is more versatile and doesn't rely on `tkinter.Canvas()`.

**Comment by TomSchimansky** [comment]
@JM-command for questions please use the Discussion section.
