### ISSUE TITLE
CTkSwitch and CTkCheckbox background not working

### ISSUE THREAD

**Issue by Badden420** [TomSchimansky/CustomTkinter#1715]
When i set the background color to the same as the frame i made, it wont change, when i change the border_color it works without a problem.

code:
        self.var = IntVar()
        self.var.set(0)
        self.threshold_filter = customtkinter.CTkSwitch(master=self, text="test",fg_color="#2b2b2b",variable=self.var)
        self.threshold_filter.grid(row=6, column=0,columnspan=1,padx=(20, 20), pady=(20, 10), sticky="w")
        self.threshold_filter.configure(fg_color="#2b2b2b", border_color ="#2179bc", height=50)
        
![Switch](https://github.com/TomSchimansky/CustomTkinter/assets/76973148/7943c00d-8512-42c1-810c-b459484f1c8c)

**Comment by dishb** [comment]
Easier to read code (that you provided):
```python
self.var = IntVar()
self.var.set(0)
self.threshold_filter = customtkinter.CTkSwitch(master = self,
                                                text = "test",
                                                fg_color = "#2b2b2b",
                                                variable = self.var
                                                )
self.threshold_filter.grid(row = 6,
                           column = 0,
                           columnspan = 1,
                           padx = (20, 20),
                           pady = (20, 10),
                           sticky = "w"
                           )
self.threshold_filter.configure(fg_color = "#2b2b2b",
                                border_color = "#2179bc",
                                height = 50
                                )
```

**Comment by dishb** [comment]
First off, (in `self.threshold_filter`) you don't need to use the `.configure()` method to override the `fg_color` attribute when you've assigned the same value when creating the widget.

Assuming #2179BC is the color of the `CTkFrame` that has the child widget `self.threshold_filter`, you never set the `self.threshold_filter`'s `fg_color` attribute to #2179BC.

Please close as "not planned/the gray button" because this _isn't_ an issue with CustomTkinter.

**Comment by Badden420** [comment]
So howcome when i remove both of them that i still have the same issue? And i only have this with the slider and checkbox...

**Comment by dishb** [comment]
In the code example you provided, you aren't configuring the CTkSwitch's foreground color _at all_. That means the foreground color will be the default, which is _not_ the same as your foreground color for the CTkFrame or CTk widget behind it.

**Comment by avalon60** [comment]
Not clear what you are trying to achieve here, the question needs to be expressed more clearly.

**Comment by Badden420** [comment]
I found the problem :
self.threshold_filter = customtkinter.CTkSwitch(**master=self**, text="Enable Filter 96%",variable=self.var)

 self.threshold_filter = customtkinter.CTkSwitch(master= **self.file_processing_frame**, text="Enable Filter 96%",variable=self.var)

problem solved

**Comment by avalon60** [comment]
Is the frame inside another frame? In which case you'd need to determine the top_fg_color of the CTFrame. This is all very limiting though,  unless you do it programmatically.
