### ISSUE TITLE
[Feature] Add tkinter constants to customtkinter

### ISSUE THREAD

**Issue by dishb** [TomSchimansky/CustomTkinter#1716]
I was looking at the `README.md` file, and in the Example Program section, I noticed `tkinter` was being imported to access the constant `tkinter.CENTER`. Perhaps you could add the constants to `customtkinter`. This was, importing `customtkinter` would also give you acess to these constants. Reducing one extra and unnecessary import statement.

**Comment by avalon60** [comment]
I thought these were already available by prefixing with customtkinter or whichever alias you choose on import. 🤔

**Comment by dishb** [comment]
Just checked the [`__init__.py`](https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/__init__.py) file, looks like tkinter constants are imported! I'll change this issue to updating the README.md file.
