### ISSUE TITLE
I can't change background color of a button 

### ISSUE THREAD

**Issue by 0NATI0** [TomSchimansky/CustomTkinter#1718]
My code : 
            button_delete = ctk.CTkButton(button_frame, text="Delete User", command=lambda u=user[0]: self.delete_user(u))
            button_delete.pack(side="left", padx=5, fg_color="red")
            
            
like in the docs

**Comment by avalon60** [comment]
The fg_color should be specified in the ctk.CTkButton statement.

**Comment by dishb** [comment]
`fg_color` is not a valid argument for the `.pack()` method. As @avalon60 said, that should be done when creating the button widget.

Alternatively, you can use the following code:
```python
button_delete.configure(fg_color = "red')
```
