### ISSUE TITLE
UI scaling works buggy

### ISSUE THREAD

**Issue by amiraligpu** [TomSchimansky/CustomTkinter#1724]
Hello there.
Just tested [complex_example.py](https://github.com/TomSchimansky/CustomTkinter/blob/master/examples/complex_example.py) and UI scaling works buggy.
In my opinion, the window should be frozen, then the upscale should occur, and finally, the new window should be shown.

**Comment by TomSchimansky** [comment]
What do you mean? When you change the UI scaling during runtime? In the complex_example I just included the option as a showcase but it was intended that the scaling value gets set before starting the program or just gets read from the operating system automatically on Windows. There's nothing I can do about the slow rendering, this is Tkinter.
