### ISSUE TITLE
Unhandles exception in script

### ISSUE THREAD

**Issue by Aminestesnaei** [TomSchimansky/CustomTkinter#1732]
hi guys i was trying to make .exe file out of .py 
but i get this error :
 Failed to execute script 'Golden' due to Unhandles exception 'CTk'
 more info :
 Traceback (most recent call last):
  File "Golden.py", line 431, in <module>
  File "Golden.py", line 268, in root
  File "customtkinter\windows\ctk_tk.py", line 51, in __init__
    super().configure(bg=ThemeManager.single_color(self.fg_color, self.appearance_mode))
KeyError: 'CTk'

**Comment by dishb** [comment]
You might be using an older version of `customtkinter`. I'm currently looking at [the code](https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/windows/ctk_tk.py) (where the error is being raised), and it looks like the code in your traceback doesn't match up.

Line 51 in your traceback:
```python
super().configure(bg=ThemeManager.single_color(self.fg_color, self.appearance_mode))
```
Line 51 in the [actual file](https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/windows/ctk_tk.py):
```python
self._fg_color = ThemeManager.theme["CTk"]["fg_color"] if fg_color is None else self._check_color_type(fg_color)
```

**Comment by dishb** [comment]
Use `pip install --upgrade customtkinter` to update your version.

**Comment by Aminestesnaei** [comment]
works ! thank you dude
