### ISSUE TITLE
More screenshots/photos/gifs to the documentation?

### ISSUE THREAD

**Issue by biscuitdelicious** [TomSchimansky/CustomTkinter#1735]
Hello there,

Since official's Tkinter(normal one) documentation doesn't have many photos of the objects/actions(ex: button, checkbox, simpledialog, slider, etc.), can we add some for reference? It will be much easier for others to see/check if that's what they want.

I've seen that `CtkInputDialog` and `CtkTopLevel` already has some screenshots as reference - it's much easier to understand what's that.

Thank you!

**Comment by TomSchimansky** [comment]
Hi, was already requested in https://github.com/TomSchimansky/CustomTkinter/issues/1614
