### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by SimoLRepo** [TomSchimansky/CustomTkinter#1746]
Hi, Would it be possible to download the documentation in an offline readable format? (html, chm or pdf).
Thank you very much.

**Comment by dishb** [comment]
In your browser, for each page of the Documentation, just right click and then click "save as". Make sure to select "complete page" to get the CSS, JS, and other assets.

I believe this could be automated with Python. However, for both automation and manual, you need to be online.

**Comment by Awle** [comment]
Another solution would be to copy the documentation code that you can find on the wiki tab.
Then use a markdown(.md) to pdf converter.
I used a VSCode extension to do just that and it works well.

**Comment by dishb** [comment]
Wasn't aware you could copy the markdown sourc, I thought you coukd only copy the rendered blob.

**Comment by SimoLRepo** [comment]
I finally solved it by creating a pdf (with Print Friendly & PDF) with all the pages and the table of contents. Thank you all.
