### ISSUE TITLE
Is scrollbar available in Combobox/OptionMenu?

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#175]
I want to add lots of items in the combobox but the list window size is exceeding the main window, so the scrollbar in combobox/optionMenu is necessary if lots of items are inserted in the list.

It looks like this in normal combobox:
![Akascape_screenshots](https://user-images.githubusercontent.com/89206401/172813544-5804347e-8a2c-42c9-bdc8-c1aa47557527.png)
(the height parameter is used to set the popup listbox height)

Is it possible in CustomTkinter's Combobox/OptionMenu?

**Comment by TomSchimansky** [comment]
No it is not possible, the dropdown menu will be replaced by a tkinter menu soon, and then it should work.
