### ISSUE TITLE
CTkScrollableFrame's expansion (sticky attr.) not working as expected

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#1764]
`CTkScrollableFrame` inside `CTkScrollableFrame` doesn't work the way it's supposed to.
It expands alongside with columns but not with rows.

```python
import customtkinter

root = customtkinter.CTk()
root.grid_rowconfigure(0, weight=1)
root.grid_columnconfigure(0, weight=1)

master_frame = customtkinter.CTkScrollableFrame(root, fg_color="orange")
master_frame.grid(sticky="nsew")
master_frame.grid_rowconfigure(0, weight=1)
master_frame.grid_columnconfigure(0, weight=1)

frame = customtkinter.CTkScrollableFrame(master_frame, fg_color="red")
frame.grid(sticky="nsew")

root.mainloop()
```

**Comment by Awle** [comment]
I am not familiar enough with the code to know if this behavior is intended or not but if you look at the` CTkScrollableFrame` and check the `_fit_frame_dimensions_to_canvas`:
```python
    def _fit_frame_dimensions_to_canvas(self, event):
        if self._orientation == "horizontal":
            self._parent_canvas.itemconfigure(self._create_window_id, height=self._parent_canvas.winfo_height())
        elif self._orientation == "vertical":
            self._parent_canvas.itemconfigure(self._create_window_id, width=self._parent_canvas.winfo_width())
```
You can see that for a vertical ` CTkScrollableFrame` only the width is scaled.

A workaround I found is:
```python
import customtkinter

root = customtkinter.CTk()
root.grid_rowconfigure(0, weight=1)
root.grid_columnconfigure(0, weight=1)

width = root.winfo_screenwidth()               
height = root.winfo_screenheight() 

master_frame = customtkinter.CTkScrollableFrame(root, fg_color="orange")
master_frame.grid(sticky="nsew")
master_frame.grid_rowconfigure(0, weight=1)
master_frame.grid_columnconfigure(0, weight=1)

frame = customtkinter.CTkScrollableFrame(master_frame, width=width, height=height, fg_color="red")
frame.grid(sticky="nsew")

root.mainloop()
``` 

Let me know if it helped.

**Comment by duruburak** [comment]
> I am not familiar enough with the code to know if this behavior is intended or not but if you look at the` CTkScrollableFrame` and check the `_fit_frame_dimensions_to_canvas`:
> 
> ```python
>     def _fit_frame_dimensions_to_canvas(self, event):
>         if self._orientation == "horizontal":
>             self._parent_canvas.itemconfigure(self._create_window_id, height=self._parent_canvas.winfo_height())
>         elif self._orientation == "vertical":
>             self._parent_canvas.itemconfigure(self._create_window_id, width=self._parent_canvas.winfo_width())
> ```
> 
> You can see that for a vertical ` CTkScrollableFrame` only the width is scaled. It also make sense since if your children ` CTkScrollableFrame` would cover your parent widget, there would be no need for scrolling.
> 
> A workaround I found is:
> 
> ```python
> import customtkinter
> 
> root = customtkinter.CTk()
> root.grid_rowconfigure(0, weight=1)
> root.grid_columnconfigure(0, weight=1)
> 
> width = root.winfo_screenwidth()               
> height = root.winfo_screenheight() 
> 
> master_frame = customtkinter.CTkScrollableFrame(root, fg_color="orange")
> master_frame.grid(sticky="nsew")
> master_frame.grid_rowconfigure(0, weight=1)
> master_frame.grid_columnconfigure(0, weight=1)
> 
> frame = customtkinter.CTkScrollableFrame(master_frame, width=width, height=height, fg_color="red")
> frame.grid(sticky="nsew")
> 
> root.mainloop()
> ```
> 
> Let me know if it helped.

Thank you, this works for the given example, yes. But for my case it's not working. In my case, the `CTkScrollableFrame` doesn't take the 100% place, it takes barely 50% of the window height and this code doesn't work for that. The source code gotta be updated i guess.

**Comment by duruburak** [comment]
Updating the source code worked for me:

```python
def _fit_frame_dimensions_to_canvas(self, event):
        if self._orientation == "horizontal":
            self._parent_canvas.itemconfigure(self._create_window_id, width=self._parent_canvas.winfo_width(), height=self._parent_canvas.winfo_height())
        elif self._orientation == "vertical":
            self._parent_canvas.itemconfigure(self._create_window_id, width=self._parent_canvas.winfo_width(), height=self._parent_canvas.winfo_height())
```
