### ISSUE TITLE
window geometry (size) save and restore problem on Win 10 with screen scaling

### ISSUE THREAD

**Issue by ozinka** [TomSchimansky/CustomTkinter#1772]
Hey,
I face an issue to set and restoring the main window size. I want to save the window size into an INI file and restore it on the next run. But see the problem. When I set geometry 500x500 and save the value of wm_geometry() it saves different values - 718x599.
I use Windows 10 with a scaling of 120%. So, seems it saves proper value but does not restore properly using the same values and makes it every time bigger and bigger.
From what I've already read on the Internet, seems it's related to the Windows scaling. But I wonder why I can't use the same values on setting and restoring.
Do we have any workaround for this?
Thnx,
Vitaliy

**Comment by TomSchimansky** [comment]
Instead of `wm_geometry` try to use the normal `geometry` method. All the methods with the "wm" prefix are not working correct in CustomTkinter, I don't know why they even exist in tkinter. Maybe I will overwrite them as well inn the future.

**Comment by ozinka** [comment]
Wow, I missed that geometry exit as well ).
Thank you it works! :)
And thanks for CTK! )
