### ISSUE TITLE
CTKButton posts an event error when not exactly clicked on its text

### ISSUE THREAD

**Issue by joep-m** [TomSchimansky/CustomTkinter#1773]
Hi Tom,
For an application I change the CTKButton text by clicking on it. The issue is that I have to exactly click on the text, otherwise an error is posed. See the application and error text below. I wonder if this has a relation with #656 and if so, how to implement the suggested workaround?

Application:
import tkinter
from tkinter import *
import customtkinter
from customtkinter import *

app = CTk()
app.geometry("400x300")

#text = Label(app, text="Hello World!")
text = CTkLabel(app, text="Hello World!")
text.pack()

def single_click(event):
    print("test1")
    event.widget.configure(text="test")
    print("test2")

#btn = Button(master=app, text="click me")
btn = CTkButton(master=app, text="click me")
btn.pack()

btn.bind('<Button-1>', lambda event: single_click(event))

app.mainloop()

Error:
/usr/local/bin/python3.9 /Users/joep/PycharmProjects/TrippleYathzee/venv/test.py 
test1
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/joep/PycharmProjects/TrippleYathzee/venv/test.py", line 25, in <lambda>
    btn.bind('<Button-1>', lambda event: single_click(event))
  File "/Users/joep/PycharmProjects/TrippleYathzee/venv/test.py", line 17, in single_click
    event.widget.configure(text="test")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-text"

Thanks for all you efforts!
Joep

**Comment by TomSchimansky** [comment]
The problem is that the `event.widget` passed to the callback function refers only to the actual tkinter widget clicked. But a CTkButton consists of multiple tkinter widgets, so this method of using the `event.widget` is not working for CustomTkinter. Just use the `btn` directly in the callback function.

If you want to use the same method for different buttons you can pass the corresponding button to the callback function yourself like this:
```python
btn.bind("<Button-1>", lambda event: single_click(btn))
```

**Comment by joep-m** [comment]
Works like a charm! Thanks
