### ISSUE TITLE
Enhancement Request : Add Password  [ New Widget ]

### ISSUE THREAD

**Issue by YoussefEssalhi** [TomSchimansky/CustomTkinter#1793]
**Maybe Password Entry would be a nice addition as a new widget in customtkinter**

![pas](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/2a57817e-0f04-44b4-9d3e-db51f06c5d3b)

normal must be like this :
![image](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/ae317a5f-7e7e-4137-8a90-4d4c9d2a5b1d)

The Widget must have an option to add a toggle button
- and the toggle button must be hsa an option to add custom icons

**Comment by YoussefEssalhi** [comment]
Btw, using `show="*"` is work

![image](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/e65d8e6f-d23d-4bec-a2f3-ecbd9a73a22a)

**but * not like circle**

**Comment by TomSchimansky** [comment]
You can build it yourself:
```python
import customtkinter
from PIL import Image


class PasswordEntry(customtkinter.CTkFrame):
    def __init__(self, master, **kwargs):
        super().__init__(master, fg_color="transparent")

        self.eye_open_image = customtkinter.CTkImage(Image.open("test_images/eye-password-show.png"))
        self.eye_closed_image = customtkinter.CTkImage(Image.open("test_images/eye-password-hide.png"))

        self.entry = customtkinter.CTkEntry(self, **kwargs, show="•")
        self.entry.grid(row=0, column=0)

        self.button = customtkinter.CTkButton(self, width=20, height=20, text="", image=self.eye_closed_image, command=self.button_callback)
        self.button.grid(row=0, column=1, padx=(5, 0))

        self.password_hide = True

    def button_callback(self):
        if self.password_hide:
            self.password_hide = False
            self.button.configure(image=self.eye_open_image)
            self.entry.configure(show="")
        else:
            self.password_hide = True
            self.button.configure(image=self.eye_closed_image)
            self.entry.configure(show="•")


app = customtkinter.CTk()

password_entry = PasswordEntry(app)
password_entry.grid(row=0, column=0, padx=20, pady=20)

app.mainloop()
```
<img width="333" alt="Bildschirm­foto 2023-07-09 um 10 51 18" src="https://github.com/TomSchimansky/CustomTkinter/assets/66446067/66864e57-5728-4c24-a8d5-8ec64d830fb5">

![eye-password-show](https://github.com/TomSchimansky/CustomTkinter/assets/66446067/1b2d7b8d-5e74-409e-afb0-3915f4459e78)
![eye-password-hide](https://github.com/TomSchimansky/CustomTkinter/assets/66446067/d6b89029-8acf-45d9-a254-b9a83464807a)

**Comment by YoussefEssalhi** [comment]
**This is The Problem!**

I used the same solution but I can't get to the same result as the image

![Capture d'écran 2023-07-09 154654](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/9bfe510c-d68c-4806-8c94-8803d3db7553)

code : 

```
from PIL import Image
from customtkinter import CTk, CTkFrame, CTkEntry, CTkButton, CTkImage

class PasswordEntry(CTkFrame):
    def __init__(self, master, **kwargs):
        super().__init__(master, fg_color="transparent")
        self.password_hide = True
        
        self.entry = CTkEntry(self, corner_radius=1, fg_color="#FFFFFF",
                              border_width=1, border_color="#000000", show="•")
        self.entry.pack(side="left")

        icon_path = Image.open("eye.png")
        icon = CTkImage(icon_path, icon_path)
        
        self.button = CTkButton(self, width=25, border_width=1, corner_radius=1, hover_color="#FFFF00",
                                border_color="#000000", fg_color="#FFFFFF", image=icon,
                                text='', command=self.button_callback)
        self.button.pack(side="left")

    def button_callback(self):
        if self.password_hide:
            self.password_hide = False
            self.entry.configure(show="")
        else:
            self.password_hide = True
            self.entry.configure(show="•")

if __name__ == "__main__":
    app = CTk(fg_color="#FFFFFF")
    app.geometry("400x250")
    password_entry = PasswordEntry(app)
    password_entry.pack(pady=50)
    app.mainloop()
```

I think my enhancement request #1794 if added, and the user can add borders in certain only in left or right or top or bottom and add same feature in button, than we can reach the goal (The First Image)
or just make a new widget that why i open this issue

**Thanks**

**Comment by YoussefEssalhi** [comment]
**This is The Problem!**

I used the same solution but I can't get to the same result as the image

![Capture d'écran 2023-07-09 154654](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/9bfe510c-d68c-4806-8c94-8803d3db7553)

code : 

```
from PIL import Image
from customtkinter import CTk, CTkFrame, CTkEntry, CTkButton, CTkImage

class PasswordEntry(CTkFrame):
    def __init__(self, master, **kwargs):
        super().__init__(master, fg_color="transparent")
        self.password_hide = True
        
        self.entry = CTkEntry(self, corner_radius=1, fg_color="#FFFFFF",
                              border_width=1, border_color="#000000", show="•")
        self.entry.pack(side="left")

        icon_path = Image.open("eye.png")
        icon = CTkImage(icon_path, icon_path)
        
        self.button = CTkButton(self, width=25, border_width=1, corner_radius=1, hover_color="#FFFF00",
                                border_color="#000000", fg_color="#FFFFFF", image=icon,
                                text='', command=self.button_callback)
        self.button.pack(side="left")

    def button_callback(self):
        if self.password_hide:
            self.password_hide = False
            self.entry.configure(show="")
        else:
            self.password_hide = True
            self.entry.configure(show="•")

if __name__ == "__main__":
    app = CTk(fg_color="#FFFFFF")
    app.geometry("400x250")
    password_entry = PasswordEntry(app)
    password_entry.pack(pady=50)
    app.mainloop()
```

I think my enhancement request #1794 if added, and the user can add borders in certain only in left or right or top or bottom 
or add border just in left ,right and bottom and add same feature in button, than we can reach the goal (The First Image)
or just make a new widget that why i open this issue

**Thanks**

**Comment by dishb** [comment]
@YoussefEssalhi - Maybe open a new issue for this? This issue should be closed as using `show="*"` works. Even if you want circles, Tom has provided a [solution](https://github.com/TomSchimansky/CustomTkinter/issues/1793#issuecomment-1627652021). Furthermore, it looks like you can't replicate what Tom made due to differences in the code (and possibly OS). #1794 doesn't appear to be related to his issue.
