### ISSUE TITLE
Widget feature request: step size in slider widget

### ISSUE THREAD

**Issue by IshanJ25** [TomSchimansky/CustomTkinter#18]
As the title suggests

**Comment by TomSchimansky** [comment]
I added number_of_steps argument for the CTkSlider, which is None by default (no step size).

**Comment by IshanJ25** [comment]
in `customtkinter_slider.py` `line 55`:
could you change it from `highlightthicknes=0`, to `highlightthickness=0,`

**Comment by TomSchimansky** [comment]
even though its working like this, yes I can correct this

**Comment by IshanJ25** [comment]
okay
