### ISSUE TITLE
Question: Configuring `corner_radius`

### ISSUE THREAD

**Issue by pourhakimi** [TomSchimansky/CustomTkinter#180]
Hey Tom - would it be possible to configure the `corner_radius` argument to be different for each corner of a widget? So something like having one side of a widget curved, while the opposite remains at a 90 degree angle? Thanks.

**Comment by TomSchimansky** [comment]
Hi, this was already discussed here, it would be too much work: https://github.com/TomSchimansky/CustomTkinter/issues/96
