### ISSUE TITLE
CTkButton Enhancement Request : Icon Position

### ISSUE THREAD

**Issue by YoussefEssalhi** [TomSchimansky/CustomTkinter#1800]
**It would be nice to add an option, which allows you to place the icon to the left or the right side of the Button.**

![ex](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/eb05c203-b21c-4fce-96e1-608d738a2c11)

Maybe now you see there no big difference ? `Yeah`, I agree with you, but wait! let's change the button text length and than will be see a problem !

![ctkbutton_update](https://github.com/TomSchimansky/CustomTkinter/assets/76540840/4c85b2f6-a9ed-49a3-b824-3b14ed3dbe64)

** in Enhancement The text is still centered and the icons look so good**

**Comment by Akascape** [comment]
I guess we can do this with anchor parameter.

**Comment by YoussefEssalhi** [comment]
Oh my God, @Akascape  u are right,
I'm new with CustomTkinter but i do not know how i'm forget this part.
**Thanks Dude**

**Comment by YoussefEssalhi** [comment]
Btw I Edit the Images, with Adobe Ps to clarify

**Comment by Akascape** [comment]
> Btw I Edit the Images, with Adobe Ps to clarify

I know
