### ISSUE TITLE
Slow configure call

### ISSUE THREAD

**Issue by ceteke** [TomSchimansky/CustomTkinter#1802]
Hello,

First of all thank you for the nice library but I have an issue.  I noticed that updating labels via the `configure` method slows down the GUI drastically. Here is an example code snipped to reproduce the issue.

```python
class TestGUI(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.label = customtkinter.CTkLabel(master=self, text="text")
        self.label.grid(row=1, column=1, padx=0, pady=(5, 0), sticky="nsew")

        self.tick = time.time()

    def test_label(self):
        print("FPS", int(1/(time.time()-self.tick)))
        self.tick = time.time()

        self.label.configure(text='updated text')
        self.after(33, self.test_label)

if __name__ == "__main__":
    gui = TestGUI()
    gui.test_label()
    gui.mainloop()
```

Here is the output

```
FPS 15
FPS 15
FPS 8
FPS 12
FPS 9
FPS 9
FPS 12
FPS 9
FPS 11
FPS 10
FPS 9
```

Thank you

**Comment by MaxNiark** [comment]
what is the module about "time" var ?

**Comment by ceteke** [comment]
It’s a built-in Python library. Simply add `import time`

**Comment by TomSchimansky** [comment]
You got a strange way to measure the performance of a function. If you want to know how long the configure method takes simply time it like this:
```python
        t1 = time.perf_counter()
        self.label.configure(text='updated text')
        t2 = time.perf_counter()
        print(t2 - t1)
```
For me the results on macOS are:
```
0.00030475299999999095
0.0003079820000007061
0.00031581200000019294
0.0002652029999996586
```
Seems quite fast, but I also get this for you're program:
```
FPS 29
FPS 28
FPS 29
FPS 29
FPS 29
FPS 29
FPS 28
FPS 29
FPS 29
FPS 29
```
I think Tkinter is just very slow on Windows, nothing I can do anything about.

**Comment by ceteke** [comment]
Thank you for the answer. I am using Ubuntu 20.04. The reason why I measured it in that way is being able to update a label with frames obtained through the webcam.

Nevertheless of the way I measure the time, isn’t it still problematic to get such a performance issue?
