### ISSUE TITLE
Uncheck Buttons

### ISSUE THREAD

**Issue by Yoko11111111** [TomSchimansky/CustomTkinter#1806]
Hello,

i currently work on an checkbox that when you check the box the switches gets disabled but is there an method to uncheck it too?

Code:

        self.home_frame = customtkinter.CTkFrame(self, corner_radius=0, fg_color="transparent")
        self.home_frame.grid_columnconfigure(0, weight=1)

        self.home_frame_large_image_label = customtkinter.CTkLabel(self.home_frame, text="", image=self.third_frame_image)
        self.home_frame_large_image_label.grid(row=0, column=0, padx=20, pady=10)

        self.home_frame_button_1 = customtkinter.CTkCheckBox(self.home_frame, text="Enable (?)", command=self.update_button_state2, fg_color="#34abeb")

        self.home_frame_button_1.grid(row=1, column=0, padx=20, pady=10)
        self.home_frame_button_2 = customtkinter.CTkSwitch(self.home_frame, text="", progress_color="#34abeb")
        self.home_frame_button_2.grid(row=2, column=0, padx=20, pady=10)
        self.home_frame_button_3 = customtkinter.CTkSwitch(self.home_frame, text="", progress_color="#34abeb")
        self.home_frame_button_3.grid(row=3, column=0, padx=20, pady=10)
        self.home_frame_button_4 = customtkinter.CTkSwitch(self.home_frame, text="", progress_color="#34abeb")
        self.home_frame_button_4.grid(row=4, column=0, padx=20, pady=10)

    def update_button_state2(self):
        if self.home_frame_button_1.get():
            self.home_frame_button_2.configure(state="normal")
            self.home_frame_button_3.configure(state="normal")
            self.home_frame_button_4.configure(state="normal")
        else:
            self.home_frame_button_2.configure(state="disabled")
            self.home_frame_button_3.configure(state="disabled")
            self.home_frame_button_4.configure(state="disabled")

**Comment by YoussefEssalhi** [comment]
I think you should open this up in discussions, not issues

**Comment by YoussefEssalhi** [comment]
@Yoko11111111 I think you should open this up in discussions, not issues

**Comment by Yoko11111111** [comment]
yea you are right
