### ISSUE TITLE
Wrong type annotations

### ISSUE THREAD

**Issue by CallMePixelMan** [TomSchimansky/CustomTkinter#1810]
Hello,
a lot of widget having a `command` parameter have the same issue, the parameter is typed `Callable[[], None] | None` while the return value of the command is never used inside the widget, thus, forcing the developer to void the return value of his function, or ignoring the type warring by itself.

In my case, I use `command=webbrowser.open_new_tab(...)` with a button, but as the parameter is expecting None as the return value and as `webbrowser.open_new_tab` is returning a `bool`, it creates a warning with tools such as mypy ou pyright.

Like so, nearly all the widget use `any` (the built-in function) as their `master`'s parameter type. This is an invalid type annotation.

In both case, the type annotation should be replaced with [`typing.Any`](https://docs.python.org/3/library/typing.html#typing.Any), or the seconds one maybe needs `tkinter.Misc` (?).

Thanks

**Comment by dishb** [comment]
For the master, would it be plausible to set it as `customtkinter.CTk | customtkinter.CTkToplevel`? As these are the only possible `customtkinter` windows...

**Comment by CallMePixelMan** [comment]
That could be `tkinter.TopLevel | tkinter.Tk` too

**Comment by TomSchimansky** [comment]
Should be fixed with 5.2.2
