### ISSUE TITLE
CTkScrollableFrame - MouseWheel not working

### ISSUE THREAD

**Issue by Tenebrys** [TomSchimansky/CustomTkinter#1816]
Hello,

I got a problem with the scrolling bind to the MouseWheel in my app. I have a ScrollableFrame witch takes fill completely my app with the same code used in the example here : https://customtkinter.tomschimansky.com/documentation/widgets/scrollableframe.

But the scrolling only works when my mouse is on the ScrollBar, because i got no explicit error for this I opened the source code for the Scrolable Frame and I found that there is this funtion : 

`def check_if_master_is_canvas(self, widget):
        if widget == self._parent_canvas:
            return True
        elif widget.master is not None:
            return self.check_if_master_is_canvas(widget.master)
        else:
            return False`

So I check on my code if it was working properly : 

`    self.bind_all('<MouseWheel>', self.CheckCanvas)

    def CheckCanvas(self, event):
        print(event.widget)
        print(event.widget.master)
        if event.widget.master is not None:
            print("OK")

        print(self.check_if_master_is_canvas(event.widget))`

And I got this result : 

.!ctkframe.!canvas.!mainwindow.!frameheader.!ctklabel.!label
.!ctkframe.!canvas.!mainwindow.!frameheader.!ctklabel
OK
False

So the master of my widget exists when I checked it from my app but it doesn't seem to exists when the Scrollable Frame checking it on it.

The result is that I got a Scrollable Frame whitch is not scrollable with the mousewheel. 

Does someone know a solution ?

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/1356

**Comment by Tenebrys** [comment]
@TomSchimansky 

I think I found a solution to this problem. When the ScrollableFrame is structured into a class the master of the custom ScrollableFrame is define with the initiation method : 

`self.MainWindow = MainWindow(master=self, TexteTitre=self.TexteTitre, TexteCourant=self.TexteCourant,
                                     width=300, height=300)`

like this the master of the ScrollableFrame is not `.!ctkframe.!canvas` but `.` 

If I test the master of each widget passing by

`

        def check_if_master_is_canvas(self, widget):

            print(widget)

            print(widget.master)

            if widget == self._parent_canvas:

               print("ok")

               return True

           elif widget.master is not None:

               return self.check_if_master_is_canvas(widget.master)

           else:

               return False

`

I got this : 

![image](https://github.com/TomSchimansky/CustomTkinter/assets/139339402/470157ab-172a-4e90-99ac-3155598eab42)

I don't why the function skip the widget from `!mainwindow` to the root but if I reset the master of my custom Scrollable frame in the init function like this : 

`self.master = self._parent_canvas`

I got this : 

![image](https://github.com/TomSchimansky/CustomTkinter/assets/139339402/409c8cb7-dedc-4f05-9cae-a17d1aea741e)

And with this my Frame is scrollable with the MouseWheel
