### ISSUE TITLE
Input Dialog

### ISSUE THREAD

**Issue by 1-Utkarsh-Pandey-1** [TomSchimansky/CustomTkinter#1817]
Can I add iconbitmap in input dialog in custom tkinter If possible then please give solution

**Comment by Akascape** [comment]
Have you tried this method?
```python
dialog = customtkinter.CTkInputDialog(text="Type in a number:", title="Test")
dialog.iconbitmap("icon.ico")
...
```

**Comment by dishb** [comment]
If you're on macOS, the `.iconbitmap` hardly ever works. It really only works on Windows.
