### ISSUE TITLE
Problem with combobox if values goes higher !!

### ISSUE THREAD

**Issue by Armanadabi** [TomSchimansky/CustomTkinter#183]
So by deafualt  in ttk.combobox you can scroll down or up if the values goes out of range. 
here is the image of this problem :
![image](https://user-images.githubusercontent.com/104437739/173204980-be0a0926-020a-49cc-a47b-2fe12f1d16cb.png)

and this the example in ttk.combobox :
![image](https://user-images.githubusercontent.com/104437739/173205029-b1a652ca-b8e6-4af5-a789-7b851dd584bc.png)
![image](https://user-images.githubusercontent.com/104437739/173205080-8b15c6ca-8f8f-439d-8f3a-44459884525e.png)

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/175
