### ISSUE TITLE
Can't center text inside Textbox 

### ISSUE THREAD

**Issue by kondamo1806** [TomSchimansky/CustomTkinter#1839]
This's from the docs but I have no clue how to center text inside the textbox   

    #!/usr/bin/env python3 
    
    import customtkinter
    
    class App(customtkinter.CTk):
        def __init__(self):
            super().__init__()
            self.grid_rowconfigure(0, weight=1)  # configure grid system
            self.grid_columnconfigure(0, weight=1)
    
            self.textbox = customtkinter.CTkTextbox(master=self, width=400, corner_radius=0)
            self.textbox.grid(row=0, column=0, sticky="nsew")
            self.textbox.insert("0.0", "Some example text!\n" * 20)
    
    
    app = App()
    app.mainloop()

PLEASE FIX

**Comment by dishb** [comment]
Not possible. You'll need to use spaces or change the width of the textbox manually until it looks centered.

What does the code example have to do with this issue?

Furthermore, I'd suggest asking questions in the Q&A section of the Discussions tab.

**Comment by Akascape** [comment]
@kondamo1806 @dishb It's possible, but you have to use the tag method, as the ctktextbox is basically a tkinter Text widget.

```python
import customtkinter

class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()
        self.grid_rowconfigure(0, weight=1)  # configure grid system
        self.grid_columnconfigure(0, weight=1)

        self.textbox = customtkinter.CTkTextbox(master=self, width=400, corner_radius=0)
        self.textbox.grid(row=0, column=0, sticky="nsew")
        
        self.textbox._textbox.tag_configure("text", justify='center') # first, justify text position using tag_configure

        self.textbox.insert("0.0", "Some example text!\n" * 20) # insert all the text 
    
        self.textbox._textbox.tag_add("text", "0.0", "end") # add this line in the end


app = App()
app.mainloop()
```

**Comment by kondamo1806** [comment]
@Akascape Thank you bro 
I followed you on youtube
