### ISSUE TITLE
State of Button 

### ISSUE THREAD

**Issue by smtalds** [TomSchimansky/CustomTkinter#1843]
when i click button, my function is running but button color is not configured. I want to change color of button when function is running. When function is complated , color will be normal state color. Like recording a voice.

**Comment by Akascape** [comment]
@smtalds when you call the function, the whole app freezes untill the call ends. During this, no configure method will work. To avoid this, we have to use threading in order to separate the function process from the main thread. 

Here is a basic example:
```python
import threading

def thread_func():
    self.button.configure(state='disabled')
    threading.Thread(target=clicked).start() # target will be your 'clicked' function.

def clicked(self, event=None):
     # your main function code here
     ...
     self.button.configure(state='normal')

self.button = customtkinter.CTkButton(self, command=thread_func)
```

**Comment by smtalds** [comment]
Is there required for global definition for button ? Thanks for example btw.
