### ISSUE TITLE
How to place  CTkCheckBox at center without text?

### ISSUE THREAD

**Issue by raja2505** [TomSchimansky/CustomTkinter#1860]
I have a problem with the checkboxes as it wont aligned in center. tried anchor, justify and sticky all are not working. any help will be appreciated. 

`box = CTkCheckBox(obj, variable=check_f2ok,text="",
                fg_color="#5A5")
            box.grid(row=i+1, column=1)
            box1 = CTkCheckBox(obj, variable=check_f2notok,text="",
                fg_color="#5A5")
            box1.grid(row=i+1, column=2)`

![image](https://github.com/TomSchimansky/CustomTkinter/assets/124249760/a1c9e21a-7109-4df3-ac3a-c4c287dd48a2)

I want the checkbox to be placed at the center of the column just like the inch and mm labels

**Comment by loafthecomputerphile** [comment]
Are you sure you tried sticky?
Have you tried `sticky="WE"`?

**Comment by loafthecomputerphile** [comment]
> > Are you sure you tried sticky? Have you tried `sticky="WE"`?
> 
> Yes. Tried all combos. "NSEW","WE","EW". nothing working. 
> 
> ![image](https://github.com/TomSchimansky/CustomTkinter/assets/124249760/1086ddfd-c85d-45b9-b9af-effbbcfbbd44)
> 

What about adding padding?

**Comment by raja2505** [comment]
> > > Are you sure you tried sticky? Have you tried `sticky="WE"`?
> > 
> > 
> > Yes. Tried all combos. "NSEW","WE","EW". nothing working.
> > ![image](https://user-images.githubusercontent.com/124249760/256827773-1086ddfd-c85d-45b9-b9af-effbbcfbbd44.png)
> 
> What about adding padding?

that increases the top label width.
`from customtkinter import CTk,CTkCheckBox,CTkLabel
from tkinter import BooleanVar

obj = CTk()
lst = [f'row{i}' for i in range(5)]
for j in range(2):
    label1 = CTkLabel(obj,width=10, text=f"column{j+1}",anchor="center", justify="center",text_color="#9ff",font=("Verdana",12,"bold"))
    label1.grid(row=0, column=j+1)
for i in range(len(lst)):
    label0 = CTkLabel(obj, text=f"{lst[i]}",width=70, anchor="center", justify="center",text_color="#9ff",font=("Verdana",12,"bold"))
    label0.grid(row=i+1, column=0)
    check_f2ok = BooleanVar()
    check_f2notok = BooleanVar()
    check_f2ok.set(True)
    check_f2notok.set(False)
    box = CTkCheckBox(obj, variable=check_f2ok,text="",
        fg_color="#5A5", onvalue=True,offvalue=False)
    box.grid(row=i+1, column=1)
    box1 = CTkCheckBox(obj, variable=check_f2notok,text="",
        fg_color="#5A5", onvalue=True,offvalue=False)
    box1.grid(row=i+1, column=2)
obj.mainloop()`

**Comment by loafthecomputerphile** [comment]
try placing the whole thing in its own frame and add the grid configs before using the grid method

**Comment by raja2505** [comment]
I didn't understand what you are saying

**Comment by raja2505** [comment]
> try placing the whole thing in its own frame and add the grid configs before using the grid method

Actually setting the width to lower like 25 willsolve this issue.

`from customtkinter import CTk,CTkCheckBox,CTkLabel
from tkinter import BooleanVar

def setcmd(lst,var):
    for i in range(0,len(lst),2):
        lst[i].configure(command=lambda i=i: (var[i].set(True),var[i+1].set(False)) )
        lst[i+1].configure(command=lambda i=i: (var[i].set(False),var[i+1].set(True)))



obj = CTk()
lst = []
var = []
for j in range(2):
    label1 = CTkLabel(obj,width=120, text=f"column{j+1}",anchor="center", justify="center",text_color="#9ff",font=("Verdana",12,"bold"))
    label1.grid(row=0, column=j+1)
for i in range(5):
    label0 = CTkLabel(obj, text=f"row {i}",width=70, anchor="center", justify="center",text_color="#9ff",font=("Verdana",12,"bold"))
    label0.grid(row=i+1, column=0)
    c1 = BooleanVar()
    c2 = BooleanVar()
    c1.set(True)
    c2.set(False)
    box = CTkCheckBox(obj, variable=c1,text="",width=25,
        fg_color="#5A5", onvalue=True,offvalue=False)
    box.grid(row=i+1, column=1)
    box1 = CTkCheckBox(obj, variable=c2,text="",width=25,
        fg_color="#5A5", onvalue=True,offvalue=False)
    box1.grid(row=i+1, column=2)
    lst.append(box)
    lst.append(box1)
    var.append(c1)
    var.append(c2)
setcmd(lst,var)
obj.mainloop()`
