### ISSUE TITLE
Bug for CTkFrame

### ISSUE THREAD

**Issue by yasntrk** [TomSchimansky/CustomTkinter#187]
First of all thank you for this amazing library! 

I experienced a kind of bug when i was working with this library. When i am creating a CTkFrame with this code:

`frame_left3 = customtkinter.CTkFrame(root,width=0,corner_radius=0)
frame_left3.place(x=350, y=450)`

then i plotted a pie chart after some kind of things.

![image](https://user-images.githubusercontent.com/51214879/173251779-b23da896-8a5e-4e36-af22-dbe78b2b50db.png)

then i am deleting this chart with this code:

`bar3.get_tk_widget().pack(side=tk.BOTTOM, fill=tk.BOTH, expand=0)`

and the result is:

![image](https://user-images.githubusercontent.com/51214879/173252049-5e328d41-0d81-4823-81b2-070242e690be.png)

and frame is not black, it becomes gray

**Comment by felipetesc** [comment]
It's a little bit hard to know what is happening without your code, but when I want to remove a frame from the which I used the method "pack" for laying out, I use pack_forget, for example. Is get_tk_widget only a getter, or it does something else ?

**Comment by felipetesc** [comment]
If you provide a sample we can try to figure it out what's happening. Thanks.

**Comment by TomSchimansky** [comment]
I think this is just a rendering lag of tkinter which happens very often. Try to call .update() on the frame after you delete the chart and then it should work fine.
