### ISSUE TITLE
AttributeError: 'str' object has no attribute 'trace_add'

### ISSUE THREAD

**Issue by Koulmoir** [TomSchimansky/CustomTkinter#1886]
after trying to make a login System, as soon as I put in the textvariable="my text variable" which was first created using tkinter.StringVar()
it just gives me this error I've tried repairing my IDE which is pycharm but even that doesn't work

**Comment by Koulmoir** [comment]
just figured it out you have to put in the variable not the variable name as a string lol

**Comment by medhanshrath-t** [comment]
I faced the same problem and used variable_name = customtkinter.StringVar(value="value") to fix it

**Comment by lam-lee** [comment]
I am facing the same problem.
