### ISSUE TITLE
Can't get the state of a CTkButton

### ISSUE THREAD

**Issue by Yapollon** [TomSchimansky/CustomTkinter#189]
First off thanks for the amazing library it's great!
Now to the problem, so I was trying to get the state of CTkButton by the usual way it's done with normal tkinter. But this caused an error saying that this option was unknown. I researched to fix this problem but couldn't find anything so here I am.

Example code:
``` python
from tkinter.constants import NORMAL, CENTER
import customtkinter

app = customtkinter.CTk()
app.geometry("400x240")


def button_function():
    if button['state'] == NORMAL:
        print("State is normal")


button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
button.place(relx=0.5, rely=0.5, anchor=CENTER)

app.mainloop()

```

The Error: **_tkinter.TclError: unknown option "-state"**

**Comment by TomSchimansky** [comment]
You can use `button.state` instead, the bracket method of getting the attributes is not implemented in CTk yet...

**Comment by Yapollon** [comment]
Woah thanks a lot for the fast reply, helped a lot ^^
