### ISSUE TITLE
TopLevel AttributeError  'CheckUpdateDialog' object has no attribute 'enable_macos_dark_title_bar'

### ISSUE THREAD

**Issue by bosd** [TomSchimansky/CustomTkinter#190]
In an  exsisting application, replaced the Toplevel call with CTKToplevel.

Running the ap on python3.10 on windows
Got an error:
```
  File "D:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\ctk_toplevel.py", line 21, in __init__
    self.enable_macos_dark_title_bar()
AttributeError: 'CheckUpdateDialog' object has no attribute 'enable_macos_dark_title_bar'
```

Steps to reproduce:
<details>

used as a subject: https://github.com/vlachoudis/bCNC/blob/master/bCNC/Updates.py

added import
```
import customtkinter
customtkinter.set_default_color_theme("dark-blue")  # Themes: "blue" (standard), "green", "dark-blue"
```

replaced:
`Toplevel.__init__(self, master)`

with:
`customtkinter.CTkToplevel.__init__(self, master)`

and added:
```
        label = customtkinter.CTkLabel(window, text="CTkToplevel window")
        label.pack(side="top", fill="both", expand=True, padx=40, pady=40)
```

</details>

**Comment by felipetesc** [comment]
Perhaps if we change the method enable_macos_dark_title_bar for this it will work:

```python
@staticmethod
    def enable_macos_dark_title_bar():
        if sys.platform == "darwin" :  # macOS
            if not Settings.deactivate_macos_window_header_manipulation:
                if Version(platform.python_version()) < Version("3.10"):
                    if Version(tkinter.Tcl().call("info", "patchlevel")) >= Version("8.6.9"):  # Tcl/Tk >= 8.6.9
                        os.system("defaults write -g NSRequiresAquaSystemAppearance -bool No")
```

**Comment by felipetesc** [comment]
> In an exsisting application, replaced the Toplevel call with CTKToplevel.
> 
> Running the ap on python3.10 on windows Got an error:
> 
> ```
>   File "D:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\ctk_toplevel.py", line 21, in __init__
>     self.enable_macos_dark_title_bar()
> AttributeError: 'CheckUpdateDialog' object has no attribute 'enable_macos_dark_title_bar'
> ```
> 
> Steps to reproduce:

Hello. Can you provide a sample code?

**Comment by bosd** [comment]
> Hello. Can you provide a sample code?

Example code in: https://github.com/bosd/bCNC/commit/f5e9e01520496e661cc55422738f3ab09ef01f99

**Comment by TomSchimansky** [comment]
Please provide a minimal code example where the error appears, otherwise I will close this. I don't want to deal with such a big project and a lot of unnecessary code I don't understand when searching for a bug in the customtkinter library.

**Comment by bosd** [comment]
That is very understandable :)
In my attempt to update the gui of the project I wanted to start simple and small. That's why I chose to do only a simple top level popup. Only one file (Updates.py) of the project is relevant for that.
However, it does not seem as simple as replacing the standard tk calls with custom tk.

The relevant code changes are:
![image](https://user-images.githubusercontent.com/11499387/175262522-7792d5b9-f35f-455b-8730-0b282f3c7cdb.png)

This is my first attempt using this lib in a real use case.
So might be that I'm doing something wron here.

**Comment by TomSchimansky** [comment]
I can not run this file:
```ModuleNotFoundError: No module named 'tkExtra'```

**Comment by bosd** [comment]
My bad, it's fixed now

**Comment by bosd** [comment]
Sorry my comment was not clear. I had fixed the tkExtra error.
 ( previously commited wrong files, now placed the proper ones in that branch)





The error related to this module still exsists.

**Comment by bosd** [comment]
Can you reopen? As it has not been resolved?

**Comment by TomSchimansky** [comment]
The import  error with tkExtra is still there for me, but again, I don't want to debug an error in such a big project. Can you create a small onefile example where the error appears?
