### ISSUE TITLE
Is there any Color Picking Dialogue?

### ISSUE THREAD

**Issue by DoduCode** [TomSchimansky/CustomTkinter#1908]
I was looking through the windows file and widgets file, but I couldn't find the color picking dialogue that tkinter has. 
Does CustomTkinter have a color picking dialogue?
If no is there a plan to make it?

**Comment by Akascape** [comment]
@DoduCode Yes we have a color picking dialogue (extension): https://github.com/Akascape/CTkColorPicker

![](https://user-images.githubusercontent.com/89206401/209182773-d76bf05c-610e-4297-aec5-7bb61a11d6d3.jpg)

**Comment by Akascape** [comment]
@DoduCode You can find more awesome widgets like this here: https://github.com/Akascape/tkinter-toolkit

**Comment by DoduCode** [comment]
@Akascape thanks alot for this
