### ISSUE TITLE
Cannot use customtkinter library

### ISSUE THREAD

**Issue by Jlsorr** [TomSchimansky/CustomTkinter#1915]
I did my research but couldn't find the solution.

`@MacBook-Pro ~ % pip3 install customtkinter --upgrade`
`Requirement already satisfied: customtkinter in /opt/homebrew/lib/python3.11/site-packages (5.2.0)`
`Requirement already satisfied: darkdetect in /opt/homebrew/lib/python3.11/site-packages (from customtkinter) (0.8.0)`

IN VS CODE OUTPOUT : 
`ModuleNotFoundError: No module named 'customtkinter'`

ty for ur help

**Comment by Akascape** [comment]
@Jlsorr 
Your VS code is using a different python version where it doesn't have customtkinter installed. Install the module in that specific version.

**Comment by Jlsorr** [comment]
> @Jlsorr Your VS code is using a different python version where it doesn't have customtkinter installed. Install the module in that specific version.

How do I install it on 3.9 because it automatically installs on 3.10 ?

**Comment by avalon60** [comment]
You should consider  viritual environments. Check out the `pip -m venv venv`  command.
This allows a project to work with its own libraries and executables. When you want to switch on the env for a specific project, you use a local `activate` command, which allows you to then be working on that specific project.

**Comment by Jlsorr** [comment]
indeed I succeeded with the venv thank you very much

**Comment by Akascape** [comment]
@Jlsorr close this issue

**Comment by Jlsorr** [comment]
sorry to bother you again, but my customtinker window works but I can't see the different elements

**Comment by Akascape** [comment]
@Jlsorr That's a big problem with tkinter and macosx, basically due to older python versions, solution is to create your venv with python 3.11+
Check here: https://github.com/TomSchimansky/CustomTkinter/issues/1690

**Comment by Jlsorr** [comment]
> @JlsorrC'est un gros problème avec tkinter et macosx, essentiellement en raison des anciennes versions de python, la solution consiste à créer votre venv avec python 3.11+ Vérifiez ici : #1690

fixed ty a lot

**Comment by trandinhnamuet** [comment]
in my case:
python --version    return 3.7.1
python3 --version    return 3.10.1
so i go to control panel -> programs and features -> uninstall python 3.7.1. Problem solved. If not yet, reinstall venv
