### ISSUE TITLE
Widgets suddenly becoming smaller and blurrier with no change in code

### ISSUE THREAD

**Issue by ltp7** [TomSchimansky/CustomTkinter#1920]
Hi,

With no changes in my code, the GUI I'm working on suddenly went from looking like what's presented in the repo's main page screenshots, to this : 

![Screenshot from 2023-08-19 10-43-40](https://github.com/TomSchimansky/CustomTkinter/assets/41062994/f1078c24-392a-4cdb-aa71-50bf7317e960)

with all widgets becoming smaller than they were, and the buttons in particular becoming pixelated (most visible on the button corners).

I'm working on PyCharm with virtualenv (Python version 3.8) on Ubuntu 20.04. What I've tried so far : 
- Downgrading customtkinter from version 5.2.0 to older ones inside the virtual environment, 
- Launching my GUI with the global Python interpreter outside the virtual environment after installing customtkinter in the global packages

Thanks a lot for your help and congrats for the great project !

**Comment by TomSchimansky** [comment]
Try it without a virtualenv. On Linux the program needs access to the system font folder for rendering the ground corners and that's a problem on some Linux versions.
