### ISSUE TITLE
CTk ScrollingFrame Draws Incorrectly

### ISSUE THREAD

**Issue by Turnrp** [TomSchimansky/CustomTkinter#1927]
I'm using a scrolling frame and I am removing and adding stuff to it but if a scroll far down then add something small that wouldn't fit that length it bugs out completely then I gotta redo the function

**Comment by Turnrp** [comment]
https://github.com/TomSchimansky/CustomTkinter/assets/70816015/2a411b92-d2b5-42ea-856d-8834e7098c80

**Comment by Turnrp** [comment]
Hope that helps you understand!

**Comment by Akascape** [comment]
Try adding this in your function after removing the widgets:
```python self.scrollable_frame._parent_canvas.yview_moveto(0.0)
```

Or you can also try [CTkXYFrame](https://github.com/Akascape/CTkXYFrame), an alternative of ctk scrollable frame.

**Comment by Akascape** [comment]
Try adding this in your function after removing the widgets:

```python
 self.scrollable_frame._parent_canvas.yview_moveto(0.0)
```
Or you can also try [CTkXYFrame](https://github.com/Akascape/CTkXYFrame), an alternative of ctk scrollable frame.

**Comment by Akascape** [comment]
@Turnrp 
Try adding this in your function after removing the widgets:

```python
 self.scrollable_frame._parent_canvas.yview_moveto(0.0)
```
Or you can also try [CTkXYFrame](https://github.com/Akascape/CTkXYFrame), an alternative of ctk scrollable frame.
