### ISSUE TITLE
How to destory a CTkLabel ?

### ISSUE THREAD

**Issue by mahmouddello** [TomSchimansky/CustomTkinter#1929]
So i have a project where i display an image via CTklabel, the user upload the image manually and everything is fine but when the user try to re-upload, the old image still stick and the new image out of no reason goes out from the frame. In Tkinter the method `destroy()`
handles the operation but in custom tkinter i didn't see something similar.

**Comment by joocam** [comment]
If I understand correctly, you want to update the image, right? Use the update() method

**Comment by mahmouddello** [comment]
This is what I was looking for! Thank you very much
