### ISSUE TITLE
Automatic scaling not working

### ISSUE THREAD

**Issue by Paulomt93** [TomSchimansky/CustomTkinter#1940]
Hi,

From what i understood of the documentation, customtkinter should detect the scaling of the os and adjust accordingly. But if i change the scale, part of the Gui is cut. I'm working on windows 11

Did i get it wrong or it should adjust the scale?
If it should, did someone had the same problem and was able to fix it?

Thanks

**Comment by TomSchimansky** [comment]
You have to send a small example code with a screenshot, otherwise I cannot know what's going on.
