### ISSUE TITLE
CTkButton configure doesn't have relief on sunken and raised

### ISSUE THREAD

**Issue by Junxian0405** [TomSchimansky/CustomTkinter#1957]
below are the sample doesn't work on customtkinter but work on tkinter
`import customtkinter as ctk

def toggle_button(button):
    if button['relief'] == 'raised':
        button.config(relief='sunken', bg='light blue')
    else:
        button.config(relief='raised', bg='SystemButtonFace')

def create_toggle_button(text):
    button = ctk.CTkButton(root, text=text, relief='raised')
    button['command'] = lambda: toggle_button(button)
    button.pack()
    return button 

root = ctk.CTk()
button = create_toggle_button("Toggle Me")
root.mainloop()
`

**Comment by TomSchimansky** [comment]
It doesn't work because there aren't such options for the CTkButton, I don't know the look you want to achieve, but if you want to have a sunken relief you can just use a tkinter button.
