### ISSUE TITLE
Documentation isn't detailed!

### ISSUE THREAD

**Issue by MediaEU** [TomSchimansky/CustomTkinter#1959]
Tom don't you think when you create something about GUI that it has to do with something that is **visual**. I came to customtkinter from a Stackoverflow question, so I wanna take a closer look. By visiting your site and the docs section I could not see under the widgets how your widgets look like, instead you added this minimalistic documentation that is probably autogenerated based on your code. My advise: Add at least pictures from 3 main OS's out there(Linux, Microsoft, Mac...) for each widget.
Greetz

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/1614
