### ISSUE TITLE
orient='vertical' doesn't work for the ctk tabview widget. Any Solutions?

### ISSUE THREAD

**Issue by UnknownEngineOfficial** [TomSchimansky/CustomTkinter#1975]
orient='vertical' doesn't work for the ctk tabview widget. Any Solutions?

**Comment by DragonOfShuu** [comment]
Can you describe your issue with more resources, such as posting your code in its most basic form?

**Comment by TomSchimansky** [comment]
Tabview has no argument `orient`.
