### ISSUE TITLE
QUESTION: reset CtkScrollableFrame

### ISSUE THREAD

**Issue by A-Lamia** [TomSchimansky/CustomTkinter#1982]
Is it possible to reset CtkScrollableFrame view to a top position, i have a setup where information is being injected in to a frame and if a button is selected that injects a new set of data and the scroll or view position is outside the new contents view nothing loads so you need to manually scroll back up to update the frame.

thanks!

**Comment by Resvith** [comment]
Try this:
`your_frame._scrollbar._command("moveto", 0.0)`

If you need to scroll to the bottom:
`your_frame._scrollbar._command("moveto", 1.0)`

**Comment by A-Lamia** [comment]
@Resvith works perfectly, thank you!

**Comment by EduardoWS** [comment]
thank you! i was with the same problem
