### ISSUE TITLE
Import "customtkinter" could not be resolved

### ISSUE THREAD

**Issue by kubixi** [TomSchimansky/CustomTkinter#2003]
Please help with this problem. Checked all the folders. Installed with the command "pip3 install customtkinter" via the console.
![image](https://github.com/TomSchimansky/CustomTkinter/assets/84450566/9a32aa11-a914-46d4-b9b6-4bbbe7629369)

**Comment by Akascape** [comment]
https://github.com/TomSchimansky/CustomTkinter/discussions/636

**Comment by DarkPhinx** [comment]
you need to do pip install customtkinter
