### ISSUE TITLE
ModuleNotFoundError: No module named 'customtkinter'

### ISSUE THREAD

**Issue by Tyrsus666** [TomSchimansky/CustomTkinter#2009]
Hello i have tried to reinstall CTk several times but i always get this error. 
![e2](https://github.com/TomSchimansky/CustomTkinter/assets/15941695/844178ca-94b2-4c35-bcb8-9101c165ed78)

**Comment by Akascape** [comment]
@Tyrsus666 
You installed the package in a different python version. Properly install it in the version which you are using to run the program. 

Check this: https://stackoverflow.com/questions/2812520/dealing-with-multiple-python-versions-and-pip

**Comment by DarkPhinx** [comment]
@Akascape  the StackOverflow do not help me

**Comment by Tyrsus666** [comment]
@Akascape thank you, that worked for me.
@DarkPhinx  I have specified my pip command. 
instead of using pip install I used pip3.11 install

**Comment by TechPro424** [comment]
Fixed in VSC by using a virtual environment or venv by following this site https://code.visualstudio.com/docs/python/environments
and selecting python 3.11.5 as interpreter
