### ISSUE TITLE
How can i custom width of option menu with fixed width?

### ISSUE THREAD

**Issue by TIMMYPPV** [TomSchimansky/CustomTkinter#202]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/46839572/175260048-4ce88ebb-6ca5-4c3a-9ad9-5f0605d0cb3e.png">
i mean fix width size of option menu

**Comment by TomSchimansky** [comment]
I added an option: `dynamic_resizing`. Now you can disable automatic resizing of text is too big. (with version 4.5.0)
