### ISSUE TITLE
The font does not change in CustomTkinter

### ISSUE THREAD

**Issue by YoussefEssalhi** [TomSchimansky/CustomTkinter#2039]
I set the font and it doesn't change in **CTK** Version **5.2.1**

```python
# Import Widgets from CustomtKinter
from customtkinter import CTk, CTkFont, CTkButton, CTkLabel

# Setup App
app = CTk()
app.geometry("400x200")

# Set Font
my_font = CTkFont(family="DaddyCute.otf", size=18)

# Layout
CTkLabel(app, font=my_font).pack()
CTkButton(app, font=my_font).pack(pady=15)
CTkButton(app, font=my_font).pack()

# Run
app.mainloop()

```

**Comment by YoussefEssalhi** [comment]
Hey guys, is there a way to change the font without having to install it?

I want to put the fonts in their own folder.

**Comment by YoussefEssalhi** [comment]
is there a way to change the font without having to install it?

I want to put the fonts in their own folder.

**Comment by Akascape** [comment]
@YoussefEssalhi 
Yes bro, you just have to search your questions in old discussions and the issues tab.

https://github.com/TomSchimansky/CustomTkinter/discussions/936#discussioncomment-4491310
