### ISSUE TITLE
CTkEntry arguments width and height

### ISSUE THREAD

**Issue by Celesium** [TomSchimansky/CustomTkinter#2041]
Hi, I am trying to create a simple entrybox using this line of code
`self.entry_1 = customtkinter.CTkEntry(self, width=10, height=10, placeholder_text="Sets")
 self.entry_1.grid(row=0, column=1, columnspan=1, rowspan=1, padx=10, pady=10, sticky="nsew")`
but it resulted in a big entry box (the width and height arguments is kinda ignored now for some reason)
<img width="820" alt="image" src="https://github.com/TomSchimansky/CustomTkinter/assets/148928959/a1c7ad21-c4c5-4d1d-b8f8-2f185f7c4339">
`import tkinter
import tkinter.messagebox
import customtkinter

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("dark-blue")

class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        # configure window
        self.title("Rekognisi Olahraga Real-Time")
        self.geometry(f"{1100}x{580}")

        # configure grid layout (4x4)
        self.grid_columnconfigure(1, weight=1)
        self.grid_columnconfigure((2, 3), weight=0)
        self.grid_rowconfigure((0, 1, 2), weight=1)
        # Main entry for input repetitions and set.
        self.entry_1 = customtkinter.CTkEntry(self, width=10, height=10, placeholder_text="Sets")
        self.entry_1.grid(row=0, column=1, columnspan=1, rowspan=1,
                        padx=10, pady=10, sticky="nsew")
        self.entry_2 = customtkinter.CTkEntry(self, width=10, height=10, placeholder_text="Repetition")
        self.entry_2.grid(row=1, column=1, columnspan=1, rowspan=1,
                        padx=10, pady=10, sticky="nsew")
if __name__ == "__main__":
    app = App()
    app.mainloop()`
if anyone knows the issue, please help me thanks :)

**Comment by Akascape** [comment]
@Celesium Its because you used `sticky="nsew"` in your grid method.

**Comment by Celesium** [comment]
ohhh thanks it actually works after that, tyty

**Comment by Akascape** [comment]
@Celesium Close the issue then.
