### ISSUE TITLE
InputDialog add show option

### ISSUE THREAD

**Issue by GermanYoshi** [TomSchimansky/CustomTkinter#2054]
for exampel if you want to ask for a Password in the InputDialog it would be great if i could use show='*' instead of plain text

**Comment by Akascape** [comment]
@GermanYoshi Try adding this line after opening the input dialog:

```python
input_dialog._entry.configure(show="*")
```

**Comment by GermanYoshi** [comment]
@Akascape 
![image](https://github.com/TomSchimansky/CustomTkinter/assets/39739909/64b35f0d-4c36-428a-8305-f07aa26deef3)
![image](https://github.com/TomSchimansky/CustomTkinter/assets/39739909/fbc81385-3b79-4098-b556-349bd7e562d9)
sadly not working :(

**Comment by Akascape** [comment]
@GermanYoshi You used `dialog.configure(show='*')` which is wrong. 

Try this:
```python
dialog.after(50, lambda: dialog._entry.configure(show="*"))
```
This will work for sure!

**Comment by GermanYoshi** [comment]
@Akascape thanks that worked :)

btw is there a way to check if ok or cancel is pressed?

**Comment by Akascape** [comment]
@GermanYoshi  
> btw is there a way to check if ok or cancel is pressed?
```python
value = dialog.get_input()
if value is None:
    return # don't proceed if cancel/close is clicked
...
```

**Comment by GermanYoshi** [comment]
@Akascape 
yeah but if you type something in the dialog and then press Cancel the Value is not None :(

**Comment by Akascape** [comment]
@GermanYoshi Update tot the latest version, that issue was fixed.

**Comment by Akascape** [comment]
Close the issue if everything is okay @GermanYoshi

**Comment by GermanYoshi** [comment]
ok ty
