### ISSUE TITLE
Render in Ubuntu

### ISSUE THREAD

**Issue by vincentcasseau** [TomSchimansky/CustomTkinter#206]
Hello,

I just installed CustomTkinter on Ubuntu 18.04 LTS using pip
```sh
pip3 install customtkinter
```
and ran an example. Something is off with the render (see image below). I searched for 'Linux' and 'Ubuntu' in Issues and Discussions but could not find a similar problem reported. Is Ubuntu supported? Am I missing something obvious?

![CustomTkinter](https://user-images.githubusercontent.com/10944529/175536606-90777606-1cae-4591-a3ce-98d6afc0f3b1.png)

Thanks for your help.

Regards,
Vincent

**Comment by TomSchimansky** [comment]
Hi, for rendering custom fonts are needed and need to be loaded from .otf files. That's  platform specific, and on Ubuntu i just copy them into `~/.fonts/` and then they are available in tkinter. Do you have this folder (`~/.fonts/`) is there a font called `CustomTkinter_shapes_font.otf`?

**Comment by vincentcasseau** [comment]
Hi, thank you for your quick reply!
Yes, I can see that the directory `~/.fonts/` got created today and contains `CustomTkinter_shapes_font.otf`, `Roboto-Medium.ttf`, and `Roboto-Regular.ttf`.

**Comment by TomSchimansky** [comment]
Can you test to copy the fonts into `~/.local/share/fonts` and check if its working?

**Comment by vincentcasseau** [comment]
I created the `fonts/` directory (missing) in `~/.local/share/` and copied the 3 files.
It didn't make any difference unfortunately.
I could live with a sub-par font for the moment. I am most concerned by all elements having rounded corners.
Please let me know if you want the output of `pip list`.

**Comment by vincentcasseau** [comment]
I searched a bit online and realised that using Conda isn't the best thing.
I will reinstall the modules using the system python3.6 and keep you updated.
Thanks.

**Comment by felipetesc** [comment]
Use python 3.10

> I searched a bit online and realised that using Conda isn't the best thing. I will reinstall the modules using the system python3.8 and keep you updated. Thanks.
> 
> **EDIT: this was the problem, Anaconda should not be used.** ([ContinuumIO/anaconda-issues#6833](https://github.com/ContinuumIO/anaconda-issues/issues/6833)) Thanks for your time, I am closing this issue.

Try to install Python 3.10 and not 3.8

**Comment by vincentcasseau** [comment]
3.8 works well, you need at least 3.7 because of
```python
from __future__ import annotations
```
But if you think 3.10 is better in the long run, I'll switch.

**Comment by felipetesc** [comment]
> 3.8 works well, you need at least 3.7 because of
> 
> ```python
> from __future__ import annotations
> ```
> 
> But if you think 3.10 is better in the long run, I'll switch.

The reason to use 3.10.* is based on this: https://github.com/TomSchimansky/CustomTkinter/issues/101
And here comes to explanation https://docs.python.org/3/whatsnew/3.10.html

[PEP 604](https://www.python.org/dev/peps/pep-0604), Allow writing union types as X | Y
