### ISSUE TITLE
hover effect to text color in button

### ISSUE THREAD

**Issue by PrazolMalla** [TomSchimansky/CustomTkinter#2068]
Is there a way you can add hover effect to the text of the button

**Comment by MaxNiark** [comment]
Hi, 

U could add a if condition on event focus widget. that's call can call .config with new color, or a ttk.style()

**Comment by PrazolMalla** [comment]
Can please elaborate I am kinda new to programming 
thank to for commenting 
@MaxNiark

**Comment by PrazolMalla** [comment]
Thank You I have solved it
