### ISSUE TITLE
How to assimilate one element into back ground image?

### ISSUE THREAD

**Issue by ElinLiu0** [TomSchimansky/CustomTkinter#2076]
From this [sample](https://github.com/TomSchimansky/CustomTkinter/blob/master/examples/example_background_image.py)
I checked that the background color isn't transparent,like below:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/75596885/2046053e-9597-4753-8f43-68796c0b0180)
So is that possible to make it transparent?
Thank you so much sir!

**Comment by Fett-Mops** [comment]
waht exactly do you want transparent?

**Comment by ElinLiu0** [comment]
> waht exactly do you want transparent?

The Middle Login Page Background,is that possible?

**Comment by Fett-Mops** [comment]
try this:
self.login_frame = customtkinter.CTkFrame(self, corner_radius=0,  fg_color='transparent')

**Comment by ElinLiu0** [comment]
> try this:
> self.login_frame = customtkinter.CTkFrame(self, corner_radius=0,  fg_color='transparent')
> 
> 

Checked,i would bring you response.

**Comment by Ricardoarsv** [comment]
![image](https://github.com/TomSchimansky/CustomTkinter/assets/124947570/80cb4bd9-1a81-4307-9437-806a1d8fe7bf)

I couldn't make transparent labels to assimilate them with the background image...

**Comment by Fett-Mops** [comment]
sorry i had a misconception on how fg_color='transparent' works i looked in the code and i think it doesn't make the foreground transparent, the foreground and will just be the same color as the parent fg_color. the only solution i could find is here
[https://stackoverflow.com/questions/46498499/tkinter-making-background-image-as-semi-transparent-under-all-widgets](#https://stackoverflow.com/questions/46498499/tkinter-making-background-image-as-semi-transparent-under-all-widgets).

**Comment by Akascape** [comment]
@ElinLiu0 @Ricardoarsv @Fett-Mops @o0morgan0o It is now possible: https://github.com/TomSchimansky/CustomTkinter/discussions/2214

**Comment by ElinLiu0** [comment]
> @ElinLiu0 @Ricardoarsv @Fett-Mops @o0morgan0o It is now possible: https://github.com/TomSchimansky/CustomTkinter/discussions/2214

Great,got you post,i will have a check,issue currently closed by new update.
