### ISSUE TITLE
Custom graph implementation

### ISSUE THREAD

**Issue by dolphin007x** [TomSchimansky/CustomTkinter#2081]
Is there any graph implementation within this library itself? I'm talking something which integrates with the UI nicely as compared to something like matplotlib which disrupts the overall application's UI design.

**Comment by Akascape** [comment]
@dolphin007x Yes, we have some separate graph widgets which you can use within your project easily and itis made with customtkinter/tkinter only.

1) TkChart: https://github.com/Thisal-D/tkchart

https://user-images.githubusercontent.com/93121062/204729605-44027b37-c9f5-4588-a316-1205e5917ae2.gif

This one looks very modern and detailed, we can also add animations

2) CTkDataVisualizingWidgets: https://github.com/ZikPin/CTkDataVisualizingWidgets

There are special widgets designed for visualizing data. These widgets looks simple and clean.

![image](https://github.com/ZikPin/Custom-widgets-for-CTk/assets/65452275/17b46820-d881-4f27-8ea9-7dd572d9d704)

![image](https://github.com/ZikPin/Custom-widgets-for-CTk/assets/65452275/e40ea973-77d0-42c4-b740-535c15ad5748)

Hope this will help :)

**Comment by Akascape** [comment]
@dolphin007x Yes, we have some separate graph widgets which you can use within your project easily and itis made with customtkinter/tkinter only.

1) TkChart: https://github.com/Thisal-D/tkchart

https://user-images.githubusercontent.com/93121062/204729605-44027b37-c9f5-4588-a316-1205e5917ae2.gif

This one looks very modern and detailed, we can also add animations

2) CTkDataVisualizingWidgets: https://github.com/ZikPin/CTkDataVisualizingWidgets

There are special widgets designed for visualizing data. These widgets looks simple and clean.

**CTkGraph**
![image](https://github.com/ZikPin/Custom-widgets-for-CTk/assets/65452275/17b46820-d881-4f27-8ea9-7dd572d9d704)

**CTkChart**
![image](https://github.com/ZikPin/Custom-widgets-for-CTk/assets/65452275/e40ea973-77d0-42c4-b740-535c15ad5748)

Hope this will help :)

**Comment by Akascape** [comment]
To explore more customtkinter based libraries, try this: https://github.com/Thisal-D/tkchart

**Comment by dolphin007x** [comment]
Appreciate the help!
