### ISSUE TITLE
Customtkinter issues

### ISSUE THREAD

**Issue by Potatooff** [TomSchimansky/CustomTkinter#2083]
Customtkinter new version has "package issue" i dont know, it just doesnt work so i decided to go on a older version but with python 3.12 version it removes disutils module which is deprecated and make customtkinter not working too soo 
customtkinter only support python3.11.6> 

Hope you could solve this!

**Comment by Akascape** [comment]
@Potatooff 
Install the packaging module. This module was removed from default after the new python update, that is why it is showing that import error.

```
pip install packaging
```

**Comment by TomSchimansky** [comment]
Should be fixed with 5.2.2, as packaging is now added to requirements
