### ISSUE TITLE
ScrollableFrame with both vertical and horizontal scrollbars required.

### ISSUE THREAD

**Issue by KarthikBammidi3369** [TomSchimansky/CustomTkinter#2084]
Hi, 
I need information on how to create both scrolls to a frame i.e., vertical and horizontal. I didn't find it in customtkinter documentation. 
If this feature is implemented let me know how to create it or else let me know by which release this feature will be available. 

Thanks in Advance.

**Comment by FreiLacke-Frederik** [comment]
This feature isn't available yet, but I made my own ScrollableFrame Widget. You may have to play around with it for a bit to make it suit your program.

Scrollable Frame:

class ScrollableFrame(ctk.CTkFrame):
    def __init__(self, parent):
        super().__init__(master=parent, fg_color="transparent") 

        vscrollbar = ctk.CTkScrollbar(master=self, orientation="vertical", fg_color="transparent", bg_color="transparent")
        vscrollbar.pack(fill="y", side="right", expand=False)

        hscrollbar = ctk.CTkScrollbar(master=self, orientation="horizontal", fg_color="transparent", bg_color="transparent")
        hscrollbar.pack(fill="x", side="bottom", expand=False)

        canvas = ctk.CTkCanvas(self, bd=0,
                               width=1200,
                               height=300,
                               highlightthickness=0,
                               yscrollcommand=vscrollbar.set,
                               xscrollcommand=hscrollbar.set)
        
        canvas.pack(side="left", fill="both", expand=True)

        vscrollbar.configure(command=canvas.yview)
        hscrollbar.configure(command=canvas.xview)

        canvas.xview_moveto = 0
        canvas.yview_moveto = 0

        self.interior = interior = ctk.CTkFrame(master=canvas, fg_color=APP_BACKGROUND)
    
        def _configure_interior(event):
            canvas.config(scrollregion=canvas.bbox("all"))

        interior.bind("<Configure>", _configure_interior)

Example Usage:

      self. scrollable_frame = ScrollableFrame(parent=self)

      self.table = CTkTable(master=self.scrollable_frame.interior, 
                            values=values)
        
        self.table.pack(expand=False, fill="none")

        self.scrollable_frame.grid(column=0, row=3)

Keep in mind, that the master of the widget that you want to place in the scrollable frame needs to be ScrollableFrame.interior and not ScrollableFrame itself.

Hope that helps

**Comment by Akascape** [comment]
@KarthikBammidi3369 Check this widget: https://github.com/Akascape/CTkXYFrame
