### ISSUE TITLE
Request: make CTkBaseClass public

### ISSUE THREAD

**Issue by felipetesc** [TomSchimansky/CustomTkinter#209]
- **How to implement the feature:**

<p>Add to CustomTkinter/customtkinter/__init__.py  the line:</p>

```python
from .widgets.widget_base_class import CTkBaseClass
```
- **What it allows:**
It allows the creation of new widgets without adding them to customtkinter itself. So, people will be able to extend ctk. 

- **What it might solve:**
CustomTkinter can add new ui elements slowly, at its own pace. Less pull requests and more independence for developers to enhance ctk widgets. If the widget is tested and if it is ok for adding to ctk it can be done later

If the reader likes the idea feel free to react using emojis

**Comment by sumeshir26** [comment]
This would be aswsome, I could make my own witgets that use CtkDrawEngine. Please consider adding this would take no more than 5 mins +1

**Comment by TomSchimansky** [comment]
I can make this class public, but I cannot guarantee that the behaviour and usage of the class will stay consistent. There definitely will be changes in that class in the future that won't be backwards compatible.

**Comment by TomSchimansky** [comment]
CTkBaseClass is now public with version 4.5.1

**Comment by felipetesc** [comment]
Thank you very much.
