### ISSUE TITLE
Set appearance close the app

### ISSUE THREAD

**Issue by P3rdigas** [TomSchimansky/CustomTkinter#2090]
I'm doing an application where the user can change the appearance by clicking in one button. However, when i try to use `root._set_appearance_mode("system")` the app close but is still running, needing to terminate with Ctrl + C in the terminal. My app, first read a config.ini file to see the user preference and can load the system theme without errors, however when the user click on the button to chose the System mode this error occurs.

These are the buttons:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/91698253/a336a939-4835-42a8-aee3-827c820dffb7)

And the fucntion to handle the System mode:
```
def load_system_mode():
    try:
        root._set_appearance_mode("system")
        
        #appearance_mode = root._get_appearance_mode()

        #print(appearance_mode)

        # if appearance_mode == "light":
        #     configure_light_mode()
        # else:
        #     configure_dark_mode()

        config.set('Settings', 'theme', 'system')

        with open('config.ini', 'w') as configfile:
            config.write(configfile)
    except Exception as e:
        print(f"An error occurred: {e}")
```
I tried using try catch, however no exception is printed.

Note, the Dark and Light Mode change without issue, using `root._set_appearance_mode("dark")` and `root._set_appearance_mode("light")`

**Comment by P3rdigas** [comment]
After trying to understand better the issue, i found that the error occurs inside the function `_windows_set_titlebar_color`. 

The error seems to occur in the following if statement:
```
if color_mode.lower() == "dark":
                value = 1
            elif color_mode.lower() == "light":
                value = 0
            else:
                return
```

Once the color_mode is "system", returns None

**Comment by P3rdigas** [comment]
Anyone had the same problem or have an idea how to resolve this?

**Comment by LorenzoMattia** [comment]
Hi @P3rdigas , have you tried using *customtkinter.set_appearance_mode* instead of *root._set_appearance_mode*? I made a couple of projects with customtkinter and always used it to allow the user to change the appearance.

**Comment by P3rdigas** [comment]
Hi @LorenzoMattia, thanks a lot for the advice. Building a class for the appliction and using `customtkinter.set_appearance_mode` seems to fix the issue.
