### ISSUE TITLE
Linux GUI

### ISSUE THREAD

**Issue by Jakcrimson** [TomSchimansky/CustomTkinter#2098]
The linux GUI seems to be quite off compared to the Windows and MacOS GUI. Any plans on fixing it ?

**Comment by Akascape** [comment]
@Jakcrimson Another duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/1757 https://github.com/TomSchimansky/CustomTkinter/issues/1620 https://github.com/TomSchimansky/CustomTkinter/issues/1358 https://github.com/TomSchimansky/CustomTkinter/issues/1400 https://github.com/TomSchimansky/CustomTkinter/issues/1384 https://github.com/TomSchimansky/CustomTkinter/issues/1620 ...

Simple answer: Update python
