### ISSUE TITLE
Issue with the corner in buttons

### ISSUE THREAD

**Issue by Anonymous-ABC-XYZ** [TomSchimansky/CustomTkinter#2101]
When I try to set a corner radius, it doesn't appear correctly.

The issue:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/c8a559af-ad96-4c43-97ea-d32795e6470e)
It creates something that looks like a bone, instead of creating a smooth curved button.

The code:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/5b90bfeb-4a93-4c2e-aa2c-7aa25a2545aa)

This issue occurs with every widget, whether it be a scrollbar or a button

The scrollbar:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/47a5f05b-7b93-4b56-bb29-15add7259505)

Code for the scrollbar:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/a57d4aeb-d357-4d0e-959b-62387fc94529)

I hope you can help me solve this.

Thank you in advance.

**Comment by Akascape** [comment]
@Anonymous-ABC-XYZ Adjust the corner width and border width properly.

**Comment by Anonymous-ABC-XYZ** [comment]
@Akascape , could you please suggest some values?

**Comment by Anonymous-ABC-XYZ** [comment]
I am using a python venv environment with python 3.11

**Comment by Akascape** [comment]
@Anonymous-ABC-XYZ Is this happening with the standard examples?

**Comment by Anonymous-ABC-XYZ** [comment]
@Akascape Yes, it is still happening even with the standard code

Standard code:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/2a53012f-f64b-434f-9c62-84b8a7411861)

Result:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/34665f36-17d0-4657-afcd-70914f9d12e6)

Sample code with added border width and corner radius:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/9d92971f-50fb-4066-82e3-b093d92c9c33)

Result:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/70518092/ce28a1df-b77d-4250-a818-b8e725258400)

**Comment by Akascape** [comment]
@Anonymous-ABC-XYZ Then this is fault with tkinter and your operating system. Updating tkinter/python generally fixes this issue. Tkinter is still buggy in mac os and in some linux distributions.

**Comment by Anonymous-ABC-XYZ** [comment]
Ok, thank you
