### ISSUE TITLE
Button colors not working properly

### ISSUE THREAD

**Issue by correa-coder** [TomSchimansky/CustomTkinter#211]
The background and the foreground color of the buttons is not being applied correctly

I tried the following code but the `bg_color` and `fg_color` are inverted, the `fg_color` is using the `bg_color`

```python
import tkinter
import customtkinter

customtkinter.set_appearance_mode("dark")
customtkinter.set_default_color_theme("blue")

app = customtkinter.CTk()

frame = customtkinter.CTkFrame(app)

customtkinter.CTkButton(frame, text="Add", fg_color="red", bg_color="cornflowerblue").grid(row=0, column=0, padx=10)
customtkinter.CTkButton(frame, text="Update", fg_color="black", bg_color="orange").grid(row=0, column=1, padx=10)
customtkinter.CTkButton(frame, text="Remove", fg_color="white", bg_color="red").grid(row=0, column=2, padx=10)

frame.place(relx="0.5", rely="0.5", anchor="center")

app.mainloop()

```

![btn_color_1](https://user-images.githubusercontent.com/80556636/175754381-dc96d454-4f96-4cb8-96f3-34024f899da2.png)

So I swapped the `fg_color` with the `bg_color` and vice-versa and got the correct colors on the background of the buttons but the foreground doesn't change, it's always white (on dark mode).

```python
customtkinter.CTkButton(frame, text="Add", fg_color="cornflowerblue", bg_color="red").grid(row=0, column=0, padx=10)
customtkinter.CTkButton(frame, text="Update", fg_color="orange", bg_color="black").grid(row=0, column=1, padx=10)
customtkinter.CTkButton(frame, text="Remove", fg_color="red", bg_color="white").grid(row=0, column=2, padx=10)
```
![btn_color_2](https://user-images.githubusercontent.com/80556636/175754385-f83a14a7-cbf5-42b5-9dc8-212369aee748.png)

**Comment by TomSchimansky** [comment]
Everything is working fine, the colors work like this:

`bg_color`: Color behind the button (background). This color gets automatically chosen dependant on the fg_color of the widget the button is placed on. Normally you wouldn't need to set this color manually.

`fg_color`/`hover_color`: Color of the button (foreground). This is the main color of the button you want to change.

`border_color `: Color of the border, only visible if border_width > 0.

`text_color`/`text_color_disabled `: Color of the text on the button.

**Comment by correa-coder** [comment]
Got it, I suggest you explain this difference in the documentation because other people may get confused like I did because Tkinter uses `fg` for the color of the text.
