### ISSUE TITLE
Not able to focus on CTkEntry using .focus()

### ISSUE THREAD

**Issue by Himanshu700296** [TomSchimansky/CustomTkinter#212]
i just started using customtkinter and i am not able to use the focus model

**Comment by Himanshu700296** [comment]
Please check the problem as i am not able to use the .focus method with entry, when i am creating a normal entry i am not findig issue in focus but when i am using CTkEntry, the focus is not working

**Comment by felipetesc** [comment]
> Please check the problem as i am not able to use the .focus method with entry, when i am creating a normal entry i am not findig issue in focus but when i am using CTkEntry, the focus is not working

Is normal entry the Tkinter Entry ?

**Comment by Himanshu700296** [comment]
Yes, when i am using the tkinter module and creating the widget entry from it by using Entry() function, i am finding no problem in .focus() method but when i am using custom tkinter and creating new entry using CTkEntry, the . focus () mode is not taking the focus on the Entry widget

**Comment by Himanshu700296** [comment]
> > Please check the problem as i am not able to use the .focus method with entry, when i am creating a normal entry i am not findig issue in focus but when i am using CTkEntry, the focus is not working
> 
> Is normal entry the Tkinter Entry ?

have you got any solution

**Comment by TomSchimansky** [comment]
I added these functions in CTkEntry so that the focus works properly:
```python
    def focus(self):
        self.entry.focus()

    def focus_force(self):
        self.entry.focus_force()
```
It will be available with the next version on pip.

**Comment by Himanshu700296** [comment]
Thank you for the help....when will be next update available? As i am working on a software and i will be providing the software to the client in some days....so...

**Comment by TomSchimansky** [comment]
Ok, I uploaded version 4.5.1 now on pip.

**Comment by Himanshu700296** [comment]
Thank you so much
