### ISSUE TITLE
`.winfo_x()` Giving Incorrect Value Of X-distance Due To Scaling

### ISSUE THREAD

**Issue by dipeshSam** [TomSchimansky/CustomTkinter#2125]
The following code where I want X-distance of a widget (Button in this case) with respect to its parent or master widget, returning incorrect value:

``` Python
from customtkinter import CTk, CTkButton

if __name__ == "__main__":
    app = CTk()
    app.geometry("900x600")
    app.columnconfigure(0, weight=1)

    button = CTkButton(app, text="Profile", command=lambda: print(button.winfo_x()))
    button.grid(row=0, column=0, padx=20, pady=20, sticky="e")

    app.mainloop()
```
**It prints _925_ as output. But the width of the parent widget is _900_, while both the widgets are visible and have no scrollbars.**

One of the solution to print the correct x-distance, I found is to remove Scaling:
``` Python
from customtkinter import CTk, CTkButton
from customtkinter import deactivate_automatic_dpi_awareness

if __name__ == "__main__":
    app = CTk()
    app.geometry("900x600")
    app.columnconfigure(0, weight=1)
    deactivate_automatic_dpi_awareness()


    button = CTkButton(app, text="Profile", command=lambda: print(button.winfo_x()))
    button.grid(row=0, column=0, padx=20, pady=20, sticky="e")

    app.mainloop()
```
**It prints desired value as 740, but removes scaling.**

**I want an exact and reliable solution because it already works well with `Tkitnter` only, without anything.**
``` Python
from tkinter import Tk, Button

if __name__ == "__main__":
    window = Tk()
    window.geometry("900x600")
    window.columnconfigure(0, weight=1)

    button = Button(window, text="Profile", command=lambda: print(button.winfo_x()))
    button.grid(row=0, column=0, padx=20, pady=20, sticky="e")

    window.mainloop()
```
It gives the correct value as 835. **This should also be fixed in `customtkinter`**.

**Comment by dipeshSam** [comment]
> The following code where I want X-distance of a widget (Button in this case) with respect to its parent or master widget, returning incorrect value:
> 
> ``` Python
> from customtkinter import CTk, CTkButton
> 
> if __name__ == "__main__":
>     app = CTk()
>     app.geometry("900x600")
>     app.columnconfigure(0, weight=1)
> 
>     button = CTkButton(app, text="Profile", command=lambda: print(button.winfo_x()))
>     button.grid(row=0, column=0, padx=20, pady=20, sticky="e")
> 
>     app.mainloop()
> ```
> **It prints _925_ as output. But the width of the parent widget is _900_, while both the widgets are visible and have no scrollbars.**
> 
> One of the solution to print the correct x-distance, I found is to remove Scaling:
> ``` Python
> from customtkinter import CTk, CTkButton
> from customtkinter import deactivate_automatic_dpi_awareness
> 
> if __name__ == "__main__":
>     app = CTk()
>     app.geometry("900x600")
>     app.columnconfigure(0, weight=1)
>     deactivate_automatic_dpi_awareness()
> 
> 
>     button = CTkButton(app, text="Profile", command=lambda: print(button.winfo_x()))
>     button.grid(row=0, column=0, padx=20, pady=20, sticky="e")
> 
>     app.mainloop()
> ```
> **It prints desired value as 740, but removes scaling.**
> 
> **I want an exact and reliable solution because it already works well with `Tkitnter` only, without anything.**
> ``` Python
> from tkinter import Tk, Button
> 
> if __name__ == "__main__":
>     window = Tk()
>     window.geometry("900x600")
>     window.columnconfigure(0, weight=1)
> 
>     button = Button(window, text="Profile", command=lambda: print(button.winfo_x()))
>     button.grid(row=0, column=0, padx=20, pady=20, sticky="e")
> 
>     window.mainloop()
> ```
> It gives the correct value as 835. **This should also be fixed in `customtkinter`**.
> 

**Solved it!**
It was pretty satisfying solution as I already knew about scaling.

**Comment by Akascape** [comment]
@dipeshSam Can you explain how you did it? I am currently getting wrong values of winfo_x, winfo_y and even winfo_width or winfo_height

**Comment by dipeshSam** [comment]
@Akascape **Sure brother.**

Here is the solution:

“Multiply resulting value with the device scaling value.”

For example:
If `winfo_x()` gives value as `250` and device scaling value is `1.25` then `250*1.25` will produce the accurate x-distance as `312.5`.

This happens because `customtkinter` forcibly sets the DPI Awareness without ensuring the Tkinter calls.

This is valid in all cases inside the window. I'm assuming that you know how to get scaling value in `CTk`. If you have further questions, let me know.

Regards.
