### ISSUE TITLE
Justifying text in CTkLabel

### ISSUE THREAD

**Issue by SiddyG8** [TomSchimansky/CustomTkinter#213]
I am trying to justify text to the left in my program. Here is the label code:
```python
self.lblUserInfo = CTkLabel(
    self.frameMain,
    width=200,
    text="User (Username)",
    text_font=("Inter", -14, "bold"),
    text_color=("#0969DA", "#58A6FF"),
    justify="left",
    anchor="w",
    fg_color="gray30" # <- temporary, just for highlighting the issue
)
```
and the code for placement (using grid):
```python
self.lblUserInfo.grid(row=0, column=0, padx=10, pady=10, sticky="w")
```

This is what the GUI looks like:
![image](https://user-images.githubusercontent.com/80557973/175807865-d8de002e-3684-4d21-bfc4-24ac830654b1.png)
As shown the label with text "User (Username)" still has text that is not justified properly, I'm not sure why the options aren't working, could someone please explain why this is happening and what I could do to fix it?

**Comment by SiddyG8** [comment]
Update: It seems the issue only happens for labels with **bold** text and also goes away when they are configured (even if the configure isn't changing the justify attribute).

**Comment by SiddyG8** [comment]
**Update:** I believe this may be an issue with the way the CTkLabel is created. While the anchor option is passed to the internal tkinter Label widget through **kwargs in ctk_label.py, the label itself is placed inside the canvas using grid which always places it in the centre of the canvas. This placement renders the anchor value input into the CTkLabel useless.

In my own installation of customtkinter I have fixed this issue by adding an anchor option into the __init__ function of with a default value of "center". I then pass this anchor value into the internal tkinter Label widget that the CTkLabel class creates. Afterwards I assign the anchor value to a variable called 'stickyness' (with "center" being mapped to None as "center" is not an accepted stickyness value). This stickyness value is then passed into the 'sticky' attribute of the grid function to properly align the internal tkinter Label widget according to the anchor specified in the CTkLabel. Here are the images of my changes (Atom IDE with Atom Material theme):
![image](https://user-images.githubusercontent.com/80557973/175811407-4d28a160-e813-4833-851d-14688da7fee5.png)
![image](https://user-images.githubusercontent.com/80557973/175811426-05a9520c-e7ba-4381-959f-1ac85d020231.png)
![image](https://user-images.githubusercontent.com/80557973/175811459-c53d788e-5128-4488-a002-4a9bba14b74a.png)
![image](https://user-images.githubusercontent.com/80557973/175811489-5c622731-47d9-4824-871b-f59362d214e4.png)

This fix works for my use case, however I haven't thoroughly tested this. That being said, could a permanent fix like this be implemented to the actual customtkinter library sometime soon?

**Comment by TomSchimansky** [comment]
I know of this behaviour, I think I will try to do it like you suggested it and move the text to the correct edge when the anchor attribute is passed.

**Comment by SiddyG8** [comment]
That's great to hear, hope to see it implemented soon.

**Comment by TomSchimansky** [comment]
Works now with version 4.5.5.
