### ISSUE TITLE
Delete a CTk label

### ISSUE THREAD

**Issue by Prajwal201011** [TomSchimansky/CustomTkinter#2136]
### Discussed in https://github.com/TomSchimansky/CustomTkinter/discussions/2117

<div type='discussions-op-text'>

<sup>Originally posted by **Prajwal201011** December  2, 2023</sup>
So I have been trying to delete a CTk Label using .delete function but it doesn't work 
does anyone know how to do it

```
def cal():
    princip = int(p.get())
    Term = int(t.get())
    Rate = int(r.get())
    amt = (princip*Term*Rate)/100
    amtl = CTkLabel(interest, text=f"Amount is: {amt}")
    amtl.pack(pady= 15)
    
    def clear():
        amtl.delete(0, 'end')
        
    btnc = CTkButton(interest, text="Clear", fg_color="#1dc444", command=clear())
    btnc.pack(padx=5, pady=5)</div>
```

**Comment by P3rdigas** [comment]
Hi @Prajwal201011, i think i didn't understand what tou want to achieve, but i'm going to give you two approaches.

First, if you want to change the number inside the Label (change from a value to 0 for example), you show use the funtion `.configure()`, here is an example:

```
class ExampleApp(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        # Configure window
        self.title("Delete Label")
        self.geometry(f"{800}x{600}")
        self.resizable(width=False, height=False)

        self.amt = 10
        self.amtl = customtkinter.CTkLabel(self, text=f"Amount is: {self.amt}")
        self.amtl.pack(pady= 15)

        btnc = customtkinter.CTkButton(self, text="Clear", fg_color="#1dc444", command=self.clear)
        btnc.pack(padx=5, pady=5)
    
    def clear(self):
        self.amt = 0
        self.amtl.configure(text=f"Amount is: {self.amt}")
        
    

def main():
    app = ExampleApp()
    app.mainloop()

if __name__ == "__main__":
    main()
```

Second if you want to delete the all Label, then you should you the function `.destroy()`, here is an example:

```
class ExampleApp(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        # Configure window
        self.title("Delete Label")
        self.geometry(f"{800}x{600}")
        self.resizable(width=False, height=False)

        self.amt = 10
        self.amtl = customtkinter.CTkLabel(self, text=f"Amount is: {self.amt}")
        self.amtl.pack(pady= 15)

        btnc = customtkinter.CTkButton(self, text="Clear", fg_color="#1dc444", command=self.clear)
        btnc.pack(padx=5, pady=5)
    
    def clear(self):
        self.amtl.destroy()
        
    

def main():
    app = ExampleApp()
    app.mainloop()

if __name__ == "__main__":
    main()
```

Try this examples and see if it suits your case. If it don't feel free to reply and i will try to help you.

**Comment by dipeshSam** [comment]
> ### Discussed in https://github.com/TomSchimansky/CustomTkinter/discussions/2117
> 
> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **Prajwal201011** December  2, 2023</sup>
> So I have been trying to delete a CTk Label using .delete function but it doesn't work 
> does anyone know how to do it
> 
> 
> ```
> def cal():
>     princip = int(p.get())
>     Term = int(t.get())
>     Rate = int(r.get())
>     amt = (princip*Term*Rate)/100
>     amtl = CTkLabel(interest, text=f"Amount is: {amt}")
>     amtl.pack(pady= 15)
>     
>     def clear():
>         amtl.delete(0, 'end')
>         
>     btnc = CTkButton(interest, text="Clear", fg_color="#1dc444", command=clear())
>     btnc.pack(padx=5, pady=5)</div>
> ```

**In `customtkinter`, use `.destroy()` method to remove a widget completely.**

**Comment by P3rdigas** [comment]
I also notice that you in the button put `command=clear()`. With the parentheses, the code will call the function and the value return will be assign to the `command `parameter. That being said, you should not include the parentheses. Without the parentheses, the function will be assign to the `command `parameter.

**Comment by Prajwal201011** [comment]
Thank you @P3rdigas , @dipeshSam , your response was really helpful
