### ISSUE TITLE
Website Github Discussions Link Label

### ISSUE THREAD

**Issue by Kyle2241** [TomSchimansky/CustomTkinter#2145]
The label for the link from [(https://customtkinter.tomschimansky.com/)](https://customtkinter.tomschimansky.com/) to take you to the Github Discussions page is misspelled as Github Dicsussions.

The link isn't broken, but I noticed and wanted to post here. 

I am pasting an image below
![image](https://github.com/TomSchimansky/CustomTkinter/assets/43285404/c4a93abf-d7c8-42a5-b7db-42ceea5fb042)

**Comment by TomSchimansky** [comment]
Fixed.
