### ISSUE TITLE
CTkToolTip not found

### ISSUE THREAD

**Issue by P3rdigas** [TomSchimansky/CustomTkinter#2155]
Hi, anyone know if CTkToolTip exists in this version or was it remove? Is possible to use something similar?

**Comment by dipeshSam** [comment]
> Hi, anyone know if CTkToolTip exists in this version or was it remove? Is possible to use something similar?

CTkToolTip is not produced by this repository. This is the official repository or library of the `customtkinter`.

CTkToolTip is a third-party library create by a user named Akascape or something similar. You can reach out there: https://github.com/Akascape/CTkToolTip

**Comment by P3rdigas** [comment]
Thank you vey much!

**Comment by dipeshSam** [comment]
> Thank you vey much! 

You are most welcome!
