### ISSUE TITLE
 ctk.CTkTextbox.config() height in px instead of lines

### ISSUE THREAD

**Issue by lorenzolpandolfo** [TomSchimansky/CustomTkinter#2159]
Hello everyone!
Im trying to develop a code, but it works on tkinter and doesn't in customtkinter. The reason for that is because the unit for height in a Textbox in customtkinter is in pixels. I wonder if there is a way to make it interpret lines instead of pixels.
I tried to multiply the **font size** by the **number of lines**, but it returns a bigger value than the number of lines in pixels and I don't know why this is happening.

**tkinter code (works fine):**
```
import tkinter as tk

class App:
    def __init__(self, root):
        self.root = root
        self.root.geometry("300x200")
        self.root.bind("<Key>", self.on_resize)

        self.textbox = tk.Text(root, wrap="word")
        self.textbox.grid(row=0, column=0, sticky="new")
        
        
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)

    def on_resize(self, event):
        
        print(event.height)
        print(self.root.winfo_height() // 19)
        self.textbox.config(height=(self.root.winfo_height() // 19))
        

if __name__ == "__main__":
    root = tk.Tk()
    app = App(root)
    root.mainloop()

```

**customtkinter code (not working the way I want):** 
```
import customtkinter as ctk

class App:
    def __init__(self, root):
        self.root = root
        self.root.geometry("300x200")
        self.root.bind("<Key>", self.on_resize)

        self.textbox = ctk.CTkTextbox(root, wrap="word")
        self.textbox.grid(row=0, column=0, sticky="new")
        

        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)

    def on_resize(self, event):

        print(event.height)
        print(self.root.winfo_height() // 19)
        self.textbox.configure(height=(self.root.winfo_height() // 19))
        

if __name__ == "__main__":
    root = ctk.CTk()
    app = App(root)
    root.mainloop()

```

The code purpose is to add new lines if there is space to them. The text must not expand if won't fit a full line height.
Thank you, people! :)

**Comment by dipeshSam** [comment]
> Hello everyone! Im trying to develop a code, but it works on tkinter and doesn't in customtkinter. The reason for that is because the unit for height in a Textbox in customtkinter is in pixels. I wonder if there is a way to make it interpret lines instead of pixels. I tried to multiply the **font size** by the **number of lines**, but it returns a bigger value than the number of lines in pixels and I don't know why this is happening.
> 
> **tkinter code (works fine):**
> 
> ```
> import tkinter as tk
> 
> class App:
>     def __init__(self, root):
>         self.root = root
>         self.root.geometry("300x200")
>         self.root.bind("<Key>", self.on_resize)
> 
>         self.textbox = tk.Text(root, wrap="word")
>         self.textbox.grid(row=0, column=0, sticky="new")
>         
>         
>         self.root.columnconfigure(0, weight=1)
>         self.root.rowconfigure(0, weight=1)
> 
>     def on_resize(self, event):
>         
>         print(event.height)
>         print(self.root.winfo_height() // 19)
>         self.textbox.config(height=(self.root.winfo_height() // 19))
>         
> 
> if __name__ == "__main__":
>     root = tk.Tk()
>     app = App(root)
>     root.mainloop()
> ```
> 
> **customtkinter code (not working the way I want):**
> 
> ```
> import customtkinter as ctk
> 
> class App:
>     def __init__(self, root):
>         self.root = root
>         self.root.geometry("300x200")
>         self.root.bind("<Key>", self.on_resize)
> 
>         self.textbox = ctk.CTkTextbox(root, wrap="word")
>         self.textbox.grid(row=0, column=0, sticky="new")
>         
> 
>         self.root.columnconfigure(0, weight=1)
>         self.root.rowconfigure(0, weight=1)
> 
>     def on_resize(self, event):
> 
>         print(event.height)
>         print(self.root.winfo_height() // 19)
>         self.textbox.configure(height=(self.root.winfo_height() // 19))
>         
> 
> if __name__ == "__main__":
>     root = ctk.CTk()
>     app = App(root)
>     root.mainloop()
> ```
> 
> The code purpose is to add new lines if there is space to them. The text must not expand if won't fit a full line height. Thank you, people! :)

**Could you please explain what exactly you want to do? Do you want to fit the box to the lines? Or something else?**

**Comment by lorenzolpandolfo** [comment]
> > Hello everyone! Im trying to develop a code, but it works on tkinter and doesn't in customtkinter. The reason for that is because the unit for height in a Textbox in customtkinter is in pixels. I wonder if there is a way to make it interpret lines instead of pixels. I tried to multiply the **font size** by the **number of lines**, but it returns a bigger value than the number of lines in pixels and I don't know why this is happening.
> > **tkinter code (works fine):**
> > ```
> > import tkinter as tk
> > 
> > class App:
> >     def __init__(self, root):
> >         self.root = root
> >         self.root.geometry("300x200")
> >         self.root.bind("<Key>", self.on_resize)
> > 
> >         self.textbox = tk.Text(root, wrap="word")
> >         self.textbox.grid(row=0, column=0, sticky="new")
> >         
> >         
> >         self.root.columnconfigure(0, weight=1)
> >         self.root.rowconfigure(0, weight=1)
> > 
> >     def on_resize(self, event):
> >         
> >         print(event.height)
> >         print(self.root.winfo_height() // 19)
> >         self.textbox.config(height=(self.root.winfo_height() // 19))
> >         
> > 
> > if __name__ == "__main__":
> >     root = tk.Tk()
> >     app = App(root)
> >     root.mainloop()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **customtkinter code (not working the way I want):**
> > ```
> > import customtkinter as ctk
> > 
> > class App:
> >     def __init__(self, root):
> >         self.root = root
> >         self.root.geometry("300x200")
> >         self.root.bind("<Key>", self.on_resize)
> > 
> >         self.textbox = ctk.CTkTextbox(root, wrap="word")
> >         self.textbox.grid(row=0, column=0, sticky="new")
> >         
> > 
> >         self.root.columnconfigure(0, weight=1)
> >         self.root.rowconfigure(0, weight=1)
> > 
> >     def on_resize(self, event):
> > 
> >         print(event.height)
> >         print(self.root.winfo_height() // 19)
> >         self.textbox.configure(height=(self.root.winfo_height() // 19))
> >         
> > 
> > if __name__ == "__main__":
> >     root = ctk.CTk()
> >     app = App(root)
> >     root.mainloop()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The code purpose is to add new lines if there is space to them. The text must not expand if won't fit a full line height. Thank you, people! :)
> 
> **Could you please explain what exactly you want to do? Do you want to fit the box to the lines? Or something else?**
> 
> **If you want to handle the height of the text box in lines instead of in pixels, you can configure internal test box of the CTkTextbox. Here is how:**
> 
> Your updated code statement:
> 
> ```python
> self.textbox._textbox.configure(height=(self.root.winfo_height() // 19))
> ```
> 
> **It will manage the height in rows, and not in pixels. Keep in mind that, to use this, you need to pass the height as 0 while instantiating the CTkTextbox object.**

Hello dipeshSam, thank you so much for the reply. I tested your fix and my code works correctly now! At least, it works in my laptop resolution. I will run it in my computer later to see if it works with different resolutions.

> **Could you please explain what exactly you want to do? Do you want to fit the box to the lines? Or something else?**

Basically, I have a Textbox that must have the highest height possible, but its lines must fit completely too.
If this answer isn't clear enough, I can record you a clip to show you what I wanted and the problem itself.

Again, thanks a lot! :)

**Comment by dipeshSam** [comment]
> Hello everyone!
> Im trying to develop a code, but it works on tkinter and doesn't in customtkinter. The reason for that is because the unit for height in a Textbox in customtkinter is in pixels. I wonder if there is a way to make it interpret lines instead of pixels.
> I tried to multiply the **font size** by the **number of lines**, but it returns a bigger value than the number of lines in pixels and I don't know why this is happening.
> 
> **tkinter code (works fine):**
> ```
> import tkinter as tk
> 
> class App:
>     def __init__(self, root):
>         self.root = root
>         self.root.geometry("300x200")
>         self.root.bind("<Key>", self.on_resize)
> 
>         self.textbox = tk.Text(root, wrap="word")
>         self.textbox.grid(row=0, column=0, sticky="new")
>         
>         
>         self.root.columnconfigure(0, weight=1)
>         self.root.rowconfigure(0, weight=1)
> 
>     def on_resize(self, event):
>         
>         print(event.height)
>         print(self.root.winfo_height() // 19)
>         self.textbox.config(height=(self.root.winfo_height() // 19))
>         
> 
> if __name__ == "__main__":
>     root = tk.Tk()
>     app = App(root)
>     root.mainloop()
> 
> ```
> 
> **customtkinter code (not working the way I want):** 
> ```
> import customtkinter as ctk
> 
> class App:
>     def __init__(self, root):
>         self.root = root
>         self.root.geometry("300x200")
>         self.root.bind("<Key>", self.on_resize)
> 
>         self.textbox = ctk.CTkTextbox(root, wrap="word")
>         self.textbox.grid(row=0, column=0, sticky="new")
>         
> 
>         self.root.columnconfigure(0, weight=1)
>         self.root.rowconfigure(0, weight=1)
> 
>     def on_resize(self, event):
> 
>         print(event.height)
>         print(self.root.winfo_height() // 19)
>         self.textbox.configure(height=(self.root.winfo_height() // 19))
>         
> 
> if __name__ == "__main__":
>     root = ctk.CTk()
>     app = App(root)
>     root.mainloop()
> 
> ```
> 
> The code purpose is to add new lines if there is space to them. The text must not expand if won't fit a full line height.
> Thank you, people! :)

    @lorenzolpandolfo Glad to hear that it worked for you. You are most welcome.
Happy customtkinter :)
