### ISSUE TITLE
multi-display windows scaling 

### ISSUE THREAD

**Issue by 0xYST** [TomSchimansky/CustomTkinter#217]
Hello! 

I recently started working with the CustomTkinter library and I actually discovered quite a unique bug.

![image](https://user-images.githubusercontent.com/54594278/175975920-b3e84393-3454-4682-ac4b-c3271552366c.png)

When using a second display, that has a different scaling percentage in windows there are some weird interactions that actually break the library. 

Using the code from the complex example, when I drag the customtkinter window to my other display with different scaling these errors are generated: 

![image](https://user-images.githubusercontent.com/54594278/175976851-b061a783-b3f0-4e00-89ad-23ba66be9c91.png)

The result of these errors causes the program to lose features like appearance mode, and the general GUI changes its scale drastically

For now I solved it by adjusting my second monitors scaling within windows but I figured I would share my expereince.

**Comment by TomSchimansky** [comment]
Hi, Thanks for posting this, I will try to reproduce this error.
