### ISSUE TITLE
How do I create a table?

### ISSUE THREAD

**Issue by childeyouyu** [TomSchimansky/CustomTkinter#2170]
What should I do if I want to set up a table space to display my data? It's like Treeview in Tk。

eg：https://www.cnblogs.com/rainbow-tan/p/14125768.html

**Comment by dipeshSam** [comment]
> What should I do if I want to set up a table space to display my data? It's like Treeview in Tk。
> 
> eg：https://www.cnblogs.com/rainbow-tan/p/14125768.html

@childeyouyu, There is a third-party library created by a user named as Akascape or something similar may fulfil your requirements. Check: https://github.com/Akascape/CTkTable

**Comment by childeyouyu** [comment]
ok,thankes. It's got my needs covered

> > What should I do if I want to set up a table space to display my data? It's like Treeview in Tk。如果要设置表空间来显示数据，该怎么办？就像Tk中的Treeview一样。
> > eg：https://www.cnblogs.com/rainbow-tan/p/14125768.html例如：https://www.cnblogs.com/rainbow-tan/p/14125768.html
> 
> @childeyouyu, There is a third-party library created by a user named as Akascape or something similar may fulfil your requirements. Check: https://github.com/Akascape/CTkTable，有一个名为 Akascape 的用户创建的第三方库或类似的东西可以满足您的要求。检查：https://github.com/Akascape/CTkTable
