### ISSUE TITLE
Update 5.10 not installing.

### ISSUE THREAD

**Issue by TheAnonymous13** [TomSchimansky/CustomTkinter#2176]
I've been using customtkinter for a while, and this is the first problem I've ran into with it. I been using version 4.0.2 but want to update to version 5.10. My system does not seem to recognize it as having updates. 

```
PS C:\Users\User\OneDrive\Desktop\RokTracker-3.0.0> pip install customtkinter==5.10.0
ERROR: Could not find a version that satisfies the requirement customtkinter==5.10.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 4.0.0, 4.0.1, 4.0.2)
ERROR: No matching distribution found for customtkinter==5.10.0
```

```
PS C:\Users\User\OneDrive\Desktop\RokTracker-3.0.0> pip show customtkinter
Name: customtkinter
Version: 4.0.2
Summary: Create modern looking GUIs with Python
Home-page: https://github.com/TomSchimansky/CustomTkinter
Author: Tom Schimansky
Author-email:
License: Creative Commons Zero v1.0 Universal
Location: c:\users\user\appdata\local\programs\python\python36\lib\site-packages
Requires: darkdetect
Required-by:
```

**Comment by dipeshSam** [comment]
> I've been using customtkinter for a while, and this is the first problem I've ran into with it. I been using version 4.0.2 but want to update to version 5.10. My system does not seem to recognize it as having updates. 
> 
> 
> 
> ```
> PS C:\Users\User\OneDrive\Desktop\RokTracker-3.0.0> pip install customtkinter==5.10.0
> ERROR: Could not find a version that satisfies the requirement customtkinter==5.10.0 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 4.0.0, 4.0.1, 4.0.2)
> ERROR: No matching distribution found for customtkinter==5.10.0
> ```
> 
> ```
> PS C:\Users\User\OneDrive\Desktop\RokTracker-3.0.0> pip show customtkinter
> Name: customtkinter
> Version: 4.0.2
> Summary: Create modern looking GUIs with Python
> Home-page: https://github.com/TomSchimansky/CustomTkinter
> Author: Tom Schimansky
> Author-email:
> License: Creative Commons Zero v1.0 Universal
> Location: c:\users\user\appdata\local\programs\python\python36\lib\site-packages
> Requires: darkdetect
> Required-by:
> ```

@TheAnonymous13, Don't be confused. Go to the following standard website and install the `customtkinter` with love: https://pypi.org/project/customtkinter/

After this installation: Go to: https://customtkinter.tomschimansky.com/ for demos and nice sample codes with well written documentations.

**Comment by TheAnonymous13** [comment]
Solution was an issue with pip - just re-installed pip then install customtkinter
