### ISSUE TITLE
Text is interfering with fixed button size/ Fixed button size is not working properly because of text.

### ISSUE THREAD

**Issue by 963224** [TomSchimansky/CustomTkinter#2178]
I have the following problem: When I set a button to a fixed size with 'width=' and have a text that is wider than the set button width, the button expands to the text width. 

Example Code where the button is displayed much wider than the set 50pixels:

    from customtkinter import CTk, CTkButton

    window = CTk()
    window.geometry("400x400")
    button = CTkButton(window, text="Example of button text", width=50)
    button.pack()
    window.mainloop()

This behaviour only occurs with customtkinter and not with the regular tkinter module. Is there a way I can make the button widget complety ignore the text width?

**Comment by TomSchimansky** [comment]
You could add `button.grid_propagate(0)` to achive this, since this is not standard for the button or label, maybe I will chnage this in the future.
