### ISSUE TITLE
How to know if the actual line is visually broken

### ISSUE THREAD

**Issue by lorenzolpandolfo** [TomSchimansky/CustomTkinter#2184]
Hello everyone!
Im trying to find a way to check if, in a CTkTextbox, the selected line is visually broken, because of the widget size that can't fit the full line.

I tried to get the **widget width** and **divide by the font.metrics()['linespace']**, but it doesn't work because some characters have different widths.
Then I tried to check if there is "\n" in the actual line, but it doesn't work too, because tkinter doesn't add "\n" to the line if it is visually broken.

![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/8bce69a2-5e77-44b6-ad8e-f32c342730e0)
![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/b25c1fb3-5da2-4ada-84d4-97bc9e8b5452)

If I wasn't clear enough, feel free to comment and ask more details about.
Thank you guys! :)

**Comment by dipeshSam** [comment]
@lorenzolpandolfo 
You want to know whether a line is wrapped into two lines, yes??

Scenario 1:
—⟩ This is a single line of text on textbox.

Scenario 2:
—⟩ This is a single line of 
      text on textbox.

You want to check scenario 1 to scenario 2, yes??

If yes, I can write my answer here.

**Comment by lorenzolpandolfo** [comment]
> @lorenzolpandolfo 
> You want to know whether a line is wrapped into two lines, yes??
> 
> Scenario 1:
> —⟩ This is a single line of text on textbox.
> 
> Scenario 2:
> —⟩ This is a single line of 
>       text on textbox.
> 
> You want to check scenario 1 to scenario 2, yes??
> 
> If yes, I can write my answer here.
> 
> 

Hello dipeshSam! Yes, you're right

**Comment by dipeshSam** [comment]
@lorenzolpandolfo Okay, appreciable! I'm writing my answer, it may take some time. 
:)

**Comment by dipeshSam** [comment]
@lorenzolpandolfo Sorry brother, it took a bit longer.

It can be achieved using **mapping** the _text length_ to the length of the text box. It can easily done every update to the text box. Length occupied by every character is different, so for more accurate and efficient mapping, it's recommended to write a logic that can handle each character in different length.

To know the length occupied by the text, we use a function `measure` provided by the class `Font`, well supported by `customtkinter`.

**Video demonstration:**

https://github.com/TomSchimansky/CustomTkinter/assets/72375763/9b55c19d-ee68-4e0d-8f02-b9dfbe1c46d5




**Updated class code:**
``` Python
from customtkinter import CTkTextbox, CTkFont

class CTkEasyTextBox(CTkTextbox):
    """Updated with two new functions. `getLine` and `isWrapped`."""
    def __init__(self,
        master: any,
        width: int = 200,
        height: int = 200,
        corner_radius: int | None = None,
        border_width: int | None = None,
        border_spacing: int = 3,
        bg_color: str | tuple[str, str] = "transparent",
        fg_color: str | tuple[str, str] | None = None,
        border_color: str | tuple[str, str] | None = None,
        text_color: str | None = None,
        scrollbar_button_color: str | tuple[str, str] | None = None,
        scrollbar_button_hover_color: str | tuple[str, str] | None = None,
        font: tuple | CTkFont | None = None,
        activate_scrollbars: bool = True,
        **kwargs):

        super().__init__(master, width, height, corner_radius, border_width, border_spacing, bg_color, fg_color, border_color, text_color, scrollbar_button_color, scrollbar_button_hover_color, font, activate_scrollbars, **kwargs)

    def getLine(self, line_number: int):
        """
        Returns full line of a text box by line number.
        Args:
            - line_number   -> Line number >= 1
        """
        if line_number <= 0: return ""

        line: str     = ""
        column: int   = 0
        char: str = self.get(f"{line_number}.{column}")
        
        while char != "\n" and len(char) != 0:
            line     = line + char
            column   = column + 1
            char = self.get(f"{line_number}.{column}")

        return line
    
    def isWrapped(self, line_number: int):
        """
        It can state whether a line is wrapped or not.
        Args:
            - line_number   -> Line number >= 1
        """

        if not (line:=self.getLine(line_number)): return False
        # Updating the to get current value
        self.nametowidget(".").update()
    
        line_length         = self._font.measure(line) + self._textbox["padx"] + self._textbox.grid_info()["padx"][0]
        text_box_mean_width = self._current_width

        print(line_length, text_box_mean_width)
        if line_length >= text_box_mean_width:
            return True
        else:
            return False
        
```

**Let you have saved the above class into a file named as `ctk_easy_text_box.py` in your current working directory, then a sample usage case:**
``` Python
from ctk_easy_text_box import CTkEasyTextBox
from customtkinter import CTk, CTkLabel, CTkFont

def on_click():
    if text_box.isWrapped(1):
        label.configure(text="Wrapped: Yes!", text_color="green")
    else:
        label.configure(text="Wrapped: No!", text_color="brown")


if __name__ == "__main__":
    app = CTk()
    app.geometry("500x350")
    app.grid_columnconfigure(0, weight=1)
    app.grid_rowconfigure((0, 1), weight=1)

    text_box = CTkEasyTextBox(app, width=200, height=100, wrap="char")
    text_box.grid(sticky="ew")

    label = CTkLabel(app, text=f"Wrapped: {text_box.isWrapped(1)}", font=CTkFont(size=30, weight="bold"))
    label.grid(row=1, column=0)

    text_box.insert(0.0, "Sample alphabets line: ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    text_box.bind("<KeyRelease>", lambda _: on_click())
    text_box.bind("<Configure>", lambda _:  on_click())

    app.mainloop()
```

**Hope, it will be helpful for you.**

**Comment by lorenzolpandolfo** [comment]
@dipeshSam Thank you for your answer! Your code works fine, but when I added it to mine, some bugs happened and Im a little exausted to fix them rn. If it is interesting to you, Im trying to develop a text editor in python with customtkinter. The repository is "pytext" and it is public in my profile.
I'm trying to develop the "number relativenumber" function that exists in Vim, but, in my text editor, when you have a wrapped line, the line counter doesn't know how to realize that the line occupies more than one line space and it desyncs :(
Again, thank you for all your help! 😄

Bug example:
img 1 (working fine, no bugs)
![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/4170799a-cda9-461d-9e32-4df2a5fb8c1d)

img 2 (real example)
![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/4c06ce49-d86e-4051-b9e2-12c213e3b685)

img 3 (how it should be)
![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/593f613f-b24b-4478-85d1-6b4ce237b7a9)


img 4 (desynced line counter and how it should be)
![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/047de4fe-5a1d-4269-8074-d4e0adeeb7c0)

**Comment by dipeshSam** [comment]
@lorenzolpandolfo It is really nice that your are developing a text editor, it's really interesting.
I saw, may I please know why the number series is started from a random number rather than serially?

**I'm working on the problem you've mentioned, when it will be completed, I'll post it. It is also nice that you've introduced a repository, I'll also look through that.** 

**Best regards. :)**

**Comment by lorenzolpandolfo** [comment]
> I saw, may I please know why the number series is started from a random number rather than serially?

The number series can be a little confuse in the first view, but they work in this way:
- In the selected line, the number will be the **absolute line number**.
So, if my text has 1000 lines and the cursor is selected in the last line, the number will be 1000.

The other numbers are the **relative distance between their lines and the selected line**
So, if the cursor is selected in the 51 line, the line above will show the number "1", as the line below, because that's their distance to the selected line.

example:
![image](https://github.com/TomSchimansky/CustomTkinter/assets/133379234/930fde25-80cf-4abd-bcdd-acc619a7a4e3)


> **I'm working on the problem you've mentioned, when it will be completed, I'll post it. It is also nice that you've introduced a repository, I'll also look through that.** 
> 
> **Best regards. :)**

Thank you man! Im glad that I met somebody as cool as you! 😃 
And nice Python skills! I will try to code like you do, because my code looks nooby comparing to yours, lol!
all the best and a happy 2024! :)

**Comment by dipeshSam** [comment]
> ...The other numbers are the **relative distance between their lines and the selected line** So, if the cursor is selected in the 51 line, the line above will show the number "1", as the line below, because that's their distance to the selected line.

@lorenzolpandolfo  **Okay brother, it's really nice what code logic you've planned about the series and other effective factors of the software. Really appreciable!**

> Thank you man! Im glad that I met somebody as cool as you! 😃
> And nice Python skills! I will try to code like you do, because my code looks nooby comparing to yours, lol!
> all the best and a happy 2024! :)

**You are most welcome brother. Yes, you are absolutely right, it's awesome meeting of both of us😊. In my opinion, code skills are way you consider it, more practice make you able to write more effective code, and everyone can get it. A very happy 2024😊.**

**The standard solution to the problem is found!**
There is always two ends (extremes) of a line (in case of single, consider both the ends as same), so what we need to know is their `y-position`. If the `y-position` of both the ends (end characters) are same, it implies that line is not wrapped and fix to the single one. And hence, if both the extremes (`y-positions`) are not same, the line is wrapped. And to calculate how many lines are wrapped, divide the difference of the ends (`y-positions`) by a constant i.e., height of the line. These two properties can be obtained using `bbox(index)` method of the text box. The `bbox` method returns value as tuple of [x, y, width, height].

**Here is complete updated class**
``` Python
from customtkinter import CTkTextbox, CTkFont
from string import printable
from tkinter import Event
from typing import Callable

class CTkEasyTextBox(CTkTextbox):
    """Updated to know a wrapping is done or not."""
    def __init__(self,
        master: any,
        width: int = 200,
        height: int = 200,
        corner_radius: int | None = None,
        border_width: int | None = None,
        border_spacing: int = 3,
        bg_color: str | tuple[str, str] = "transparent",
        fg_color: str | tuple[str, str] | None = None,
        border_color: str | tuple[str, str] | None = None,
        text_color: str | None = None,
        scrollbar_button_color: str | tuple[str, str] | None = None,
        scrollbar_button_hover_color: str | tuple[str, str] | None = None,
        font: tuple | CTkFont | None = None,
        activate_scrollbars: bool = True,
        wrap_callable: Callable[..., None] | None = None,
        **kwargs):

        super().__init__(master, width, height, corner_radius, border_width, border_spacing, bg_color, fg_color, border_color, text_color, scrollbar_button_color, scrollbar_button_hover_color, font, activate_scrollbars, **kwargs)

        # Line specific storage
        self._current_line: int = 1
        self._new_line_pos: list = []
        self._wrap_command: Callable = wrap_callable

        # Adding character validation by default
        self.bind("<Key>", self._handle_pressed_button)

    def _handle_pressed_button(self, event: Event):
        if len(event.char) == 0:           return

        char = event.char
        pos  = str(self.index("insert"))

        if char not in printable:
            if pos in self._new_line_pos:
                self._new_line_pos.remove(pos)
                self._current_line -= 1
            return
    
        # Detecting the enter key
        if ord(char) in (10, 13):
            self._current_line += 1
            self._new_line_pos.append(pos)
        
        else:
            self._on_live_entry()

    def _on_live_entry(self):
        def action():
            y_old    = self.bbox(first_index)[1]
            y_new    = self.bbox(last_index)[1]

            if y_new != y_old:
                if self._wrap_command:
                    diff = y_new - y_old
                    cons = self.bbox(last_index)[3]
                    self._wrap_command({"line": self._current_line, "wrapped_lines": int(diff/cons)})
            
        first_index = f"{self._current_line}.0"
        last_index = self.index("insert")

        self.after(2, lambda: action())

    def getLines(self) -> list[str]:
        """Returns list of all the lines."""
        return [line for line in self.get(0.0, "end").split("\n") if line != ""]
    
    def getLine(self, line_number: int) -> str:
        """Returns line at the given index."""
        # Checking whether `line_number` >= 1 or not.
        if line_number <=0: return ""

        # Defining indicating variables
        column: int = 0
        line: str   = ""
        char: str   = self.get(f"{line_number}.{column}")

        # Getting the full line.
        while char != "\n" and len(char) != 0:
            line   = line + char
            column = column + 1
            char   = self.get(f"{line_number}.{column}")
        return line
    
    def addNewline(self, line: str = ""):
        self.insert("end", line + "\n", tags=f"line{self._current_line}")
        self._current_line = self._current_line + 1

        # Updating the master to the current
        self.nametowidget(".").update()

    def getExtremes(self, line_number: int) -> (float, float):
        """Returns first and last characters' indeces."""
        # Checking whether `line_number` >= 1 or not.
        if line_number <=0: return ""

        # Defining indicating variables
        column: int = 0
        char: str   = self.get(f"{line_number}.{column}")

        first_index = float(f"{line_number}.{column}")

        # Getting the full line.
        while True:
            column = column + 1
            char   = self.get(f"{line_number}.{column}")
            if char == "\n" or len(char) == 0:
                last_index = float(f"{line_number}.{column-1}")
                return (first_index, last_index)
        
    def isWrapped(self, line_number: int):
        """Returns `False` if line is not wrapped else number of the wrapped lines."""
        if line_number <= 0: return False

        # Updating the master to the current
        self.nametowidget(".").update()

        first_index, last_index      = self.getExtremes(line_number)
        first_position, last_positon = self.bbox(first_index)[1], self.bbox(last_index)[1]

        if first_position == last_positon:
            return False
        else:
            difference = last_positon - first_position
            constant   = self.bbox(last_index)[3]         # Height of the line
            lines      = difference/constant 
            return int(lines)
```

Let the class is saved in a file named as `ctk_easy_textbox2.py` in current working directory then sample usage cases:
***Internal lines handling:***
```Python
from ctk_easy_textbox2 import CTkEasyTextBox
from customtkinter import CTk, CTkLabel, CTkFont

def on_configure(line_num: int):
    wrap = text_box.isWrapped(line_num)
    if wrap:
        label.configure(text=f"Line {line_num} is wrapped into {wrap} line(s).")
    else:
        label.configure(text=f"Line {line_num} is fit.")


if __name__ == "__main__":
    app = CTk()
    app.geometry("400x300")
    app.grid_columnconfigure(0, weight=1)
    app.minsize(width=200, height=300)

    text_box = CTkEasyTextBox(app, font=CTkFont(size=20))
    text_box.grid(sticky="ew", pady=25)

    label = CTkLabel(app, text=f"Wrappig message", font=CTkFont(size=20))
    label.grid(row=1)

    text_box.addNewline("Newton introduced gravity.")
    text_box.addNewline("No. Gravity was first found by his friend!")
    text_box.addNewline("No matter what it is. It is natural.")
    text_box.addNewline("But its study do!!!")

    observable_line = 2                      # <-- Will analise line "2".
    text_box.bind("<Configure>", lambda _: on_configure(observable_line))

    app.mainloop()
```
**Output video:**
https://github.com/TomSchimansky/CustomTkinter/assets/72375763/a0b0124d-86d7-4901-a6f5-44506058f059

***Typing lines handling:****
``` Python
from ctk_easy_textbox2 import CTkEasyTextBox
from customtkinter import CTk, CTkLabel, CTkFont

def on_configure(data: dict):
    label.configure(text=f"Line {data["line"]} is wrapped into {data["wrapped_lines"]} line(s).")

if __name__ == "__main__":
    app = CTk()
    app.geometry("400x300")
    app.grid_columnconfigure(0, weight=1)
    app.minsize(width=200, height=300)

    text_box = CTkEasyTextBox(app, font=CTkFont(size=20), wrap_callable=on_configure, wrap="word")
    text_box.grid(sticky="ew", pady=25)

    label = CTkLabel(app, text=f"Wrappig message", font=CTkFont(size=20))
    label.grid(row=1)

    app.mainloop()
```
**Output:**
*You can run the snippets, and can type long multiple infinite lines. It will work fine.*

***In the class code:***
- The solution is standard, so feel free to use it.
- Optimized to work in all scenarios.
- If you want to wrap at typing, provide `wrap_callable` function to the class argument that can accept a `dict` parameter.
- If you want to check line by line which are already written, simply use `isWrapped(line_number: int)` function.
- It may produce bug on removing single enter character and restoring the character again. To fix it, you can precisely locate the cursor position in `_handle_pressed_button()` method.
- All other functionalities are same.
- Introduced function to add line.
- Introduced function to get a line.
- Attention that `bbox` returns `None` if window size if too small. To fix it, make sure to set minimum size of the window.
- To dynamically check the wrapping, bind the `"<Configure>"` event and then check `isWrapped()` at each configuration.
- Works well, smoothly, and efficiently.

**Hope, it will be helpful for you. :)**

**Comment by dipeshSam** [comment]
> ...The other numbers are the **relative distance between their lines and the selected line**
> So, if the cursor is selected in the 51 line, the line above will show the number "1", as the line below, because that's their distance to the selected line.

@lorenzolpandolfo **Okay bother, it's really nice what code logic you've designed about the series and other effective factors of the software. Really appreciable.**



> Thank you man! Im glad that I met somebody as cool as you! 😃
> And nice Python skills! I will try to code like you do, because my code looks nooby comparing to yours, lol!
> all the best and a happy 2024! :)

**You are most welcome brother. Yes, you are absolutely right, it is awesome meeting of both of us😊. In my opinion, code skills are way you perceive it. More practice make you able to write more effective code. And, everyone can get it. A very happy 2024😊.**

**The standard solution to the problem, found!**
***Explanation of standard solution:***
There are always two ends (extremes) of a line (in case of a single character, consider both the ends as same), so what we need to know is their `y-position`. If the y-positions of both the ends (end characters) are same, it implies that the line is **not** wrapped and is fixed to the single line space. And hence, if both the extremes (y-positions) are not same, the **line is wrapped**. And, to calculate how many lines are wrapped, divide the difference of the ends (y-positions) by a constant number i.e., height of the line. These two properties (`y-position` and `height` of the line) can be obtained using a function `bbox(index)` provided by the `CTkTextbox`, and `tkinter`'s `Text` classes. The `bbox` method returns value as tuple of `(x, y, width, height)` taking `index` of the line as its argument.

**Here is completely refurbished and updated class:**
``` Python
from customtkinter import CTkTextbox, CTkFont
from tkinter import Event
from typing import Callable

# Standard Solution. Handles all interections well.

class CTkEasyTextBox(CTkTextbox):
    """Updated to know a wrapping is done or not."""
    def __init__(self,
        master: any,
        width: int = 200,
        height: int = 200,
        corner_radius: int | None = None,
        border_width: int | None = None,
        border_spacing: int = 3,
        bg_color: str | tuple[str, str] = "transparent",
        fg_color: str | tuple[str, str] | None = None,
        border_color: str | tuple[str, str] | None = None,
        text_color: str | None = None,
        scrollbar_button_color: str | tuple[str, str] | None = None,
        scrollbar_button_hover_color: str | tuple[str, str] | None = None,
        font: tuple | CTkFont | None = None,
        activate_scrollbars: bool = True,
        wrap_callable: Callable[..., None] | None = None,
        **kwargs):

        super().__init__(master, width, height, corner_radius, border_width, border_spacing, bg_color, fg_color, border_color, text_color, scrollbar_button_color, scrollbar_button_hover_color, font, activate_scrollbars, **kwargs)

        # Line specific storage
        self._current_line: int = 1
        self._wrap_command      = wrap_callable

        # Adding character validation by default
        self.bind("<Key>", lambda _: self._handle_pressed_button())

    def getCursoredExtremes(self) -> (str, str):
        first_index = self.index("insert linestart")
        last_index  = self.index(first_index + " lineend")

        return first_index, last_index
    
    def getCursoredLine(self) -> str:
        return self.index("insert").split(".")[0]

    def _handle_pressed_button(self) -> None:
        def check():
            wrap = self._isWrapped(*self.getCursoredExtremes())
            if wrap:
                self._wrap_command({"line": self.getCursoredLine(), "wrapped_lines": wrap})
            else:
                self._wrap_command({"line": self.getCursoredLine(), "wrapped_lines": 0})

        self.after(2, check)

    def getTotalLines(self) -> int:
        """Returns total number of lines in the text box in real time."""
        return self.get("1.0", "end").count("\n")

    def getLines(self) -> list[str]:
        """Returns list of all the lines."""
        return [line for line in self.get(1.0, "end").split("\n") if line != ""]
    
    def getLine(self, line_number: int) -> str:
        """Returns line at the given index."""

        # Checking whether `line_number` >= 1 or not.
        if line_number <=0: return ""

        # Getting line's extremes
        first_index = self.index(f"{line_number}.0 linestart")
        last_index  = self.index(first_index + " lineend")

        return self.get(first_index, last_index)
    
    def addNewline(self, line: str = ""):
        """Adds new line."""
        # Adding new line character (Enter) at the end of the line
        self.insert("end", line + "\n", tags=f"line{self._current_line}")
        self._current_line = self._current_line + 1

        # Updating the master to the current
        self.nametowidget(".").update()

    def getLineExtremes(self, line_number: int) -> (float, float):
        """Returns first and last character with of the line with indeces."""
        first_index = self.index(f"{line_number}.0 linestart")
        last_index  = self.index(first_index + " lineend")

        return first_index, last_index
    
    def _isWrapped(self, first_index: str, last_index: str):
        first_position, last_positon = self.bbox(first_index)[1], self.bbox(last_index)[1]
        if first_position == last_positon:
            return False
        else:
            difference = last_positon - first_position
            constant   = self.bbox(last_index)[3]         # Height of the line
            lines      = difference/constant 
            return int(lines)
        
    def isWrapped(self, line_number: int) -> bool | int:
        """Returns `False` if line is not wrapped else number of the wrapped lines."""
        if line_number <= 0: return False

        # Updating the master to the current
        self.nametowidget(".").update()

        # Getting the extremes of the line
        first_index, last_index = self.getLineExtremes(line_number)

        return self._isWrapped(first_index, last_index)

```
Let the class is saved in a file named as `ctk_easy_textbox.py` in the current working directory, then sample usage cases examples:
**Internal Handling:**
``` Python
from ctk_easy_textbox import CTkEasyTextBox
from customtkinter import CTk, CTkLabel, CTkFont

def on_configure(line_num: int):
    wrap = text_box.isWrapped(line_num)
    if wrap:
        label.configure(text=f"Line {line_num} is wrapped into {wrap} line(s).")
    else:
        label.configure(text=f"Line {line_num} is fit.")

if __name__ == "__main__":
    app = CTk()
    app.geometry("400x300")
    app.grid_columnconfigure(0, weight=1)
    app.minsize(width=200, height=300)

    text_box = CTkEasyTextBox(app, font=CTkFont(size=20))
    text_box.grid(sticky="ew", pady=25)

    label = CTkLabel(app, text=f"Wrappig message", font=CTkFont(size=20))
    label.grid(row=1)

    text_box.addNewline("Newton introduced gravity.")
    text_box.addNewline("No. Gravity was first found by his friend!")
    text_box.addNewline("No matter what it is. It is natural.")
    text_box.addNewline("But its study do!!!")

    observable_line = 2                      # <-- Will analise line "2".
    text_box.bind("<Configure>", lambda _: on_configure(observable_line))

    app.mainloop()
```
**Output:**

https://github.com/TomSchimansky/CustomTkinter/assets/72375763/34e2ad42-4d84-4c21-890f-59cf45b69ccb

**Typing Handling:**
``` Python
from ctk_easy_textbox import CTkEasyTextBox
from customtkinter import CTk, CTkLabel, CTkFont

def on_configure(data: dict):
    label.configure(text=f"Line {data["line"]} is wrapped into {data["wrapped_lines"]} line(s).")

if __name__ == "__main__":
    app = CTk()
    app.geometry("400x300")
    app.grid_columnconfigure(0, weight=1)
    app.minsize(width=200, height=300)

    text_box = CTkEasyTextBox(app, font=CTkFont(size=20), wrap_callable=on_configure, wrap="word")
    text_box.grid(sticky="ew", pady=25)

    label = CTkLabel(app, text=f"Wrappig message", font=CTkFont(size=20))
    label.grid(row=1)

    app.mainloop()
```
**Output:**

https://github.com/TomSchimansky/CustomTkinter/assets/72375763/7684136d-7a81-44d4-ab3b-5852d3e2fc0b

**In the codes:**
- It is the standard solution, so you can use it in all type projects.
- Optimized to work in all the scenarios including cut, paste, and cursor on different positions.
- The `wrap_callable` command will be triggered if the focused or cursored line will be wrapped, also on losing the wrapping.
- It is recommended to use class's own `addNewLine()` function to add new lines.
- If you want to know wrapping at typing, provide the `wrap_callable` function to the class argument that can accept a `dict` parameter.
- If you want to check line by line wrapping, use `isWrapped()` method at any time.
- Attention that `bbox` method returns `None` if window size is too small. To fix it, make sure to set minimum size of the window.
- To dynamically check the wrapping, bind `<"Configure">` event and use `isWrapped` method n line or lines.
- Other co-operative functions are introduced to work in ideal conditions, utilize them to work efficiently.
- Other functionalities of the text box are same.
- Works well, smoothly, and efficiently.

**Hope, it will be helpful for you.**

**Comment by lorenzolpandolfo** [comment]
@dipeshSam 
Thank you so much for all your help! With some time, I will try to make my system work perfectly, thanks to your help 😊.
There is any way we can keep in touch? If you use Discord, please add me! My tag is "lo#7557".

**Comment by dipeshSam** [comment]
@lorenzolpandolfo May I please know at what time did you scene this reply? Because a similar looking reply was also sent by me which was incorrect and I deleted that. I want you don't be confused with THIS and THAT version. This is the only correct version. I recommend to test it once.

**Comment by dipeshSam** [comment]
@lorenzolpandolfo **You are most welcome brother. We'll definitely be in the discord. :)**

**Comment by lorenzolpandolfo** [comment]
> @lorenzolpandolfo May I please know at what time did you scene this reply? Because a similar looking reply was also sent by me which was incorrect and I deleted that. I want you don't be confused with THIS and THAT version. This is the only correct version. I recommend to test it once.

I tested your new code yesterday at night and it worked fine, I just need to adjust it to mine and debug some things.
But today like at 9am or something, I recieved a new email about your answer and I thought it was a bug, because the answer was similar to the yesterday's, but you updated it, right?
I will test it today again 😁

**Comment by dipeshSam** [comment]
@lorenzolpandolfo Yes, exactly! **I just updated this code 2 hours ago.**

The code you tested yesterday was completely different and full of bugs. I've deleted that code reply.

Please test this new version, this is 100% correct, and accurate code with no related bugs.

Again, please test this new version updated or sent just 2 hours ago.

**Comment by lorenzolpandolfo** [comment]
@dipeshSam No problem! I will test it today and then I reply you.
You wrote it super fast and it covers a lot of complex logic, this is really impressing!

**Comment by dipeshSam** [comment]
@lorenzolpandolfo Yeah. The deleted yesterday was complex one😅. This is today's I think way easier than that one.

**I sent you a request on discord.**

What do you think GitHub should have an option to chat good ones or should we create a simple chatting application using customtkinter?😅

**Comment by lorenzolpandolfo** [comment]
@dipeshSam haha let's do this!! 😎

**Comment by Anonymous6598** [comment]
@dipeshSam, you are the best! Your code is magnificent!

**Comment by dipeshSam** [comment]
@Anonymous6598 **Thank you so much, brother. :)**
