### ISSUE TITLE
Filedialog by tkinter is kinda ugly 

### ISSUE THREAD

**Issue by NotJuba** [TomSchimansky/CustomTkinter#2188]
I want to create something that looks pleasing on CustomTkinter 
Can anyone provide me with guidance on where to start or what to do please?

**Comment by Akascape** [comment]
Yeah, the filedialog looks ugly for linux distros like ubuntu. In mac and windows, the modern filedialog opens up which is fine. 

An alternative solution is to use [TkFilebrowser](https://github.com/j4321/tkFileBrowser) package which have some custom file dialogs. 

https://user-images.githubusercontent.com/89206401/242241123-5796e3cf-5246-42a9-b606-99485bdfd979.png

More awesome tkinter/ctk packages can be found here: https://github.com/Akascape/tkinter-toolkit

**Comment by Akascape** [comment]
@NotJuba

**Comment by NotJuba** [comment]
Thank you bro
