### ISSUE TITLE
Message Boxes

### ISSUE THREAD

**Issue by nerd-man** [TomSchimansky/CustomTkinter#219]
Are there message boxes like showinfo or show error?

**Comment by SiddyG8** [comment]
No unfortunately, you will have to use the default tkinter messageboxes or create your own.

**Comment by felipetesc** [comment]
> Are there message boxes like showinfo or show error?

I have used tk tooltip, you can find more about this here : https://pypi.org/project/tkinter-tooltip/2.1.0/
