### ISSUE TITLE
Scrollbar does not reset when the contents of CTkScrollableFrame are emptied.

### ISSUE THREAD

**Issue by calucita** [TomSchimansky/CustomTkinter#2192]
Say for example you have some labels in the CTkScrollableFrame  and then delete it all with label.destroy() (similar to: https://github.com/TomSchimansky/CustomTkinter/issues/1965)

All the contents are deleted, but the scroll bar is left exactly in the same position as it was before meaning, if it was possible to scroll and the user had scrolled all the way down, upon deleting all the contents of the scrollableframe, the list is empty, but still scrolled.

![image](https://github.com/TomSchimansky/CustomTkinter/assets/1617370/e76b763f-1c79-4c56-9af8-5722acbe100c)

Is there a way to force the scroll bar to reset? I tried my best to look at the other community questions, but couldn't find any hints. 

thanks!

**Comment by dipeshSam** [comment]
You try following:
- Update the master after deletion (`.destroy()` is recommended).
- Use `CTkScrollableFrame._y_scrollbar.move_to("1.0")` to manually reset the position.

If these won't work, sharing code snippets may help to answer better.

**Comment by calucita** [comment]
> * ._y_scrollbar.move_to(fraction)

you mean like `self._parent_canvas.yview_moveto(0.0)` ? similar to https://github.com/TomSchimansky/CustomTkinter/issues/1982 ?

That gets the scroll up, but it still shows as if there were more content to scroll. 

I have tried calling update everywhere where I thought could make sense :( 

```
class ScrollableLabelFrame(customtkinter.CTkScrollableFrame):
    def __init__(self, master, **kwargs):
        super().__init__(master, **kwargs)
        self.grid_columnconfigure(0, weight=1)
        self.label_list = []

    def add_item(self, item):
        label = customtkinter.CTkLabel(self, text=item, compound="left", padx=5, anchor="w")
        label.grid(row=len(self.label_list), column=0, pady=(0, 10), sticky="w")
        self.label_list.append(label)

    def remove_item(self, item):
        for label, button in zip(self.label_list, self.button_list):
            if item == label.cget("text"):
                label.destroy()
                self.label_list.remove(label)
                return 

    def deleteAll(self):
        while self.label_list:
            label = self.label_list.pop()
            label.destroy()
        self._parent_canvas.yview_moveto(0.0)
        self.update()

```

**Comment by dipeshSam** [comment]
Got it. I'm working on it, I'll post further edits here.

**Comment by dipeshSam** [comment]
Solved!

**Comment by calucita** [comment]
Got a workaround :D 


```
    def deleteAll(self):
        while self.label_list:
            label = self.label_list.pop()
            label.destroy()
            self._parent_canvas.yview_moveto(0.0)
            self.update()
```

i was doing the yview and update outside the while loop... because that made sense... but doing it in the while loop fixes the issue... sooo..

**Comment by dipeshSam** [comment]
Update your function:

def deleteAll(self):
        while self.label_list:
            label = self.label_list.pop()
            label.destroy()
            self.update()
     

Basically, we need to update the frame at every deletion we make.

**Comment by calucita** [comment]
brilliant @dipeshSam  :) thanks for the help
