### ISSUE TITLE
Removing All Widgets.

### ISSUE THREAD

**Issue by VSPuzzler** [TomSchimansky/CustomTkinter#22]
For regular tkinter, you can remove all the widgets using:
    for widget in root.winfo_children():
        widget.destroy()

This doesn't work in customtkinter. Does anyone know if there is an alternative way to do this?

**Comment by VSPuzzler** [comment]
My code is:
def GUI():
    customtkinter.set_appearance_mode("Dark")
    frame1 = customtkinter.CTkFrame(master=root, width=585, height=385, corner_radius=15)
    frame1.place(x=10,y=10)
    customtkinter.CTkLabel(master=frame1,
                           text="Token Finder",
                           width=120,
                           height=25,
                           corner_radius=8).place(x=250, y=25)
    customtkinter.CTkButton(master=frame1,text = "Discord Token", command=discord_token_displayer).place(x=250, y=80)
    customtkinter.CTkButton(master=frame1, text="Minecraft Token", command=discord_token_displayer).place(x=245, y=130)
    customtkinter.CTkButton(master=frame1, text="Wifi Password", command=wifi_password_display).place(x=250, y=180)
    root.mainloop()
def discord_token_displayer():
    for widget in root.winfo_children():
        widget.destroy()
    customtkinter.set_appearance_mode("Dark")
    frame1 = customtkinter.CTkFrame(master=root, width=585, height=385, corner_radius=15)
    frame1.place(x=10,y=10)
    customtkinter.CTkLabel(master=frame1,
                           text="Token Finder",
                           width=120,
                           height=25,
                           corner_radius=8).place(x=250, y=25)
    customtkinter.CTkButton(master=frame1,text = "Discord Token", command=discord_token_displayer).place(x=250, y=80)
    customtkinter.CTkButton(master=frame1, text="Minecraft Token", command=discord_token_displayer).place(x=245, y=130)
    customtkinter.CTkButton(master=frame1, text="Wifi Password", command=wifi_password_display).place(x=250, y=180)
    customtkinter.CTkLabel(master=frame1,
                           text="Yout token is:",
                           width=120,
                           height=25,
                           corner_radius=8).place(x=250, y=170)
    root.mainloop()

**Comment by TomSchimansky** [comment]
For me this is working, I can delete a single widget by calling .destroy() on it or delete all widgets by looping through all children of root. Maybe you can post the error message you get or a complete code example.

**Comment by VSPuzzler** [comment]
![image](https://user-images.githubusercontent.com/79369814/147857415-84b908e1-be5c-4b3d-8522-1ea46546f418.png)

**Comment by TomSchimansky** [comment]
Thanks for mentioning this, it was a bug, I never thought about deleting widgets before, but now its fixed. (not updated on pip yet)

**Comment by TomSchimansky** [comment]
It's now updated on pip: `pip install customtkinter --upgrade`

**Comment by VSPuzzler** [comment]
Thanks!
