### ISSUE TITLE
Pack children doesn't count parent height

### ISSUE THREAD

**Issue by P3rdigas** [TomSchimansky/CustomTkinter#2200]
Hi, i was creating an app i ran into an issue while packaging my frames. I created a simple example where this issue occur.

### Code
```python
import customtkinter


class AutoContract(customtkinter.CTk):
    APP_WIDTH = 800
    APP_HEIGHT = 600

    TEMPLATE_FRAME_HEIGHT = 75
    DESTINATION_FRAME_HEIGHT = 75

    SEPARATOR_COLOR_LIGHT = "grey90"
    SEPARATOR_COLOR_DARK = "black"

    def __init__(self):
        super().__init__()

        # Configure window
        self.geometry(f"{self.APP_WIDTH}x{self.APP_HEIGHT}")
        self.resizable(width=False, height=False)

        # Layout (Template Frame(100px), Data Frame(what's left), Destination Frame(100px))
        # Template Frame
        template_frame = customtkinter.CTkFrame(
            self, height=self.TEMPLATE_FRAME_HEIGHT, corner_radius=0, fg_color="red"
        )

        # Data Frame
        data_frame = customtkinter.CTkFrame(self, corner_radius=0, fg_color="yellow")

        # Destination Frame
        destination_frame = customtkinter.CTkFrame(
            self,
            height=self.DESTINATION_FRAME_HEIGHT,
            corner_radius=0,
            fg_color="green",
        )

        destination_label_frame = customtkinter.CTkFrame(
            destination_frame,
            corner_radius=0,
            fg_color="red",
        )

        # Template Layout
        template_frame.pack(fill="x")

        # Data Layout
        data_frame.pack(expand=True, fill="both")

        # Destination Layout
        destination_label_frame.pack(expand=False)
        destination_frame.pack(fill="x")


def main():
    app = AutoContract()
    app.mainloop()


if __name__ == "__main__":
    main()
```

### Result
![image](https://github.com/TomSchimansky/CustomTkinter/assets/91698253/c0ee5748-2d6b-4446-a2eb-0287488fdc40)

### Issue
The top frame (template_frame) and bottom frame (destination_frame) should have a fixed size, being 75px and the middle frame (data_frame) having the rest of the space available. However, when i pack the frame inside the bottom frame (destination_label_frame), it increases the height of the parent frame (destination_frame), despite not having expand=True. 

Anyone knows how to solve this issue? I want to had two frames that are childs of the bottom frame, and when i do that the bottom frame increases it size to almost half of the app height.

When i don't had any frame as a child of the bottom frame i get the result i want, being:

![image](https://github.com/TomSchimansky/CustomTkinter/assets/91698253/14479d74-84b8-467f-92f3-ca250165eb10)

**Comment by ElectricCandlelight** [comment]
CTkFrame has a default height and width of 200.

'``Python 
destination_label_frame = customtkinter.CTkFrame(
destination_frame, height=self.DESTINATION_FRAME_HEIGHT, corner_radius=0, fg_color="red",)
```

That should fix it.

**Comment by P3rdigas** [comment]
Thanks for the reply. So if i wanted to had 2 frames inside of one (that has 100px height)  i must set an height for that 2 frames, right? Mean while, i found a solution that uses place() with relheight!
