### ISSUE TITLE
When I was trying to run my customtkinter script an errore occured

### ISSUE THREAD

**Issue by cclowny** [TomSchimansky/CustomTkinter#221]

**Comment by cclowny** [comment]
this is the error: : "Traceback (most recent call last):   File "Jumper.py", line 5, in <module>   File "C:\Users\Clowny\output\Jumper\customtkinter\__init__.py", line 10, in <module>     from .appearance_mode_tracker import AppearanceModeTracker   File "C:\Users\Clowny\output\Jumper\customtkinter\appearance_mode_tracker.py", line 3, in <module>     from distutils.version import StrictVersion as Version ModuleNotFoundError: No module named 'distutils'"

how can I fix it?

**Comment by felipetesc** [comment]
What ctk version are you using ? 
Can you update ctk ?
What Python version do you have ? 
Do you have at least Python 3.8 ?
What OS version (Win 10, or 11) ?
Do you have the default Python library ?
Did you change ctk source ?
What were you doing when it happened (you cold not even start your app, I suppose) ?


**_No module named 'distutils_** it's a import error

**Comment by cclowny** [comment]
I have python 3.10
i'm using windows 10
how can I update customtkinter?
I do have the default python library
Btw I fixed it lol

**Comment by cclowny** [comment]
just another question: can I set an icon using ctk?
now I tried with `window.iconbitmap("path to the icon")` but I can't see the icon when I run the program

**Comment by felipetesc** [comment]
> just another question: can I set an icon using ctk? now I tried with `window.iconbitmap("path to the icon")` but I can't see the icon when I run the program

Note the answer to your question, but it may help, who knows ?
Right now I'm using this package, at https://pypi.org/project/tkfontawesome/ and it seems nice to me
