### ISSUE TITLE
titlebar color change when using transient() on CTkToplevel window

### ISSUE THREAD

**Issue by LaserLisa** [TomSchimansky/CustomTkinter#2213]
I encounterd the following issue when using a Toplevelwindow with customtkinter using the following code:
```python
import customtkinter as ctk


class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.geometry("400x400")
        self.label_name = ctk.CTkLabel(self, text="main window", font=("Arial", 15, "bold"))

        self.button_open = ctk.CTkButton(self, text="open", command=self.open_window)

        self.label_name.pack()
        self.button_open.pack()

    def open_window(self):
        new_window = ctk.CTkToplevel(self)
        new_window.title("new window")
        new_window.geometry(f"200x200+{self.winfo_x()}+{self.winfo_y()}")
        label_name = ctk.CTkLabel(new_window, text="new window", font=("Arial", 15, "bold"))
        label_name.pack()
        # new_window.transient(self)


if __name__ == "__main__":
    app = App()
    app.mainloop()
```
Here everything works fine despite that the Toplevelwindow does appear beneath the main window. So I tried to use 
```python
new_window.transient(self)
```
to display the window on top of the parent root window. When using the transient function though the window title bar changed from dark mode into light mode.  
without the transient() function:

https://github.com/TomSchimansky/CustomTkinter/assets/126000198/91a6c0ee-5162-4dd2-9096-d1bba70a7a3a

with the transient() function:

https://github.com/TomSchimansky/CustomTkinter/assets/126000198/8862c6d6-57a2-40dc-a64e-4e06701216b2

Any ideas how to fix this?
Thanks in Advance!

**Comment by Akascape** [comment]
@LaserLisa Add `new_window.resizable(True, True)` before using transient.

**Comment by LaserLisa** [comment]
> @LaserLisa Add `new_window.resizable(True, True)` before using transient.

Oh that works nice, thanks! I have not thought of trying this as they should in my eyes not be connected. But it works fine now so anyways thanks a lot! @Akascape
