### ISSUE TITLE
Request: CTkPasswordEntry

### ISSUE THREAD

**Issue by Bartek20** [TomSchimansky/CustomTkinter#222]
Would you be able to create the **CTkPasswordEntry** widget?
Just like **CTkEntry**, but instead of text there will be '*' characters.
*It would be nice if it had hide/reveal the password button.*

**Comment by cclowny** [comment]
just add `show="*` in the pack section

**Comment by Bartek20** [comment]
good to know that you can also use arguments from the original tkinter, I did not pay attention to it, but if it was possible, such an element with a hide/reveal button strictly for passwords would be a good idea

**Comment by TomSchimansky** [comment]
I think this is a but specific, but you can build it easily by yourself, for example like this:
```python
import customtkinter

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("blue")

app = customtkinter.CTk()
app.geometry("400x240")
app.grid_columnconfigure((0, 1), weight=1)

def hide_show_passwd():
    if hide_show_switch.get() == 0:
        passwd_entry.configure(show="")
    else:
        passwd_entry.configure(show="•")

passwd_entry = customtkinter.CTkEntry(app, placeholder_text="Password")
passwd_entry.grid(row=0, column=0, pady=20, padx=0)

hide_show_switch = customtkinter.CTkSwitch(app, text="Hide", command=hide_show_passwd)
hide_show_switch.grid(row=0, column=1, pady=20, padx=0)
hide_show_switch.select()

app.mainloop()
```
Note that I fixed a bug in CTkEntry with the placeholder so this will only work properly with version 4.5.2 or higher.
