### ISSUE TITLE
Cannot destroy scrollable frame with .destroy()

### ISSUE THREAD

**Issue by Cashcoow** [TomSchimansky/CustomTkinter#2228]
whenever I try and do frame.destroy() on a frame that's a scrollable frame it only destroys the widgets inside the scrollable frame and not the entire frame, is there a way to destroy scrollable frames that's different to frames?

**Comment by Anonymous6598** [comment]
Try using this:
```python
place_forget()
```

**Comment by Cashcoow** [comment]
I tried frame.place_Forget() but it didn't do anything the widgets and frame were still there, when I try frame.destroy it only destroys the widgets and not the frame: 
<img width="796" alt="Screenshot 2024-01-24 at 10 06 02" src="https://github.com/TomSchimansky/CustomTkinter/assets/157479592/a449c135-45e8-46ac-938a-735659fa879c">

**Comment by Anonymous6598** [comment]
Show full code please

**Comment by Anonymous6598** [comment]
Try using this:
```python
frame.pack_forget()
````

**Comment by Cashcoow** [comment]
Thank you bro this worked, kinda weird though you have to use a different function to specially delete scrollable frames

**Comment by Anonymous6598** [comment]
You forgot to mark it as an answer.
