### ISSUE TITLE
Customtkinter GUI INTERFACE lagging

### ISSUE THREAD

**Issue by Jubaarte** [TomSchimansky/CustomTkinter#2237]
Hi there, i have an app wrote in python using customtkinter library. On this app, when i execute a function that updates some label it makes the interface freeze til the function is completed, like it is not respondig.

An example:

def something():
   label.configure(text="Be welcome!")

This function makes the app freeze for 3 sec.

Can somebody help me?

**Comment by Akascape** [comment]
@Jubaarte If the function have some internal processes, then the ui will lag for sure.
Better use threading in the functions.

**Comment by Jubaarte** [comment]
Here is the full function of that the button executes, what do u think?

def aconselharbutton():
    App.aconselhar(App)
    textoconselho.configure(text=App.conselhoptbr)


    def aconselhar(self):
        tradutor = GoogleTranslator(source= "en", target= "pt")
        info = requests.get("https://api.adviceslip.com/advice")
        info = info.json()
        conselho = info["slip"]["advice"]
        print(conselho)
        self.conselhoptbr = tradutor.translate(conselho)
        print (self.conselhoptbr)

**Comment by Akascape** [comment]
@Jubaarte try threading.Thread method while calling the function

**Comment by Jubaarte** [comment]
Amazing!!!
I used a "Thread(target=xxx).start() for each function and it worked, no more lag. 
Thank you so much for the help, i am a newbie.

**Comment by Akascape** [comment]
@Jubaarte you can close this issue...
