### ISSUE TITLE
CTkEntry configure placeholder_text

### ISSUE THREAD

**Issue by Dotolox** [TomSchimansky/CustomTkinter#224]
Hi,
when I define an entry:
`entry_1 = customtkinter.CTkEntry(master=window, placeholder_text="first text", width=425, height=40)
entry_1.place(
    x=190.0,
    y=150.0
)`

and I try to change its `placeholder_text` by doing:
`entry_1.configure(placeholder_text="second text")`

I get this error message:
`_tkinter.TclError: unknown option "-placeholder_text"`

**Comment by TomSchimansky** [comment]
Hi, configuring the placeholder_text is not implemented, I will do it with the next version.

**Comment by TomSchimansky** [comment]
Configuring the placeholder_text now works with version 4.5.2.

**Comment by Free-Radical** [comment]
Was trying to figure out same as above, great job, Thanks, just started using your module and loving it!
