### ISSUE TITLE
Not able to understand how to clear a text box in custom tkinter

### ISSUE THREAD

**Issue by Himanshu700296** [TomSchimansky/CustomTkinter#225]
I just tried to use the CTktextbox and as compared to Text widgit in tkinter, i am not able to clear the textbox, so can you kindly let me know how to clear a textbox created by CTkTextbox

**Comment by TomSchimansky** [comment]
The CTkTextBox is currently in development and not yet supported, many things are missing. It will be ready in the next minor version 4.6.0.
