### ISSUE TITLE
How to set the background color of customtkinter.CTkCheckBox

### ISSUE THREAD

**Issue by orztrickster** [TomSchimansky/CustomTkinter#2280]
How to set the background color of customtkinter.CTkCheckBox?
You can see that there is a darker area behind "test".
![1708709594521](https://github.com/TomSchimansky/CustomTkinter/assets/39370279/b47086ab-68f0-47a0-8357-39906d57b0c3)
`checkbox = customtkinter.CTkCheckBox(frame[3], text="test", command=checkbox_event_1,
                                         variable=check_var_1, onvalue="on", offvalue="off")`

**Comment by Anonymous6598** [comment]
Just use
```python
bg_color = "green" #enter color
```

**Comment by orztrickster** [comment]
That's the same, just changes the color of the selection.
![1708869495241](https://github.com/TomSchimansky/CustomTkinter/assets/39370279/49e0b0a2-de20-4423-91c5-6e728949ac2a)
![1708869510341](https://github.com/TomSchimansky/CustomTkinter/assets/39370279/ebbbf8ef-9191-46ec-891f-622c2caeae43)

**Comment by orztrickster** [comment]
> That's the same, just changes the color of the selection. ![1708869495241](https://private-user-images.githubusercontent.com/39370279/307596485-49e0b0a2-de20-4423-91c5-6e728949ac2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Njk4NzUsIm5iZiI6MTcwODg2OTU3NSwicGF0aCI6Ii8zOTM3MDI3OS8zMDc1OTY0ODUtNDllMGIwYTItZGUyMC00NDIzLTkxYzUtNmU3Mjg5NDlhYzJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEzNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYTdkZDFhYTlkNDE5ZjEzYjk5NGM1YmZhMjA1ZWRlNGVhYjY0ZGMyNTZjNWMyZmIyZDkzMTIxZjdjMDlkMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TzlnV7pM8J5BzwFnUfAlKebD3uQjeYvg5pRf3sSnEKg) ![1708869510341](https://private-user-images.githubusercontent.com/39370279/307596490-ebbbf8ef-9191-46ec-891f-622c2caeae43.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Njk4NzUsIm5iZiI6MTcwODg2OTU3NSwicGF0aCI6Ii8zOTM3MDI3OS8zMDc1OTY0OTAtZWJiYmY4ZWYtOTE5MS00NmVjLTg5MWYtNjIyYzJjYWVhZTQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDEzNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjYzYmNkODc5NGQxMzE5MWJhOWIzMTg1MTEzNjYwMGQ3M2U2OTJlMjdjYzgwZjMwODFjYmQzMjRlY2VkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5Nl7b2Uz0wUXrMCuIckRfZyh5otiJ7ms16BMgYXFm0)
`    checkbox = customtkinter.CTkCheckBox(frame[3], text="test", command=checkbox_event_1, variable=check_var_1, onvalue="on", offvalue="off",fg_color = "green")
    checkbox.grid(row=0, column=0, padx=(550,5), pady=(0,30))`

**Comment by Anonymous6598** [comment]
try this:
```python
bg_color = "green" #enter color
```

**Comment by Anonymous6598** [comment]
```python
checkbox = customtkinter.CTkCheckBox(frame[3], text="test", command=checkbox_event_1, variable=check_var_1, onvalue="on", offvalue="off", bg_color = "green")
```

**Comment by orztrickster** [comment]
Thank you, this works. Setting bg_color = "#2b2b2b" will make it the same as the background.
![1708870312719](https://github.com/TomSchimansky/CustomTkinter/assets/39370279/103035d1-de09-4860-ab89-e72f249c94c6)
`checkbox = customtkinter.CTkCheckBox(frame[3], text="test", command=checkbox_event_1, variable=check_var_1, onvalue="on", offvalue="off", bg_color = "green")`
![1708870364402](https://github.com/TomSchimansky/CustomTkinter/assets/39370279/194ba8b5-5261-40b4-990f-07461edcbfd3)
`checkbox = customtkinter.CTkCheckBox(frame[3], text="test", command=checkbox_event_1, variable=check_var_1, onvalue="on", offvalue="off", bg_color = "#2b2b2b")`
