### ISSUE TITLE
Why widgets appearance are different??? 

### ISSUE THREAD

**Issue by fronos** [TomSchimansky/CustomTkinter#2286]
I've tested samples from this repo under Windows and it's looks pretty and under Ubuntu. The results under Ubuntu are awful. It looks like UI broken or some settings doesn't work
![image](https://github.com/TomSchimansky/CustomTkinter/assets/37273805/0cc5e940-2866-437c-a4bd-1458180b7569)

**Comment by JanPanthera** [comment]
maybe a scaling issue?  I don't know if it has something to do with it,  but you can try to disable scaling, since its not official supported on linux i think. 
https://customtkinter.tomschimansky.com/documentation/scaling/

**Comment by fronos** [comment]
Thank you for help

**Comment by fronos** [comment]
I found similar issue https://github.com/TomSchimansky/CustomTkinter/issues/1358 
This issue was solved by using python venv instead conda environment.
