### ISSUE TITLE
Getting the following error when using multiple frame design when ever clicking any entry widgit

### ISSUE THREAD

**Issue by Himanshu700296** [TomSchimansky/CustomTkinter#229]
E:\Python\graph\venv\Scripts\python.exe E:/Python/graph/kkkk.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mayru\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\Python\graph\venv\lib\site-packages\customtkinter\widgets\ctk_entry.py", line 215, in entry_focus_out
    self.set_placeholder()
  File "E:\Python\graph\venv\lib\site-packages\customtkinter\widgets\ctk_entry.py", line 204, in set_placeholder
    self.entry.insert(0, self.placeholder_text)
  File "C:\Users\mayru\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 3056, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".!ctkframe.!ctkframe3.!ctkentry3.!entry insert index text"

**Comment by felipetesc** [comment]
Do you have a  sample code for us ?

**Comment by Himanshu700296** [comment]
I can tell you.....i used a main_cointener frame as main frame in which i have multiple frames, i added entry widget in all the frames, when ever i move from one frame to another using button click

**Comment by Himanshu700296** [comment]
I can also attach the whole code but the code is very big to add here so i jst descried the issue

**Comment by felipetesc** [comment]
> I can tell you.....i used a main_cointener frame as main frame in which i have multiple frames, i added entry widget in all the frames, when ever i move from one frame to another using button click, after moving from one frame to another and clicking on any entry, this is the error i am getting that i mentioned.

check this code : https://felipetesc.github.io/CtkDocs/#/multiple_frames

**Comment by TomSchimansky** [comment]
I think it's the same problem as https://github.com/TomSchimansky/CustomTkinter/issues/232, it's probably a bug.

**Comment by felipetesc** [comment]
It would be nice to have your code, or the related part to the issue, so, we can try figure what's happening. Thanks.

**Comment by Himanshu700296** [comment]
the problem is that with the code you wont understand anything.......i can tell you.....so i have a multiframe project where i have added a main_container which has a left side frame in it and a right side frame in it.....the right side has different frame on button click.....i have added two entry widgit using ctkentry in both the right frame......so when ever i click  button in left frame and then clcik any entry widgit on the right frame the error is shown

**Comment by TomSchimansky** [comment]
Should be fixed with version 4.5.4

**Comment by TomSchimansky** [comment]
version 4.5.4 is already on pip
