### ISSUE TITLE
How to auto scroll textbox?

### ISSUE THREAD

**Issue by AdroitBit** [TomSchimansky/CustomTkinter#2303]
I'm working on a project where I'm creating serial monitor while also beable to do other tasks
The serial data from USB device will be updated to textbox https://customtkinter.tomschimansky.com/documentation/widgets/textbox

So I'm wondering how to autoscroll textbox just to mimic like Serial monitor in arduino ide
![image](https://github.com/TomSchimansky/CustomTkinter/assets/46592105/3cff0e89-ff08-4315-8148-41633701a4c4)

**Comment by FaheemM1020** [comment]
This might help 
https://stackoverflow.com/questions/30669015/autoscroll-of-text-and-scrollbar-in-python-text-box

**Comment by AdroitBit** [comment]
So it's just .see("end")
Thank you very much
