### ISSUE TITLE
Is it possible to embed a website in a scrollable frame

### ISSUE THREAD

**Issue by KorryKatti** [TomSchimansky/CustomTkinter#2306]
Specifically, I'm interested in integrating web browser controls within the CustomTkinter framework to display web content directly within the application's GUI. This could be particularly useful for applications that need to present dynamic or interactive web content alongside other GUI elements.

Could you please provide some insight into whether CustomTkinter has built-in support for embedding webpages, or if there are any recommended approaches for achieving this functionality using CustomTkinter?

**Comment by Akascape** [comment]
@KorryKatti 
There is a tkinter widget for HTML view called [tkinterweb](https://pypi.org/project/tkinterweb/) which you can implement in the scrollable frame and it will display the webpage, but it doesn't render all the components properly. See this examplte: #1423

I recommend using `webbrowser.open_new_tab("url")` method which simply opens the url in the default web browser of the system. There is also a separate package called `pywebview` which acts like a browser but it is a totally separate window and has no link with tkinter/ctk.

**Comment by KorryKatti** [comment]
I see, thank you i will try and close this issue in about 2 days , please let it remain open for that time

**Comment by KorryKatti** [comment]
I used tkinter ( the original module ) . Thanks
