### ISSUE TITLE
CTkSegmentedButton has no attribute checkbox_width or checkbox_height

### ISSUE THREAD

**Issue by SamerKharabish** [TomSchimansky/CustomTkinter#2317]
CTkCheckBox has no attribute checkbox_width or checkbox_height as shown in the documentation of the official website.

**Comment by PhilipNelson5** [comment]
I don't see `checkbox_width` or `checkbox_height` on https://customtkinter.tomschimansky.com/documentation/widgets/segmentedbutton like you are describing.

**Comment by SamerKharabish** [comment]
> I don't see `checkbox_width` or `checkbox_height` on https://customtkinter.tomschimansky.com/documentation/widgets/segmentedbutton like you are describing.

Your are totally right. I meant CTkCheckBox. I edited my post.

**Comment by PhilipNelson5** [comment]
They are right here:
 - `checkbox_width`: [ctk_checkbox.py:22](https://github.com/TomSchimansky/CustomTkinter/blame/b9b57d95c7d3bb821a2260527315b6079161f5c9/customtkinter/windows/widgets/ctk_checkbox.py#L22)
 - `checkbox_height`: [ctk_checkbox.py:23](https://github.com/TomSchimansky/CustomTkinter/blame/b9b57d95c7d3bb821a2260527315b6079161f5c9/customtkinter/windows/widgets/ctk_checkbox.py#L23)

**Comment by SamerKharabish** [comment]
I'm very confused. I think i mixed up the widgets. 
Thank you for the help!
