### ISSUE TITLE
Website Guide Error

### ISSUE THREAD

**Issue by Ezriral** [TomSchimansky/CustomTkinter#2318]
![image](https://github.com/TomSchimansky/CustomTkinter/assets/56836301/22d85ef7-f090-490c-a74a-e92c6535074e)

Bottom of the page. https://customtkinter.tomschimansky.com/tutorial/scrollable-frames

**Comment by its-joseph-230606** [comment]
I agree with that

**Comment by TomSchimansky** [comment]
fixed
