### ISSUE TITLE
Frame inside frame

### ISSUE THREAD

**Issue by KorryKatti** [TomSchimansky/CustomTkinter#2319]
I have a scrollable frame , i would like to create a non scrollable frame inside it , which will be on the right side of a button placed on the left side of the scrollable frame. How do i achieve this.

or in simpler words

I need to put a small frame next to a button inside a bigger frame that can scroll. How do I do that?

**Comment by KorryKatti** [comment]
![OnPaste 20240321-083308](https://github.com/TomSchimansky/CustomTkinter/assets/143781663/327560d4-6a3e-4496-b3ee-13774173904d)


i would like to place a frame inside the red border area

**Comment by FaheemM1020** [comment]
Here it is:
```
import customtkinter 

root = customtkinter.CTk()

scrollable_frame = customtkinter.CTkScrollableFrame(root)
scrollable_frame.pack(padx=10,pady=10)

frame = customtkinter.CTkFrame(scrollable_frame,fg_color='grey55',bg_color='grey55')
frame.pack(padx=10,pady=10)

root.mainloop()

```

**Comment by KorryKatti** [comment]
sounds to good to be true , will check and tell

**Comment by KorryKatti** [comment]
It actually worked. Man what was i even doing last time. Thanks @FaheemM1020 , closing this issue
