### ISSUE TITLE
Error when using .delete() on CTkEntry

### ISSUE THREAD

**Issue by AidenRaaphorst** [TomSchimansky/CustomTkinter#232]
Using `entry.delete(0, tkinter.END)` gives this error:
```_tkinter.TclError: wrong # args: should be ".!notebook.!ctkframe.!ctkentry.!entry insert index text"```

Using `entry.delete(0, customtkinter.END)` gives the same error

**Comment by TomSchimansky** [comment]
Should be fixed with version 4.5.4
