### ISSUE TITLE
AttributeError: module 'customtkinter' has no attribute 'CTk'

### ISSUE THREAD

**Issue by T011235** [TomSchimansky/CustomTkinter#2320]
Hi, I tried 3 of your examples and always got an error regarding CTk and set_default_color_theme("blue").
Im using VS Code, Python 3.11.6 and customtkinter 5.2.2.

customtkinter.set_default_color_theme("blue")  # Themes: blue (default), dark-blue, green
AttributeError: module 'customtkinter' has no attribute 'set_default_color_theme'

app = customtkinter.CTk()  # create CTk window like you do with the Tk window
AttributeError: module 'customtkinter' has no attribute 'CTk'

**Comment by Akascape** [comment]
@T011235 Did you renamed some file as customtkinter.py?

**Comment by T011235** [comment]
No, I haven't renamed any File. I created a new file with the name test.py. Which Python version do you use?

**Comment by Akascape** [comment]
@T011235 I use multiple python versions like 3.9, 3.10, 3.11 ..  and no issue like this appears if you have properly installed customtkinter.

Recheck if there is any folder or file named as customtkinter. 

Reinstall customtkinter, check the install location manually in python3.11>site_packages>lib>customtkinter.
