### ISSUE TITLE
hi guys, two quick questions:

### ISSUE THREAD

**Issue by cclowny** [TomSchimansky/CustomTkinter#233]
1) How can I enable a ctkbutton only when a check box is on?

`checkbox = customtkinter.CTkCheckBox(master=window, text="I accept the consequences", command=<enable button>, onvalue="on", offvalue="off")`

    `checkbox.pack(padx=20, pady=5)
    buttondel = customtkinter.CTkButton(master=window, text="Enter", command=deleteAccount, width=100, state='disabled')
    buttondel.pack(padx=10, pady=15)`

2) Probably it's not cause customtkinter but since I started using it when I try to create a setup for my exe file the av says there is a trojan in the script (i checked all the script but i didn't find anything weird that might have triggered the av, even in the other libraries so I suppose that this is a false positive)

**Comment by IshanJ25** [comment]
try something like this:

```python
checkbox = customtkinter.CTkCheckBox(master=window, text="I accept the consequences",
                                     command=lambda *args, **kwargs: checkbox_clicked(),
                                     onvalue="on", offvalue="off")
checkbox.pack(padx=20, pady=5)
checkbox.deselect()


buttondel = customtkinter.CTkButton(master=window, text="Enter", command=deleteAccount,
                                    width=100, state='disabled')
buttondel.pack(padx=10, pady=15)


def checkbox_clicked():
    if checkbox.get() == 'on':
        buttondel.configure(state=tkinter.NORMAL)
    else:
        buttondel.configure(state=tkinter.DISABLED)
```

initially box is unchecked and button is disabled
if box is clicked, it triggers an event (command)
check if box it ticked of not (on/off)
set button state accordingly

**Comment by cclowny** [comment]
It works!
Thank you so much :-)
