### ISSUE TITLE
TopLevel window not appearing on top of ctk.CTk() window

### ISSUE THREAD

**Issue by Eduard0110** [TomSchimansky/CustomTkinter#2334]
Not much to describe really, just when creating a TopLevel window (for multiple windows because this is the only way) it does not appear on top of the main window. You have to click on it in oreder for it go on top.

**Comment by 3022-2** [comment]
my fix is:

lets say the the name of your top level is top

`
import customtkinter

def toplevel(root):
    top = customtkinter.CTkToplevel(root)
    top.after(300, lambda: top.lift())
root = customtkinter.CTk()

btn = customtkinter.CTkButton(master=root, text="goto next level", command=lambda: toplevel(root))
btn.pack()

root.mainloop()
`

top.after(300, lambda: top.lift()) - this waits 300ms before applying the effect
i also ran into issues with displaying icons on toplevel windows
the same fix applied

top.after(300, lambda: top.iconbitmap("link to icon"))

**Comment by Eduard0110** [comment]
Thanks! I find it a little weird that the window initially appears on top of other windows and after approximately 300ms it disappears.

**Comment by 3022-2** [comment]
> Thanks! I find it a little weird that the window initially appears on top of other windows and after approximately 300ms it disappears.

honestly idk why it works but it does lol

**Comment by Karbonite** [comment]
I think it's cleaner using something like:`
```
top = customtkinter.CTkToplevel(root)
top.attributes('-topmost', True)
```
No Lambda's and it's cleaner.
