### ISSUE TITLE
pady button make bug

### ISSUE THREAD

**Issue by MaxNiark** [TomSchimansky/CustomTkinter#2340]
When i add pady on the second button, that will move the both button in the row.
__version__ = "5.1.2"
```
        self.export_txt=CTkButton(self,text="EXPORT",command=lambda:self.txt_export())
        self.export_txt.grid(row=2,column=3)


        self.lic_reload=CTkButton(self,text="lic_reload",command="")
        self.lic_reload.grid(row=2,column=3,sticky="s",)#pady data will move both widget
```

**Comment by SamerKharabish** [comment]
Is that intentionell that you put both buttons in the same cell? Because you overlapp them like that and then it would be totally normal that they behave the same.
