### ISSUE TITLE
how to use font from `.ttf` file

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [TomSchimansky/CustomTkinter#2354]
Is there any way to use a Custom Font by importing from a `.ttf` file in CustomTkinter?

**Comment by Akascape** [comment]
@Sayad-Uddin-Tahsin Duplicate of #900

**Comment by Akascape** [comment]
@Sayad-Uddin-Tahsin 
Check this: https://github.com/TomSchimansky/CustomTkinter/discussions/900#discussioncomment-8954115
