### ISSUE TITLE
Spelling mistake in documentation

### ISSUE THREAD

**Issue by sueszli** [TomSchimansky/CustomTkinter#237]
First line in: [https://github.com/TomSchimansky/CustomTkinter/wiki/CTk-(tkinter.Tk)](https://github.com/TomSchimansky/CustomTkinter/wiki/CTk-(tkinter.Tk))

Output: "[...] but it is highly recommended to use the `cuatomtkinter.CTk` to create [...]"
Expected output: "[...] but it is highly recommended to use the `customtkinter.CTk` to create [...]"

**Comment by TomSchimansky** [comment]
corrected it, thanks
