### ISSUE TITLE
ctk.CTk().state("zoomed") doesn't work

### ISSUE THREAD

**Issue by joe00271** [TomSchimansky/CustomTkinter#2372]
I am trying to do a windows in state zoomed as with tkinter but the windows appear very small
![vscode_3](https://github.com/TomSchimansky/CustomTkinter/assets/149353577/aede4c64-78e9-45a0-b6ef-c0c939c20164)
![vscode_4](https://github.com/TomSchimansky/CustomTkinter/assets/149353577/7f8028e4-d1cb-4b5a-ac28-a95d67e3702a)

**Comment by SmallChief** [comment]
![image](https://github.com/TomSchimansky/CustomTkinter/assets/130750555/2ceeb72d-601a-4fbf-943a-b127491942fa)
Had the same issue and this post found on https://github.com/TomSchimansky/CustomTkinter/discussions/1500 helped me fix it.
