### ISSUE TITLE
Invoking .geometry(), .winfo_height() or .winfo_width() on a window always returns 200

### ISSUE THREAD

**Issue by Kamran496** [TomSchimansky/CustomTkinter#2375]
**Code:**
```
import customtkinter

root = customtkinter.CTk()

print(f".geometry() -> {root.geometry()}")
print(f".width() -> {root.winfo_width()}")
print(f".height() -> {root.winfo_height()}\n")

width = 500
height = 500
root.geometry(f"{width}x{height}")

print(f".geometry() -> {root.geometry()}")
print(f".width() -> {root.winfo_width()}")
print(f".height() -> {root.winfo_height()}")
```
**Output**
```
.geometry() -> 200x200+208+208
.width() -> 200
.height() -> 200

.geometry() -> 200x200+208+208
.width() -> 200
.height() -> 200
```

**Questions**
1.  According to docs, none of these functions are implemented for a custom tkinter window. Any plans to implement in future?
2. In the meantime, any proposed workarounds? 
      - Could manually set window geometry and keep own track of width and height this way. But don't always want to manually set geometry.

**Comment by Akascape** [comment]
@Kamran496 Have you tried `winfo_reqwidth()` and `winfo_reqheight()`?

**Comment by Kamran496** [comment]
> @Kamran496 Have you tried `winfo_reqwidth()` and `winfo_reqheight()`?

Same result, at least for me.

**Comment by Akascape** [comment]
@Kamran496 Remove this line: 

`print(f".geometry() -> {root.geometry()}")`

**Comment by Kamran496** [comment]
@Akascape 

Still same result.

**Code**
```
import customtkinter

root = customtkinter.CTk()

print(f".width() -> {root.winfo_reqwidth()}")
print(f".height() -> {root.winfo_reqheight()}\n")

width = 500
height = 500
root.geometry(f"{width}x{height}")

print(f".width() -> {root.winfo_reqwidth()}")
print(f".height() -> {root.winfo_reqheight()}")
```

**Output**
```
.width() -> 200
.height() -> 200

.width() -> 200
.height() -> 200

```

**Comment by Akascape** [comment]
@Kamran496 Maybe you should call them after initialising the app. Like using .after :

`root.after(500, lambda: print(f".width() -> {root.winfo_reqwidth()}"))`

**Comment by Kamran496** [comment]
@Akascape 

Thank you for the suggestion. Using root.after as you've described above does indeed produce the correct output.

Another way to get correct output is root.update before calling .geometry(), .winfo_height() or .winfo_width(). 

See below Comment.

**Comment by Kamran496** [comment]
**Code**
