### ISSUE TITLE
Transparent Window

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [TomSchimansky/CustomTkinter#2376]
Is there any way to have the main window background to be transparent and the frame(s), labels in a word other component will work in normal way?

**Comment by Akascape** [comment]
@Sayad-Uddin-Tahsin 

Transparency is only possible in windows/mac:

```python
import sys

if sys.platform.startswith("win"):
            self.transparent_color = self._apply_appearance_mode(self.cget("fg_color"))
            self.attributes("-transparentcolor", self.transparent_color)
elif sys.platform.startswith("darwin"):
            self.transparent_color = 'systemTransparent'
            self.attributes("-transparent", True)
else:
            self.transparent_color = '#000001'
```
Then use `self.transparent_color` in the background of widget to make the area transparent

**Comment by Sayad-Uddin-Tahsin** [comment]
> ```python
> self.transparent_color = self._apply_appearance_mode(self.cget("fg_color"))
> ```

Seems this solution slightly breaks if we change the theme while running the program, is there anyway to detect theme change? like an event? @Akascape
