### ISSUE TITLE
*Minor Issue* Mistake in Docs

### ISSUE THREAD

**Issue by mosquitonator** [TomSchimansky/CustomTkinter#238]
I know this is picky but in the docs for CTkLabel there is an error where it has variable, when it should say textvariable.

Following example is the one I believe to be wrong:

`text_var = tkinter.StringVar(value="CTkLabel")

label = customtkinter.CTkLabel(master=root_tk,
                               variable=text_var,
                               width=120,
                               height=25,
                               fg_color=("white", "gray75"),
                               corner_radius=8)
label.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)`

And should be:

`text_var = tkinter.StringVar(value="CTkLabel")

label = customtkinter.CTkLabel(master=root_tk,
                               textvariable=text_var,
                               width=120,
                               height=25,
                               fg_color=("white", "gray75"),
                               corner_radius=8)
label.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)`

**Comment by TomSchimansky** [comment]
fixed it
