### ISSUE TITLE
How do i remove the text over the image

### ISSUE THREAD

**Issue by KorryKatti** [TomSchimansky/CustomTkinter#2396]
![image](https://github.com/TomSchimansky/CustomTkinter/assets/143781663/97d3f27d-4dff-401d-9cb4-6cbb8b51a0f8)

I wanna remove the text on top the grass image , here's the related code

`
scrollable_frame = ctk.CTkScrollableFrame(frame, width=1024, height=576, corner_radius=0, fg_color="transparent")
scrollable_frame.grid(row=2, column=0, columnspan=4, sticky="nsew")

create_labels()

alpha_path = "media/grass.jpg" 
alpha = PILImage.open(alpha_path)

ctk_alpha = ctk.CTkImage(light_image=alpha, dark_image=alpha, size=(1280, 100))

alpha_label = ctk.CTkLabel(frame, image=ctk_alpha)
alpha_label.grid(row=1, column=0, columnspan=4, padx=20, pady=20, sticky="ew")  # Adjust padding and alignment as needed

 Start the main event loop
app.mainloop() `

**Comment by rigvedmaanas** [comment]
Hi @KorryKatti, You can pass the argument `text=""` in `ctk.CTkLabel`

```python
alpha_label = ctk.CTkLabel(frame, image=ctk_alpha, text="")
alpha_label.grid(row=1, column=0, columnspan=4, padx=20, pady=20, sticky="ew") # Adjust padding and alignment as needed
```

**Comment by KorryKatti** [comment]
Thanks it works
