### ISSUE TITLE
label.config(text='text') > Error: unknown option "-text"

### ISSUE THREAD

**Issue by Nomanpour** [TomSchimansky/CustomTkinter#240]
Hello,

After updating to 4.5.4 the "text" option from "label.config" is not working anymore...

`label.config(text='text') `
`_tkinter.TclError: unknown option "-text"`

**Comment by TomSchimansky** [comment]
Hi, you have to use configure, only for some widgets the .config is implemented, but I will add it again for the label.

**Comment by Nomanpour** [comment]
Thanks for the information,

I updated my code to use .configure instead.
