### ISSUE TITLE
Failed to launch on windows7 when using padx/pady. 

### ISSUE THREAD

**Issue by Femtometer** [TomSchimansky/CustomTkinter#2446]
Build: Windows 10
Package: Nuikta

Works fine on Windows 10.
No response on Windows 7.
Remove padx/pady parameters used, it goes to normal.

**Comment by dipeshSam** [comment]
Where did you've used `padx` and `pady` parameters? In Class Constructor or in `grid` or `pack` geometry managers?

A reproducible code might be helpful.

Regards.
