### ISSUE TITLE
Canvas borders

### ISSUE THREAD

**Issue by Shishkoder** [TomSchimansky/CustomTkinter#2450]
![Снимок экрана 2024-06-02 192018](https://github.com/TomSchimansky/CustomTkinter/assets/84919659/a0a9af45-7554-4505-be9f-6e2d4a3d4744)
Hello! I use a canvas on which I then place an image as a background. Then I place the remaining widgets on the canvas itself. In regular tkinter, when creating a canvas, you had to specify bd = -2 to remove this white border. But when using CTkCanvas, this frame may or may not appear. Tell me, please, what is the reason? I have attached a screenshot to show which white border we are talking about. I would be grateful for your help!

**Comment by dipeshSam** [comment]
Setting `highlightthickness=0` will remove any border around the Canvas.

Something like the following:

`CTkCanvas(..., highlightthickness=0, ...)`.

Regards.

**Comment by Shishkoder** [comment]
Thanks for the answer! It really helped me. It’s just strange that with tkinter it was enough to specify the bd parameter and the problem was solved, but with customtkinter it worked every other time.
Thanks again!
