### ISSUE TITLE
CTkProgressBar change length

### ISSUE THREAD

**Issue by aoi2010** [TomSchimansky/CustomTkinter#2464]
```
import customtkinter

app = customtkinter.CTk()
progressbar = customtkinter.CTkProgressBar(app, orientation="horizontal",length=150)
progressbar.pack(padx=10, pady=10)
```
This shows this error :- ValueError: ['length'] are not supported arguments. Look at the documentation for supported arguments.
But the below code doesnot show this error
```
from tkinter import * 
from tkinter.ttk import *
  
root = Tk() 
  
progress = Progressbar(root, orient = HORIZONTAL, 
              length = 100) 

root.mainloop()
```
But I want to use customtkinter not normal tkinter

**Comment by dipeshSam** [comment]
`customtkinter` has different support for parameters. You can govern ~~`length`~~ using **`width`** argument instead.

Helpful link: https://customtkinter.tomschimansky.com/documentation/widgets/progressbar
