### ISSUE TITLE
Reversed Word Order for right to left languages in Custom Tkinter Widget Labels

### ISSUE THREAD

**Issue by edenhanan** [TomSchimansky/CustomTkinter#2501]
When using the CustomTkinter library, the text labels within widgets (buttons, labels, etc...) appear with their word order reversed on right to left languages like hebrew. This issue is not present in the standard Tkinter library(vanilla tkinteron the left, CustomTkinter on the left). i didnt do anything fancy with the text just passed it to the label/button
![image](https://github.com/user-attachments/assets/886e2d6a-26c7-4a8d-8216-28b293770df6)

you can clearly see this behavior in the bottuns
![image](https://github.com/user-attachments/assets/a9032b20-401a-4fec-9c46-2df6ba3e937b)

and in the first steps in the bottom window
![image](https://github.com/user-attachments/assets/19ce3d26-b0cd-427e-bb32-df5c6f8c9bcb)

Additional Information:
Custom Tkinter Version: [5.2.2]
Operating System: [Windows 11]
Python Version: [3.12]

**Comment by dipeshSam** [comment]
**Could you please have a Sample Reproducible Code?**

Regards.

**Comment by edenhanan** [comment]
not the exact code i used in the first picture but still shows the reversed text

    import tkinter as tk
    import customtkinter as ctk


    class CTKMain(ctk.CTk):
        def __init__(self):
            super().__init__()
            self.title("Main")
            self.geometry("600x400")
            self.create_widgets()

        def create_widgets(self):

            view_tests_button = ctk.CTkLabel(self, text="הצג-בדיקות").grid(row=0, column=0)
            create_test_iteration_button = ctk.CTkButton(self, text="איטרציית בדיקות חדשה").grid(row=1, column=0)
            test1 = ctk.CTkLabel(self, text="התחבר/י").grid(row=2, column=0)

    class TkMain(tk.Tk):
        def __init__(self):
            super().__init__()
            self.title("Main")
            self.geometry("600x400")
            self.create_widgets()

        def create_widgets(self):

            view_tests_button = tk.Label(self, text="הצג-בדיקות").grid(row=0, column=0)
            create_test_iteration_button = tk.Button(self, text="איטרציית בדיקות חדשה").grid(row=1, column=0)
            test1 = tk.Label(self, text="התחבר/י").grid(row=2, column=0)


    if __name__ == '__main__':
        inst_ctk = CTKMain()
        inst_tk = TkMain()
        inst_ctk.mainloop()
        inst_tk.mainloop()

**Comment by dipeshSam** [comment]
This is because Tkinter follows standard alphabet order of English which is Left To Right. But, in Hebrew, text is written and read from Right To Left.

Default alignment in Tkinter is also Left To Right, therefore, text is rendered as reversed.

To fix this, you can either reverse the text explicitly or use a module `reshaper`.

Code sample:
``` Python 

import reshaper
import tkitner as tk
...
...
root = tk.Tk()
text = 'שלום HI מה נשמע?'
text = reshaper.hebrew_reshaper(text)
label = tk.Label(root, text=text)
label.pack(fill=tk.BOTH)
root.mainloop()

```


Helpful links:
Third Party Module: https://pypi.org/project/reshaper/
Hebrew Introduction: https://mena-languages.northwestern.edu/language-learning/languages-with-different-scripts/hebrew-alphabet.html#:~:text=Hebrew%20is%20written%20from%20right,and%20Tav%20is%20the%20last.

**Comment by edenhanan** [comment]
maybe i didnt understand you correctly but it dosen't seems like this method hebrew_reshaper exists in resparper  

my test code:


```python
import tkinter as tk
import customtkinter as ctk
import reshaper


class CTKMain(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("Main")
        self.geometry("600x400")
        self.create_widgets()

    def create_widgets(self):

        text = "הצג-בדיקות"
        reshaped_text = reshaper.hebrew_reshaper(text)
        view_tests_button = ctk.CTkLabel(self, text=reshaped_text).grid(row=0, column=0)
        create_test_iteration_button = ctk.CTkButton(self, text="איטרציית בדיקות חדשה").grid(row=1, column=0)
        test1 = ctk.CTkLabel(self, text="התחבר/י").grid(row=2, column=0)
```
i also tried you example got the same error
the error i got

`AttributeError: module 'reshaper' has no attribute 'hebrew_reshaper'`

**Comment by dipeshSam** [comment]
Actually, if we see on PyPI, this module is not getting any update after 2017, this might be discontinued.

But you can implement it by your own.

Regards.

**Comment by edenhanan** [comment]
unfortunately i get the same results the text is still backwards, i will try implementing somthing myself. 
anyway thank you for the help
