### ISSUE TITLE
What is the CustomTkinter method for rendering transparencies?

### ISSUE THREAD

**Issue by Nigacatch** [TomSchimansky/CustomTkinter#2525]
Hello, @TomSchimansky!
I used the [win32mica](https://github.com/marticliment/win32mica) library to apply the Mica effect to my program, but there was a problem with rendering the images. That's why I talked to the owner of the library, but @marticliment has little information about: 'How are transparencies rendered in the CustomTkinter library?'. I will put the link of the issue here, if you have an explanation that is helpful, I would appreciate it if you could help me.
https://github.com/marticliment/win32mica/issues/21

**Comment by Akascape** [comment]
@Nigacatch you may find your answer here: https://github.com/TomSchimansky/CustomTkinter/discussions/2214

**Comment by Akascape** [comment]
@Nigacatch you can try this mica effect too: https://github.com/littlewhitecloud/win32material

**Comment by Nigacatch** [comment]
@Akascape Thank you for your help!
 I tried, but the result was the same as before and did not change.

**Comment by Akascape** [comment]
@Nigacatch Did you try the pywinstyles' opacity method?
https://github.com/TomSchimansky/CustomTkinter/discussions/2214

**Comment by Nigacatch** [comment]
@Akascape The problem was solved with your help! Thank you very much.

![{D359D66B-DC5C-46DF-909C-576497C66911}](https://github.com/user-attachments/assets/037ebca2-69d2-4127-8c57-c6f642156637)

**Comment by Akascape** [comment]
@Nigacatch You can close this issue
