### ISSUE TITLE
Themes bugging out

### ISSUE THREAD

**Issue by WolfJack24** [TomSchimansky/CustomTkinter#2535]
So i am creating a app and when i tried to run it

i keep getting this error:
```console
_tkinter.TclError: unknown color name "gray92 gray14"
```
so i changed the default theme to contain hex codes rather then color names:
```console
_tkinter.TclError: unknown color name "{#EBEBEB} #242424"
```
i still get the same thing

here is the code:
```python
from customtkinter import (
    # Imports
    set_default_color_theme as color_theme,
)

# Rest of code

def main() -> None:
    color_theme("./assets/theme/blue_in_hex.json")
    # Rest of code
```
[blue_in_hex.json](https://github.com/user-attachments/files/16629535/blue_in_hex.json)

**Comment by WolfJack24** [comment]
if the whole of the main file is needed i will upload it

**Comment by dipeshSam** [comment]
Does the provided Code Snippet you provided also throw same error?

Regards.

**Comment by WolfJack24** [comment]
Yes it does

**Comment by dipeshSam** [comment]
In my testing, it isn't showing any error.

**Comment by WolfJack24** [comment]
Huh that is weird

but i have uploaded the project to github so ig that makes something easier:
https://github.com/WolfJack24/Morse-Code-Translator

**Comment by Akascape** [comment]
If you are passing the color to a non-customtkinter widget, then this issue can happen. 
To avoid this, we can use `self._apply_appearance_mode(color_string)` when you try to use the theme colors

**Comment by WolfJack24** [comment]
I figured it out, it was because i was modifying the default list object

here is the code that broke it:
```python

import builtins


class List(list):
    def delisttify(self) -> str:
        string = ""
        if self:
            for item in self:
                string += f"{item} "
        return string


builtins.list = List
```
