### ISSUE TITLE
How to add custom fonts from figma to custom tkinter?

### ISSUE THREAD

**Issue by FriesFriday** [TomSchimansky/CustomTkinter#2556]
Hey guys, I'm trying to add an font from figma to my GUI and I don't know how. Thanks for your time :)

**Comment by Akascape** [comment]
@FriesFriday If you want to import a .ttf font, then you can do it with `customtkinter.FontManager.load_font("my_font_file.ttf")`.
Check here for more info: #900

**Comment by FriesFriday** [comment]
Thanks @Akascape ,Maybe they should add this to the docs since I didn't saw it there
