### ISSUE TITLE
Fedora 40 KDE Linux weird widgets

### ISSUE THREAD

**Issue by hacker-3342** [TomSchimansky/CustomTkinter#2593]
I am coding a simple customtkinter program in Fedora 40 KDE linux distribution. The code provided below works as expected in windows, but the checkboxes and the rounded corners look weird. I took the code from https://customtkinter.tomschimansky.com/tutorial/grid-system. My current python version is 3.10.15. My current Fedora KDE version is 6.1.5. I am using the Wayland graphics platform. My current customtkinter version is 5.2.2. I installed CustomTkinter in a virtual environment (.venv). Here is the code:

#!/usr/bin/env python3.10

import customtkinter

def button_callback():
    print("button pressed")

app = customtkinter.CTk()
app.title("my app")
app.geometry("400x150")
app.grid_columnconfigure((0), weight=1)

button = customtkinter.CTkButton(app, text="my button", command=button_callback)
button.grid(row=0, column=0, padx=20, pady=20, sticky="ew", columnspan=2)
checkbox_1 = customtkinter.CTkCheckBox(app, text="checkbox 1")
checkbox_1.grid(row=1, column=0, padx=20, pady=(0, 20), sticky="w")
checkbox_2 = customtkinter.CTkCheckBox(app, text="checkbox 2")
checkbox_2.grid(row=1, column=1, padx=20, pady=(0, 20), sticky="w")

app.mainloop()

**Comment by Akascape** [comment]
Another duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/1757 https://github.com/TomSchimansky/CustomTkinter/issues/1620 https://github.com/TomSchimansky/CustomTkinter/issues/1358 https://github.com/TomSchimansky/CustomTkinter/issues/1400 https://github.com/TomSchimansky/CustomTkinter/issues/1384 https://github.com/TomSchimansky/CustomTkinter/issues/1620 https://github.com/TomSchimansky/CustomTkinter/issues/1271 https://github.com/TomSchimansky/CustomTkinter/issues/931 ...

Simple answer: Update python or use a different env

**Comment by hacker-3342** [comment]
Okay, I will update python to the latest version and try another virtual environment. I'll post the output when I do Thanks for the fast response!

**Comment by hacker-3342** [comment]
Okay so this is what happened.
I installed Anaconda, as you told me to use a different env, and anaconda is one of the most popular ones.
The anaconda version I installed had the python 3.12.6 version (newest stable as of 26th of September, 2024)
`python --version`
`Python 3.12.6`
I did "pip install customtkinter", as I have seen pip is compatible on conda virtual environments.

The result did not change. The UI still looks strange:
![bruh_wtf](https://github.com/user-attachments/assets/f8019d23-f683-47c6-bf34-7fbe57a724b4)
The same code on my windows laptop works as expected. The corners are round, the scaling is normal... But on Linux, the borders look like they aren't rendered correctly. Is there anything else I can do to fix this? Thanks.

**Comment by Akascape** [comment]
@hacker-3342 I am not so sure but you can search for answers in these issues posted by other users who were facing the same issues: https://github.com/TomSchimansky/CustomTkinter/issues/1757 https://github.com/TomSchimansky/CustomTkinter/issues/1620 https://github.com/TomSchimansky/CustomTkinter/issues/1358 https://github.com/TomSchimansky/CustomTkinter/issues/1400 https://github.com/TomSchimansky/CustomTkinter/issues/1384 https://github.com/TomSchimansky/CustomTkinter/issues/1620 https://github.com/TomSchimansky/CustomTkinter/issues/1271 https://github.com/TomSchimansky/CustomTkinter/issues/931 ...

**Comment by hacker-3342** [comment]
Okay, I will search for answers in those issues. Thanks!

**Comment by hacker-3342** [comment]
This was fixed by switching to Python 3.12.7 on Arch Linux on the Hyprland desktop environment with the venv environment.

**Comment by benasraudys** [comment]
![Image](https://github.com/user-attachments/assets/f03fa450-260c-4d4d-ab09-f06fefc1c9b5)
I'm having the same problem. I'm on Fedora 42 with GNOME. I've tried Python 3.13.3 and 3.12.10, using venv and conda — nothing seems to work. The issues @Akascape  mentioned seem different, as the glitches appear quite different.

**Comment by benasraudys** [comment]
**Found a solution**, [this](https://github.com/TomSchimansky/CustomTkinter/issues/2467#issuecomment-2164833158) was the way I fixed it. Something is buggy about font shapes.

![Image](https://github.com/user-attachments/assets/f78dc8ec-ece2-4a3a-af1c-d598ecc5f2b4)
