### ISSUE TITLE
CTkEntry background color when disabled is different than for CTkTextbox

### ISSUE THREAD

**Issue by Ju-plop** [TomSchimansky/CustomTkinter#2599]
Hello,

When disabled, the `CTkTextbox` widget has a grey background color. This is not the case for the `CTkEntry` widget which has a white color with a light grey border whether is is active or disabled.

Could the look of the disabled `CTkTextbox` widget be applied to the disabled `CTkEntry` widget?

I saw that similar issues have already been brought up to choose the background color of the `CTkEntry` widget when it is disabled ( #1870, #922) but it does not answer my question.

Thank you!

**Comment by dipeshSam** [comment]
What about setting it manually?

**Comment by Ju-plop** [comment]
I could do that but I do not know how:

- What is the colour of the disabled `CTkTextbox`? I do not know its hex value.

- What is the name of the property to change to set the disabled background color of the `CTkEntry` widget?

- Is the "border" around the `CTkEntry` widget linked to `border_width`? I am not sure if it really is a border.

- How do I link the change of state between disabled and enabled to the background change?

Thank you

**Comment by dipeshSam** [comment]
Please clarify it what do you want to modify `CTkTextbox` or `CTkEntry`?
Or both?

**Comment by Ju-plop** [comment]
I want to modify `CTkEntry` to give it the same disabled look as `CTkTextbox`.

**Comment by dipeshSam** [comment]
As you asked about how to retrieve existing widget color information, you can use `ThemeManager` to get color and all other data value of any widget in `customtkinter`.

Sample code:
``` Python
from customtkinter import ThemeManager

text_box_data = ThemeManager.theme["CTkTextbox"]

print(text_box_data)
```
Outputs:
```
{'corner_radius': 6, 'border_width': 0, 'fg_color': ['#F9F9FA', '#1D1E1E'], 'border_color': ['#979DA2', '#565B5E'], 'text_color': ['gray10', '#DCE4EE'], 'scrollbar_button_color': ['gray55', 'gray41'], 'scrollbar_button_hover_color': ['gray40', 'gray53']}
```

Now, to change widget properties on State change, you can override `.configure()` method in `CTkEntry` or in any widget. Here is sample code for CTkEntry to change its all the properties on state change:
``` Python
from customtkinter import CTk, CTkEntry
from customtkinter import set_appearance_mode

class Entry(CTkEntry):
    def __init__(self, *args, **kwargs):
        """All `CTkEntry` arguments are supported."""
        super().__init__(*args, **kwargs)

        self._normal_properties = {}
        self._disabled_properties = {}
        
        
    def set_disabled_properties(self, **kwargs):
        self._disabled_properties.update(kwargs)
        self._normal_properties.update({key: self.cget(key) for key in self._disabled_properties.keys()})
        
    
    def configure(self, require_redraw=False, **kwargs):
        if "state" in kwargs:
            if kwargs["state"] == "disabled":
                super().configure(**self._disabled_properties)
            else:
                super().configure(**self._normal_properties)
            
        return super().configure(require_redraw, **kwargs)



if __name__ == "__main__":
    app = CTk()
    set_appearance_mode("Dark")
    app.configure(width=500, height=300)

    entry = Entry(app, placeholder_text="Type something...")
    entry.place(relx=0.5, anchor="center", rely=0.5)


    entry.set_disabled_properties(border_width=0, placeholder_text_color="#6b6b60", text_color="#9ea3aa")


    entry.configure(state="disabled")
    # entry.configure(state="normal")
    
    

    app.mainloop()
``` 
**Outputs:**
_With disabled_
![With_Disabled](https://github.com/user-attachments/assets/2a6eccaa-7f84-4fe6-aaa7-fb1455b21ebd)
_With normal again_
![Normal_again](https://github.com/user-attachments/assets/93b58602-3202-4ddd-976b-834d8b6a9874)


The two methods `set_disabled_properties()` and `configure()` in above class code are completely widget-independent, you can use them to override any widget like `CTkTextbox` or `CTkLabel` etc.

Hope it would be helpful for you. Let me know what you expect more from above explanation.
Regards.

**Comment by Ju-plop** [comment]
This works perfectly, thank you!

**Comment by Ju-plop** [comment]
This works perfectly, thank you!
