### ISSUE TITLE
Cannot get txt from entry

### ISSUE THREAD

**Issue by ilify** [TomSchimansky/CustomTkinter#26]
import customtkinter
from tkinter import *
import tkinter as tk
wn = Tk()
def printtxt(text):
    print(text)
text=''
entry = customtkinter.CTkEntry(master=wn,
                               width=120,
                               height=25,
                               corner_radius=10)
entry.place(relx=0.5, rely=0.5, )
text = entry.get()
button = customtkinter.CTkButton(master=wn,
                                 text="CTkButton",
                                 command=lambda:printtxt(text),
                                 width=120,
                                 height=32,
                                 border_width=0,
                                 corner_radius=8)
button.place(relx=0.7, rely=0.5)

wn.mainloop()

**Comment by ilify** [comment]
`import customtkinter
from tkinter import *
import tkinter as tk
wn = Tk()
def printtxt(text):
    print(text)
text=''
entry = customtkinter.CTkEntry(master=wn,
                               width=120,
                               height=25,
                               corner_radius=10)
entry.place(relx=0.5, rely=0.5, )
text = entry.get()
button = customtkinter.CTkButton(master=wn,
                                 text="CTkButton",
                                 command=lambda:printtxt(text),
                                 width=120,
                                 height=32,
                                 border_width=0,
                                 corner_radius=8)
button.place(relx=0.7, rely=0.5)

wn.mainloop()`

**Comment by ilify** [comment]
text is always NULL

**Comment by TomSchimansky** [comment]
You are getting the text when the program starts and nothing is in the entry. You have to .get() the text every time you press the button and execute your lambda function:

```python
import customtkinter
from tkinter import *
import tkinter as tk

wn = Tk()

def printtxt(text):
    print(text)

entry = customtkinter.CTkEntry(master=wn, width=120, height=25, corner_radius=10)
entry.place(relx=0.5, rely=0.5, )

button = customtkinter.CTkButton(master=wn, text="CTkButton", command=lambda: printtxt(entry.get()), width=120,
                                 height=32, border_width=0, corner_radius=8)
button.place(relx=0.7, rely=0.5)

wn.mainloop()
```
