### ISSUE TITLE
CTkLabel cget method

### ISSUE THREAD

**Issue by NiAmhras** [TomSchimansky/CustomTkinter#27]
Due to the fact that I'm an absolute beginner, not only regarding to UI but also to coding itself, I hope it is really an issue and not stupidity... However, I tried to get the text from a CTkLabel with expressions "CTkLabel .cget("text")" and CTkLabel ["text"]. Nothing worked for me.

**Comment by TomSchimansky** [comment]
The .cget() function doesn't work on the CTk elements as expected, it refers to the tkinter.Frame around which the CTk widget is build.

Currently you have two options to get the text from a label.
You could call the .cget() function on the tkinter.Label which is part of the CTkLabel widget or you can get the text from the .text attributing of the CTkLabel:
```python
label_1 = customtkinter.CTkLabel(master=frame_1)
label_1.pack(pady=y_padding, padx=10)

label_text = label_1.text_label.cget("text")  # method 1
label_text = label_1.text                                 # method 2
```

Or you could set the text to the label with a textvariable and then get the text from the tkinter.StringVar:
```python
txt_var = tkinter.StringVar(value="some label text")

label_1 = customtkinter.CTkLabel(master=frame_1, textvariable=txt_var)
label_1.pack(pady=y_padding, padx=10)

label_text = txt_var.get()  # get text
txt_var.set("some new text")  # set new label text
```

**Comment by NiAmhras** [comment]
Thank you ver much for your detailled answer. :)
It works very well now and is much more understandable (for me) than the Tk way. I just learned again very much and I should take a closer look to the code of the CTk elements, maybe I'll understand something.
