### ISSUE TITLE
Bindings not working with CTkButton

### ISSUE THREAD

**Issue by TheFallen-Cat** [TomSchimansky/CustomTkinter#274]
Key bindings are not working with CTKButton, the issue arised when I tried to use `"<Button-1>"` to to a button. The reason i was using bindings with a button is, that I wanted a way to bind the `"<Return>"` key to a input field to run the function while still possible to use the button to run the same command.

**Comment by TomSchimansky** [comment]
I can try to add .bind() method to CTkButton, but on CTkEntry it should work and that's how you should do it I think. Because if you focused to the entry the Return event will not be recognised by the button I would say.

**Comment by TheFallen-Cat** [comment]
yeah maybe i should do it with button instead

**Comment by TomSchimansky** [comment]
You can do it like this:
```python
entry.bind("<Return>", callback_function)
```

**Comment by TomSchimansky** [comment]
Also duplicate: https://github.com/TomSchimansky/CustomTkinter/issues/65
