### ISSUE TITLE
Prints something in terminal

### ISSUE THREAD

**Issue by Nomanpour** [TomSchimansky/CustomTkinter#278]
Hello,
The latest version '4.5.8' printing this to the terminal on run.
```

['', 'x', '']
['', 'x', '']

```
I believe it was to test the geometry issue...

**Comment by Nomanpour** [comment]
![image](https://user-images.githubusercontent.com/11517299/179467348-c6f8d277-ebcd-4a7e-b6ec-422fa4facb0b.png)

**Comment by TomSchimansky** [comment]
fixed with version 4.5.9
