### ISSUE TITLE
Print when I click a button

### ISSUE THREAD

**Issue by cclowny** [TomSchimansky/CustomTkinter#279]
Since I upgraded customtkinter (litterally 5 minutes ago) every time I press a button the software prints a list:
['', 'x', '']

**Comment by TheFallen-Cat** [comment]
this issue is being faced by everyone who updated the customtkinter to the new version, its a bug most probably

**Comment by cclowny** [comment]
oh okay thanks

**Comment by TomSchimansky** [comment]
fixed with version 4.5.9
