### ISSUE TITLE
PyInstaller: ModuleNotFoundError: No module named 'darkdetect'

### ISSUE THREAD

**Issue by MrBananaPants** [TomSchimansky/CustomTkinter#282]
I'm trying to make a windows executable using PyInstaller but I get the following error when launching the app:
```
Traceback (most recent call last):
  File "PyFit.py", line 9, in <module>
  File "C:\Users\Joran Vancoillie\PycharmProjects\PyFit\dist\PyFit\customtkinter\__init__.py", line 10, in <module>
    from .appearance_mode_tracker import AppearanceModeTracker
  File "C:\Users\Joran Vancoillie\PycharmProjects\PyFit\dist\PyFit\customtkinter\appearance_mode_tracker.py", line 14, in <module>
    raise err
  File "C:\Users\Joran Vancoillie\PycharmProjects\PyFit\dist\PyFit\customtkinter\appearance_mode_tracker.py", line 7, in <module>
    import darkdetect
ModuleNotFoundError: No module named 'darkdetect'
```
The `darkdetect` module is imported in `appearance_mode_tracker.py`

I followed [these steps](https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging#windows-pyinstaller-auto-py-to-exe) to make the build command.

This is the command I use:
`pyinstaller --noconfirm --onedir --windowed --hidden-import distutils --hidden-import distutils.version --add-data "c:\users\joran vancoillie\pycharmprojects\pyfit\venv\lib\site-packages/customtkinter;customtkinter/"  "PyFit.py"
`

I also tried adding `--hidden-import customtkinter` but that also didn't work.

Is this an CustomTkinter issue or an issue with PyInstaller?

**Comment by TomSchimansky** [comment]
Do you have darkdetect installed? Can you try `--hidden-import darkdetect`

**Comment by MrBananaPants** [comment]
Yes, I've also tried that but it gives me the same error:
```
Traceback (most recent call last):
  File "PyFit.py", line 9, in <module>
  File "C:\Users\Joran Vancoillie\PycharmProjects\PyFit\dist\PyFit\customtkinter\__init__.py", line 10, in <module>
    from .appearance_mode_tracker import AppearanceModeTracker
  File "C:\Users\Joran Vancoillie\PycharmProjects\PyFit\dist\PyFit\customtkinter\appearance_mode_tracker.py", line 14, in <module>
    raise err
  File "C:\Users\Joran Vancoillie\PycharmProjects\PyFit\dist\PyFit\customtkinter\appearance_mode_tracker.py", line 7, in <module>
    import darkdetect
ModuleNotFoundError: No module named 'darkdetect'
```

**Comment by TheFallen-Cat** [comment]
I've made an executable too but i didnt get that error, maybe you should try it with `auto-py-to-exe`, it worked for me.

**Comment by TomSchimansky** [comment]
Could be possible that pyinstaller uses an other python version with no darkdetect installed

**Comment by MrBananaPants** [comment]
So how could this be fixed? Is it possible to exclude or remove the darkdetect module if I don't use it?

 I'm also having lots of issues trying to install `auto-py-to-exe`. Both the pip installer and the offline build (from the source code) don't work for me.

**Comment by TheFallen-Cat** [comment]
What are the issues with `auto-py-to-exe`, any errors?

**Comment by Akascape** [comment]
@MrBananaPants In my case I had 2 python version installed (3.9 and 3.10). I have auto py to exe installed in 3.9 so I have to download the modules in 3.9 only.

Ways to fix:

1) if you are using 2 or more python versions then move the environment variable path of that version to the top and use cmd to 'pip install customtkinter'. This should fix the problem.

2) Go to this path: 'python/Lib/site packages/darkdetect' and copy this folder path in your auto-py-to-exe 'add folder' option.

**Comment by RutgerLit** [comment]
Use a hidden import for darkdetect:

--hidden-import=darkdetect 

in combination with:

--add-data="path_to_python/Lib/site-packages/customtkinter;customtkinter/"

**Comment by MrBananaPants** [comment]
@Akascape This fixed my issue! I completely removed all python versions and packages that were installed and did a clean install of 1 python version and all the required packages. Now I can launch the .exe without any issues.
