### ISSUE TITLE
Bug after changing the version from 4.5.6 to 4.5.9 (also to 4.5.7 or 4.5.8)

### ISSUE THREAD

**Issue by egwald** [TomSchimansky/CustomTkinter#287]
The code:
```python
 # set the position of the window to the center of the screen
        self.geometry(f'{window_width}x{window_height}+{center_x}+{center_y}')
```
ends with a error in ctk_tk.py", line 137, in geometry
```
    numbers = list(map(int, re.split(r"[x+-]", geometry_string)))  # split geometry string into list of numbers
ValueError: invalid literal for int() with base 10: ''

(<class 'ValueError'>, ValueError("invalid literal for int() with base 10: ''"), <traceback object at 0x7f17e8f4d400>)
```
With version 4.5.6 my app runs fine!

**Comment by felipetesc** [comment]
To center a window I'm using this code:

```python
def center_window(win):
    win.update_idletasks()
    width = win.winfo_width()
    frm_width = win.winfo_rootx() - win.winfo_x()
    win_width = width + 2 * frm_width
    height = win.winfo_height()
    titlebar_height = win.winfo_rooty() - win.winfo_y()
    win_height = height + titlebar_height + frm_width
    x = win.winfo_screenwidth() // 2 - win_width // 2
    y = win.winfo_screenheight() // 2 - win_height // 2
    win.geometry('{}x{}+{}+{}'.format(width, height, x, y))
    win.deiconify()
```
Perhaps it can be used as utl function like  I'm right now

**Comment by TomSchimansky** [comment]
@egwald what are the values you inserted into the geometry f-string? You cannot insert floats there, maybe it worked before but it shouldn't.

**Comment by egwald** [comment]
**All values are integer:**

        window_width = 19200
        window_height = 1200

        # get the screen dimension
        screen_width = self.winfo_screenwidth()
        screen_height = self.winfo_screenheight()

        # find the center point
        center_x = int(screen_width / 2 - window_width / 2)
        center_y = int(screen_height / 2 - window_height / 2)

        # set the position of the window to the center of the screen
        self.geometry(f'{window_width}x{window_height}+{center_x}+{center_y}')

What should I do?

Now I use the function from **felipetesc**. It is very use full and works fine.

**Comment by TomSchimansky** [comment]
I changed the parsing and the geometry method now works with the following formats:
```python
app.geometry("300x300")
app.geometry("-100-100")
app.geometry("+-100+-100")
app.geometry("+100+100")
app.geometry("300x300-100-100")
app.geometry("300x300+-100+-100")
app.geometry("300x300+100+100")
```
Tested in `test/manual_integration_tests/test_window_geometry.py`
I will upload the next version very soon.
