### ISSUE TITLE
auto-py-to-exe gridding changes

### ISSUE THREAD

**Issue by Moeman101** [TomSchimansky/CustomTkinter#290]
Today I used auto-py-to-exe to convert the software I was working on to an .exe to set up in my lab's computer.  the customtkinter library was looking for itself in the wrong folder but that was easy enough to fix.  But when i run my program as an .exe, for some reason the gridding does not line up.  Please advice.  Also I would love to zoom and show you this live.

**Comment by TheFallen-Cat** [comment]
Can you upload some screenshots showing what is the problem? Also, does the same problem occur while running the python file too?

**Comment by Moeman101** [comment]
Im recompiling it now.  I was looking for any errors and I did not see anything on my end.  Ill upload screen captures in 5 minutes and make a separate ticket for the library looking for itself in the wrong folder

**Comment by Moeman101** [comment]
Here are screenshots of the program ran in spyder (IDE), aka the result I expect) and the second one is after its compiled.  There are no changes to the code between the two.
![Ran in Spyder (IDE)](https://user-images.githubusercontent.com/71300984/180176779-64742487-fd94-4905-8984-f2cd7f9b81a7.png)
![Auto-py-to-exe compiled](https://user-images.githubusercontent.com/71300984/180176797-6165b261-8eff-4293-a3f0-1c7b4071d4ff.png)

**Comment by TomSchimansky** [comment]
I don't know why compiling to exe would change how the grid system looks. Maybe the window has a different size when it's compiled? Can you show me the code somehow?

**Comment by Moeman101** [comment]
What code would you like to see?  My code or it compiled?  Everything looks the same between both programs until I go to display the PNGs.

**Comment by TomSchimansky** [comment]
The whole code, or a running example where this appears. I mean I have no idea why this would happen, and if its really a bug, I don't think that its happening because of customtkinter. Then it would be more of a tkinter bug. But I want to have a look how you created the grid and set the weights of the cells.

**Comment by Moeman101** [comment]
There seem to be more visual bugs than that.  If possible, im wondering if we can zoom and discuss the bugs.  Im in Germany working at the MPI in Freiburg so our timezomes should line up.

**Comment by Moeman101** [comment]
On my profile I have a public directory of the code.  Please let me know if you see anything that is causing the visual errors

**Comment by Moeman101** [comment]
I was able to fix it.  The issue was something to do with Image.open's scaling.  I was able to manually pass resizing parameters and it fixed the gridding issue.

**Comment by TomSchimansky** [comment]
Ok, currently I'm very busy with other stuff. But If you found other bugs just post them.
