### ISSUE TITLE
Update image of a label

### ISSUE THREAD

**Issue by GambetG** [TomSchimansky/CustomTkinter#292]
With the windown already open, when executing the command to update an image in a label, the image is not updated
```
     photo = ImageTk.PhotoImage(PIL.Image.open("src/album.jpg"))
      img = customtkinter.CTkLabel(app, image=photo)
      img.configure(image=photo)
```
In tkinter thats works normal

**Comment by Akascape** [comment]
@GambetG You don't have to define img label again before configuring, and also update the method of importing the image like this:

```python
from PIL import Image, ImageTk
height=100 #define the height of image for the label
width=100 #define the width of image for the label
photo = ImageTk.PhotoImage(Image.open("src/album.jpg").resize((width, height), Image.Resampling.LANCZOS))
img.configure(image=photo)
```
Also update both PIL and customtkinter if you face any other errors.

**Comment by TomSchimansky** [comment]
@GambetG For configuring the image is working. Do you have thee newest version installed?

**Comment by GambetG** [comment]
@Akascape  @TomSchimansky 
Thanks for commenting.

I just showed the whole part of the image to see if I was doing something wrong with the label too, but I tried with 

```Image.Resampling.LANCZOS```

And it says it is not an attribute of Image, I tried to update pillow and the error remains.

Tom ,Yes it's updated, I installed the CTK yesterday, and now to test I removed it and installed it again.

**Comment by Akascape** [comment]
@GambetG update the PIL module via 'pip install pillow --upgrade'. Or use `Image.LANCZOS` directly.

**Comment by GambetG** [comment]
Yes, I just updated, the LANCZOS directly doesn't work either for some reason.

Definitely the problem with updating the image is something in my code, I tried to put it in a simpler code and it worked, I'll check where I'm going wrong. thank you again.

**Comment by Akascape** [comment]
@GambetG Actually it was the old method, you may get a DeprecationWarning message while running the program with the newer PIL version.

You can also use `Image.ANTIALIAS` which I believe is a very traditional method.
