### ISSUE TITLE
Can we configure/change themes within the app?

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#295]
Is it possible to change/configure the theme of customtkinter like the `set_appearance_mode` method?

**Comment by TomSchimansky** [comment]
You select a theme with `set_default_color_theme`.

**Comment by Akascape** [comment]
How can we change it later?

**Comment by TomSchimansky** [comment]
Not possible at the moment, but this could be an enhancement, maybe I will add this at some point.

**Comment by Akascape** [comment]
@TomSchimansky please review the pull request.

**Comment by TheFallen-Cat** [comment]
> Is it possible to change/configure the theme of customtkinter like the `set_appearance_mode` method?

Yes it is possible to change the theme while the app is running. You can check this app i made with a change theme command here, https://github.com/TheFallen-Cat/VocabiPy/blob/d039fa49e93e37dee98616b5afec16fc175c48f8/main.py#L117

**Comment by TheFallen-Cat** [comment]
If you're wondering what the `if` statement is for [there](https://github.com/TheFallen-Cat/VocabiPy/blob/d039fa49e93e37dee98616b5afec16fc175c48f8/main.py#L120) its because i used tkinter textbox so i had to change the `fg` and `bg` seperately when the theme gets changed.

**Comment by Akascape** [comment]
@TheFallen-Cat Its not about the dark mode bro, 
A theme file has one dark and one light attribute for each widget type. You are only switching between those parts of the theme. But it is not possible to change the whole theme.

**Comment by Akascape** [comment]
Check the json file of a theme of customtkinter and you will understand.

**Comment by TheFallen-Cat** [comment]
@Akascape Oh i see now, you mean switching different themes like sweetkind and such.

**Comment by Akascape** [comment]
@TheFallen-Cat Absolutely, I am working on some new themes for my applications. 

Even made this thememaker tool.

**Comment by TheFallen-Cat** [comment]
@Akascape yeah i saw the PR you made, it looks amazing!
