### ISSUE TITLE
Detect system theme in Windows

### ISSUE THREAD

**Issue by sumeshir26** [TomSchimansky/CustomTkinter#3]
`darktetect` looks like it supports Windows as well so I am not really sure why you check if the system is darwin before setting the theme to system. (Line 5, 38, and 75 of `appearance_mode_tracker.py`)
I can create a PR if you are interested.

**Comment by TomSchimansky** [comment]
Ok thanks, the support of Windows and Linux in darkdetect is new, when I created it, darkdetect only supported macOS. So I will change this in the next few days.

**Comment by TomSchimansky** [comment]
I updated the code and the Readme.md file now, but I didn't test if its working on Windows or Linux, so for now I won't update it on pip.

**Comment by sumeshir26** [comment]
@TomSchimansky Can confirm it works on Windows 11.
