### ISSUE TITLE
How to implement dark title bar in windows OS?

### ISSUE THREAD

**Issue by Sanket-8801** [TomSchimansky/CustomTkinter#30]
Can you tell how to implement dark Title bar in windows using  Ctk?

**Comment by TomSchimansky** [comment]
The dark titlebar on Windows works when you set `customtkinter.set_appearance_mode("Dark")` (or set it to "System" and have Dark theme on Windows activated), but is currently only available on the Github version. But I will push a new version containing this feature to pip maybe today.

**Comment by Sanket-8801** [comment]
Thank you. Waiting for the new pip version.

**Comment by TomSchimansky** [comment]
Version 2.3 is now on pip, does the black titlebar work for you?

**Comment by Sanket-8801** [comment]
I updated and used ` customtkinter.set_appearance_mode("Dark")` but title bar is still black

**Comment by TomSchimansky** [comment]
That's how it's supposed to be. When you set it to "Dark" the titlebar is dark and when you set it to "Light" the titlebar is white.

**Comment by Sanket-8801** [comment]
sorry its still white, typed black by mistake

**Comment by TomSchimansky** [comment]
What version of Windows are you using?

**Comment by Sanket-8801** [comment]
Windows 10 pro 19042.1466

**Comment by TomSchimansky** [comment]
And which program are you using to test it?

**Comment by Sanket-8801** [comment]
U mean software?
its VSCODE

**Comment by TomSchimansky** [comment]
I mean your python script, where you create the window

**Comment by Sanket-8801** [comment]
`import tkinter
import customtkinter
from numpy import size  # <- import the CustomTkinter module
import pyglet
 
customtkinter.set_appearance_mode("Dark")
root_tk = customtkinter.CTk()  # create CTk window like you do with the Tk window
root_tk.geometry("800x480")
root_tk.title("Login\ SignUp")
root_tk.resizable(False,False)

pyglet.font.add_file('Chonburi-Regular.ttf')

def button_function():
    print("button pressed")
    
''' =============================================Frame============================================='''
frame = customtkinter.CTkFrame(master=root_tk,
                               width=700,
                               height=380,
                               corner_radius=10)
frame.place( x=50,y=50)


''' ===============================================Labels========================================'''

username = customtkinter.CTkLabel(master=frame,
                               text="Username",
                               width=180,
                               height=30,
                               text_font=('',16,),
                               corner_radius=8)
username.place(x=30,y=30)

pswd = customtkinter.CTkLabel(master=frame,
                               text="Password",
                               width=180,
                               height=30,
                               text_font=('',16,),
                               corner_radius=8)
pswd.place(x=30,y=80)


''' =============================================Entries============================================= '''
uentry = customtkinter.CTkEntry(master=frame,
                               placeholder_text="Type your username here",
                               width=280,
                               height=30,
                               corner_radius=10)
uentry.place(x=260, y=30)

pentry = customtkinter.CTkEntry(master=frame,
                               placeholder_text="Type your password here",
                               width=280,
                               height=30,
                               corner_radius=10)
pentry.place(x=260, y=80)


'''=======================================Button============================================'''
# Use CTkButton instead of tkinter Button
button = customtkinter.CTkButton(master=frame,
                                 fg_color=("black", "#ffae00"),
                                 text="Forgot password?",
                                 text_color="black",
                                 hover_color='#d1971b',
                                 corner_radius=10, 
                                 command=button_function)
button.place(x=380,y=120)

button = customtkinter.CTkButton(master=frame,
                                 fg_color=("black", "#ffae00"),
                                 width=100,
                                 text="LOGIN",
                                 text_color="black",
                                 hover_color='#d1971b',
                                 corner_radius=10, 
                                 command=button_function)
button.place(x=300,y=220)

root_tk.mainloop()`

**Comment by Sanket-8801** [comment]
here it is. everything is working properly except titlebar

**Comment by TomSchimansky** [comment]
Oh I think the .resizable(False,False) reverts the titlebar setting. You can try to remove this line, but I will also try to fix this.

**Comment by Sanket-8801** [comment]
Yeah you were right. I removed resizable and now its dark. Thank you. But how can we make our window not resizable if we want to?

**Comment by TomSchimansky** [comment]
You can call root_tk.windows_set_titlebar_color("dark") after you make the .resizable call. But I wil also overwrite the .resizable function so that .windows_set_titlebar_color() will be called again automatically with the correct setting ("dark or light").

**Comment by Sanket-8801** [comment]
I did as u told and now `root_tk.resizable(False,False)` and `root_tk.windows_set_titlebar_color("dark")` both are working fine. Thanks for helping out.
