### ISSUE TITLE
CTkOptionMenu dropdown menu customization not working

### ISSUE THREAD

**Issue by MrBananaPants** [TomSchimansky/CustomTkinter#304]
Whatever arguments I give the CTkOptionMenu to change the appearance of the dropdown menu where you can select a value, it just doesn't change a thing.

Here's some code to reproduce the issue:
```
import customtkinter as ctk


def optionmenu_callback(choice):
    print("optionmenu dropdown clicked:", choice)


app = ctk.CTk()
app.geometry("600x300")

option_menu = ctk.CTkOptionMenu(master=app, dropdown_hover_color="green", dropdown_text_color="red", dropdown_color="blue",
                                values=["value 1", "value 2", "value 3", "value 4"], command=optionmenu_callback)
option_menu.place(relx=0.5, rely=0.5, anchor=ctk.CENTER)
option_menu.set("value 2")

if __name__ == "__main__":
    app.mainloop()
```

As you can see in the screenshot below, the `dropdown_hover_color="green"`, `dropdown_text_color="red"` and the `dropdown_color="blue"` don't have any effect on the appearance:

![Screenshot 2022-07-23 at 19 59 01](https://user-images.githubusercontent.com/41532982/180617338-4b930cb7-9159-4a5d-a0b2-a1a9aecf17d7.png)

It keeps showing the default macOS style dropdown menu. Even if I don't add any arguments to change the style, it doesn't look like the default style in your screenshot:
<img width="651" alt="171516774-e362df77-8420-4eaf-9694-a393f82ee9f5" src="https://user-images.githubusercontent.com/41532982/180617213-55f8a8d3-ade7-4fe4-955c-01dc38c55558.png">

**Comment by TomSchimansky** [comment]
The custom dropdown menu was replaced with a default tkinter menu, because of multiple platform specific bugs. It's not possible to build a custom dropdown menu with tkinter which is reliable.
