### ISSUE TITLE
CTk.withdraw method doesn't appear to work (customtkinter 4.5.9)

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#305]
Please see test case:

https://github.com/TomSchimansky/CustomTkinter/discussions/302

**Comment by ArielMAJ** [comment]
Duplicate #277

**Comment by avalon60** [comment]
Thanks @ArielMAJ

**Comment by TomSchimansky** [comment]
Should work now with version 4.5.11.
