### ISSUE TITLE
CtkInputDialog: cancel is not ending the process.

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#307]
I used CtkInputDialog like this, but facing an issue with the options

```python
import customtkinter
import tkinter

customtkinter.set_appearance_mode("dark")
app = customtkinter.CTk()
app.geometry("400x300")

def button_click_event():
    dialog = customtkinter.CTkInputDialog(master=None, text="Type in a number:", title="Test")
    print("Number:", dialog.get_input())
button = customtkinter.CTkButton(app, text="Open Dialog", command=button_click_event)
button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

app.mainloop()
```

When I press Cancel, it prints 'Number: None' instead of returning/ending the process.
If I use `if dialog.get_input()!=None:` then it doesn't print anything even when I press OK. Instead it prints everything only after closing the main program. It also happens if I close the dialog box.

What to do?

**Comment by Akascape** [comment]
@TomSchimansky Please review the ThemeMaker program which I have just updated,
I have updated the program structure to class and also changed it to grid layout.
https://github.com/TomSchimansky/CustomTkinter/pull/268

**Comment by koka051** [comment]
Try this:
```
def button_click_event():
    dialog = customtkinter.CTkInputDialog(master=None, text="Type in a number:", title="Test")

    dialog_input = dialog.get_input()
    
    if dialog_input is not None:
        print("Number:", dialog_input)
```
