### ISSUE TITLE
Request - CTk.Spinbox & CTk.Notebook

### ISSUE THREAD

**Issue by codeCollision4** [TomSchimansky/CustomTkinter#316]
I read some other issues and saw that it is possible to create buttons that switch "tabs" similar to the notebook. I am not sure if that is how to implement a custom tkinter style notebook. If so I will do that. However, I have not seen anything about spin boxes. It would be really nice if these were apart of custom tkinter. Or if there is another way to implement them I would appreciate some insight. Thank you for your time.

**Comment by felipetesc** [comment]
I have used buttons and a frame for that:
Also, you can  check 
https://github.com/TomSchimansky/CustomTkinter/issues/229#issuecomment-1173146775
https://github.com/TomSchimansky/CustomTkinter/issues/100#issue-1244114141
https://felipetesc.github.io/CtkDocs/#/multiple_frames
https://github.com/TomSchimansky/CustomTkinter/discussions/259


![Peek 25-07-2022 18-21](https://user-images.githubusercontent.com/2336812/180876911-8f2a7117-d041-4214-83f7-25b8caac88c5.gif)

**Comment by codeCollision4** [comment]
@felipetesc Thank you so much for the resources. They will help tremendously with create a Notebook style interface.
Do you know of any way to create a Spinbox? If not I totally understand, thank you for your time.

**Comment by dishb** [comment]
@codeCollision4 - Maybe this...? [Akascape/TkDial](https://github.com/Akascape/TkDial)
