### ISSUE TITLE
Button Disabling Graphical Error

### ISSUE THREAD

**Issue by Hexseral** [TomSchimansky/CustomTkinter#328]
I've encounterd this problem a few times where I will have a button to run a function and I will put the button state back to being disabled after the function completion and for whatever reason I get a weird graphical error:
![image](https://user-images.githubusercontent.com/54594278/181766486-f40efea4-02de-4370-abcd-175a0dcca318.png)

Not too sure why it occurs and I've expereinced it a few times but just wanted to make sure you were aware!

**Comment by TomSchimansky** [comment]
Can you post the code and your platform, python and customtkinter version please?

**Comment by felipetesc** [comment]
> I've encounterd this problem a few times where I will have a button to run a function and I will put the button state back to being disabled after the function completion and for whatever reason I get a weird graphical error: ![image](https://user-images.githubusercontent.com/54594278/181766486-f40efea4-02de-4370-abcd-175a0dcca318.png)
> 
> Not too sure why it occurs and I've expereinced it a few times but just wanted to make sure you were aware!

I'm curious about something, are you using Anaconda ?

**Comment by Hexseral** [comment]
Sorry for the delayed response, I am not using andaconda. I will try to get the rest of your requested info when I can!

**Comment by TomSchimansky** [comment]
I can not reproduce this, therefore I will close this issue.
