### ISSUE TITLE
Cannot set state argument with CTkTextbox.config() / CTkTextbox.configure()

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#331]
Trying to toggle between CTkTextbox being normal and disabled.

CTkTextbox.config does not recognise the "state" argument:

![image](https://user-images.githubusercontent.com/89534395/181919551-1127c29f-5204-43f1-b9a6-91a9c255b068.png)

**Comment by TheFallen-Cat** [comment]
You're using `tk.DISABLED` which isnt supported by `CTk`, thus you have to pass `"disabled"` or `"enabled"` as a string to `state`

**Comment by avalon60** [comment]
@TheFallen-Cat that makes no difference, the value of tk.DISABLED resolves to "disabled", and  if you look at the error, it's "-state" that it's balking on. The textbox code actually uses tkinter, under the hood, so it would be logical to assumed that tk.DISABLED should work, for consistency.

Besides, I tried using a literal, "disabled" prior:

![image](https://user-images.githubusercontent.com/89534395/182023458-7ccccca0-2ef0-41cc-9a4a-b16afd822f36.png)

**Comment by TomSchimansky** [comment]
There are many things that are not working for the CTkTextboxy. It isn't completed yet.

**Comment by avalon60** [comment]
Hi @TomSchimansky.  I have submitted a solution for your review - it's a two line fix.

**Comment by lmwenda** [comment]
@avalon60 Is it solved? I think if you want to configure the state you might want to use .configure() instead of .config()

**Comment by TomSchimansky** [comment]
Works now with version 5.0.0.
