### ISSUE TITLE
How to align Labels?

### ISSUE THREAD

**Issue by Hemang-Dwivedi** [TomSchimansky/CustomTkinter#34]
I am making a app where in i need to align my labels to the left side, How do I do that?

**Comment by TomSchimansky** [comment]
Do you mean the text of the marker?
No there is no option to change the text position.
But you could get a local copy of the tkintermapview library folder and edit line 124 in `canvas_position_marker.py`
where the text of the marker is placed.

**Comment by TomSchimansky** [comment]
Sorry, my first answer was a fail.
So there is no such option to align the text inside a CTkLabel. You can use the justify argument, but this affects only the label itself, and not where the label is placed inside the label frame.
In the following image you can see the green part which is a tkinter.Label and it is placed on a CTkFrame (red) and together this is a CTkLabel:
<img width="335" alt="Bildschirmfoto 2022-03-07 um 22 36 53" src="https://user-images.githubusercontent.com/66446067/157121818-d4d636a0-a593-4fe9-9c4f-c6efacd26644.png">
And the green label is always placed in the center of the red frame.

But with a small hack you can re-arrange the label again to the left side:
```python
label_1 = customtkinter.CTkLabel(master=frame_1, justify=tkinter.LEFT, text="test")
label_1.text_label.grid(row=0, column=0, sticky="w")
label_1.pack(pady=y_padding, padx=10)
```
Then it would look like this:
<img width="349" alt="Bildschirmfoto 2022-03-07 um 22 39 18" src="https://user-images.githubusercontent.com/66446067/157122171-02c43ad6-3998-4166-a0b1-f5eb7078f7ab.png">

**Comment by Hemang-Dwivedi** [comment]
Will this also work with buttons

**Comment by TomSchimansky** [comment]
Yes but you should do it like this because the button has a 2x2 grid system, and it won't work with an image on the button:
```python
button_1.text_label.grid(row=0, column=0, rowspan=2, columnspan=2, sticky="w")
```

**Comment by Hemang-Dwivedi** [comment]
Oh alright
