### ISSUE TITLE
Please change user fonts directory on linux

### ISSUE THREAD

**Issue by antrrax** [TomSchimansky/CustomTkinter#340]
On linux the user fonts should be in this directory:
~/.local/share/fonts/

instead of
~/fonts/

https://help.gnome.org/admin/system-admin-guide/stable/fonts-user.html.en

-----
file: font_manager.py
https://github.com/TomSchimansky/CustomTkinter/blob/ec8cecb5757850d2e1d03062bdca68fd95338677/customtkinter/font_manager.py

**Comment by lmwenda** [comment]
I can work on this issue for you.

**Comment by antrrax** [comment]
> 

I appreciate if you can do this

**Comment by lmwenda** [comment]
No problem, I'll start working on it soon.

**Comment by TomSchimansky** [comment]
Do you know if this also applies to other desktop environments or just GNOME? Or is this independent of the desktop environment?

**Comment by TomSchimansky** [comment]
So it seems to be working on kali Linux but this is only one test, and that's not enough for me.

**Comment by lmwenda** [comment]
What type of linux do you have? @antrrax

**Comment by antrrax** [comment]
@lmwenda 
Linux Mint 20.3 Cinnamon

**Comment by antrrax** [comment]
@TomSchimansky , @lmwenda 
see this:
https://wiki.archlinux.org/title/Fonts

> 
> Manual installation
> 
> The recommended way of adding fonts that are not in the repositories of your system is described in #Creating a package. This gives pacman the ability to remove or update them at a later time.
> 
> Alternatively, fonts can be installed manually:
> 
>     For a single user, install fonts to ~/.local/share/fonts/.
>         In many cases this suffices, unless you run graphical applications as other users.
>         In the past ~/.fonts/ was used, but is now deprecated.

**Comment by lmwenda** [comment]
Yeah I've just done some research and this is true.
I'm currently making some changes and should make a pull request for @TomSchimansky to review soon.

**Comment by antrrax** [comment]
A complement to the previous answer.
see the file
/etc/fonts/fonts.conf

**the following element will be removed in the future:**
<dir>~/.fonts</dir>

**Comment by lmwenda** [comment]
The first pull request was a mistake so I closed it however I solved it with #353 pull request. I'm still waiting for @TomSchimansky to review

**Comment by TomSchimansky** [comment]
Changed the fonts directory on Linux now with version 4.5.11.
