### ISSUE TITLE
4.5.10 - self.geometry error

### ISSUE THREAD

**Issue by akseidel** [TomSchimansky/CustomTkinter#345]
After upgrading to 4.5.10 my code fails at the self.geomtry line:
```python
    w_width = 1120
    w_height = 668
    pos_x = int(self.winfo_screenwidth() / 2 - w_width / 2)
    pos_y = int(self.winfo_screenheight() / 3 - w_height / 2)
    self.geometry("{}x{}+{}+{}".format(w_width, w_height, pos_x, pos_y))
```

error statement is:

> File "/Users/aks/.pyenv/versions/3.9.13/lib/python3.9/site-packages/customtkinter/windows/ctk_tk.py", line 137, in geometry
>     numbers = list(map(int, re.split(r"[x+-]", geometry_string)))  # split geometry string into list of numbers
> ValueError: invalid literal for int() with base 10: ''

**Comment by akseidel** [comment]
The issue shows up starting with 4.5.7.

**Comment by akseidel** [comment]
I see this is the same as **Bug after changing the version from 4.5.6 to 4.5.9 (also to 4.5.7 or 4.5.8) #287**

**Comment by akseidel** [comment]
The values initially passed to self.geometry were: 1129, 668, 160, -34
This evaluated to the geometry string: "1129x668+160+-34"
That is where that [x+-] in the message comes from.
Hardcoding to self.geometry("1129x668+160+-34") generates the same problem. Ok, fine, the parsing
has a problem with +-.
But hardcoding  to self.geometry("1129x668+160+34") generates a different error. 
bad geometry specifier "1129x668x160+34"
I assume that x character before the 160 should be a + character.

**Comment by legopitstop** [comment]
Additionally when you just enter a screen position `self.geometry("+300+300")` it throws a similar error

**Comment by TomSchimansky** [comment]
I changed the parsing and the geometry method now works with the following formats:
```python
app.geometry("300x300")
app.geometry("-100-100")
app.geometry("+-100+-100")
app.geometry("+100+100")
app.geometry("300x300-100-100")
app.geometry("300x300+-100+-100")
app.geometry("300x300+100+100")
```
Tested in `test/manual_integration_tests/test_window_geometry.py`
I will upload the next version very soon.
