### ISSUE TITLE
Possible Bug with Radio Buttons

### ISSUE THREAD

**Issue by Hemang-Dwivedi** [TomSchimansky/CustomTkinter#35]
I am trying to make a radio button and this error is popping up,

File "xxxxxxxxxxx", line 171, in <module>
    rightoption1 = customtkinter.CTkRadioButton(test_create_frame, )
  File "xxxxxxxxxxx\venv\lib\site-packages\customtkinter\customtkinter_radiobutton.py", line 67, in __init__
    self.corner_radius = CTkThemeManager.theme["shape"]["radiobutton_corner_radius"] if corner_radius == "default_theme" else corner_radius
KeyError: 'radiobutton_corner_radius'

The part giving the error is:
rightoption1 = customtkinter.CTkRadioButton(test_create_frame, text="Option A is correct", )

**Comment by TomSchimansky** [comment]
Are you using a theme other than standard "blue"? There were versions were the other themes were missing some information for the new widgets, but in the current version this should be fixed. So try upgrading with:
`pip3 install customtkinter --upgrade`
