### ISSUE TITLE
Disabled buttons still trigger their corresponding event.

### ISSUE THREAD

**Issue by splewdge** [TomSchimansky/CustomTkinter#351]
Even if you configure a button to be **disabled**, the linked event will *still be fired* on the button press. The code in the attached video is the file `/examples/complex_example.py`

https://user-images.githubusercontent.com/110092160/182795839-d08588b3-3224-4a88-b5c8-694e36cd1213.mp4

.

**Comment by lmwenda** [comment]
I'll see what I can do and try help out.

Do you usually use tkinter?

**Comment by TheFallen-Cat** [comment]
Did you make any changes to the `complex_example.py` code?

**Comment by lmwenda** [comment]
Not yet, sorry. I'm new to the codebase and trying to work it out. I'm going to work on it now.

**Comment by lmwenda** [comment]
> Even if you configure a button to be **disabled**, the linked event will _still be fired_ on the button press. The code in the attached video is the file `/examples/complex_example.py`
> 2022-08-04.09-01-20.mp4
> 
> . May you please send your current code? Or is it straight copy and paste from complex_example.py?

**Comment by splewdge** [comment]
> Did you make any changes to the `complex_example.py` code?

No

**Comment by splewdge** [comment]
> I'll see what I can do and try help out.
> 
> Do you usually use tkinter?

No, not really.

**Comment by lmwenda** [comment]
> > Did you make any changes to the `complex_example.py` code?
> 
> No. It is a direct copy of the complex example code.

Ah Alright, I'll see what I can do.

**Comment by lmwenda** [comment]
It's strange because I ran the exact same code and the disabled button functions as it should. the `button_event()` doesn't run since its disabled

**Comment by splewdge** [comment]
I found a fix. One [this](https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/widgets/ctk_button.py#L365) line, `is not` should be changed to `!=` to fix the bug (at least for me). Even if it doesn't change anything for you, it would be a better practise to use `!=` than `is not`, since `!=` checks for value inequality, whereas `is not` checks for reference inequality, and in this case we are looking for value inequality.

**Comment by lmwenda** [comment]
Alright, thanks. I can create a pull request.

**Comment by splewdge** [comment]
I made one [here](https://github.com/TomSchimansky/CustomTkinter/pull/352).

**Comment by lmwenda** [comment]
Alright, thanks.

**Comment by TomSchimansky** [comment]
@splewdge which python version are you using?

**Comment by splewdge** [comment]
> @splewdge which python version are you using?

Python 3.9

**Comment by TomSchimansky** [comment]
I got the point why comparing with != and "is not" is different, but I wonder why I never had problems with this. But nevermind, I changed it now...
