### ISSUE TITLE
TextBox Jump to End

### ISSUE THREAD

**Issue by geoffbroth** [TomSchimansky/CustomTkinter#369]
With tkinter you can jump to the end of the textbox with the .see('end') method.  Is this available with customtkinter?  Thanks!

**Comment by Nomanpour** [comment]
https://github.com/TomSchimansky/CustomTkinter/discussions/297

**Comment by TomSchimansky** [comment]
Look here: https://github.com/TomSchimansky/CustomTkinter/issues/378
