### ISSUE TITLE
Script Error when converted .py to .exe

### ISSUE THREAD

**Issue by gravityyusuf** [TomSchimansky/CustomTkinter#37]
I got this error when I tried opening my .exe file,
Also when I run this .exe the customtkinter library isnt there in temp folder too smh that means pyinstaller cant recognize this library.
![image](https://user-images.githubusercontent.com/57557257/158196277-abe7990c-9712-40ca-a94e-14a2ca76da08.png)

**Comment by TomSchimansky** [comment]
Can your process of compiling to an .exe program. I never tried to package something with customtkinter, but the error means that the external files (not the .py files) of the library were not copied to the new standalone app.

**Comment by gravityyusuf** [comment]
https://www.geeksforgeeks.org/convert-python-script-to-exe-file/amp/
I used this method this is the generalized method,
I also tried to convert your examples which you gave in the github same error happened for that too.

**Comment by TomSchimansky** [comment]
I looked at this guide: https://dev.to/eshleron/how-to-convert-py-to-exe-step-by-step-guide-3cfi
And it states that the one-file-option, what you did above, is only suitable for programs without media files. But  customtkinter needs media files. The library does not only contain .py files, but also .json and .otf font files. So I think you need to use the other option which is described in the guide, which creates a folder in addition to the .exe file.

**Comment by gravityyusuf** [comment]
Thanks it worked :) amazing I think so you should add this in the documentation or is this common thing idk but I added the directory of customtkinter in the py to exe converter and it worked !

**Comment by TomSchimansky** [comment]
Yeah I got it to work too, with this method. I don't know if this will work for everyone, or if its a good idea to add a library this way, but it works for now. I will add this in the documentation!
