### ISSUE TITLE
Customtkinter destroy

### ISSUE THREAD

**Issue by galipyuksel** [TomSchimansky/CustomTkinter#375]
After the `self.destroy()` code is activated, something appears on the console as in the picture. What is this?
![image](https://user-images.githubusercontent.com/85893202/183591136-1ffaa701-fb1d-4657-af33-d4e92f9c6af1.png)

**Comment by Jdsdofp** [comment]
it's pointing the same log in my project🤔

**Comment by luisotaviocintra** [comment]
Here too, same message...

**Comment by TomSchimansky** [comment]
@galipyuksel can you post an example code where this appears for you?

**Comment by Aadhityaa04** [comment]
link for the code: [https://github.com/Aadhityaa04/Customtkinter-destroy---error/blob/2fa951752cbc9e26819997b1ef0e596a96fbcb77/playgrund.py](url)
<img width="343" alt="Screenshot 2022-09-04 110957" src="https://user-images.githubusercontent.com/112793792/188299195-9c2bdfaf-c1c4-460f-8737-f1d564717c02.png">
while clicking login button you will get the error. Maybe in line 25.

**Comment by PosthumasFrankestein** [comment]
Your link is broken.

**Comment by Aadhityaa04** [comment]
Sorry for the inconveniences [Click this ](https://github.com/Aadhityaa04/Customtkinter-destroy---error)

**Comment by TomSchimansky** [comment]
@Aadhityaa04 you can not create multiple instances of CTk in the same process. Here is an example on how you would create a second window, which can only be opened once and which is written as a class:
```python
import customtkinter


class ToplevelWindow(customtkinter.CTkToplevel):
    def __init__(self, *args, closing_event=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.protocol("WM_DELETE_WINDOW", self.closing)
        self.geometry("500x300")
        self.closing_event = closing_event

        self.label = customtkinter.CTkLabel(self, text="ToplevelWindow")
        self.label.pack(padx=20, pady=20)

    def closing(self):
        self.destroy()
        if self.closing_event is not None:
            self.closing_event()


class App(customtkinter.CTk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.geometry("500x400")

        self.button_1 = customtkinter.CTkButton(self, text="Open CTkToplevel", command=self.open_toplevel)
        self.button_1.pack(side="top", padx=40, pady=40)

        self.toplevel_window = None

    def open_toplevel(self):
        if self.toplevel_window is None:  # create toplevel window only if not already open
            self.toplevel_window = ToplevelWindow(self, closing_event=self.toplevel_close_event)

    def toplevel_close_event(self):
        self.toplevel_window = None


if __name__ == "__main__":
    app = App()
    app.mainloop()
```
If you follow this template there shouldn't be any `invalid command name` logs. Personally I never experienced them...
