### ISSUE TITLE
CTkTextbox placeholder and UI problem

### ISSUE THREAD

**Issue by DyNgPinasOfficial** [TomSchimansky/CustomTkinter#378]
- There is no documentation yet about this on the Wiki of this repository.
- Doesn't recognize the placeholder of CTk
- tried other ways of putting a placeholder but still not working
- The inner border of the textbox is visible
![image](https://user-images.githubusercontent.com/50480977/183793349-804ecda2-a788-43cb-9417-30b1fb88fdfb.png)

**Comment by TomSchimansky** [comment]
The CTkTextbox is under development and not finished yet. Therefore its not mentioned in the wiki. I just made it usable in the pip version by accident and now everyone is complaining about it not working properly, maybe I will just remove it in the next upgrade until its finished 😅.
