### ISSUE TITLE
AttributeError: 'CTkTextbox' object has no attribute 'get'

### ISSUE THREAD

**Issue by Barry-sze** [TomSchimansky/CustomTkinter#386]
How to resolve ?
AttributeError: 'CTkTextbox' object has no attribute 'get'
Textbox_3=customtkinter.CTkTextbox(master=frame_1,height = 165,width=290)
Textbox_3.get() can not work.
Pls help

**Comment by Mohammed-Ibrahim99** [comment]
That it is kind of weird, for now you could use this:

```
    Textbox_3 = customtkinter.CTkTextbox(master=frame_1, height=165, width=290)
    Textbox_3.textbox.get('1.0', tk.END)
```

One thing I am a bit worried about is the text box is not the documentation which could mean the owner has future plans for it later on, this means it could change at any time.

**Comment by TomSchimansky** [comment]
The CTkTextbox is still under development and therefore also not present in the wiki. A lot of functionality is still missing.

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/378
