### ISSUE TITLE
ipadx and ipady args in grid() and pack() not accepting tuple arguments, int argument only pads one side

### ISSUE THREAD

**Issue by captainbanaynays** [TomSchimansky/CustomTkinter#389]
```
import tkinter
from customtkinter import *

root = CTk()
general = CTkFrame(master=root)
general.pack(ipadx=(10, 50), ipady=(10, 50))
CTkLabel(master=general, text="Is it centered?").pack()
root.mainloop()
```

When I try to run above code, I get a TclError: bad ipadx value "10 50": must be positive screen distance.

If instead I set ipadx=10 and ipady=10, this is the result:
<img width="712" alt="Screen Shot 2022-08-16 at 3 16 44 PM" src="https://user-images.githubusercontent.com/22987660/184963576-a898f883-3d02-4fe3-bf2c-a4ab97e65d68.png">

In a more complex example, the following code produces the following result:

import tkinter
from customtkinter import *

```
root = tkinter.Tk()
general = CTkFrame(master=root, fg_color=('#F3F4F7', '#091D7F'))
general.pack(side='top', pady=(20, 50), ipadx=90, ipady=10)
CTkLabel(master=general, text='General', text_font="System 14 bold").grid(row=0, column=0, columnspan=2)
CTkCheckBox(master=general, hover_color=("#374795", "#F3F4F7"),
            fg_color=("#091D7F", "white"), text='').grid(row=1, column=0)
CTkLabel(master=general, text='Generate Barnyard Stats').grid(row=1, column=1)
CTkCheckBox(master=general, hover_color=("#374795", "#F3F4F7"), fg_color=("#091D7F", "white"), text='').grid(row=2, column=0)
CTkLabel(master=general, text='Resume Last Run').grid(row=2, column=1)

root.mainloop()
```
<img width="712" alt="Screen Shot 2022-08-16 at 3 32 04 PM" src="https://user-images.githubusercontent.com/22987660/184966187-b8b3d05c-29cc-41a0-b872-e8ad9f68e273.png">

What is causing the ipadx value to be asymmetrical? Only one int is specified for each dimension.

**Comment by captainbanaynays** [comment]
The text is being gridded in this way instead of using the baked in text option for the checkbox to left align the checkboxes, but there should still be internal padding to the left of the leftalign.

**Comment by TomSchimansky** [comment]
Sometimes I thought the internal padding of tkinter isn't working at all but sometimes it has an effect, but its not reliable, I just wouldn't use it. I don't know what's the problem there but you would have to write a bug report for tkinter, because I have no influence on the geometry managers with customtkinter, its all tkinter.

I don't know exactly how you want your example to look like, but I would do something like the following without extra labels for the checkboxes, because I don't think its necessary:
```python
import customtkinter

app = customtkinter.CTk()
app.grid_columnconfigure(0, weight=1)

general_frame = customtkinter.CTkFrame(master=app)
general_frame.grid(row=0, column=0, padx=20, pady=20, sticky="ns")
app.grid_columnconfigure(0, weight=1)

header_label = customtkinter.CTkLabel(master=general_frame, text='General', text_font="System 14 bold")
header_label.grid(row=0, column=0, padx=10, pady=10)

checkbox_1 = customtkinter.CTkCheckBox(master=general_frame, text='Generate Barnyard Stats')
checkbox_1.grid(row=1, column=0, padx=20, pady=(10, 0), sticky="w")
checkbox_2 = customtkinter.CTkCheckBox(master=general_frame, text='Resume Last Run')
checkbox_2.grid(row=2, column=0, padx=20, pady=(10, 20), sticky="w")

app.mainloop()
```
<img width="707" alt="Bildschirmfoto 2022-08-16 um 22 05 38" src="https://user-images.githubusercontent.com/66446067/184974677-47556036-776b-4714-959e-ed52bf8ecdfc.png">

**Comment by TomSchimansky** [comment]
And as a tip, I would structure your tkinter programs with classes like I described here: https://github.com/TomSchimansky/CustomTkinter/wiki/Multiple-frames
