### ISSUE TITLE
AttributeError: 'str' object has no attribute '_root'

### ISSUE THREAD

**Issue by ertucode** [TomSchimansky/CustomTkinter#39]
- This is the code which i copy pasted from you

import tkinter
import customtkinter

customtkinter.set_appearance_mode("System")  # Modes: system (default), light, dark
customtkinter.set_default_color_theme("blue")  # Themes: blue (default), dark-blue, green

root_tk = customtkinter.CTk()  # create CTk window like you do with the Tk window
root_tk.geometry("400x240")

check_var = tkinter.StringVar("on")

def checkbox_event():
    print("checkbox toggled, current value:", check_var.get())

checkbox = customtkinter.CTkCheckBox(master=root_tk, text="CTkCheckBox", command=checkbox_event,
                                     variable=check_var, onvalue="on", offvalue="off")

root_tk.mainloop()

- With this code i get this error 

  File "c:\Users\____\venv\ProjectName\main.py", line 29, in <module>
    check_var = tkinter.StringVar("on")
  File "C:\Users\____\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 540, in __init__
    Variable.__init__(self, master, value, name)
  File "C:\Users\____\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'str' object has no attribute '_root'

**What i am missing here**

**Comment by ertucode** [comment]
When I use check_var = tkinter.StringVar() instead 
>I get "off" when it is on, "on" when it is off

**Comment by forsaken-dev** [comment]
try
`import tkinter
import customtkinter

customtkinter.set_appearance_mode("System") # Modes: system (default), light, dark
customtkinter.set_default_color_theme("blue") # Themes: blue (default), dark-blue, green

root_tk = customtkinter.CTk() # create CTk window like you do with the Tk window
root_tk.geometry("400x240")


def checkbox_event():
    global checkbox
    print("checkbox toggled, current value:", checkbox.get())

checkbox = customtkinter.CTkCheckBox(master=root_tk, text="CTkCheckBox", command=checkbox_event, onvalue="on", offvalue="off")
checkbox.pack()

root_tk.mainloop()`

**Comment by forsaken-dev** [comment]
try this

```
import tkinter
import customtkinter

customtkinter.set_appearance_mode("System") # Modes: system (default), light, dark
customtkinter.set_default_color_theme("blue") # Themes: blue (default), dark-blue, green

root_tk = customtkinter.CTk() # create CTk window like you do with the Tk window
root_tk.geometry("400x240")


def checkbox_event():
    print("checkbox toggled, current value:", checkbox.get())

checkbox = customtkinter.CTkCheckBox(master=root_tk, text="CTkCheckBox", command=checkbox_event, onvalue="on", offvalue="off")
checkbox.pack()

root_tk.mainloop()
```

**Comment by ertucode** [comment]
Thank you for the answer, but me forgetting to pack wasn't the cause of this problem.

I just solved it on my own. 

- The solutions is as follows if anyone wonders

from dataclasses import dataclass
```
@dataclass
class Checkbox:
    root: object

    def __post_init__(self):
        self.var = tkinter.StringVar()
        self.checkbox = customtkinter.CTkCheckBox(master=self.root, text="Check", variable=self.var, 
                                                    offvalue="off", onvalue="on",command=self.checkbox_event)
        self.checkbox.pack(padx=20, pady=5)

    def checkbox_event(self):
        print("checkbox toggled, current value:", self.checkbox.get())

# Then you can create as many checkboxes as you want and the toggle works perfectly

checkboxs = []
for i in range(0,20):
    checkboxs.append(Checkbox(root_tk))
```

**Comment by glr-87278mau** [comment]
hey, I'm having the same problem, so is the solution using a dataclass?

**Comment by TomSchimansky** [comment]
Hi, @glr-87278mau can you again explain what your'e doing and paste the error you're getting? Are you using tkinter variables too?

**Comment by glr-87278mau** [comment]
> Hi, @glr-87278mau can you again explain what your'e doing and paste the error you're getting? Are you using tkinter variables too?

Hi, I fixed the problem by creating the checkboxes in the same function I use to count the number of checked checkboxes, I don't have the error anymore sorry!
