### ISSUE TITLE
alpha channel for widgets

### ISSUE THREAD

**Issue by CarlosHGL** [TomSchimansky/CustomTkinter#390]
I would love it if adding the alpha channel option for customtkinter widgets and canvas would help a lot, and solve a lot of problems.

**Comment by TomSchimansky** [comment]
alpha channel and transparent is not possible in tkinter and therefore will be never possible in customtkinter. There are some limited transparency options for tkinter, where you can set a specific color to be transparent, but it's not useful and reliable across platforms.
