### ISSUE TITLE
cget command to get variable

### ISSUE THREAD

**Issue by luisotaviocintra** [TomSchimansky/CustomTkinter#395]
cget doesn't work either.

**Comment by TomSchimansky** [comment]
Its not implemented... Maybe I will do it at some point

**Comment by luisotaviocintra** [comment]
fine, I managed to get around it. thanks!

**Comment by CarlosHGL** [comment]
> fine, I managed to get around it. thanks!
could you show me your solution?

**Comment by luisotaviocintra** [comment]
> 

In my case, I just needed the text of a button, so I simply used:
var = IntVar()
btn = customtkinter.CTkButton(master, text='A', textvariable=var)
text = btn.text
variable = btn.textvariable
...

**Comment by luisotaviocintra** [comment]
> 

No meu caso, eu só precisava do texto de um botão, então simplesmente usei:
var = IntVar()
btn = customtkinter.CTkButton(master, text='A', textvariable=var)
text = btn.text
variable = btn. variável de texto
...

**Comment by luisotaviocintra** [comment]
> could you show me your solution?

In my case, I just needed the text of a button, so I simply used:
var = IntVar()
btn = customtkinter.CTkButton(master, text='A', textvariable=var)
text = btn.text
variable = btn.textvariable

**Comment by fathimaNasmin** [comment]
How to get CTkLabel text?
.cget("text") is not working for CTkLabel

**Comment by Nikushavar** [comment]
> fine, I managed to get around it. thanks!

hello, i also need cget but it isn't working, can you tell me how you got around it?

**Comment by TomSchimansky** [comment]
cget is now implemented.

**Comment by Nikushavar** [comment]
> cget is now implemented.



> cget is now implemented.

Es gab anno '02 eine große Rauferei
Da war mein lieber biererprobter Opapa dabei
Es war die größte Sensation im deutschen Kaiserreich
Und wie es damals zuging, das erzähl' ich ihnen gleich
 
Hurra, das war noch ein herrliches Vergnügen
Da zeigte sich der bayerische-deutsche Mannesmut
Wenn Krüge und Zähne durch die Gegend fliegen
Das tut dem echten, rechten Mann seit jeher schon so gut
 
In München geschah es, auf dem Oktoberfest:
Ein Mann probierte aus, wie sich's am Boden schlafen lässt
Ein Schutzmann kam und stemmte das Subjekt zu sich herauf
Da setzte ihm ein Dritter seinen vollen Maßkrug auf
 
Hurra, das war noch ein herrliches Vergnügen
Da zeigte sich der bayerische-deutsche Mannesmut
Wenn Krüge und Zähne durch die Gegend fliegen
Das tut dem echten, rechten Mann seit jeher schon so gut
 
Mit Schnurrbart und Helm kam die Wiesenpolizei
Und stand dem braven Schutzmann mit der Maßkrugkeule bei
Die Bierverbraucher ihrerseits, die tranken hastig aus
Dann warfen sie die Krüge und die Polizei hinaus
 
Hurra, das war noch ein herrliches Vergnügen
Da zeigte sich der bayerische-deutsche Mannesmut
Wenn Krüge und Zähne durch die Gegend fliegen
Das tut dem echten, rechten Mann seit jeher schon so gut
 
Da kam hoch zu Ross die Ulanenpolizei
Doch das war den erbosten Wiesendimpfeln grade recht
Denn jeder stieg auf ein Pferd der Brauerei
Und schon begann ein imposantes Kavall'riegefecht
 
(Hackts zua - hackts zua, hackts zua)
(Hackts zua - hackts zua)
 
Die Onkeln und Freunde der feindlichen Partei'n
Die griffen frohen Mutes in das Kampfgeschehen ein
Und weil's so schön war, hat sich jeder irgendwen gekauft
Und 15.000 Menschen haben frisch drauflosgerauft
 
Hurra, das war noch ein herrliches Vergnügen
Da zeigte sich der bayerische-deutsche Mannesmut
Wenn Krüge und Zähne durch die Gegend fliegen
Das tut dem echten, rechten Mann seit jeher schon so gut
 
Die Schlacht war geschlagen, die Räusche war'n vorbei
Wer gesiegt hat, ist leider auch heut' noch ungewiss
Mein Opa blieb noch die Nacht bis um drei
Und suchte auf dem Broadway sein verlorenes Gebiss
 
(Hackts zua, hackts zua, hackts zua)
(Hackts zua, hackts zua)
(Hackts zua, hackts zua, hackts zua - hackts zua)
