### ISSUE TITLE
Line-height option for text

### ISSUE THREAD

**Issue by Cptain** [TomSchimansky/CustomTkinter#396]
Is it possible to customize this spacing between each new line (line-height) somehow?

![image](https://user-images.githubusercontent.com/5928159/185216611-73eefdab-b775-4179-9f50-48f0a8565cde.png)

**Comment by CarlosHGL** [comment]
if you want the buttons to have a spacing between them you can use padx or pady.

example:
clickme = CTkButton(master=root, text=click me,)
clickme.grid(column=1, row=0, padx=0, pady=15)

**Comment by TomSchimansky** [comment]
@Cptain The tkinter/customtkinter label does not allow for any changes of the line height. You would have to use a textbook to achieve this. There will be a CTkTextBox, but its not completed yet.
