### ISSUE TITLE
Why can you not have an InputDialog be in the same window?

### ISSUE THREAD

**Issue by 32-git** [TomSchimansky/CustomTkinter#402]
Why is it that another window is automatically opened for InputDialogs? Or am I missing something? Because I would really like to have an input field within the originial app window.

**Comment by liviayas** [comment]
Can't you use the .CTkEntry()?

If this is the case, there is a simple example here: https://pypi.org/project/customtkinter/0.3/

**Comment by TomSchimansky** [comment]
A CTkInputDialog opens a new window and an entry is a widget inside the window...
