### ISSUE TITLE
CTK.switch with two labels

### ISSUE THREAD

**Issue by Mohammed-Ibrahim99** [TomSchimansky/CustomTkinter#403]
I was wondering if it's possible to add a text on both sides of the switch just like constant and random shown below. Is this currently available? if not would it be a good idea to add it as an option to the current switch?

![image](https://user-images.githubusercontent.com/61741122/185807316-50e80b47-f110-4e00-b5aa-257063ac2dc4.png)

I was able to do the example above using the following piece of code for the switch

```
    root = customtkinter.CTk()
    switch_var = customtkinter.StringVar(value="Constant")
    label = customtkinter.CTkLabel(root, text='Constant  ', width=0, height=18)
    label.grid(row=1, column=1, pady=5, sticky=tk.W)
    switch = customtkinter.CTkSwitch(root, text='Random', command=switch_event, variable=switch_var, onvalue="Random", offvalue="Constant")
    switch.grid(row=1, column=2, pady=5, sticky=tk.E)
    root.mainloop()
```

**Comment by TomSchimansky** [comment]
Currently its not available, maybe I will add it at some point, but currently there are more urgent things...
