### ISSUE TITLE
AttributeError: 'CTkTextbox' object has no attribute 'delete'

### ISSUE THREAD

**Issue by sim2511** [TomSchimansky/CustomTkinter#405]
Hello,

I can not text.delete(0, END), but its already a command for textbox, any idea why ?

here the error message :
AttributeError: 'CTkTextbox' object has no attribute 'delete'

Regards,

**Comment by TomSchimansky** [comment]
The textbook is not completed: https://github.com/TomSchimansky/CustomTkinter/issues/378

**Comment by sim2511** [comment]
Ok thanks for your answer. Do you see a workaround i could do ?
