### ISSUE TITLE
Wrong option menu display

### ISSUE THREAD

**Issue by SanderBevers22** [TomSchimansky/CustomTkinter#416]
Unfortunately I cannot post my code here but I can give an example:

Whenever I want to use the CTkOptionMenu I do this by menu = ctk.CTkOptionMenu(master=frame, values=["Option 1", "Option 2"], command=random function here)
menu.grid(row=a row, column= a column)

However, I get this drop down menu that looks like tkinter and not customtkinter:

<img width="112" alt="optionmenu" src="https://user-images.githubusercontent.com/101271849/186685689-31544882-9d0a-404e-b7b6-74521cd96d6e.png">

Could it be because i'm using an older version of customtkinter or is there something else going on here?

**Comment by TomSchimansky** [comment]
Have a look at https://github.com/TomSchimansky/CustomTkinter/issues/304 and https://github.com/TomSchimansky/CustomTkinter/issues/196
