### ISSUE TITLE
Is there no Menu widget for Custom Tkinter ?

### ISSUE THREAD

**Issue by dibakarbose** [TomSchimansky/CustomTkinter#417]
Hi,

I was not able to find custom Menu Widget. If I use the default one and use the dark theme the result which I get is as below

![image](https://user-images.githubusercontent.com/16408964/186693971-9ae52623-9fe1-4923-9dd9-f6898e4f38cf.png)

If the menu bar color also changes based on the theme it would look better I believe. Anything possible like that ?

**Comment by felipetesc** [comment]
Have a look at https://github.com/TomSchimansky/CustomTkinter/issues/220

**Comment by dibakarbose** [comment]
Thanks.. I will try this

**Comment by TomSchimansky** [comment]
Currently there is no CTk menu bar or CTk menu, but maybe I will add this in the future!
