### ISSUE TITLE
Issue with window display

### ISSUE THREAD

**Issue by dibakarbose** [TomSchimansky/CustomTkinter#418]
For the below code I am getting this kind of display. Why is there extra white boxes in the window. I have just added padding only. Is there any way to get rid of that.

```
import tkinter as tk
import customtkinter as ctk


class App(ctk.CTk):

	def __init__(self):
		super().__init__()
		self.set_appearance_mode("Dark")
		self.title("Demo")
		self.geometry('700x430')
		self.resizable(False, False)
		self.top_frame = ctk.CTkFrame(self)
		self.mid_frame_1 = ctk.CTkFrame(self)
		self.mid_frame_2 = ctk.CTkFrame(self)
		self.bottom_frame = ctk.CTkFrame(self)
		self.top_frame['padding'] = (5, 10, 5, 10)
		self.mid_frame_1['padding'] = (5, 10, 5, 10)
		self.mid_frame_2['padding'] = (10, 10, 10, 10)
		self.bottom_frame['padding'] = (5, 10, 5, 10)
		self.top_frame.grid(row=0, column=0, columnspan=2)
		self.mid_frame_1.grid(row=1, column=0)
		self.mid_frame_2.grid(row=1, column=1)
		self.bottom_frame.grid(row=2, column=0, columnspan=2)

		top_label = ctk.CTkLabel(self.top_frame, text="Today's Date : ")
		top_label.grid(row=0, column=0)

if __name__ == "__main__":
	app = App()
	app.mainloop()
```

The output that I am getting is below :
![image](https://user-images.githubusercontent.com/16408964/186708301-00b6fedd-9248-4eb1-a6f0-3133e9c887f9.png)

Can anyone please help me with this ?

**Comment by dibakarbose** [comment]
It seems that CTkFrame is automatically adding a `fg_color` and hence it shows like this.

**Comment by TomSchimansky** [comment]
The frames have a default color yes, if you want them to be the same as the background you have to set `fg_color=None`. But somehoww your frames are in light mode while the window is in dark mode. Maybe try calling `self.set_appearance_mode("Dark")` at the beginning of the program.

**Comment by dibakarbose** [comment]
Sure. I will try that
