### ISSUE TITLE
ComboBox dropdown has border which can't be removed

### ISSUE THREAD

**Issue by 32-git** [TomSchimansky/CustomTkinter#438]
The code I have for my ComboBox is the following:
```
combobox = CTkComboBox(master=root, values=["--", "Length", "Area", "Volume", "Mass", "Temperature"],
                       width=200, height=30, corner_radius=8, command=fields, text_color="chartreuse3", 
                       dropdown_text_font=("OCR A Extended", 10), dropdown_text_color="chartreuse3")
```

And this is the output:
![image](https://user-images.githubusercontent.com/110297700/189436431-687796fc-8fb7-434f-9736-2c88f7f85fea.png)

`border_width=0` does not change anything for the dropdown, but merely for the selection menu above:
![image](https://user-images.githubusercontent.com/110297700/189436589-e1ea74ca-9586-4a49-9f88-0fee9e0abc1e.png)

**Question: How do I remove that white border around the dropdown field?**

I would be very grateful towards any assistance regarding this matter.

**Comment by TomSchimansky** [comment]
The dropdown uses a tinter menu and the white border around the tkinter.Menu sadly can't be removed on Windows...
