### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by thisSELFmySELF** [TomSchimansky/CustomTkinter#44]
Hi Tom,

Noticed you had some update changes to the install package recently so I ran the pip3 install customtkinter --upgrade.

I'm getting traceback errrors when I try to run my python script and the test examples you have provided.

The error:

justinho@Justins-Mac-mini test % python3 test_all_widgets_with_colors.py
Traceback (most recent call last):
  File "/Users/justinho/Downloads/CustomTkinter-master/test/test_all_widgets_with_colors.py", line 2, in <module>
    import customtkinter  # <- import the CustomTkinter module
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/customtkinter/__init__.py", line 4, in <module>
    from .widgets.customtkinter_button import CTkButton
ModuleNotFoundError: No module named 'customtkinter.widgets'

Seems like '.widget' in this __init__py file was added to all  customtkinters import modules for version 3.10.  

How do I roll back to 3.9 or the files associated with the previous installation package?

I'm on OSX Monterey M1 Mac mini.  Python 3.10.4.

Any assistance would be much appreciated,

Justin

**Comment by TomSchimansky** [comment]
Thanks a lot for reporting this, I forgot to include one module (`customtkinter.widgets`) when building it for pip. So the latest update (Version 3.10) was not functional: But version 3.11 no should work fine.
