### ISSUE TITLE
CustomeTkinter

### ISSUE THREAD

**Issue by Hirusha-Dulaj** [TomSchimansky/CustomTkinter#443]
Hey I used CustomeTkinter to Make program today i convert it to exe it's successfully converted but i Open it Nothing happened ☹️WHT is the problem bro

**Comment by Akascape** [comment]
@Hirusha-Dulaj Please give details, I hope you have followed this [guide](https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging) to convert your exe.

Run your application through CMD and provide the error details here.

**Comment by Hirusha-Dulaj** [comment]
Nothing show in cmd
I do it before 🤧

**Comment by Akascape** [comment]
@Hirusha-Dulaj Are you using Auto-py-to-exe or direct Pyinstaller? 
Give the details of your Pyinstaller code.

Try changing it to console based instead of window based.

**Comment by Hirusha-Dulaj** [comment]
I use pyinstaller and auto py to exe

**Comment by Akascape** [comment]
This should be the options:
![program.jpg](https://user-images.githubusercontent.com/89206401/189531877-6e407b4f-4be7-407c-8c1f-5592cf196cdd.jpg)

**Comment by Hirusha-Dulaj** [comment]
Thanks, I'll Try it ♥
