### ISSUE TITLE
corner_radius only increases width within labels

### ISSUE THREAD

**Issue by Jdeadevil** [TomSchimansky/CustomTkinter#446]
```
prompt_label = customtkinter.CTkLabel(master=app,
                                      text="Prompt",
                                      bg_color="#484848",
                                      width=10,
                                      height=25,
                                      text_font=("Calibri", 12),
                                      corner_radius=8
                                      )

prompt_label.place(x=20, y=20, anchor=tkinter.NW)

```

The corner radius doesn't change and if I increase it, it just increases the width of the button.

**Comment by Akascape** [comment]
@Jdeadevil It's because you have used `bg_color="#484848"` which is the background color for the button, instead you have to use `fg_color="#484848"`

![Example](https://user-images.githubusercontent.com/89206401/189685084-f3bacda3-88c7-415c-93e5-916c61c2c1c0.png)

**Comment by Jdeadevil** [comment]
Oh that explains everything, thanks.

________________________________

**Comment by Akascape** [comment]
@Jdeadevil Plz close the issue if it's answered

**Comment by Jdeadevil** [comment]
Done, I appreciate the timely response. Love this module.
