### ISSUE TITLE
TclErrors when trying to destroy all widgets in a CTkFrame

### ISSUE THREAD

**Issue by Lagejohn** [TomSchimansky/CustomTkinter#45]
First I'd like to say that this library is phenomenal and was exactly what I was looking for for my project!

As the title suggests, I'm running into errors when I try to iterate through .winfo_children() of a CTkFrame like below.
`for widgets in self.question_frame.winfo_children():
    widgets.destroy()`

This approach worked fine for my old TTK code, but I now get 
![image](https://user-images.githubusercontent.com/94564895/163105811-5286b22c-ce1b-44a1-8036-023b1b55be5d.png)
whenever I try the same code on a CTkFrame.

My current workaround is to destroy everything in the frame EXCEPT the ".!frame.![myclass].!ctkframe.!ctkframe.!ctkframe.!ctkcanvas" widget specifically, and that seems to be working. Is this intended behavior?

**Comment by TomSchimansky** [comment]
I could reproduce this error, the reason for this is that with `.winfo_children()` you not only delete the widgets you placed on the frame, but also the canvas widget which is used to render the round corners of the CTkFrame. The canvas is also a child of the CTkFrame and gets deleted. I will try to overwrite the `.winfo_children()` method and filter out the canvas widget.

**Comment by TomSchimansky** [comment]
You're method of deleting all child widget with `.winfo_children()` should work now with version 3.11. I removed the CTkFrame.canvas from the winfo_children list, and for me it works now.
