### ISSUE TITLE
Get the value of a Textbox

### ISSUE THREAD

**Issue by MiKalem898** [TomSchimansky/CustomTkinter#458]
I have to get the value of a Textbox but, how ? "get" and "getvar" don't work...

**Comment by Beelzebub-uwu** [comment]
can't you use CTkEntry?

**Comment by MiKalem898** [comment]
> ne pouvez-vous pas utiliser CTkEntry ?

The texts to enter are long and must be indented. I can use Entry, yes, but its better with Textbox

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/378
