### ISSUE TITLE
CtkOptionMenu enhancement

### ISSUE THREAD

**Issue by Beelzebub-uwu** [TomSchimansky/CustomTkinter#459]
is it possible to make it so that when the button is clicked a second time it closes the list instead of showing it again?
![image](https://user-images.githubusercontent.com/65181309/190902375-09575239-d5f7-45cb-8891-12f16d9c91a6.png)

**Comment by TomSchimansky** [comment]
I think there is no way of closing the menu when its open, because there is no way of telling if a tkinter.Menu is still open or already closed. But let me know if you know of a way doing it...
