### ISSUE TITLE
DPI scaling

### ISSUE THREAD

**Issue by dumblob** [TomSchimansky/CustomTkinter#46]
I wonder whether this library supports custom scaling of the whole application. Any hints?

Thanks!

**Comment by TomSchimansky** [comment]
At the moment there is no DPI scaling and the widgets won't look good on a HighDPI display with DPI scaling enabled (`ctypes.windll.shcore.SetProcessDpiAwareness(1)`), they will be too small. But it should be possible to just double all internal values for a 4K screen for example, and it should work. I just have to implement it, I will try to do it in the next time!

**Comment by dumblob** [comment]
Ok, thanks. Btw. do you think it'd be possible to implement non-integer scaling? That'd be desired IMHO for modern UIs.

**Comment by TomSchimansky** [comment]
That would be possible, I could simply scale the widgets with float value. But I'm not sure if the tkinter padding and positioning works correct when you activate DPI awareness for the window with `SetProcessDpiAwareness(1)`. Maybe I need to scale the padding too for example, but I need to test it.

**Comment by demberto** [comment]
Tk has its own scaling mechanism probably: https://stackoverflow.com/a/34133102/5541355

**Comment by TomSchimansky** [comment]
Scaling is now implemented with version 4.0.0, you can do the following:
```python
customtkinter.set_widget_scaling(float_value)
customtkinter.set_spacing_scaling(float_value)
customtkinter.set_window_scaling(float_value)
```
CustomTkinter additionally adapts to the system scaling on Windows and macOS:

<img width="827" alt="Windows_scaling" src="https://user-images.githubusercontent.com/66446067/169710599-b7479382-dd9d-4423-9d48-50ec06ca880a.png">

This is accomplished by setting ctypes.windll.shcore.SetProcessDpiAwareness(2), if you want to disable this automatic DPI awareness you can set:
```python
customtkinter.ScalingTracker.deactivate_automatic_dpi_awareness = True
```

**Comment by dumblob** [comment]
Nice, thanks a lot!

**Comment by knoopx** [comment]
just testing this for the first time, this is what I get on linux/gnome (scale at 150%) with:

```
customtkinter.set_widget_scaling(3)
customtkinter.set_spacing_scaling(3)
customtkinter.set_window_scaling(3)
```

![image](https://user-images.githubusercontent.com/100993/204411600-99ccb024-9726-4508-b629-68f32909ca44.png)

**Comment by TomSchimansky** [comment]
Do you have the newest version installed?
