### ISSUE TITLE
is there anyway to restart the gui trhough a button?

### ISSUE THREAD

**Issue by Beelzebub-uwu** [TomSchimansky/CustomTkinter#462]
there are some changes like the color theme that require a restart, is there any way to do it with a function linked to a button?

**Comment by TomSchimansky** [comment]
No, currently this is not possible but I will try to implement this at some point in the future! https://github.com/TomSchimansky/CustomTkinter/issues/295

**Comment by Beelzebub-uwu** [comment]
okay good to know :)
