### ISSUE TITLE
CTkComboBox background became white when state is "readonly"

### ISSUE THREAD

**Issue by ManHinnn0509** [TomSchimansky/CustomTkinter#464]
Thank you for creating this lib.

The background color of CTkComboBox() became white when the state is setted to "readonly"
customtkinter version: 4.6.3

![img](https://i.imgur.com/1EqxoiS.png)

**Comment by ManHinnn0509** [comment]
I found a solution to this issue, there's a `readonlybackground` parameter in `tk.Entry()` and you can use `configure()` to change to color of the entry.

Example code:
```python
self.comboBox.entry.configure(readonlybackgroun="#00ff00")
```

Solution from: https://stackoverflow.com/questions/28973756/tk-entry-background-color-change-in-readonly-mode

**Comment by TomSchimansky** [comment]
Should be resolved with version 5.0.0.

**Comment by FerumFist** [comment]
![image](https://github.com/TomSchimansky/CustomTkinter/assets/20613994/baecf09d-453a-4908-be47-d880591c75fb)

5.0.3 still has the bug
