### ISSUE TITLE
CTKScrollBar Does Not Allow Scrolling

### ISSUE THREAD

**Issue by SrikarGathey1** [TomSchimansky/CustomTkinter#474]
I am unable to scroll down using a CTKScrollBar. I could do the same easily using a TTK ScrollBar but it does not look good on the screen. Please try to resolve this if you can or let me know if there is a fix to this. Thank you.

**Comment by TomSchimansky** [comment]
Please show me a minimal example of the scrollbar not working, for me the scrollbar is working.
