### ISSUE TITLE
how to place video in frame

### ISSUE THREAD

**Issue by limpredator** [TomSchimansky/CustomTkinter#482]
so far have edited the modern gui and there is a frame in the middle, is there a way to add a video into it ?

![16642162084977293735421302766383](https://user-images.githubusercontent.com/114434805/192350699-1f16e579-ce18-47db-8d1f-ba12a0c11653.jpg)

**Comment by TomSchimansky** [comment]
Maybe look here: https://stackoverflow.com/questions/7227162/way-to-play-video-files-in-tkinter
CustomTkinter has no widgets for playing videos...
