### ISSUE TITLE
Window scalling

### ISSUE THREAD

**Issue by a95444** [TomSchimansky/CustomTkinter#483]
When I use my application in a monitor bigger than the one my laptop has, the widgets size just goes nuts. Is there any way I can "fixate" the size of the entire window/widgets?
Thanks for your time.

![biggermonitor](https://user-images.githubusercontent.com/92484922/192495141-a2675d22-7a87-4787-8c0a-810d8ac03124.png)
![mylaptop](https://user-images.githubusercontent.com/92484922/192495144-e9dadde4-90b0-445b-80fb-214ee0d7a68a.png)

**Comment by a95444** [comment]
# the listbox is a "normal tkinter" widget, I dont think customtkinter library has a listbox option yet.

**Comment by TomSchimansky** [comment]
Can you give me some information about your monitor setup?
What resolution has the external monitor? And what are the scaling settings (100%, 150%, 200%) for the internal and external monitor in the Windows display settings?
The first image is on the external monitor?

**Comment by a95444** [comment]
Yes of course!
1st image - external monitor /  100% ; 1920 x 1080
2nd image - laptop monitor  /   200%;  3000 x 2000
 
Thanks for the help! If you require some more info, I'll be glad to give it.

**Comment by TomSchimansky** [comment]
There are a few different things going on which make it look ugly:

1. The window header size remains like it was, when it got created. So when the window gets created on a 200% scaled monitor, the window header looks twice as big on a 100% monitor like the normal window headers. But there is nothing I can do about this I think, I don't know why this happens with tkinter windows.

2. Normal tkinter widgets don't adapt to the scaling set in Windows for the monitors. So when you design the app on the internal monitor you make the listbox as big as it needs to be to look normal with the font size. But when you move the window to the 100% monitor it looks way too big. Also something you can't do anything about it. You can just wait till I create a CTkListbox which will I will resize automatically according to the currently detected monitor scaling. I will also finish the CTkTextbox in the next time, maybe this will also work.

3. The images of the buttons also don't adapt to the scaling. That's something I will fix. When you move the window on the 100% monitor all the images would need to be resized to half the size...

4. The font size of the buttons (like FTC) is not scaled correctly. I don't know why this happened. How do you set the font size of the buttons? With a positive number in pt like ("Name", 12) or with a negative number in pixels like ("Name", -10)?

**Comment by a95444** [comment]
I didn't give a font size to the buttons text. I have configure them like this:
![image](https://user-images.githubusercontent.com/92484922/192515065-a0d8a3a8-3602-4429-a4b4-d7f131123016.png)

**Comment by TomSchimansky** [comment]
And how do you defined the buttons with AT SS FTC and DS contributive? Or are these labels?

**Comment by a95444** [comment]
They are buttons aswell.
![image](https://user-images.githubusercontent.com/92484922/192607551-ac6d1aa5-6608-41f5-9bc0-b51dc6a44771.png)

**Comment by TomSchimansky** [comment]
Most of the issues here should be fixed now, also by using CTkImage for the images.

**Comment by Karol1302** [comment]
Did you find a solution with a window header scalling? Got the same issue
