### ISSUE TITLE
Does it have a ListBox?

### ISSUE THREAD

**Issue by EgyptianM** [TomSchimansky/CustomTkinter#485]
Is there a ListBox widget in this library?

**Comment by TomSchimansky** [comment]
Not yet, only the ones in the wiki.

**Comment by Akascape** [comment]
@EgyptianM 
**I made this custom listbox for customtkinter:**
https://github.com/Akascape/CTkListbox

![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)
