### ISSUE TITLE
Demo only shows black window

### ISSUE THREAD

**Issue by network-shark** [TomSchimansky/CustomTkinter#49]
Hey ! 

Thank you for bringing the design for tkinter apps to a new century :) . 

I wish I could use it on my Mac m1 , but the demo code only shows a black window. 
If I click in the middle of the window I can see that the button event appears in the console. It is just black can't see the button.

Do you have any knowledge what could be the problem ? I am happy do provide logs or what ever. 

Actually there is no error in the console.

I am using python 3.9.9 MacOS 12.3.1

**Comment by TomSchimansky** [comment]
Hi, can you show me what this prints for you?
```python
import platform
import tkinter
import sys

print(sys.platform)
print(platform.python_version())
print(tkinter.Tcl().call("info", "patchlevel"))
```

**Comment by network-shark** [comment]
Thank you for pointing me to the right direction ! 

I am using pyenv which compiles python with an old tk version. Just for documentation .




Not working 
```
Python 3.10.3 (main, Apr 27 
Type "help", "copyright", 
>>> import tkinter
>>> tkinter.TclVersion, 
(8.5, 8.5)
```

How to compile https://xogk39.medium.com/install-tkinter-on-mac-pyenv-f112bd3f4663


Working 
```
>>> import tkinter
>>> tkinter.TclVersion, tkinter.TkVersion
(8.6, 8.6)
tkinter._test()>>> tkinter._test()
>>>
```

Thank you ! I will go ahead and close the issue

**Comment by TomSchimansky** [comment]
Ok fine, if it's working. The black screen occurs when macOS dark mode is activated, with a window created by Tcl/Tk < 8.6.9 and if the dark mode is forced on all windows like I do with the command: `defaults write -g NSRequiresAquaSystemAppearance -bool No`. But normally I check the Tcl version before this is done in the library, but somehow, here the command got executed anyways. Or it was executed by a customtkinter program running with Tcl/Tk >= 8.6.9 at the same time.
