### ISSUE TITLE
About creating listboxes in CustomTkinter

### ISSUE THREAD

**Issue by runbojungle** [TomSchimansky/CustomTkinter#491]
I am using tkinter to create multiple tools while employing tkinter listbox quite a lot! Just curious about if there's a way to create listboxes with CustomTkinter? If not, will listbox being considered as a feature in the future? Thank you so much for all the hard work on this project! The design is really pretty and amazing.

**Comment by TomSchimansky** [comment]
Duplicate: https://github.com/TomSchimansky/CustomTkinter/issues/69

**Comment by Akascape** [comment]
@runbojungle 
**I made this custom listbox for customtkinter:**
https://github.com/Akascape/CTkListbox

![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)

**Comment by BENZda** [comment]
> @runbojungle **I made this custom listbox for customtkinter:** https://github.com/Akascape/CTkListbox
> 
> ![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)

Nice work, but somehow it does not let me change the width and height, is this a known issue or is it an issue that only i have ?

**Comment by tamnva** [comment]
great work! thank you

**Comment by thierrycnf** [comment]
is there a way to deselect options after selecting them with your cursor?

**Comment by Akascape** [comment]
@thierrycnf Try `.deactivate(index)` method to deselect an option.

**Comment by thierrycnf** [comment]
![image](https://github.com/user-attachments/assets/4ae7e5d7-2bb7-4c97-b7c7-58c36979ece6)
These functions successfully deselect/delete the tasks that have been selected, all except the index 0/first task.  May I please have assistance in resolving these issues?

**Comment by thierrycnf** [comment]
@Akascape
