### ISSUE TITLE
CTKToplevel: resizable parameter not working!

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#493]
@TomSchimansky 
I want to make a fixed size CTKToplevel without any resizable parameter, so I used `Toplevel.resizable(width=False, height=False)` method.
But this is not working after the **new update**.
**Now the CTKToplevel is not even opening if we use this method.**

I don't want to use the `Toplevel.maxsize(width, height)` method as there is still a resizable button present.

It **used to** look like this in the older versions:

<img src=https://user-images.githubusercontent.com/89206401/193246524-bf5a5ee5-91af-4a2f-88e7-c0e5131198ae.png>

**Comment by TomSchimansky** [comment]
Already fixed, just need to upload a new version https://github.com/TomSchimansky/CustomTkinter/issues/469
