### ISSUE TITLE
CTkLabel.configure method shows unknown option "-text"

### ISSUE THREAD

**Issue by sarang-lvs** [TomSchimansky/CustomTkinter#496]
Created CTkLabel object in following way:

counterBox = ck.CTkLabel(window, height=40, width=120, text_font=("Arial", 20), text_color="white", fg_color="blue")

Can't update the text via .configure method like this:
counterBox.configure(text='0') 

It gives following error:
_tkinter.TclError: unknown option "-text"

I am a new programmer, so please forgive if this is an oversight. I have tried keeping text inside the object definition, but it is not able change it once set.

Thanks

**Comment by Akascape** [comment]
@sarang-lvs 
You have to use a StringVar if you want to change the text of the label. 

```python
text_var = tkinter.StringVar

counterBox = ck.CTkLabel(window, height=40, width=120, textvariable=text_var, text_font=("Arial", 20), text_color="white", fg_color="blue")
```

You have to use it like this:
```python
text_var.set("New_Text")
```
I know it's different from tkinter but this is how it works in customtkinter.

**Comment by TomSchimansky** [comment]
```python
ctk_label.configure(text="new text")
```
This should work with the new version 4.6.3 I think.
