### ISSUE TITLE
can you create a widget by which i can open websites in a customtkinter window

### ISSUE THREAD

**Issue by programmingbuilder** [TomSchimansky/CustomTkinter#502]
can you create a widget by which i can open websites in a customtkinter window

**Comment by TomSchimansky** [comment]
That's extremely complicated, but I think it's already done. Have a look at cefpython.

**Comment by felipetesc** [comment]
You can use webview for that: pywebview: 
- https://www.geeksforgeeks.org/how-to-open-a-website-in-a-tkinter-window/
- https://stackoverflow.com/questions/14706069/python-tkinter-with-a-simple-web-wrapper
if you want to open a link though https://docs.python.org/3/library/webbrowser.html
Have a good one
