### ISSUE TITLE
Font issue.

### ISSUE THREAD

**Issue by Jeymen** [TomSchimansky/CustomTkinter#506]
I tried setting the font, but it gives me a` TypeError: tkinter.Label() got multiple values for keyword argument 'font'` error. I debugged the file, and it seems to stay at the default font(Roberto)
![Screenshot 2022-10-08 122058](https://user-images.githubusercontent.com/109573368/194700390-fc2ccf35-79f8-4908-90d9-e502b8d99ffb.png)
![Screenshot 2022-10-08 122525](https://user-images.githubusercontent.com/109573368/194700409-bbfdaf19-e60b-4044-996a-e1cc5851682a.png)

**Comment by TomSchimansky** [comment]
The argument is called `text_font` at the moment. This will change in version 5.0.0, but for now you have to use text_font.

**Comment by Jeymen** [comment]
Alright, thanks.
