### ISSUE TITLE
Unsure of how to display a html page i.e https://google.com in a frame.

### ISSUE THREAD

**Issue by Bradly7412** [TomSchimansky/CustomTkinter#507]
Making a basic web browser in customtkinter, I have gotten the buttons to work same with the search entry. but not able to display a webpage without downloading the whole html page in another frame. `frame_1 = button and search entry` `frame_2 = webpage`. Any help would be amazing.

**Comment by TomSchimansky** [comment]
You cannot simply render a webpage in a CTkFrame, Customtkinter or Tkinter have no widgets to render webpages. But there are external libraries for Tkinter which you can probably use like cefpython, but I never tried to use them.
