### ISSUE TITLE
sticky don't work in Label.grid

### ISSUE THREAD

**Issue by HlDANN** [TomSchimansky/CustomTkinter#512]
Im try do this:

`labelNome = customtkinter.CTkLabel(frame, text="Nome", text_font=("Arial", "12"))
        labelNome.grid(row=1, column=0, padx=20, pady=10, sticky='w')`
        
![image](https://user-images.githubusercontent.com/44882409/195108492-6f52cab9-96cb-4593-a42d-84bd0b0433d0.png)

The sticky parameter does not work. Test using the default Label and everything is ok

`labelNome = Label(frame, text="Nome", font=("Arial", "12"))
        labelNome.grid(row=1, column=0, padx=20, pady=10, sticky='w')`

![image](https://user-images.githubusercontent.com/44882409/195108723-b3852a46-7c78-495e-a529-285b96eab2c7.png)

customtkinter does not support grid() method?

**Comment by HlDANN** [comment]
In my case it never worked :/ 
If anyone has a workaround I'd appreciate it, I don't like the pack method

**Comment by Akascape** [comment]
@HlDANN I think you have to use the 'anchor' parameter in that case.

` labelNome = customtkinter.CTkLabel(frame, text="Nome", text_font=("Arial", "12"), **anchor='w')** `

**Comment by HlDANN** [comment]
Hi @Akascape. Thanks for your contribution. Using anchor worked great!

I already knew this option, I hadn't tried it because some other widgets don't accept it ¯\_(ツ)_/¯

**Comment by iTerminatorX** [comment]
@HlDANN I tried anchor and it didn't work either :/

**Comment by Akascape** [comment]
@iTerminatorX I think you have problems in your layout system (grid or place).

I have two same labels here (one with anchor) and it's working properly:
```python
label = customtkinter.CTkLabel(master=frame_1,text="LABEL1", anchor='w')
label.grid(pady=10, padx=10)
label2 = customtkinter.CTkLabel(master=frame_1,text="LABEL2")
label2.grid(pady=10, padx=10)
```
![Screenshot](https://user-images.githubusercontent.com/89206401/196234326-a975a614-ae78-4786-a9ec-3dd241948f7d.jpg)
