### ISSUE TITLE
Retreiving .cget("fg_color") for customtkinter.CTkEntry ERROR: unknown option "-fg_color"

### ISSUE THREAD

**Issue by Free-Radical** [TomSchimansky/CustomTkinter#514]
Entry widget created -
`p_thr_entry = customtkinter.CTkEntry(master=prefs_window, width=40, placeholder_text=str(P_THR.get()))`
                   
Attempting to save Widget's initial fg_value-
    `tmp = p_thr_entry.cget("fg_color")`

ERROR-
main.py", line 349, in update_p_thr
    tmp = p_thr_entry.cget("fg_color")
  
File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 1681, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
_tkinter.TclError: unknown option "-fg_color"

PS, Following works-
`p_thr_entry.configure(fg_color='limegreen'`

**Comment by TomSchimansky** [comment]
The `cget()` method will be implemented in the next version 5.0.0. Currently there is no way of getting the internal values of the attributes. You can use the `fg_color` attribute, but these names will not stay the same. In version 5.0.0 I renamed all internal class attributes to be protected variables by adding a leading underscore. This indicates that you they should not be used outside of the class. Also so parameter names in the theme files can change from timt to time.

Version 5.0.0 will be released in the next days.
