### ISSUE TITLE
Buttons and File menu buttons don't launch TopLevel windows unless double-clicked

### ISSUE THREAD

**Issue by kdc1919** [TomSchimansky/CustomTkinter#516]
Good Day,

Yesterday I decided to upgrade to 4.6.3. Since then I've realized TopLevel windows by button click or file menu selection aren't working as they did before. In the older version I only had to click once to launch a TopLevel window. Now some windows aren't coming up with a single click. You have to double click. 

To launch TopLevel windows from the file menu, you click once on the menu item, then go back to the menu item and click again to launch a TopLevel window. 

Is it just me getting this strange bug or are other users getting the same thing?

Regards,

Kevin

**Comment by Akascape** [comment]
This was a bug, but it is already fixed.
It will be provided with the next version. https://github.com/TomSchimansky/CustomTkinter/issues/469

**Comment by TomSchimansky** [comment]
I don't really know what your are doing when you launch the toplevel window, so I can't say why this is not working as intended. But one possibility could be the bug mentioned in #469

**Comment by kdc1919** [comment]
Good Day,

I'm looking at the code for #469 and I believe it's a similar problem I have. For example here is some code from my project... 
`file_menu.add_command(label="Find Item", command=self.launch_inventory_items_form)`

def launch_inventory_items(self)
