### ISSUE TITLE
Question #3

### ISSUE THREAD

**Issue by Jeymen** [TomSchimansky/CustomTkinter#518]
Hello. Is there any way to make text clickable? When I say clickable, I don't mean hyperlink. For example, I wanna change text_2 from "Hello" to "Hello Word" when somebody clicks text_1. Is that possible?

**Comment by Akascape** [comment]
@Jeymen You can use a button with `fg_color=None, hover_color=None, bg_color=None`.
This will look exactly like a label. Then you can use command to change it.

**Comment by Jeymen** [comment]
Thanks!
