### ISSUE TITLE
Different font on windows 11

### ISSUE THREAD

**Issue by HlDANN** [TomSchimansky/CustomTkinter#519]
I was working on my work project normally when I decided to clone at home to work. 
After that I noticed that some labels were different. With the font half off. 
On the company pc I use windows 10, at home I use windows 11. I investigated further and realized that a label I created in standard Tkinter was normal and the labels made by customtkinter were strange. I tried to change the font a few times and nothing... 

I'll leave here some prints for comparison in win 11

Custom Tkinter:
`labelTitulo = customtkinter.CTkLabel(frame, text="Departamentos", text_font=("Verdana", "14", "bold"))`
`labelTitulo.grid(row=0, column=0, padx=20, pady=10)`

Result:
![image](https://user-images.githubusercontent.com/44882409/195962208-0a6809c7-09e5-40b2-beb5-f8da8a8c1064.png)
(It's well off, you can barely see it)

standard Tkinter:
`labelTitulo = Label(frame, text="Departamentos", font=("Verdana", "14", "bold"))`
`labelTitulo.grid(row=0, column=0, padx=20, pady=10)`

Result:
![image](https://user-images.githubusercontent.com/44882409/195962311-fc246d49-d886-4f83-baf8-920c79ad0120.png)

Does anyone have any tips?

**Comment by Akascape** [comment]
@HlDANN I think it's a text color issue, try `text_color="black"` in the CTkLabel.

**Comment by HlDANN** [comment]
@Akascape Works great! 
Thanks again. The job now is to edit all the labels :s
