### ISSUE TITLE
 from __future__ import annotations

### ISSUE THREAD

**Issue by Nielzaclord** [TomSchimansky/CustomTkinter#522]
File "C:\Users\Elève\AppData\Local\Programs\Python\Python36\lib\site-packages\customtkinter\draw_engine.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

I can't executhe with this error.

**Comment by Akascape** [comment]
@Nielzaclord Please upgrade your [python](https://www.python.org/downloads/) to the latest version.
Then also make sure that you are using the latest version of customtkinter.

**Comment by TomSchimansky** [comment]
Only python >= 3.7 is supported at the moment.
