### ISSUE TITLE
bind with variable

### ISSUE THREAD

**Issue by HlDANN** [TomSchimansky/CustomTkinter#529]
Hi! Im try this but didn't work :( :

`pesquisa.bind('<Return>', lambda event: popular(True))`
or
`pesquisa.bind('<Return>', lambda : popular(True))`

"pesquisa" is a custom button.

**Comment by Akascape** [comment]
@HlDANN You have to bind it with the main app (not the button).

Eg: `self.bind('<Return>', lambda event: popular(True))`
Now, if you press Enter, the *popular()* function will be called.

And please respond to your older issues: #519

**Comment by HlDANN** [comment]
Hi @Akascape Thanks for all your support so far. I'm going to work now to test your solution As for the #519  error, I haven't had the opportunity to test it yet :s but I'll do it today. Thanks

**Comment by HlDANN** [comment]
@Akascape The bind solution worked! As @TomSchimansky mentioned I hope that soon it will be possible to bind widgets individually. 

Thanks!
