### ISSUE TITLE
AttributeError: 'float' object has no attribute 'slider_atr'

### ISSUE THREAD

**Issue by glr-87278mau** [TomSchimansky/CustomTkinter#53]
Hi! I'm really enjoying customTkinter, However, I have run into a problem, I'm not sure how to fix this, any help is appreciated.

Code:
```python
        def indicator_settings(self):
            val_supertrend_atr = self.slider_atr.get()
            val_supertrend_factor = self.slider_factor.get()
            val_ema1_length = self.slider_ema1.get()
            val_ema2_length = self.slider_ema2.get()
            val_rsi_length = self.slider_rsi.get()
            val_leverage = self.slider_lev.get()
            print(val_supertrend_atr)
            print(val_supertrend_factor)
            print(val_ema1_length)
            print(val_ema2_length)
            print(val_rsi_length)
            print(val_leverage)

        self.rsi_length = customtkinter.CTkLabel(master=self.frame_right,
                                            text="RSI length")
        self.rsi_length.grid(row=1, column=2, columnspan=1, pady=10, padx=20, sticky="we")  
        self.slider_rsi = customtkinter.CTkSlider(master=self.frame_right,
                                                from_=1,
                                                to=32,
                                                number_of_steps=31,
                                                command=indicator_settings
                                                )
        self.slider_rsi.grid(row=2, column=2, columnspan=1, pady=10, padx=20, sticky="we")  
    ##SUPERTREND
        self.super_atr = customtkinter.CTkLabel(master=self.frame_right,
                                            text="Supertrend ATR")
        self.super_atr.grid(row=3, column=2, columnspan=1, pady=10, padx=20, sticky="we")  
        self.slider_atr = customtkinter.CTkSlider(master=self.frame_right,
                                                from_=1,
                                                to=32,
                                                number_of_steps=31,
                                                command=indicator_settings,
                                                )
        self.slider_atr.grid(row=4, column=2, columnspan=1, pady=10, padx=20, sticky="we")  
        
        self.super_factor = customtkinter.CTkLabel(master=self.frame_right,
                                            text="Supertrend Factor")
        self.super_factor.grid(row=5, column=2, columnspan=1, pady=10, padx=20, sticky="we")  
        self.slider_factor = customtkinter.CTkSlider(master=self.frame_right,
                                                from_=1,
                                                to=32,
                                                number_of_steps=31,
                                                command=indicator_settings,
                                                )
        self.slider_factor.grid(row=6, column=2, columnspan=1, pady=10, padx=20, sticky="we")  
        ##EMA
        self.ema1_length = customtkinter.CTkLabel(master=self.frame_right,
                                            text="EMA1 Length")
        self.ema1_length.grid(row=1, column=3, columnspan=1, pady=10, padx=20, sticky="we")  
        self.slider_ema1 = customtkinter.CTkSlider(master=self.frame_right,
                                                from_=1,
                                                to=32,
                                                number_of_steps=31,
                                                command=indicator_settings,
                                                )
        self.slider_ema1.grid(row=2, column=3, columnspan=1, pady=10, padx=20, sticky="we")  
        ##ema 2
        self.ema2_length = customtkinter.CTkLabel(master=self.frame_right,
                                            text="EMA2 Length")
        self.ema2_length.grid(row=3, column=3, columnspan=1, pady=10, padx=20, sticky="we")  
        self.slider_ema2 = customtkinter.CTkSlider(master=self.frame_right,
                                                from_=1,
                                                to=32,
                                                number_of_steps=31,
                                                command=indicator_settings,
                                                )
        self.slider_ema2.grid(row=4, column=3, columnspan=1, pady=10, padx=20, sticky="we")  

```
Error I receive: 
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\customtkinter\widgets\customtkinter_slider.py", line 219, in clicked
    self.callback_function(self.output_value)
  File "C:\Users\user\pyto\projects\website_bots\front\testingCheck.py", line 227, in indicator_settings
    val_supertrend_atr = self.slider_atr.get()
AttributeError: 'float' object has no attribute 'slider_atr'
```
Any Idea what might have caused this?

**Comment by TomSchimansky** [comment]
Hi, is it correct that your `indicator_settings` method is indented? If yes this is wrong, it should at the same indentation level as the other class functions. The second problem is that you assigned the `indicator_settings` function as command for the sliders, but a slider command callback function gets passed the value of the specific slider it gets called from, so your'e slider callback function should look like this: `def indicator_settings(self, slider_value)`. And if you then get the value from the lsiders directkly with `.get()` inside the callback you don't need to use the value, but it needs to be in the function header as an argument. 

But what I would do is to create a different callback function for every slider, or use tkinter variables.

**Comment by glr-87278mau** [comment]
> Hi, is it correct that your `indicator_settings` method is indented? If yes this is wrong, it should at the same indentation level as the other class functions. The second problem is that you assigned the `indicator_settings` function as command for the sliders, but a slider command callback function gets passed the value of the specific slider it gets called from, so your'e slider callback function should look like this: `def indicator_settings(self, slider_value)`. And if you then get the value from the lsiders directkly with `.get()` inside the callback you don't need to use the value, but it needs to be in the function header as an argument.
> 
> But what I would do is to create a different callback function for every slider, or use tkinter variables.

Hi, Im now only using 1 function per slider 
`        def indicator_settings_1(self, slider_value):
            val_supertrend_atr = self.slider_atr.get()` 

however this returns the error `TypeError: App.__init__.<locals>.indicator_settings() missing 1 required positional argument: 'slider_value'
PS C:\Users\user\pyto\projects\website_bots\front> `

When trying to make the same function without the argument ( `       def indicator_settings_1(self,):
            val_supertrend_atr = self.slider_atr.get()`) 
it returns the same error as before (    ```
val_supertrend_atr = self.slider_atr.get()
AttributeError: 'float' object has no attribute 'slider_atr'
```)

**Comment by glr-87278mau** [comment]
```
        def indicator_settings(self):
            print(self)
```
This worked!

**Comment by TomSchimansky** [comment]
You need the right indentation in the class! if the method `indicator_settings` should be a function of the CTk class, the it should definitely look like `def indicator_settings(self, slider_value):`. If its just a temporary function inside of the __init__ method it should look like `def indicator_settings(slider_value):`! But this is not a customtkinter related problem, so please refer to other websites like StackOverflow or python tutorials on classes and functions.
