### ISSUE TITLE
Scrollbar on CTkFrame

### ISSUE THREAD

**Issue by MaximFilimonovGH** [TomSchimansky/CustomTkinter#530]
I am using CTkFrame to store the configuration parameters in the form of pairs of CTkLabel + CTkEntry. I am using grid to have all of them nicely structured as a column. I am also using another CTkFrame to show resulting plots after some analysis is done based on those configuration parameters.

In documentation it says that CTkScrollbar takes CTkFrame as a possible master. Unfortunately, I cannot seem to make frame scrollable as it does not have any command for yscroll or yview.

Is there a way to make a scrollable frame?

Thanks!

**Comment by Akascape** [comment]
This may help: https://github.com/TomSchimansky/CustomTkinter/issues/215

**Comment by TomSchimansky** [comment]
Its not possible at the moment, but I definitely want to make a scrollable frame in the future. There are some options for normal tkinter frames: https://blog.teclado.com/tkinter-scrollable-frames/

**Comment by MaximFilimonovGH** [comment]
Thanks for a quick response. Seems like both answers refer to the similar scrollable-frame implementation. I will definitely check it out.
