### ISSUE TITLE
inconsisten behaviour when using grid? 

### ISSUE THREAD

**Issue by clear-code-projects** [TomSchimansky/CustomTkinter#537]
There seems to be a bug when using customtkinter with grid, for example: 
```
import tkinter as tk
from tkinter import ttk
from customtkinter import CTk, CTkLabel

window = CTk()
window.geometry('600x600')

window.columnconfigure(0, weight = 1)
window.columnconfigure(1, weight = 1)
window.rowconfigure(0, weight = 1)
window.rowconfigure(1, weight = 1)


ttk.Label(window, text = 'area 1', background = 'red').grid(row = 1, column = 1, sticky = 'EWNS')
CTkLabel(window, text = 'area 2', fg_color = 'green').grid(row = 0, column = 0, sticky = 'EWNS')

window.mainloop()
```

The CTkLabel always occupies more space than the ttkLabel (even when removing the sticky bit). Is this a bug or am I making a mistake somewhere?

**Comment by Akascape** [comment]
@clear-code-projects This is normal.
Customtkinter widgets are always a little bit bigger than ttklabels.
You use use width, height, font parameters to adjust it.
