### ISSUE TITLE
Dynamic resizing not working in CTkSwitch, CTkRadioButton and CTkCheckBox

### ISSUE THREAD

**Issue by Akascape** [TomSchimansky/CustomTkinter#549]
Hello @TomSchimansky,
**I am making a widget maker for customtkinter which look like this**

https://user-images.githubusercontent.com/89206401/197396161-26f89c59-d326-4ca7-b572-2cb2834b6870.mp4

I made the same for all the other widgets but some widgets like CTkSwitch are not resizing on configuring the width/height.
This is what happening with CTkSwitch:

https://user-images.githubusercontent.com/89206401/197396357-71b1b305-9956-4fba-8663-0352700b1c4d.mp4

You can see that it is not able to resize itself on configuring.
This is happening with the **radio button** and **checkbox** too,
_What can I do to fix this?_

**Comment by TomSchimansky** [comment]
The checkbox, switch and radiobutton widgets actually resize, but the switch itself and the text obviously don't resize. You can see it if you set `bg_color="red"`.

**Comment by Akascape** [comment]
@TomSchimansky Is there any way/parameter to resize the width/height of the switch part only and not the text.

**Comment by TomSchimansky** [comment]
Not in the current version. But in the next version 5.0.0 there will be `switch_width`, `switch_height` and `checkbox_width`...

**Comment by Akascape** [comment]
@TomSchimansky Release date for 5.0.0?

**Comment by TomSchimansky** [comment]
In the next days...

**Comment by TomSchimansky** [comment]
hopefully...

**Comment by TomSchimansky** [comment]
Version 5 is released now.
