### ISSUE TITLE
The .json theme file for customTkinter could not be found. Nuitka 

### ISSUE THREAD

**Issue by justabettergamer** [TomSchimansky/CustomTkinter#550]
I'm trying to compile my python project with Nuitka, Exe file cannot find blue.json, I do not find the solution to include this file, do you have any idea how I could solve it? 

CustomTkinter version: 4.6.3

Please see below:

![image](https://user-images.githubusercontent.com/81446024/197408031-bb9c89d6-dff7-4351-8d5e-19623995b090.png)

Thanks, 

Max

**Comment by TomSchimansky** [comment]
Did you read the wiki: https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging
Does this not work for you?

**Comment by TomSchimansky** [comment]
I am not familiar with Nuitka, but you have to somehow add the customtkinter folder manually...

**Comment by justabettergamer** [comment]
![image](https://user-images.githubusercontent.com/81446024/197410388-84cd19d0-16d9-4eba-a69a-27ca78535342.png)
Here is a new error after I followed your tutorial

**Comment by TomSchimansky** [comment]
Did you used the --onedir option?

**Comment by justabettergamer** [comment]
I used :  nuitka --clang --mingw64 --onefile --windows-icon-from-ico=..\Item_Gem.ico --windows-company-name=Unknown --include-data-file="C:\Users\max\AppData\Local\Programs\Python\Python310\Lib\site-packages\customtkinter\assets\themes\blue.json"=customtkinter\assets\themes\blue.json --windows-product-version=1.0 --plugin-enable=tk-inter --enable-plugin=numpy ..\BOT_Beta.py

**Comment by justabettergamer** [comment]
![image](https://user-images.githubusercontent.com/81446024/197414278-29bc58c4-a118-4a99-914a-4e6b7ffa19f4.png)

**Comment by TomSchimansky** [comment]
You have to include the whole customtkinter folder, not just the blue theme file, there are more data files that are needed.

**Comment by justabettergamer** [comment]
I seems that this extra argument is what we are looking for.
--include-data-dir="C:\Users\max\AppData\Local\Programs\Python\Python310\Lib\site-packages\customtkinter"=customtkinter 
Thank you for your help & thank you for this super nice Tkinter variation !
