### ISSUE TITLE
Disabling and reenabling a button removes the hover effect.

### ISSUE THREAD

**Issue by ArielMAJ** [TomSchimansky/CustomTkinter#552]
In other words, the button keeps looking disabled but becomes clickable again.

I also couldn't figure out how to reenable hovering later on (btn.configure(hover=True) throws an exception).

A minimal example of what I ran into (Python 3.10; ctk 4.6.3;):

```
import customtkinter as ctk


def strange_behavior():
    btn.configure(state="disabled")
    btn.configure(state="enabled", text="Hovering won't work anymore")
    # btn.configure(hover=True)  # This throws an exception.


root = ctk.CTk()

btn = ctk.CTkButton(
    text="Hovering works",
    command=lambda: print("Clicking works normally."),
    hover=True,  # Hover is an option in the button.
)
btn.pack(expand=True)

root.after(2000, strange_behavior)

root.mainloop()

```

Am I doing anything wrong? Is this a bug? Any workaround suggestions? 

Tyvm for your time and work!

**Comment by Akascape** [comment]
@ArielMAJ This is happening because you have not configured the state properly. 
You have to use `state=tkinter.NORMAL` or state=tkinter.DISABLED`.

The hover was throwing exception because it is no changeable via configuring. You have to directly use `btn.hover=True`.

### Code
```python
import customtkinter as ctk
import tkinter

def strange_behavior():
   btn.configure(state=tkinter.DISABLED) #This is the proper method to change state
   btn.configure(state=tkinter.NORMAL, text="Hovering will work now")
   
   # btn.configure(hover=True) ## --> Hover is not avaliable in the configure method
   # You have to use it like this: btn.hover=True  


root = ctk.CTk()

btn = ctk.CTkButton(
    text="Hovering works",
    command=lambda: print("Clicking works normally."),
    hover=True,  # Hover is an option in the button.
)
btn.pack(expand=True)

root.after(2000, strange_behavior)

root.mainloop()
```

**Comment by TomSchimansky** [comment]
`customtkinter.DISABLED` and `customtkinter.NORMAL` works as well.

**Comment by ArielMAJ** [comment]
Tyvm guys, I guess i didn't research enough and this isn't a bug. I also tested with strings and "disabled" & "normal" and they seem to work fine, the problem here was using "enabled" instead of "normal".
