### ISSUE TITLE
No Text Widget

### ISSUE THREAD

**Issue by vikramsamak** [TomSchimansky/CustomTkinter#56]
Please add text widget !

**Comment by vikramsamak** [comment]
And 1 more question, how to wrap sentence in entry widget ?

**Comment by TomSchimansky** [comment]
There is no TextBox in customtkinter, as I wrote:

> Request for TextBox is already there and I will do it when I have time, at the moment I focus on scaling for HighDPI / 4K displays.

You can use the normal tkinter.TextBox.

**Comment by vikramsamak** [comment]
OK thanks sir… By the way you are doing great job...kudos to you man
