### ISSUE TITLE
CTkOptionMenu

### ISSUE THREAD

**Issue by HunnyRasheed** [TomSchimansky/CustomTkinter#560]
AttributeError: module 'customtkinter' has no attribute 'CTkOptionMenu' I am getting this error,again and again, unable to run example code as well is there any version issue ?

**Comment by HunnyRasheed** [comment]
I have downloaded the custom tkinker library but still I am getting error

**Comment by Akascape** [comment]
@HunnyRasheed Your python version?

**Comment by HunnyRasheed** [comment]
python version is 3.10 and custom version is 4.2

**Comment by Akascape** [comment]
@HunnyRasheed CustomTkinter 4.2 doesn't support OptionMenu. Please upgrade it to the latest version.
