### ISSUE TITLE
Image in label doesn't get rendered

### ISSUE THREAD

**Issue by emilkevinmanuel** [TomSchimansky/CustomTkinter#561]
```customtkinter.CTkLabel(master=boxframe,image=ImageTk.PhotoImage(Image.open("LogoText.png"))).pack(padx=0, pady=10)```

The Image is invisible, but the label is there. Where my image should be is a gap with the size of my image. I also don't get an error. 
![Screenshot 2022-10-26 185508](https://user-images.githubusercontent.com/66739298/198088459-5a0f7c53-0c79-4dcd-8bce-8956dab3d18c.png)

**Comment by emilkevinmanuel** [comment]
Thanks :) @Akascape

**Comment by TomSchimansky** [comment]
You need to set `text=""` for the CTkLabel to display the image correctly.

**Comment by TomSchimansky** [comment]
Should work fine now.
