### ISSUE TITLE
Request for a CTkDualSlider widget

### ISSUE THREAD

**Issue by EN20M** [TomSchimansky/CustomTkinter#564]
Could you make a Slider version with two (or a customizabel number of) knobs or extend the existing one so it would be possible to initialise it with a variable number of knobs. I don't think making one similarly to the Floatspinbox out of the existing widgets is going to result in something adequate

**Comment by Akascape** [comment]
@EN20M Already requested here: https://github.com/TomSchimansky/CustomTkinter/issues/118

You can combine this special [RangeSlider](https://github.com/harshvinay752/RangeSlider) widget with customtkinter easily.

### Here is the final look:

![DualSlider](https://user-images.githubusercontent.com/89206401/198649545-3b9425f8-1034-406b-a0d2-b6ff052825ab.jpg)

## Code
```python
import tkinter
import customtkinter
from RangeSlider.RangeSlider import RangeSliderH

customtkinter.set_appearance_mode("Dark") 

HEIGHT = 150
WIDTH = 850
                
app = customtkinter.CTk()
app.title("CTk Dual Slider")
app.geometry((f"{WIDTH}x{HEIGHT}"))
app.grid_rowconfigure((0,1), weight=1)
app.grid_columnconfigure(0, weight=1)


label_1 = customtkinter.CTkLabel(app, anchor='w', text="From: 0", width=1, height=1)
label_2 = customtkinter.CTkLabel(app, anchor='w', text="To: 100", width=1, height=1)
label_1.grid(row=1, sticky="nsw", padx=20)
label_2.grid(row=1, sticky="nse", padx=20)


def show(*args):
        label_1.configure(text="From: "+str(int(start.get())))
        
def show2(*args):
        label_2.configure(text="To: "+str(int(end.get())))


start = tkinter.DoubleVar()
end = tkinter.DoubleVar()

rangebar = RangeSliderH(app, [start, end], Width=800, Height=60, #colors are selected based on the theme
                            bgColor=customtkinter.ThemeManager.theme["color"]["window_bg_color"][1],
                            line_color=customtkinter.ThemeManager.theme["color"]["slider"][1],
                            bar_color_outer=customtkinter.ThemeManager.theme["color"]["button"][1], bar_radius=8,
                            bar_color_inner=customtkinter.ThemeManager.theme["color"]["button"][1], min_val=0, max_val=100, show_value=False,
                            line_s_color=customtkinter.ThemeManager.theme["color"]["slider_progress"][1])
rangebar.grid(padx=20, pady=20)

start.trace_add('write', show)
end.trace_add('write', show2)

app.mainloop()                 
```
Please read the documentation of RangeSlider properly to know more about the customizations.

**Comment by TomSchimansky** [comment]
Maybe I will add it at some point if I have the time, but only with the CTkSlider as a basis. I cannot simply use these RangeSlider, it lacks fundamental functionality, like scaling,  tuple-colour with appearance_mode, antialiased rendering...
