### ISSUE TITLE
I cannot change text_color_disabled using configure() method for a button. 

### ISSUE THREAD

**Issue by alamir3ali** [TomSchimansky/CustomTkinter#565]
I need this feature for my tic-tac-toe project. I want to change color of the text of a disabled button as the function of the turn "X" or "O". However, i am not really able to do that simple way using button.configure(text_color_disabled='color'). It gives me an 'unknown option "-text_color_disabled"'. Thank you for your attention.

**Comment by Akascape** [comment]
@alamir3ali  `text_color_disabled` is not directly changeable via configure.
You have to directly use `button.text_color_disabled="color"` to change it.
**Example:**
```python
def disable_button():
    button.text_color_disabled="red"
    button.configure(state="disabled")
```

**Comment by TomSchimansky** [comment]
Duplicate: https://github.com/TomSchimansky/CustomTkinter/issues/544

**Comment by alamir3ali** [comment]
> @alamir3ali `text_color_disabled` is not directly changeable via configure. You have to directly use `button.text_color_disabled="color"` to change it. **Example:**
> 
> ```python
> def disable_button():
>     button.text_color_disabled="red"
>     button.configure(state="disabled")
> ```
Thanks, this helped me
![Screenshot 2022-10-29 144627](https://user-images.githubusercontent.com/114143531/198832270-b98c313e-8c18-4fe7-b658-14bc3793b8f2.png)
