### ISSUE TITLE
Cannot bind a function to a CTkLabel

### ISSUE THREAD

**Issue by Melih61** [TomSchimansky/CustomTkinter#566]
Hey,
i want to create a label which calls a function when i click on it but it does not work

```
def function1():
    print('Hello World')

label = customtkinter.CTkLabel(master=frame2, text=f' {username}', text_font=('Consolas',13))
label.place(x=12, y=80, anchor='w')

label.bind('<Button-1>', lambda e: function1())
```

Nothing will happen if i click on it

**Comment by TomSchimansky** [comment]
Hi, binding was already requested, I will add it with the next version 5.0.0.

**Comment by Free-Radical** [comment]
Same issue here. When is 5.0 expected?
