### ISSUE TITLE
Hey, this is an error when convert py to exe

### ISSUE THREAD

**Issue by huym07** [TomSchimansky/CustomTkinter#57]
Hey, this is an error when convert py to exe
![image](https://user-images.githubusercontent.com/97513643/167053096-1f1d5997-daf9-4e33-b112-dcc47c7a14d0.png)

**Comment by TomSchimansky** [comment]
Did you look at the wiki: https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging#windows-pyinstaller-auto-py-to-exe

This is a known problem, which can't be fixed, because pyinstaller doesn't support data files inside libraries by default.
