### ISSUE TITLE
Stacking frame and transparency

### ISSUE THREAD

**Issue by Cromwell1963** [TomSchimansky/CustomTkinter#586]
Hi, I have been using a number of frames with frames. When I set the colour, the frame is not displayed quite as expected.
I wonder if there is some transparency added to the frame. If so how can I control it.
Many thanks

**Comment by TomSchimansky** [comment]
If you set fg_color=None for the frame, it will have the same color as the frame/window it is placed on.

**Comment by Cromwell1963** [comment]
Excellent, thank you

**Comment by TomSchimansky** [comment]
Now its `fg_color="transparent"`.

**Comment by m-schwob** [comment]
> fg_color="transparent"

CTkFrame docstring need to be updated with that :)
