### ISSUE TITLE
button.cget("state") raises exception

### ISSUE THREAD

**Issue by justabettergamer** [TomSchimansky/CustomTkinter#587]
Here is the code I tested : 
`import customtkinter

app = customtkinter.CTk()
app.title("CustomTkinter")
app.geometry("150x100")

button = customtkinter.CTkButton(app, text = "test")
button.grid(pady=30)

print(button.cget("state"))

app.mainloop()`

Traceback : 
`Traceback (most recent call last):
  File "C:\Users\user\Documents\test2.py", line 11, in <module>
    print(button.cget("state"))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1681, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
_tkinter.TclError: unknown option "-state"
`

**Comment by Akascape** [comment]
@justabettergamer `cget` method is not implemented.
Use `button.state` instead.

```python
import customtkinter

app = customtkinter.CTk()
app.title("CustomTkinter")
app.geometry("150x100")

button = customtkinter.CTkButton(app, text = "test")
button.grid(pady=30)

print(button.state)

app.mainloop()
```
**Output**
`>>> normal`
