### ISSUE TITLE
Exception occurs when configuring the text of a button

### ISSUE THREAD

**Issue by Tommmo6** [TomSchimansky/CustomTkinter#588]
![image](https://user-images.githubusercontent.com/117383518/199784279-4399c81b-fdc5-4e5a-8f2d-cbf41d62dc93.png)
It seems to happen on anything that I used to be able to configure. eg border_color.

**Comment by Akascape** [comment]
@Tommmo6 Please read the [documentation](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkButton) properly.
```python
import customtkinter
                
app = customtkinter.CTk()
app.geometry("200x100")

def clicked():
    button.configure(text="Clicked", border_color="red")
    
button=customtkinter.CTkButton(text="Click", border_width=5, command=clicked)
button.pack(pady=30)

app.mainloop()                
```
<img src="https://user-images.githubusercontent.com/89206401/199906644-f70d7e86-4adf-4c63-ae20-3c9e84ae7f08.gif" width=200, height=200>
