### ISSUE TITLE
Focus_force, withdraw, deiconify, destroy with ctk.CTk and CTkTopLevel

### ISSUE THREAD

**Issue by 11Gefest11** [TomSchimansky/CustomTkinter#59]
Got an error when trying to withdraw/deiconify, destroy works but with some errors, focus_force just doesn't. Is there a way to do such things? If no, can you please add them in the next upd?

**Comment by 11Gefest11** [comment]
Im running Win11,  your test code working perfectly, but exactly same `root.iconify() ` doesn't hide my window. Can it be the problem, that i imported customtkinter like this?
`import customtkinter
from custom tkinter import *`

**Comment by 11Gefest11** [comment]
Well, i changed code a bit and managed to run it without iconify/deiconify, so i guess the topic is closed. However, i still don't know why he dont want to hide root, while running TopLevel (i bet thats a problem).

Last question: is there a way to force focus?

**Comment by TomSchimansky** [comment]
I don't know if you can force focus on a window. But this is not customtkinter specific, if this works for normal tkinter, than it will also work for customtkinter.

**Comment by ShahistaBukhari** [comment]
I am facing issue regarding the CustomTkinter widget in systemd service file on Linux could you help me out to solve that error ?
