### ISSUE TITLE
customtkinter.CTkTextbox.delete() not written in ctk_textbox.py

### ISSUE THREAD

**Issue by messina8** [TomSchimansky/CustomTkinter#593]
Was trying to delete the content in the textbox, and .delete() was not working. adding the following code on ctk_textbox.py fixed it:
    def delete(self, *args, **kwargs):
        return self.textbox.delete(*args, **kwargs)

**Comment by TomSchimansky** [comment]
Yes I know, the Textbox is not finished yet.
