### ISSUE TITLE
Corner radius,width,height of CtkFrame doesn't change.

### ISSUE THREAD

**Issue by Olawoledev** [TomSchimansky/CustomTkinter#6]
I was working with the CtkFrame and i tried increasing the width and height,nothing happens .i even tried changing the corner radius,but still no changes.

**Comment by TomSchimansky** [comment]
Can you show your code please?

**Comment by Olawoledev** [comment]
I just tried it again and it worked perfectly.Another thing is whenever i use .grid for the frame and also insert a label to the frame using .grid ,then the label changes the frame.

```
import customtkinter as ctk
import tkinter as tk

window=tk.Tk()

frame 1=ctk.CTkFrame(window,width=300,fg_color="red",height=60,corner_radius=10)

frame1.grid (column=0,row=1,sticky="w",pady=20,padx=50)

label=tk.Label(frame1,width=10,height=60)

label.grid (column=0,row=0,sticky="w",pady=10,padx=100)

window.mainloop()
```
