### ISSUE TITLE
Hey tom i needed the support of ttk notebook

### ISSUE THREAD

**Issue by Shreyas-ITB** [TomSchimansky/CustomTkinter#601]
im making some project which has windows inside the app so i needed to make multiple tabs but im currently using tkinter ttk as there is no official support from customtkinter about ttk notebook

**Comment by Akascape** [comment]
@Shreyas-ITB Tabview will be available in the next update. (v5.0.0)

It's almost ready ig. 
https://github.com/TomSchimansky/CustomTkinter/wiki/CTkTabview

**Comment by Shreyas-ITB** [comment]
> @Shreyas-ITB Tabview will be available in the next update. (v5.0.0)
> 
> It's almost ready ig. https://github.com/TomSchimansky/CustomTkinter/wiki/CTkTabview

oh okay
