### ISSUE TITLE
Is it just me or does CTkTextbox not have get()

### ISSUE THREAD

**Issue by DharmaHS** [TomSchimansky/CustomTkinter#602]
Am trying to make something with ctk, was trying to get the text from a textbox but this keeps showing up:

AttributeError: 'CTkTextbox' object has no attribute 'get'

self.text_box = ctk.CTkTextbox(master=self, height=16)
my_text=self.text_box.get("0.0", "end")

tried with tk.Text, works fine there, think there might be some function that aren't included,
delete() also doesn't seem to work

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/378
