### ISSUE TITLE
Alias ._clicked() to .invoke()

### ISSUE THREAD

**Issue by Evolution0** [TomSchimansky/CustomTkinter#605]
Not sure why the user closed [#226](https://github.com/TomSchimansky/CustomTkinter/issues/226), as its still valid even in the dev branch.

As `CTkButton` does not seem to inherit `Button` it has no `.invoke()` method currently. Calling `.event_generate('<Button-1>')` on a `CTkButton` does not trigger it either, you *need* `.invoke()` unless you want to directly call the protected member of `CTkButton`: `._clicked()`

Honestly it would be perfectly fine if `.invoke()` is just an alias of `._clicked()`, the functionality seems the same and it would get rid of any IDE warnings.

**Comment by TomSchimansky** [comment]
I will add the invoke method

**Comment by TomSchimansky** [comment]
Invoke method is now implemented with version 5.0.0.
