### ISSUE TITLE
hover_color option not working in CTk.Scrollbar

### ISSUE THREAD

**Issue by shuvam-kayal** [TomSchimansky/CustomTkinter#609]
when im using it as option python idle is giving an error stating no such option is there.

**Comment by shuvam-kayal** [comment]
stating*

**Comment by Evolution0** [comment]
Its `scrollbar_hover_color` according to `ctk_scrollbar.py`

**Comment by TomSchimansky** [comment]
It was a mistake in the wiki, its called scrollbar_hover_color.
