### ISSUE TITLE
app.iconbitmap('ic.ico')

### ISSUE THREAD

**Issue by kartfoundation** [TomSchimansky/CustomTkinter#61]
Please i want to ask is there any way that customtkinter will support iconbitmap because i try adding iconbitmap this is the error i'm getting.
```python
_tkinter.TclError: bitmap
```
```python
import os
import sys 
import tkinter
import customtkinter




customtkinter.set_appearance_mode("dark")

app = customtkinter.CTk()
app.title('Malware')
app.iconbitmap('ic.ico')
app.geometry("400x300")





app.mainloop()
```

**Comment by TomSchimansky** [comment]
CustomTkinter should support it, there is no difference between tkinter.Tk and CTk for terms of the icon.   The problem seems to be the path or the file itself.

**Comment by demberto** [comment]
@kartfoundation Have you tried this code without using customtkinter?

**Comment by felipetesc** [comment]
Linux should use .xbm, perhaps Mac too ?
Windows should use .ico

I tested on Garuda:
 
```python
import os
import tkinter
import customtkinter

customtkinter.set_appearance_mode("dark")

app = customtkinter.CTk()
app.title('Title')
app.iconbitmap('@/run/media/ftx/HD1T/Projects/Python/SweetTheme_CustomTk/ic.xbm')
app.geometry("400x300")

app.mainloop()

```
and it worked
Pay attention to the @ for linux path (Mac too ?)


Discussion about that You can find here: https://stackoverflow.com/questions/20860325/python-3-tkinter-iconbitmap-error-in-ubuntu

Hope it helps.

**Comment by TomSchimansky** [comment]
I tested it on Windows 11 and `app.iconbitmap('ic.ico')` didn't change the icon on standard tkinter or customtkinter, so this is not a customtkinter problem. If you want a custom icon I think you should compile the program to .exe and then change the icon of the .exe.

**Comment by felipetesc** [comment]
Try to add the full path to the icon.ico. Check : https://felipetesc.github.io/CtkDocs/#/change_icon.

**Comment by wuwbobo2021** [comment]
I’d like avoiding ico/xbm formats by replacing the ico file with a png file:
```
import tkinter as tk
# ...
icon = tk.PhotoImage(file='logo.png')
self.iconphoto(True, icon)
```
Could `import tkinter as tk` be avoided?

**Comment by felipetesc** [comment]
> I’d like avoiding ico/xbm formats by replacing the ico file with a png file:
> 
> ```
> import tkinter as tk
> # ...
> icon = tk.PhotoImage(file='logo.png')
> self.iconphoto(True, icon)
> ```
> 
> Could `import tkinter as tk` be avoided?

https://python-pillow.org/

https://www.geeksforgeeks.org/convert-png-to-ico-with-pillow-in-python/
