### ISSUE TITLE
How to change the current color theme while a program is running

### ISSUE THREAD

**Issue by Zingzy** [TomSchimansky/CustomTkinter#612]
I want to implement this thing that allows the user to change the color theme from green to blue on clicking a button. But when I use the command `customtkinter.set_default_color_theme("blue")` nothing seems to happen. I have also tried methods like update idle tasks but nothing seems to work.

**Comment by TomSchimansky** [comment]
This is not possible at the moment, the program needs to be restarted, but maybe I will implement this feature at some point.
https://github.com/TomSchimansky/CustomTkinter/issues/295
