### ISSUE TITLE
Request: CtkMenu & CtkTreeview

### ISSUE THREAD

**Issue by Riv3rBird** [TomSchimansky/CustomTkinter#62]
Thanks for working on this.
Looking forward to more features enabling in the coming months.

**Comment by Smart-Space** [comment]
And, you may be able to make a moving function for the appearance of the menu.

like this:
![](https://img-blog.csdnimg.cn/5f4aaad57c9a4a89b7db93bdea3f4de3.gif)

However, this is not a menu at the top border of a window.

**Comment by demberto** [comment]
Just a tip this will need a `CtkFrame` of its own since Tk's own menu is trash.

**Comment by TomSchimansky** [comment]
CtkMenu will be the next widget I do after I finish the scaling I am currently working on. I will try to do it with a transparent TopLevel window.

**Comment by TomSchimansky** [comment]
Custom menu with toplevel is not possible for several reason and across platforms and tree view is too complicated so I will close this one.
