### ISSUE TITLE
No Border colour configure for CTkEntry

### ISSUE THREAD

**Issue by ajayschoo** [TomSchimansky/CustomTkinter#63]
Hello, sir could please make a border colour configureness for entry boxes.
Thank you as I need your library for a school project, so having the border configure would have huge impact on the look.
Thank you

**Comment by TomSchimansky** [comment]
Hi, actually, you can change the border with the `border_color` attribute when creating the CTkEntry, it's just not mentioned in the wiki. But you can't change it with `configure` at runtime. I will add this.

**Comment by ajayschoo** [comment]
Hello, Tom I would like to know if you added border colour in configure as i needed this widget for my project.
Thank you!

**Comment by TomSchimansky** [comment]
Will be added in the next release version, if you need it right now you can download the GitHub repository and place the customtkinter folder next to your project. It's already implemented.

**Comment by TomSchimansky** [comment]
`border_color` of CTkEntry can now be configured via .configure() as of version 4.0.0
