### ISSUE TITLE
Treeview in CustomTkinter.

### ISSUE THREAD

**Issue by ShivanBr** [TomSchimansky/CustomTkinter#655]
Cant use Tkinter Treeview in CustomTkinter. :(

**Comment by Akascape** [comment]
@ShivanBr Here is the implementation of Tkinter Treeview in CustomTkinter:
https://github.com/TomSchimansky/CustomTkinter/discussions/524#discussioncomment-3898307

**Comment by TomSchimansky** [comment]
tkinter widgets should work, but do not scale on HighDPI displays and do not adapt to the appearance mode.
