### ISSUE TITLE
Bind method doesn't work with the combobox

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [TomSchimansky/CustomTkinter#691]
I am using the bind method to search for a value from combobox values (they are 2500 value).
but when I run the code I didn't get anything.
and this is my a part of mycode

```
root = ctk.CTk()
root = ctk.CTk()
root.geometry('400x240')
root.title('Cryptocurrencies scraping')
lst=date_range()

def check_input(event):
    value = event.widget.get()
    if value == '':
        combo_from['values'] = lst
    else:
        data = []
        for item in lst:
            if value.lower() in item.lower():
                data.append(item)
        combo_from.configure(values=data)
        print(data)
combo_from=ttk.Combobox(root,values=date_range())
combo_from.bind('<KeyRelease>', check_input)
combo_from.pack(side='left')
```
*Note:*date_range** is a function that returns all dates from 2015 to now.

**Comment by TomSchimansky** [comment]
Its not implemented in the current version, it will work with version 5.0.0

**Comment by ZeyadMoustafaKamal** [comment]
> Its not implemented in the current version, it will work with version 5.0.0

When the version will be available ,thank you for doing all of this for us.

**Comment by TomSchimansky** [comment]
Binding should now work with version 5.0.0.
