### ISSUE TITLE
Are there listbox? 

### ISSUE THREAD

**Issue by sta0003** [TomSchimansky/CustomTkinter#692]
i want to upgrade my application to custom tkinter but cant seem to find listboxes will/are these going to be added in the future?

**Comment by TomSchimansky** [comment]
They will be added but it can take some time: https://github.com/TomSchimansky/CustomTkinter/issues/69

**Comment by Akascape** [comment]
@sta0003 
**I made this custom listbox for customtkinter:**
https://github.com/Akascape/CTkListbox

![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)
