### ISSUE TITLE
Unable to Retrieve Button Text Value

### ISSUE THREAD

**Issue by ufojava** [TomSchimansky/CustomTkinter#70]
I have tried to retrieve button text by using the Tkinter cget() method.

The cget() method is not an option using the Custom library.
Is there a way I can get the text value of the button?

Kind Regards

**Comment by ufojava** [comment]
Hello,

I have worked it out.
All I had to do is to button.text.

Thanks you for the grate product

**Comment by austrianadrian** [comment]
i have the same problem with cget().. how did you solve it ? 
self.button = customtkinter.CTkButton(master=btn_frame, text="CTkButton", command = self.button_name)

def button_name(self):
print(self.button.cget("self.button.text")

terminal:
_tkinter.TclError: unknown option "-self.button.text"

**Comment by austrianadrian** [comment]
okay.. fixed it too.. 

The solution was:

def button_name(self):
print(self.button.text)

**Comment by ufojava** [comment]
Glad to hear it!
