### ISSUE TITLE
spinbox

### ISSUE THREAD

**Issue by roelvanderzee** [TomSchimansky/CustomTkinter#703]
Can you also add a spinbox?

**Comment by TomSchimansky** [comment]
You can have a look at this: https://github.com/TomSchimansky/CustomTkinter/wiki/Create-new-widgets-(Spinbox)

**Comment by LLIETAER** [comment]
Hi Tom,

In the link example above master parameter is missing ?

Traceback (most recent call last):
  File "c:\OneDrive\Python2022\spin.py", line 67, in <module>
    spinbox_1 = FloatSpinbox(master=app, width=150, step_size=3)
  File "c:\OneDrive\Python2022\spin.py", line 13, in __init__
    super().__init__(*args, width=width, height=height, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'master'

make it work by adding "app" parameter
`app = customtkinter.CTk()

spinbox_1 = FloatSpinbox(app, width=150, step_size=3)
spinbox_1.pack(padx=20, pady=20)

spinbox_1.set(35)
print(spinbox_1.get())

app.mainloop()`
