### ISSUE TITLE
How can I do like this?

### ISSUE THREAD

**Issue by zSynctic** [TomSchimansky/CustomTkinter#71]
![Screenshot 2022-05-11 215226](https://user-images.githubusercontent.com/71632495/167914695-e7737104-dc27-43c6-a3a3-9c998e37f262.png)
the border

**Comment by TomSchimansky** [comment]
What do you mean? Which border?

**Comment by zSynctic** [comment]
![Screenshot 2022-05-11 232952](https://user-images.githubusercontent.com/71632495/167930545-fcfca76b-4b3d-44c5-b6bb-22813926fbbd.png)
I mean how can I make it like a frame or Idk what is it called like another color than the theme dark, I mean how the background is black but there is some sides that have gray

**Comment by TomSchimansky** [comment]
Did you look at the wiki? The CTkFrame has a `border_width` and `border_color` attribute.

**Comment by zSynctic** [comment]
Oh ok thanks I just found out about ctk so didn't try much yet
