### ISSUE TITLE
Canvas Removed in 5.0.0

### ISSUE THREAD

**Issue by olafvandinter2** [TomSchimansky/CustomTkinter#713]
In version 5.0.0. canvas has been removed. I used this to add multiple widgets (That took up more space that the maximum vertical height of the app) and add a scrollbar to this in the vertical direction. How can I still add more widgets to a scrollbar? adding it to a frame is not possible (at least how I tried it)

**Comment by TomSchimansky** [comment]
The CTkCanvas is not intended to be publicly used, because there is no scaling. But you can just use the `tkinter.Canvas` which is exactly the same. But I will also add a syllable frame widget in the next time.

**Comment by EN20M** [comment]
But `tkinter.Canvas` does not have the method `create_aa_circle`
