### ISSUE TITLE
New doc sys with docsify

### ISSUE THREAD

**Issue by felipetesc** [TomSchimansky/CustomTkinter#72]
Hi. I've created a new repo with the documentation from your wiki using docsify, it can be found here: https://github.com/felipetesc/CtkDocs
The reason for doing this is the fact that the wiki which Github offers is a little bit too simple.
You can grab the doc folder and add to the root of the project. Since I don't know if You will like it, I didn't do it myself.
A preview can be seen here https://felipetesc.github.io/CtkDocs/#/
And if you decide to add to the project, here is a tutorial:
https://wise4rmgodadmob.medium.com/how-to-create-a-documentation-site-with-docsify-and-github-pages-doc-as-a-code-c419c44e99b7
Thanks !

**Comment by TomSchimansky** [comment]
Hi, looks good, I think I will add this to the repository and host it with GitHub pages then. But at the moment I have other things to do, so maybe I will do it in the next days.

**Comment by felipetesc** [comment]
Hi. When you have time, and since there are so many new issues everyday, perhaps in a long, long time from now, we can discuss how to proceed with the documentation. 

I wish some guidance, so I know I'm in the right path, and we can create relevant contents. Maybe to look into this right away may seem a litle bit rush, but it's going to save you a lot of time if we can offer a better doc. 

Several questions beeing opened can be almost right away closed, since they are just questions about how do I do this, or that. In the end you will have more time to deal with the bugs, and enhaencements rather than answering commom questions. 
PS:
To all reading this, if you have ideas about the documentation, please do not be shy, I'll gladly to hear you out.
We can change from docsify to any other system, but it's interesting to do it now, and save ourselves from writing everything from the beggining.

**Comment by correa-coder** [comment]
@felipetesc  I just checked your documentation and it's looking amazing, good job!

**Comment by felipetesc** [comment]
> @felipetesc I just checked your documentation and it's looking amazing, good job!

Thank you

**Comment by TomSchimansky** [comment]
I think I will stick with the documentation in the Github wiki tab for now, but feel free to extend your documentation too...

**Comment by felipetesc** [comment]
No problem, after some thoughs I realized doc system from rust seems more interesting than docsify, so I wold need to remake everything
