### ISSUE TITLE
Please add set() attribute in CTkEntry

### ISSUE THREAD

**Issue by prokanhayia** [TomSchimansky/CustomTkinter#727]
Please add set() attribute for CTkEntry() so I can make a miniature calculator and we can do many more thing and I think you know how important set() attribute is. So,  I humbly requesting you to add set().
                                                                   Thank you

**Comment by TomSchimansky** [comment]
You can do `entry.insert(0, "some text")` which would equal a set method. The first argument is the index which can be a number or "insert" (current cursor position) or "end". https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/entry.html#entry-index
