### ISSUE TITLE
Custom theme error

### ISSUE THREAD

**Issue by Koo-Kie** [TomSchimansky/CustomTkinter#731]
Hey, I am getting an error message when I try to use my own .json theme file.

````
cls.theme["text"] = cls.theme["text"]["Windows"]
                        ~~~~~~~~~^^^^^^^^
KeyError: 'text'
````

thanks

**Comment by TomSchimansky** [comment]
The format of the theme files changed completely, you can have a look here: https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/assets/themes/blue.json

I changed the format to use the correct attribute names of the widgets and to have a better understanding where the values are gonna be used.
