### ISSUE TITLE
font is not working

### ISSUE THREAD

**Issue by SaatwikCodz** [TomSchimansky/CustomTkinter#735]
import customtkinter
from tkinter import *
root = customtkinter.CTk()
customtkinter.set_appearance_mode("Dark")
customtkinter.set_default_color_theme("dark-blue")

labl = customtkinter.CTkLabel(master = root, text = "Hello World", font = ("comicsansms",14))
labl.pack()

root.mainloop()

error is
Traceback (most recent call last):
  File "G:\Hackathon GUI For Practice\Landing.py", line 7, in <module>
    labl = customtkinter.CTkLabel(master = root, text = "Hello World", font = ("comicsansms",14))
  File "C:\Users\Saatwik Coding\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\widgets\ctk_label.py", line 54, in __init__
    self.text_label = tkinter.Label(master=self,
TypeError: tkinter.Label() got multiple values for keyword argument 'font'
[Finished in 550ms]

**Comment by Puffvl** [comment]
![image](https://user-images.githubusercontent.com/51693417/205429800-ba9e890a-120f-4ab5-95b5-7069706259a1.png)
copy - paste

**Comment by FranzKol** [comment]
Your source code works for me.
Did you use the latest version of customtkinter, which is 5.0.1 ?
There are some syntax changes between version 4 and 5.

**Comment by TomSchimansky** [comment]
I think you are using a version <5.0.0. Then you have to set the font with the text_font argument. If you use version >=5.0.0 you have to use the font argument.

**Comment by Puffvl** [comment]
This code work on windows 10  customtkinter version  5.0.1 , but not in windows >8 customtkinter version  4.6.3

**Comment by SaatwikCodz** [comment]
I changed the version and It works thanks
