### ISSUE TITLE
Is there a listbox for customtkinter?

### ISSUE THREAD

**Issue by daehwan5024** [TomSchimansky/CustomTkinter#739]
Is there anything I can use like a tkinter listbox?

**Comment by TomSchimansky** [comment]
NO you have to use a tkinter listbox. But I will create one soon. https://github.com/TomSchimansky/CustomTkinter/issues/69

**Comment by Akascape** [comment]
@daehwan5024 
**I made this custom listbox for customtkinter:**
https://github.com/Akascape/CTkListbox

![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)
