### ISSUE TITLE
CTkBaseClass, CTkCanvas, DrawEngin not accessible anymore

### ISSUE THREAD

**Issue by EN20M** [TomSchimansky/CustomTkinter#757]
I have seen in another issue that CTkCanvas was removed because the CTkCanvas is not intended to be publicly used, because there is no scaling. I understand that but isn't there a way to have them accessible via a more specific include. Otherwise it is close tio impossible to write other custom widgest that can't be glued together by exiting ones (e.g. a Range slider). I have no issue with dealing with changes made to these classes along the way but I would prefer to code my stuff alongside the package rather than forking the whole thing.

**Comment by louislautz** [comment]
I agree,
I used the CTkCanvas to build a scrollable frame widget for a long settings menu, but now it doesnt work anymore.

**Comment by TomSchimansky** [comment]
They are public again with version 5.0.2.
