### ISSUE TITLE
Difference between tkinter variables and customtkinter variables?

### ISSUE THREAD

**Issue by clear-code-projects** [TomSchimansky/CustomTkinter#760]
I noticed that there are customtkinter variables (like customtkinter.StringVar) besides the normal tkinter variables. Is there a difference between the two?

**Comment by TomSchimansky** [comment]
At the moment there is no difference, just an other name. But maybe there will be a difference at some point. So I would just use the customtkinter versions of the variables.

**Comment by clear-code-projects** [comment]
ok, thanks. By the way, while looking at this, I found a minor documentation error for the segmented button (https://github.com/TomSchimansky/CustomTkinter/wiki/CTkSegmentedButton) 

The code snippet for using the tkinter variable is missing the pack method.

**Comment by TomSchimansky** [comment]
thanks
