### ISSUE TITLE
Please add a listbox

### ISSUE THREAD

**Issue by ivoxprojects** [TomSchimansky/CustomTkinter#761]
Theres no CTkListBox in customtkinter please add it. Thanks :)

**Comment by TomSchimansky** [comment]
Easier said than done, probably one or two weeks of work to get it to function properly and look good. It was already requested: https://github.com/TomSchimansky/CustomTkinter/issues/69

**Comment by ivoxprojects** [comment]
> Easier said than done, probably one or two weeks of work to get it to function properly and look good. It was already requested: #69

Right, i know it's not that simple implementing something like that, but thank's for the response ✌🏻

**Comment by Akascape** [comment]
@ivoxprojects 
**I just made this custom listbox for customtkinter:**
https://github.com/Akascape/CTkListbox

![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)
