### ISSUE TITLE
Ctk not working as executable (.exe) (PyInstaller 5.7.0)

### ISSUE THREAD

**Issue by rc4000** [TomSchimansky/CustomTkinter#767]
The application works fine when run with python as a .py file but it doesn't work as an executable.

python version: 3.11.0 

Error message:
![image](https://user-images.githubusercontent.com/86579760/205761723-cdb1774a-4add-48a1-8fa8-f782936d42be.png)

**Comment by TomSchimansky** [comment]
Did you look at the wiki?

**Comment by WARD-CODE** [comment]
you can copy the module files inside your project after building with pyinstaller
![image](https://github.com/TomSchimansky/CustomTkinter/assets/79150916/95d3c36d-ce82-42f7-9626-2524cdc98ab3)
