### ISSUE TITLE
Question: what tags categories are You using

### ISSUE THREAD

**Issue by felipetesc** [TomSchimansky/CustomTkinter#77]
Hello. I wanted to know what tags are You using so I can create a better documentation to  organize and help when creating a new issue. Are You following a guide? Perhaps  I can link the guide to docs. And what else can I do to enhance the documentation ? 
What ideas and suggestions You guys have ? Tom ?

**Comment by TomSchimansky** [comment]
What did you mean by tags? You mean the Labels here on Github?
