### ISSUE TITLE
Bug with CTkScrollbar widget on 5.0.1

### ISSUE THREAD

**Issue by matiaslao** [TomSchimansky/CustomTkinter#772]
When instancing the CtkScrollbar widget with default settings, there is a KeyError when loading the `scrollbar_color` and `scrollbar_hover_color` values from the json file corresponding to each theme.

Lines 52 and 53 from `ctk_scrollbar.py` should be modified to avoid this error.

```
self._button_color = ThemeManager.theme["CTkScrollbar"]["button_color"] if button_color is None else self._check_color_type(button_color)
self._button_hover_color = ThemeManager.theme["CTkScrollbar"]["button_hover_color"] if button_hover_color is None else self._check_color_type(button_hover_color)
```

**Comment by TomSchimansky** [comment]
Got already reported: https://github.com/TomSchimansky/CustomTkinter/issues/711
