### ISSUE TITLE
Stop and Start CtkProgressbar will increase speed

### ISSUE THREAD

**Issue by boYu07** [TomSchimansky/CustomTkinter#775]
Class CTkProgressBar does not handle after event properly.  It only starts the after event in _internal_loop method, while not cancel it in stop method. It causes the speed keep increasing after stop and start progress bar few times.
My temp solution is to create a protected after_id attribute in __init__ to keep tracking the after id in _internal_loop method. When stop method is called, using self.cancel_after(self._after_id) to cancel the after event.
It works fine for me, but still need more test.

**Comment by TomSchimansky** [comment]
Fixed now, I adopted your proposed method and I think this works fine.
