### ISSUE TITLE
Scrollbar example is not working

### ISSUE THREAD

**Issue by mercerx02** [TomSchimansky/CustomTkinter#776]
![2022-12-06](https://user-images.githubusercontent.com/95192921/205921372-fc0a966e-c4a9-4cdc-abcf-20eacadf28c7.png)
I copied the Scrollbar example from the documentation and pasted it. An error occurred while executing the program.

**Comment by jmiaebrown** [comment]
Missing scrollbar_hover_color in the themes/*.json

**Comment by TomSchimansky** [comment]
Duplicate: https://github.com/TomSchimansky/CustomTkinter/issues/711
