### ISSUE TITLE
Request: vertical slider, progressbar?

### ISSUE THREAD

**Issue by onyx-and-iris** [TomSchimansky/CustomTkinter#78]
Hi! 

Thanks for all your great work!

Possible to allow CTkSlider and CTkProgressBar to be vertical?

**Comment by TomSchimansky** [comment]
Vertical rendering is already possible, I just need to implement the attributes for the widgets. I will do it in the next time.

**Comment by onyx-and-iris** [comment]
Thank you! It would be greatly appreciated.

**Comment by TomSchimansky** [comment]
CTkSlider and CTkProgressBar have now an `orientation` attribute ("horizontal", "vertical") with version 4.0.0

**Comment by agennaro1** [comment]
in version 4.5 and 4.5.1 orient =vertical do not work , also I try to put vertical slider and do not  work too
