### ISSUE TITLE
Add "indicatoron" field to radiobutton constructor.

### ISSUE THREAD

**Issue by IvanGrigorik** [TomSchimansky/CustomTkinter#798]
Unlike tkinter, your library doesn't have it.  It might be helpful in some projects.

**Comment by TomSchimansky** [comment]
Do you mean the radiobutton?

**Comment by IvanGrigorik** [comment]
Yup

**Comment by TomSchimansky** [comment]
Ok, I don't think I will implement this, this would be a whole new widget. But I don't know if I have the time to create something like this, there are more important widgets to be created at the moment.
