### ISSUE TITLE
Option Menu Request

### ISSUE THREAD

**Issue by Coding-George** [TomSchimansky/CustomTkinter#80]
Hello Tom! Could you include an OptionMenu to your custom tkinter? thank you!

**Comment by TomSchimansky** [comment]
Hi, I will add a ComboBox which is basically the same.

**Comment by TomSchimansky** [comment]
CTkComboBox and CTkOptionMenu are now available with version 4.3.0:
https://github.com/TomSchimansky/CustomTkinter/wiki/CTkComboBox
https://github.com/TomSchimansky/CustomTkinter/wiki/CTkOptionMenu

<img width="651" alt="Bildschirmfoto 2022-06-02 um 01 15 49" src="https://user-images.githubusercontent.com/66446067/171517978-42c048a8-7174-4d66-8771-1a852efccb7b.png">
