### ISSUE TITLE
CTkSegmentedButton 

### ISSUE THREAD

**Issue by roelvanderzee** [TomSchimansky/CustomTkinter#802]
At the CTkSegmentedButton wiki page,
at the "Example Code: With variable '

https://github.com/TomSchimansky/CustomTkinter/wiki/CTkSegmentedButton

you mention 
segemented_button = customtkinter.CTkComboBox
segemented_button = customtkinter.CTkOptionMenu

should this be
segemented_button = customtkinter.CTkOptionMenu

**Comment by TomSchimansky** [comment]
fixed it
