### ISSUE TITLE
Text manipulation shortcuts don't work when current keyboard layout is cyrillic

### ISSUE THREAD

**Issue by MrKleiner** [TomSchimansky/CustomTkinter#804]
CustomTkinter Version: 5.0.1 (installed with pip)
Python Version: 3.10.4

When manipulating text in CTkEntry, stuff like Ctrl+V, Ctrl+A and Ctrl+C don't work with cyrillic.
I don't know whether it's also an issue with stuff like japanese.

**Comment by TomSchimansky** [comment]
That's something i can't do anything about, because I'm using a tkinter.Entry for the CTkEntry so that's a tkinter problem.
