### ISSUE TITLE
CTkScrollbar not working (KeyError: 'scrollbar_color')

### ISSUE THREAD

**Issue by clear-code-projects** [TomSchimansky/CustomTkinter#808]
The CTkScrollbar is broken, even the demo is not working.  The error message is KeyError: 'scrollbar_color'

**Comment by jduncan8142** [comment]
The assets/themes/blue.json and maybe others need to be updated like below and it works. 

"CTkScrollbar": {
    "corner_radius": 1000,
    "border_spacing": 4,
    "fg_color": "transparent",
    "button_color": ["gray55", "gray41"],
    "button_hover_color": ["gray40", "gray53"],
    "scrollbar_color": ["#36719F", "#144870"],
    "scrollbar_hover_color": ["#27577D", "#203A4F"]
  }

**Comment by TomSchimansky** [comment]
This was fixed in version 5.0.2.
