### ISSUE TITLE
CTkProgressBar is broken

### ISSUE THREAD

**Issue by shasankp000** [TomSchimansky/CustomTkinter#809]
So I was building a resource monitor where the ram and cpu usage is being observed in real-time, and I noticed some flaws.
First of all, whenever the value of progressbar goes over 1, the whole progressbar is filled.

Secondly using CTkProgressbar.configure(progress_color="somecolor") returns an error saying this is not a valid property.

Below is a recording of the progressbar values and the progressbar being full when it should not be full.

https://user-images.githubusercontent.com/46317225/206578175-888f2d09-eba7-499c-9709-ac140651d537.mp4

**Comment by TomSchimansky** [comment]
Setting minimum and maximum values with the bracket notation is not supported. The range for the progress bar is zero to one and cannot be changed, so you have to convert your values for this range.
Configuring the progress_color is working in the latest version.

**Comment by shasankp000** [comment]
Okay! Got it.
