### ISSUE TITLE
Some letters cannot be typed in CTk's input widgets

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#810]
Apparently some letters can't be typed in CTk's input widgets such as `CTkTextbox`, `CTkEntry`.

When I try to type some Turkish letters, they can't be detected. But when I first type in Notepad then copy paste into the widgets, it works. I tried various font families but same result. Is this a bug?

Also `CTRL + Backspace` doesn't work in CTk's input widgets, it might be another bug.

![1](https://user-images.githubusercontent.com/100048974/206580891-72ac105a-c72f-4392-a840-343aaaecd44e.png)
![222222](https://user-images.githubusercontent.com/100048974/206580895-795461b1-c7c4-486d-a502-9489f1cf0629.png)

**Comment by TomSchimansky** [comment]
That's somethingg i can't do anything about because I'm using a tkinter.Entry for the CTkEntry so that's a tkinter problem.
