### ISSUE TITLE
CTkScrollbar is not functioning properly.

### ISSUE THREAD

**Issue by nozomichi00** [TomSchimansky/CustomTkinter#812]
`
import customtkinter

root = customtkinter.CTk()

root.title("Test")
root.geometry(f"{200}x{100}")

root.grid_columnconfigure(1, weight=1)
root.grid_columnconfigure((2, 3), weight=0)

main_frame = customtkinter.CTkFrame(root)
main_frame.grid(row=2, column=1, columnspan=4, padx=(20, 20), pady=(10, 0), sticky="nsew")

scrollbar = customtkinter.CTkScrollbar(main_frame, orientation="vertical")
scrollbar.place(relx=1, rely=0, relheight=1, anchor="ne")

main_label_1 = customtkinter.CTkLabel(main_frame, text="Test 1", anchor="w", height=30)
main_label_1.grid(row=1, column=1, padx=(20, 0), pady=(10, 0))
main_label_2 = customtkinter.CTkLabel(main_frame, text="Test 2", anchor="w", height=30)
main_label_2.grid(row=2, column=1, padx=(20, 0), pady=(10, 0))
main_label_3 = customtkinter.CTkLabel(main_frame, text="Test 3", anchor="w", height=30)
main_label_3.grid(row=3, column=1, padx=(20, 0), pady=(10, 0))

root.mainloop()
`
![image](https://user-images.githubusercontent.com/87961444/206638444-e0ff4f9f-acb2-4d51-91e3-58e8c2379a8d.png)

The window is too small, but the Scrollbar is not able to scroll.
How can I make the Scrollbar function properly when the window is too small?
I want the Scrollbar to work inside the Frame.
![image](https://user-images.githubusercontent.com/87961444/206637805-a13598da-9c35-4140-a578-e9d1cc22d727.png)

#215 Scrollbar is stuttering
I have referred to this article, but the following error occurs.
super().__init__(container, *args, **kwargs)

**Comment by TomSchimansky** [comment]
The scrollbar only works for the textbox at the moment. A ScrollabeFrame class will be implemented soon.

**Comment by nozomichi00** [comment]
This framework is really beautiful, looking forward to your updates, thank you.

[https://github.com/nozomichi00/AutoSoftwareUpgradeTool](url)
