### ISSUE TITLE
Text Box?

### ISSUE THREAD

**Issue by thomasrgrant** [TomSchimansky/CustomTkinter#82]
You don't seem to have a Text Box widget.

**Comment by TomSchimansky** [comment]
TextBox was already requested: https://github.com/TomSchimansky/CustomTkinter/issues/8 
I will add a TextBox if I finished working on HighDPI scaling.

**Comment by charankk21** [comment]
Any ETA for TextBox ? and in the mean time can i use existing Tkinter based Textbox on top of customtinker object ? I mean combination of Tkinter and customtkinter on the same screen. Please share sample code.

**Comment by TomSchimansky** [comment]
Maybe tomorrow night, otherwise in a about a week. You can do it like this: https://www.youtube.com/watch?v=Ew9dsDDy7pk

**Comment by charankk21** [comment]
Workaround work. Thanks @TomSchimansky.

**Comment by thomasrgrant** [comment]
[image: image.png]
I go NEON
Thank you.
