### ISSUE TITLE
Problem getting system appearance mode.

### ISSUE THREAD

**Issue by ArielMAJ** [TomSchimansky/CustomTkinter#821]
Initially, ctk shows the correct appearance mode. After I change it once, `ctk.get_appearance_mode()` only returns the last theme selected in the program instead of system theme when I use `ctk.set_appearance_mode("System")`.

```
import customtkinter as ctk

print(ctk.get_appearance_mode())  # Prints "Light"
ctk.set_appearance_mode("Dark")
print(ctk.get_appearance_mode())  # Prints "Dark"
ctk.set_appearance_mode("System")
print(ctk.get_appearance_mode())  # Should (?) print "Light" but prints "Dark" (System is Light theme here)
```

```
import customtkinter as ctk

print(ctk.get_appearance_mode())  # Prints "Dark"
ctk.set_appearance_mode("Light")
print(ctk.get_appearance_mode())  # Prints "Light"
ctk.set_appearance_mode("System")
print(ctk.get_appearance_mode())  # Should (?) print "Dark" but prints "Light" (System is Dark theme here)
```

I'm using Python 3.10.0 and this happens on ctk 4.6.3, ctk 5.0.2 and ctk 5.0.3.

Am I doing something wrong? How to get the actual system theme later on in the program?

**Comment by ivoxprojects** [comment]
Have you tried updating your customtkinter package to the latest version **5.0.3**?
if not use `pip install --upgrade customtkinter`

**Comment by TomSchimansky** [comment]
This is because at the moment you call ctk.get_appearance_mode the mode is still dark because it was dark before. The update rate for the appearance mode is 30ms when its set to system. So it takes a while before it changes.

**Comment by ArielMAJ** [comment]
> Have you tried updating your customtkinter package to the latest version **5.0.3**? if not use `pip install --upgrade customtkinter`

Yes, I did. Ty for the suggestion!


> This is because at the moment you call ctk.get_appearance_mode the mode is still dark because it was dark before. The update rate for the appearance mode is 30ms when its set to system. So it takes a while before it changes.

Tyvm. That was exactly it.
