### ISSUE TITLE
Progressbar attributes _from & to

### ISSUE THREAD

**Issue by Kippey** [TomSchimansky/CustomTkinter#828]
In the documentation, I see that you can pass "_from" and "to" attributes into a CTkProgressbar. 
![image](https://user-images.githubusercontent.com/56325821/206875697-784af708-429e-45df-a973-3cf32f04869f.png)

But when I try to pass them in, it throws an error.
`ValueError: ['_from', 'to'] are not supported arguments. Look at the documentation for supported arguments.`

Code for Progressbar:
```
wordProgressbar = customtk.CTkProgressBar(master=frameProgressbar, corner_radius=8, mode="determinate", _from=0, to=100)
wordProgressbar.pack(padx=6, pady=6)
wordProgressbar.set(0)
```

I am using CustomTkinter version 5.0.1

**Comment by TomSchimansky** [comment]
There was an error in the documentation, the range is only 0 to 1. But maybe I will implement _from and to arguments.
