### ISSUE TITLE
Main window hangs even if threads are used.

### ISSUE THREAD

**Issue by shasankp000** [TomSchimansky/CustomTkinter#830]
So I have a function which downloads a jvm runtime in the background. 

And I am using multithreading to put that function in a separate thread. 

![image](https://user-images.githubusercontent.com/46317225/206894438-9c40a797-59eb-47a9-8f6e-594ea21f05b6.png)

        

And this is binded to my button  

`
self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=self.run_jvm_install())
self.install_btn.place(x=435, y=550)`

And in my GUI when I click the button it just hangs, I am unable to use the GUI while the function is running in the background.

Any reasons as to why this is happening? (I have used the defualt tkinter in the past with multithreading but it has never hanged.)

**Comment by Akascape** [comment]
Try this:
```python
self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=self.run_jvm_install)

self.install_btn.place(x=435, y=550)
```

Or I recommend this instead if you are using thread, then there is no need to add that run_jvm_install function for threading.

```python
self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=lambda:  Thread(target=minecrust_backend.runtime_dl).start())

self.install_btn.place(x=435, y=550)
```

**Comment by Akascape** [comment]
@shasankp000 

Try this:
```python
self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=self.run_jvm_install)

self.install_btn.place(x=435, y=550)
```
 I recommend this method if you are using thread, there is no need to add that run_jvm_install function for threading:

```python
self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=lambda:  Thread(target=minecrust_backend.runtime_dl).start())

self.install_btn.place(x=435, y=550)
```

**Comment by shasankp000** [comment]
> @shasankp000
> 
> Try this:
> 
> ```python
> self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=self.run_jvm_install)
> 
> self.install_btn.place(x=435, y=550)
> ```
> 
> I recommend this method if you are using thread, there is no need to add that run_jvm_install function for threading:
> 
> ```python
> self.install_btn = CTkButton(master=self.home_page, width=140, height=50, text="Install Jvm", fg_color="#1F2022", command=lambda: Thread(target=minecrust_backend.runtime_dl).start())
> 
> self.install_btn.place(x=435, y=550)
> ```

Thanks a lot that worked!
