### ISSUE TITLE
How to add logo of my app ?

### ISSUE THREAD

**Issue by bajrangCoder** [TomSchimansky/CustomTkinter#837]
I want to add logo to my customtkinter app?

**Comment by nozomichi00** [comment]
If you are referring to a Window's Icon, you can add it using the following method.
self.iconbitmap('Images/AutoSoftwareUpgradeTool.ico')
![image](https://user-images.githubusercontent.com/87961444/206968325-7494cbe0-d73b-4ec5-9dbb-496a42f50567.png)
![image](https://user-images.githubusercontent.com/87961444/206967954-9c859082-47df-495b-858b-0aae6456abbd.png)

**Comment by Akascape** [comment]
I recommend to add png icon instead of ico.

```python
icon_path = ImageTk.PhotoImage(file=resource("Assets/icon2.png")) 
root.iconphoto(False, icon_path)
```

**Comment by bajrangCoder** [comment]
Thanku Both !
