### ISSUE TITLE
CTkEntry cant change colors on configure disabled.

### ISSUE THREAD

**Issue by thomasrgrant** [TomSchimansky/CustomTkinter#85]
When you use configure and DISABLED
self.entry_1.configure(text_color="black",state = tkinter.DISABLED)
To ghost the entry widget.
You cant change the bg color of the entry field.
![image](https://user-images.githubusercontent.com/18148511/168755723-439a2968-671e-40dc-83af-65281b5093ce.png)

**Comment by TomSchimansky** [comment]
This will be fixed in the next version.

**Comment by TomSchimansky** [comment]
This should be now fixed with version 4.0.0
