### ISSUE TITLE
Built-in table widget

### ISSUE THREAD

**Issue by NotchApple1703** [TomSchimansky/CustomTkinter#851]
Is there a way to create table without using tree-view or anything likes that?

**Comment by xwydq** [comment]
+1

**Comment by AndreFernandes37** [comment]
+1

**Comment by maxcrous** [comment]
+1

**Comment by Akascape** [comment]
@NotchApple1703 Here is a table widget for customtkinter: https://github.com/Akascape/CTkTable
![Screenshot](https://user-images.githubusercontent.com/89206401/233420929-bf210cb3-5b5f-49b2-ba7a-f01d187e72cf.jpg)

**Comment by ISAACLINDROOS** [comment]
https://github.com/TomSchimansky/CustomTkinter/discussions/1483#discussion-5110718
