### ISSUE TITLE
CTk Textbox 

### ISSUE THREAD

**Issue by anuraj3303** [TomSchimansky/CustomTkinter#854]
['scrollbar_hover_color'] are not supported arguments. Look at the documentation for supported arguments.
not able to set scrollbar colour or scrollbar hover colour 
also CTk Scroll bar cannot be used without specifying scrollbar colour

**Comment by Akascape** [comment]
@anuraj3303 I guess it should be `scrollbar_button_hover_color`, mistake in the docs.

**Comment by duruburak** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/CTkScrollbar

It's basically `button_color` and `button_hover_color`:

`scrollbar = customtkinter.CTkScrollbar(root, button_color="red", button_hover_color="yellow")`

**Comment by anuraj3303** [comment]
Actually I am talking about the inbuilt scrollbar of the CTkTextbox (https://github.com/TomSchimansky/CustomTkinter/wiki/CTkTextbox) 

And for normal CTkScrollbar you will have to set the button color in order to work or else it will give an error
