### ISSUE TITLE
Limit Number of Options in OptionMenu

### ISSUE THREAD

**Issue by JungleDifferential** [TomSchimansky/CustomTkinter#863]
I have an OptionMenu that has over 50 options in it, When you click the drop down, it displays all (or at least from the bottom to the top of the screen) of the options, I think this looks really ugly. I looked around and didn't see a simple way to limit the number of options shown at once to a certain number (then scroll to cycle through the rest of the options). Is there some simple solution to this I am missing? Or do I have to go and make a custom widget (possibly has OptionMenu as a super class?). 
Thanks

**Comment by duruburak** [comment]
I don't think it's possible with built-in methods. But you can assign a new option menu for each certain number.

**Comment by JungleDifferential** [comment]
> 

Thanks, I'll be looking more into it soon.

**Comment by Akascape** [comment]
@JungleDifferential @duruburak 
Try this scrollable dropdown menu: https://github.com/Akascape/CTkScrollableDropdown

It is very easy to add this in the optionmenu.
