### ISSUE TITLE
auto-py-to-exe error: No module named 'distuils'

### ISSUE THREAD

**Issue by 8288tom** [TomSchimansky/CustomTkinter#868]
Hi Tom and everyone who might help,

First of all - great package and wonderful documentation!

I am however encountering an issue when trying to package my script using auto-py-to-exe, I've followed the documentation and added the relevant folders (site-package/customtkinter) to the packager however I'm getting the following errors when trying to run the executeable:

![cmd_CHkq9abmiB](https://user-images.githubusercontent.com/110520326/207977872-1c4b67b4-c860-4642-a419-0b7cede5a851.png)

I've tried installing this package on my venv and pc - doesn't work.

Hopefully, someone can shed some light!

**Comment by Akascape** [comment]
@8288tom 
1. Find the `distutils` folder in your python directory. (It can be found here: `Python\Lib\distutils`)
2. Copy that path and add that folder under **additional folders** option.
3. Recompile the app.
(Do the same if you face any other import error, just find the package in your python directory. Third party modules can be found under `Python\Lib\site-packages`.)

**Comment by 8288tom** [comment]
Thank you @Akascape!
That was indeed the issue, had to add another 5 packages after distutils but eventually, it worked.
Cheers :)
