### ISSUE TITLE
multiple pages

### ISSUE THREAD

**Issue by manooS94** [TomSchimansky/CustomTkinter#87]
hello, I would like to create multiple pages,
can you help or any tips, please 
Thank you

**Comment by TomSchimansky** [comment]
Place multiple frames on top of each other, in there same grid location. And the raise them or use grid forget, to make one visible at a time:
https://www.geeksforgeeks.org/tkinter-application-to-switch-between-different-page-frames/

**Comment by manooS94** [comment]
Thank you, Mr. Tom
Is that ok if I post a simple code  to check it, please
