### ISSUE TITLE
Window close event is not working (root.protocol("WM_DELETE_WINDOW", on_closing))

### ISSUE THREAD

**Issue by duruburak** [TomSchimansky/CustomTkinter#877]
Vanilla tkinter's window close event doesn't work on customtkinter. Is it not integrated yet or I'm missing something?
```
def on_closing():
    quit = askokcancel(title="Title", message= "Message")
    if quit:
        root.destroy()
```
```
root.protocol("WM_DELETE_WINDOW", on_closing)
root.mainloop()
```

**Comment by Akascape** [comment]
@duruburak Define `askokcancel` properly:
```python
import tkinter
def on_closing():
    quit = tkinter.messagebox.askokcancel(title="Title", message= "Message")
    if quit:
        root.destroy()
```

**Comment by duruburak** [comment]
> @duruburak Define `askokcancel` properly:
> 
> ```python
> import tkinter
> def on_closing():
>     quit = tkinter.messagebox.askokcancel(title="Title", message= "Message")
>     if quit:
>         root.destroy()
> ```

I used `from tkinter.messagebox import askokcancel`, so it's already defined.

**Comment by Akascape** [comment]
@duruburak But its working on my system without any error. 
Try with a different messagebox.

**Comment by duruburak** [comment]
Yeah there was an if statement before the statement, the problem was in there. I solved it, it's now working.

**Comment by duruburak** [comment]
Yeah there was an if statement before the statement, the problem was in there. I solved it, it's now working.
