### ISSUE TITLE
Theme manager using hexidecimal

### ISSUE THREAD

**Issue by Moeman101** [TomSchimansky/CustomTkinter#89]
Is it possible for the system themes to be implemented like the color manager.  I wanted to use Hexadecimal to change the theme color just like the buttons but it takes the hexadecimal and looks for a file instead.

**Comment by Moeman101** [comment]
I guess this is more of a request.  Can you add the functionality that system_defult_color_theme can be controlled by Hexadecimal input like button color.

**Comment by TomSchimansky** [comment]
So you want to create a custom theme color? Look at this: https://github.com/TomSchimansky/CustomTkinter/wiki/Themes#custom-themes
You can copy the .json of the standard blue theme and change the blue hex color to your desired theme color. Then you load this new theme by passing the path to the `set_default_color_theme` theme function.

**Comment by Moeman101** [comment]
Thank you.  This was helpful!

**Comment by Moeman101** [comment]
Thank you!  This was helpful
