### ISSUE TITLE
CTkTextbox CPU usage

### ISSUE THREAD

**Issue by for-no-one** [TomSchimansky/CustomTkinter#897]
I'm using CtkTextbox widget as a log window where I'm constantly inserting new lines (less than 10 lines per second). CPU usage grows constantly over time until the application becomes completely frozen. This happens in less than 20 minutes, and I'm also nowhere near of being out of memory. It seems that something becomes more and more CPU expensive after many inserts.

I have tried disabling wrapping and setting undo to False, but it didn't resolve the issue. Switching to tkinter Text widget seems to help, but it doesn't provide the desired appearance.

**Comment by Akascape** [comment]
@for-no-one You can use the normal **tkinter textbox** if you are facing problems with the ctk one:

![Screenshot](https://user-images.githubusercontent.com/89206401/208460793-8f9af0f2-b567-4edf-8c3e-3ff723a3660c.jpg)

## CODE
```python
import tkinter
import customtkinter
         
app = customtkinter.CTk()
app.grid_columnconfigure(0, weight=1)
app.grid_rowconfigure(0, weight=1)

frame_1 = customtkinter.CTkFrame(master=app)
frame_1.grid(padx=20, pady=20, sticky="nswe")
frame_1.grid_columnconfigure(0, weight=1)
frame_1.grid_rowconfigure(0, weight=1)

textbox = tkinter.Text(master=frame_1, font = ("Roboto Medium",10),
                            bg=customtkinter.ThemeManager.theme["color"]["frame_low"][1],
                            fg=customtkinter.ThemeManager.theme["color"]["text"][1],relief="flat")
textbox.insert(1.0, "Write Something")
textbox.grid(padx=20, pady=20, sticky="nsew")

app.mainloop()
```

**Comment by Akascape** [comment]
@for-no-one You can use the normal **tkinter textbox widget** if you are facing problems with the ctk one:

![Screenshot](https://user-images.githubusercontent.com/89206401/208464646-5c9e8e80-e1e0-443a-b036-bcdf6d0ac30f.jpg)
## CODE
```python
import tkinter
import customtkinter
         
app = customtkinter.CTk()
app.grid_columnconfigure(0, weight=1)
app.grid_rowconfigure(0, weight=1)

if customtkinter.get_appearance_mode()=="Dark":
    o = 1
else:
    o = 0

textbox_frame = customtkinter.CTkFrame(master=app)
textbox_frame.grid(padx=20, pady=20, sticky="nswe")
textbox_frame.grid_columnconfigure(0, weight=1)
textbox_frame.grid_rowconfigure(0, weight=1)

textbox = tkinter.Text(master=textbox_frame, font=("Roboto Medium",10),
                            bg=customtkinter.ThemeManager.theme["CTkFrame"]["fg_color"][o],
                            fg=customtkinter.ThemeManager.theme["CTkLabel"]["text_color"][o], relief="flat")
textbox.grid(padx=20, pady=20, sticky="nsew")

textbox_scrollbar = customtkinter.CTkScrollbar(textbox_frame, command=textbox.yview,
                                               fg_color=customtkinter.ThemeManager.theme["CTkFrame"]["fg_color"][o])
textbox_scrollbar.grid(row=0, column=1, sticky="ns", pady=5)

textbox.configure(yscrollcommand=textbox_scrollbar.set)
textbox.insert(1.0, "Write Something")

app.mainloop()                  
```

**Comment by Akascape** [comment]
@for-no-one If the problem still remains with the tkinter text widget, then remove the **ctk textbox_scrollbar** (last 5 lines).

**Comment by TomSchimansky** [comment]
I would suspect the problem is something else in your code. I tested to insert 10000 lines into a textbox every 100ms and nothing is freezing:
```python
import customtkinter

app = customtkinter.CTk()

t = customtkinter.CTkTextbox(app)
t.pack()

def insert():
    t.insert("insert", "this is a text line\n"*10000 + "\n")
    app.after(100, insert)

app.after(100, insert)
app.mainloop()
```

**Comment by TomSchimansky** [comment]
But also, why not clear the textbox or only keep the last 1000 lines at frequent intervals, that should help if the textbox is causing performance problems.

**Comment by for-no-one** [comment]
Thanks! I think [Akascape](https://github.com/Akascape)'s tkinter.Text example helped me. I had this issue with CtkTextBox even when I wasn't appending to the end, but instead overwriting the same 4 lines (I then had to replace that element with 4 labels because my app started freezing).

I will continue investigating and will report here if I learn more about this. Thank you all for very quick help.
