### ISSUE TITLE
Complex example does not work on Windows 11

### ISSUE THREAD

**Issue by sumeshir26** [TomSchimansky/CustomTkinter#9]
While running the complex example, this error appears:
![image](https://user-images.githubusercontent.com/68823982/136735014-c670fe6f-95a7-4142-b955-2f8b5f1e535f.png)

**Comment by TomSchimansky** [comment]
Thanks for mentioning this, this bug should appear on all Windows versions I think. I fixed it now, I will soon upload a new version to PyPi
