### ISSUE TITLE
Visual representation

### ISSUE THREAD

**Issue by abdulrahmanalaa123** [TomSchimansky/CustomTkinter#91]
Add some sort of visual representation of each documentation element some have and some dont

**Comment by felipetesc** [comment]
I'm not sure about what do You want. I'm guessing You desire some sort of class diagram, and so on. 
I've used a tool to auto generate a class diagram of the project using Pyreverse. The images which You can find at https://felipetesc.github.io/CtkDocs/#/ are examples. 

Here You can find more about this tool:https://pypi.org/project/pylint/. I didn't extensively studied the lib.

Also, if You provide a sample about what do You have in your mind it would greatly help. 

PS: I'll help if I can
