### ISSUE TITLE
How to set maximum value for CTkProgressBar ?

### ISSUE THREAD

**Issue by evheniu** [TomSchimansky/CustomTkinter#914]
How I can set minimum, maximum and step values for CTkProgressBar and update it when there changed ?

When I try set progressbar.configure(maximum=100) I get error.

**Comment by TomSchimansky** [comment]
The prgressbar only supports values from 0 to 1. Other intervals have to be scaled to this one. But maybee I will add `from` and `to` arguments in the future.
