### ISSUE TITLE
Need table view

### ISSUE THREAD

**Issue by Pandurangbhor** [TomSchimansky/CustomTkinter#923]
Need table view for management system, like exel

**Comment by TomSchimansky** [comment]
Then you have to use something else, dont know if I will ever implement a 2d table.

**Comment by AndreFernandes37** [comment]
+1

**Comment by Akascape** [comment]
@Pandurangbhor  Here is a table widget for customtkinter: https://github.com/Akascape/CTkTable
![Screenshot](https://user-images.githubusercontent.com/89206401/233420929-bf210cb3-5b5f-49b2-ba7a-f01d187e72cf.jpg)
