### ISSUE TITLE
why theme pixelated on linux

### ISSUE THREAD

**Issue by hmidani-abdelilah** [TomSchimansky/CustomTkinter#931]
- customtkinter==5.0.3

![CustomTkinter](https://user-images.githubusercontent.com/39446276/209389908-16bf28c6-cb87-44af-8f85-7af3daa2a2fd.png)

![CustomTkinter1](https://user-images.githubusercontent.com/39446276/209390311-899ce96b-d50b-48af-a62d-2c27cfeb9d76.png)

**Comment by hmidani-abdelilah** [comment]
- The problem was solved by changing the version of Python 
- Python 3.10
![CustomTkinter2](https://user-images.githubusercontent.com/39446276/209396241-96a64394-78fb-49f9-8fef-1f9177e36354.png)

**Comment by Daniel-Woodford** [comment]
I am on python 3.10 on Linux, but all of the widgets are still very pixelated. I am using python 3.10 in a virtual environment, with customtkinter version 5.2.2.

![image](https://github.com/TomSchimansky/CustomTkinter/assets/80556794/500833c3-6171-4776-ab5e-e29265ac641f)
