### ISSUE TITLE
CTkLabel ignore warning

### ISSUE THREAD

**Issue by cfivek** [TomSchimansky/CustomTkinter#932]
Is there an option to disable this warning? Or warnings from CTk in general?
"CTkLabel Warning: Given image is not CTkImage but <class 'PIL.ImageTk.PhotoImage'>. Image can not be scaled on HighDPI displays, use CTkImage instead."

I am using a numpy array for my image in this label, and CTkImage doesnt seem to accept the array so I am using regular TkImage.

Regular warning filtering doesn't catch it.

**Comment by UserJoo9** [comment]
i have same problem, after too much search don't find solution

**Comment by TomSchimansky** [comment]
Fixed now with version 5.0.4.
