### ISSUE TITLE
CTkProgressbar number of steps

### ISSUE THREAD

**Issue by cfivek** [TomSchimansky/CustomTkinter#933]
From progress bar wiki:
`ctk_progressbar.configure(fg_color=..., progress_color=..., number_of_steps=None, ...)`

When trying to implement, encountering this error:
\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['number_of_steps'] are not supported arguments. Look at the documentation for supported arguments.

Seems like it was an intended function but not implemented? Would be a useful function as currently there is no way to get the maximum value in the progressbar/measure the progress of anything.

**Comment by TomSchimansky** [comment]
Was a mistake in the documentation, but maybe I will implement this in the future.
