### ISSUE TITLE
KeyError : 'text'

### ISSUE THREAD

**Issue by mbcraft-exe** [TomSchimansky/CustomTkinter#937]
Hello, I have compilated a projet with pyinstaler, but when I launch my file (note that customtkinter is installed), I have `KeyError : 'text'` and I don't understand the meaning of this error...
Details of the error on the image below.
![image_2022-12-23_220313906](https://user-images.githubusercontent.com/75203091/209405291-0ea32bcd-0229-4d29-919f-e790cf6f4558.png)
![image_2022-12-23_220351181](https://user-images.githubusercontent.com/75203091/209405326-e7d02a88-8582-4aae-9fa7-47cf31f9dd80.png)

**Comment by TomSchimansky** [comment]
I think you are using an old theme file, the format changed with version 5.0.0.

**Comment by Akascape** [comment]
@mbcraft-exe I guess you are using an old version of customtkinter to build the app but packed the new version of customtkinter in pyinstaller. So, add the correct folder again. 
I hope you are following this guide properly: https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

**Comment by Akascape** [comment]
@mbcraft-exe Paste the customtkinter folder outside your pythor file, then also add that folder using additional-file option in pyinstaller.
