### ISSUE TITLE
Cannot Compile Script to executable file

### ISSUE THREAD

**Issue by shervinbdndev** [TomSchimansky/CustomTkinter#94]
I used Pyinstaller , py2exe & auto-py-to-exe but it shows some errors after running the exe file.
Is there any way for compiling to exe?
![20220520_144926.jpg](https://user-images.githubusercontent.com/68682979/169507866-2143994c-4a36-4dad-b154-7c1fe4d39491.jpg)

**Comment by TomSchimansky** [comment]
https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

**Comment by shervinbdndev** [comment]
> https://github.com/TomSchimansky/CustomTkinter/wiki/Packaging

Thank you🙏🏻
