### ISSUE TITLE
Add documentation images

### ISSUE THREAD

**Issue by ajayschoo** [TomSchimansky/CustomTkinter#96]
Could try to make coroner radius be in tuple so user can chose which  coroner should a bend and which should not be. This would allow to create more modern sites.
Thank you,

**Comment by TomSchimansky** [comment]
This would take a lot of effort to implement and currently I have to not the time for it, but maybe I will do it at some point.
You can have a look at the DrawEngine class wich is responsible for rendering the widgets on a canvas:
https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/draw_engine.py
At the moment it is still in a state where I understand everything, but with such enhancements like individual corner radius or individual borderwidth (request https://github.com/TomSchimansky/CustomTkinter/issues/73), I fear it will get extremely messy with another 300 to 400 lines. The problem are the amount of special cases that arrive with such features and which you have to all cover.

**Comment by Adrian8115** [comment]
Tell me when it's implemented! We really need it!
