### ISSUE TITLE
Add a normal image to a CustomTkinter window

### ISSUE THREAD

**Issue by BenjaminTGa** [TomSchimansky/CustomTkinter#964]
Hi,
I want to add a normal image to my CustomTkinter window.  I have looked at [CTk Image](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkImage), but it places the image inside a button.  Is there any way to make a non-clickable image that has no border -- just a plain image?
Thanks!

**Comment by harshnagar** [comment]
Yes you can Just use CTkLabel in place of CTkButton like this:

```
from customtkinter import *
from PIL import Image
main = CTk()
main.geometry("200x200")
img = CTkImage(dark_image=Image.open("ek.shiv.bhakt___Bt75visAKQi___.jpg"), size=(100, 100))
img_label = CTkLabel(main, image=img, text="")
img_label.grid(row=0, column=0, padx=50, pady=50)
main.mainloop()
```
<img width="191" alt="Screenshot 2022-12-30 172645" src="https://user-images.githubusercontent.com/35253819/210067809-290744a4-c1a6-44a7-8ba1-ec0f27549753.png">

**Comment by BenjaminTGa** [comment]
Thank you!
It works now.
