### ISSUE TITLE
`.bind("<Enter>")` does not work on image in CTkButton

### ISSUE THREAD

**Issue by infinitel8p** [TomSchimansky/CustomTkinter#967]
When experimenting with tktooltip (https://github.com/gnikit/tkinter-tooltip) I noticed apart from #924, that the tooltip doesnt show when the mouse is on the image from my button.
It seems that the `.bind("<Enter>")` doesnt count/work for the image in the button

Am I overlooking something? It would be nice if this would work on the image as well since im planning to only have a image in the button when 924 is fixed.

Code to reproduce the issue:

`pip install tkinter-tooltip`

```py
from customtkinter import CTk, CTkButton, CTkImage
from tktooltip import ToolTip
from PIL import Image

def callback(event):
    # Callback function code goes here
    print("Mouse entered the button")

root = CTk()

test_image = CTkImage(light_image=Image.open(
    f"image.png"), size=(50, 50))
button = CTkButton(root, text="Hover over me", image=test_image)

ToolTip(button, "This is a tooltip")

button.bind("<Enter>", callback)
button.pack()

root.mainloop()
```

**Comment by Akascape** [comment]
@infinitel8p 
This is happening because the image label within the button is a separate widget.
You have to also add the tooltips for `button._image_label`:
```python
from customtkinter import CTk, CTkButton, CTkImage
from tktooltip import ToolTip
from PIL import Image

def callback(event):
    # Callback function code goes here
    print("Mouse entered the button")

root = CTk()

test_image = CTkImage(light_image=Image.open(
    f"h.png"), size=(50, 50))
button = CTkButton(root, text="Hover over me", image=test_image)

ToolTip(button, "This is a tooltip", delay=0.01)
ToolTip(button._image_label, "This is a tooltip", delay=0.01)

button.bind("<Enter>", callback)
button.pack()

root.mainloop()
```

**Comment by TomSchimansky** [comment]
@infinitel8p did you use the latest version? For me there is no problem, the tooltip is showing on the text and the image.
