### ISSUE TITLE
CTkTextBox doesn't support Georgian language

### ISSUE THREAD

**Issue by Nikushavar** [TomSchimansky/CustomTkinter#972]
Hello, i am currently making translator app using customtkinter, i am georgian (country in caucasia) by myself and tried to add georgian language, but when i am trying to type using georgian in CTkTextBox i get "???" instead of georgian letters, it's not font problem either, i tried Sylfaen font (Sylfaen supports georgian letters) but it still doesn't work.

**Comment by Akascape** [comment]
@Nikushavar Ig, it's a font issue.
I downloaded a georgian font from this website: https://www.fontsaddict.com/font/search/georgian
and tried to write in the text box:
```python
# I loaded that font file directly using this method, (you can install that in your system if you wish)
customtkinter.FontManager.load_font("chveulebrivy-itv_italic.ttf")
# Then used that font like this:
textbox = customtkinter.CTkTextbox(self, width=250, font=("Chveulebrivy-ITV Italic",20))
```
I copy pasted the word **Hello**:

![Screenshot 2022-12-31 170158](https://user-images.githubusercontent.com/89206401/210135207-f56f265f-d20e-40fa-9aa1-e04f15a79409.jpg)

**Comment by Akascape** [comment]
@Nikushavar

**Comment by Nikushavar** [comment]
> 

Thanks, it really works with copy pasting georgian words into TextBox, but when i try to **type** using georgian letters, they still show as "???" sadly.

**Comment by Akascape** [comment]
@Nikushavar 
In my system it is not showing '???' when I press any key. 
It is normally showing the georgian letters. Don't know what's wrong.

Can you try this with the normal tkinter text widget? 
Here is an example of text widget: https://github.com/TomSchimansky/CustomTkinter/wiki/CTkScrollbar

**Comment by Akascape** [comment]
@Nikushavar ig It is a problem of tkinter text widget. 
In my system, it is not showing '???' when I press any key.

Here is a relevent issue I found: https://stackoverflow.com/questions/39547969/the-georgian-language-in-tkinter-python,

Don't know what exactly is causing this.
Maybe you have to update tkinter or python.

**Comment by Nikushavar** [comment]
> @Nikushavar ig It is a problem of tkinter text widget. In my system, it is not showing '???' when I press any key.
> 
> Here is a relevent issue I found: https://stackoverflow.com/questions/39547969/the-georgian-language-in-tkinter-python,
> 
> Don't know what exactly is causing this. Maybe you have to update tkinter or python.


> @Nikushavar ig It is a problem of tkinter text widget. In my system, it is not showing '???' when I press any key.
> 
> Here is a relevent issue I found: https://stackoverflow.com/questions/39547969/the-georgian-language-in-tkinter-python,
> 
> Don't know what exactly is causing this. Maybe you have to update tkinter or python.

Oh alright, I guess it's problem with Tkinter then, thanks for your help tho 👍
