### ISSUE TITLE
CTkSwitch vertically and horizontally centered inside a CTkFrame

### ISSUE THREAD

**Issue by soyTorch** [TomSchimansky/CustomTkinter#973]
Hi, how can I make a CTkSwitch vertically and horizontally centered inside a CTkFrame?
My code is this:
        self.frame = customtkinter.CTkFrame(self, height=10, width=100)
        self.frame.grid(columnspan=4,row=0, column=0, sticky="nsew", padx=20, pady=20)
        self.frame.columnconfigure(0, weight=1)
        self.label = customtkinter.CTkSwitch(master=self.frame,text="Option", command=lambda: self.switch_callback())
        self.label.grid(row=0,columnspan=4, column=0, pady=0)

And the result looks like this:
![image](https://user-images.githubusercontent.com/96847130/210146716-c937910d-13e1-4a57-8813-6dc4007be28e.png)

**Comment by Akascape** [comment]
@soyTorch Just like **column configure**, you have to use **row configure**:
```python
frame.rowconfigure(0, weight=1)
```

**Comment by soyTorch** [comment]
Thank you, man. Is there any method to add color individually to a CTkTextbox. I need it to act like a console with colorama

**Comment by soyTorch** [comment]
def print_console(self, text, color):
        self.console.configure(state="normal")
        self.console.insert(customtkinter.END, "\n"+text)
        self.console.tag_add(color, "end - %dc" % (len(text)+1), "end")
        self.console.tag_config(color, foreground=color)
        self.console.configure(state="disabled")
        
Solved by me xD

**Comment by Akascape** [comment]
@soyTorch Great, close this issue then.
