### ISSUE TITLE
Black screen on MacOs Monterey

### ISSUE THREAD

**Issue by Mojito060** [TomSchimansky/CustomTkinter#98]
Hi I tried using CustomTkinter for the first time, but when I tried to use the example code provided in the readme I only get this window. Only the window is black the button is still there but not visible.
![grafik](https://user-images.githubusercontent.com/39467706/169661801-c13a702c-f80b-4cee-8ad2-49a2ac23f49c.png)
I use Python 3.8.9 and MacOs Monterey.

**Comment by TomSchimansky** [comment]
This is always a problem of the Tk/Tcl version. Upgrading to python>=3.10 should resolve this...
