### ISSUE TITLE
App Header weird Colors, focused and unfocused

### ISSUE THREAD

**Issue by GermanYoshi** [TomSchimansky/CustomTkinter#981]
So unfocused it looks great:
![grafik](https://user-images.githubusercontent.com/39739909/210215244-86196a7e-4063-480e-b8c3-36f81e418480.png)

but as soon as i tab in the app (focus it), it looks terrible (black):
![grafik](https://user-images.githubusercontent.com/39739909/210215289-6ae601c7-6510-449d-9065-c611c41f71b1.png)

Is there something i did wrong or is this Intended?

**Comment by TomSchimansky** [comment]
These are the normal windows header color I would say. I don't change the header colors with the CustomTkinter library, I just set the window to dark or light mode, the colors are handled by the OS.

**Comment by Akascape** [comment]
Here is the quick fix:
```python
import customtkinter
from ctypes import windll, byref, sizeof, c_int

root = customtkinter.CTk()
root.update()

HWND = windll.user32.GetParent(root.winfo_id())
HWMWA_ATTRIBUTE = 35

windll.dwmapi.DwmSetWindowAttribute(HWND, HWMWA_ATTRIBUTE, byref(c_int(0x00242424)), sizeof(c_int))

root.mainloop()
```
**This one is tested only with windows 11, idk about windows 10 (maybe have to set `HWMWA_ATTRIBUTE = 34`)**
![Screenshot](https://user-images.githubusercontent.com/89206401/211209620-ba0be19c-2cf0-49e5-8115-66b9d53bf839.jpg)

More info here: https://github.com/TomSchimansky/CustomTkinter/discussions/1011

**Comment by Akascape** [comment]
@GermanYoshi 
Here is the quick fix:
```python
import customtkinter
from ctypes import windll, byref, sizeof, c_int

root = customtkinter.CTk()
root.update()

HWND = windll.user32.GetParent(root.winfo_id())
HWMWA_ATTRIBUTE = 35

windll.dwmapi.DwmSetWindowAttribute(HWND, HWMWA_ATTRIBUTE, byref(c_int(0x00242424)), sizeof(c_int))

root.mainloop()
```
**This one is tested only with windows 11, idk about windows 10 (maybe have to set `HWMWA_ATTRIBUTE = 34`)**
![Screenshot](https://user-images.githubusercontent.com/89206401/211209620-ba0be19c-2cf0-49e5-8115-66b9d53bf839.jpg)

More info here: https://github.com/TomSchimansky/CustomTkinter/discussions/1011

**Comment by GermanYoshi** [comment]
sadly doesnt work for win10. I guess we will upgrade to win11 soon so thanks anyways :)

**Comment by Akascape** [comment]
@GermanYoshi Did you try with `HWMWA_ATTRIBUTE = 34`?
Also try with 33, 36.

**Comment by GermanYoshi** [comment]
Yeah. Doesnt work sadly
