### ISSUE TITLE
CTkComboBox background becomes white when dark appearance is used

### ISSUE THREAD

**Issue by iniridwanul** [TomSchimansky/CustomTkinter#983]
CTkComboBox background becomes white when using dark appearance with state "readonly".

`customtkinter Version: 5.0.3`

![ctkbug](https://user-images.githubusercontent.com/70999619/210255484-40a121e6-8128-4091-b82b-85bf5b2a491a.png)

**Comment by Akascape** [comment]
This is the proper fix:
```python
optionmenu = customtkinter.CTkComboBox(root, state="readonly", values=["A", "B", "C", "D"])
optionmenu._entry.configure(readonlybackground=optionmenu._apply_appearance_mode(optionmenu._fg_color))
optionmenu.pack()
```
