### ISSUE TITLE
Add the Listbox widget.

### ISSUE THREAD

**Issue by shasankp000** [TomSchimansky/CustomTkinter#997]
Add the listbox widget from ``tkinter.ListBox`` ?

**Comment by Akascape** [comment]
@shasankp000 
**Hi, I just made this custom listbox for customtkinter:**
https://github.com/Akascape/CTkListbox

![](https://user-images.githubusercontent.com/89206401/247524994-256c135f-3d6c-4daa-87a5-b4572a2c905f.jpg)
